import { chiosHotelsGuide } from "@/content/chios-hotels-guide";
import type { ChiosHotelsGuideContent } from "@/content/chios-hotels-guide-types";

export const hotelChiosGuideIt: ChiosHotelsGuideContent = {
  ...chiosHotelsGuide,
  seo: {
    canonicalPath: "/it/hotel-chios/",
    title: "Hotel a Chios | Dove soggiornare, prezzi & alternative",
    description: "Confronta hotel a Chios, camere e appartamenti per zona e stile di viaggio. Verifica la disponibilità reale del Voulamandis House a Kambos.",
    image: chiosHotelsGuide.seo.image,
    imageAlt: "Camere e appartamenti tra gli agrumeti di Kambos a Chios",
  },
  hero: {
    kicker: "HOTEL A CHIOS & DOVE SOGGIORNARE",
    title: "Hotel a Chios, camere e appartamenti: dove soggiornare sull’isola",
    description: "Cerchi hotel a Chios? Questa guida locale confronta le principali zone dell’isola, chiarisce le differenze tra hotel, strutture familiari, camere e appartamenti e permette di verificare la disponibilità reale per un soggiorno tranquillo a Kambos.",
    disclosure: "Voulamandis House non è un hotel. È una struttura ricettiva a gestione familiare con camere private e appartamenti familiari a Kambos, Chios.",
    primaryCta: { label: "Cerca disponibilità live", href: "#live-availability" },
    secondaryCta: { label: "Confronta le zone", href: "#where-to-stay" },
    aiCta: { label: "Chiedi all’AI Room Finder", href: "/ai-assistant/?lang=it" },
  },
  trustPoints: [
    { label: "Base locale", value: "Kambos storico" },
    { label: "Aeroporto di Chios", value: "Circa 3 km" },
    { label: "Porto di Chios", value: "Circa 6 km" },
    { label: "Tipi di soggiorno", value: "Camere & appartamenti" },
    { label: "Ideale per", value: "Coppie & famiglie" },
    { label: "Ricerca live", value: "Disponibilità reale" },
  ],
  intro: {
    kicker: "PARTI DALLA ZONA GIUSTA",
    title: "Una buona ricerca di hotel a Chios comincia dalla zona in cui soggiornare",
    paragraphs: [
      "La ricerca di hotel a Chios spesso comprende esigenze diverse: vicinanza al porto, accesso semplice all’aeroporto, spiaggia nelle vicinanze, spazio per una famiglia, quartiere tranquillo oppure una base pratica per esplorare l’isola in auto. La zona conta quindi quanto la camera.",
      "La città di Chios è comoda per il porto, i ristoranti e chi viaggia senza auto. Kambos offre un ambiente storico più tranquillo vicino alla città e all’aeroporto. Karfas e la costa vicina sono adatte a un soggiorno balneare, mentre i villaggi del mastice propongono un’esperienza più tradizionale e distante.",
      "Questa guida utilizza l’espressione «hotel a Chios» nel modo ampio in cui viene cercata online, distinguendo però chiaramente hotel tradizionali, strutture familiari, camere e appartamenti indipendenti. Voulamandis House appartiene alla categoria della struttura ricettiva familiare e non dichiara di offrire i servizi di un hotel o resort.",
    ],
  },
  areas: {
    kicker: "DOVE SOGGIORNARE A CHIOS",
    title: "Confronta le zone principali prima di scegliere l’alloggio",
    description: "Ogni zona crea un tipo di vacanza diverso. Confronta accessibilità, atmosfera e il viaggiatore a cui si adatta meglio.",
    items: [
      { id: "chios-town", title: "Città di Chios", badge: "Porto & vita urbana", text: "Scelta pratica per arrivi in traghetto, ristoranti, negozi e passeggiate sul lungomare. Può funzionare bene senza auto, anche se le strade centrali sono naturalmente più frequentate.", bestFor: "Soggiorni brevi, viaggiatori in traghetto e ospiti senza auto", link: "/it/chios-lisola-in-grecia/" },
      { id: "kambos", title: "Kambos", badge: "Storico & tranquillo", text: "Agrumeti, alti muri in pietra e antiche dimore caratterizzano Kambos. La zona unisce tranquillità e accesso rapido alla città, all’aeroporto e alle strade verso sud.", bestFor: "Coppie, famiglie e viaggiatori con auto", link: "/it/chios/kampos-chios/" },
      { id: "karfas", title: "Karfas e costa vicina", badge: "Soggiorno balneare", text: "Zona costiera nota per la spiaggia organizzata e l’atmosfera estiva. Adatta a chi desidera avere il mare vicino all’alloggio.", bestFor: "Vacanze estive e soggiorni al mare", link: "/it/spiagge-chios/" },
      { id: "mastic-villages", title: "Villaggi del mastice", badge: "Sud tradizionale", text: "Pyrgi, Mesta e gli altri villaggi medievali offrono architettura distintiva e forte carattere locale. L’auto è di solito il mezzo più pratico per soggiornare o esplorare la zona.", bestFor: "Itinerari in auto, storia e vita di paese", link: "/it/villaggi-chios/" },
    ],
  },
  accommodationTypes: {
    kicker: "HOTEL, CAMERA O APPARTAMENTO?",
    title: "Scegli il tipo di soggiorno che corrisponde alle tue priorità",
    description: "La parola hotel viene spesso usata come ricerca generale, ma i tipi di alloggio disponibili a Chios possono essere molto diversi.",
    items: [
      { title: "Hotel tradizionale", idealFor: "Viaggiatori che privilegiano i servizi in struttura", features: "Reception, aree comuni e, a seconda della proprietà, ristorante, piscina o servizi aggiuntivi." },
      { title: "Struttura familiare", idealFor: "Un soggiorno più piccolo e personale", features: "Meno camere, contatto diretto con i gestori e atmosfera più tranquilla rispetto a un grande hotel o resort." },
      { title: "Camera privata", idealFor: "Coppie e soggiorni brevi", features: "Bagno privato e servizi essenziali, spesso con formula più semplice e prezzo competitivo." },
      { title: "Appartamento familiare", idealFor: "Famiglie e soggiorni più lunghi", features: "Più spazio, camera separata, zona giorno e cucina per maggiore autonomia." },
    ],
    note: "Voulamandis House è una struttura familiare con camere private e appartamenti. Rappresenta un’alternativa a un hotel tradizionale a Chios e non viene presentato come hotel con un altro nome.",
  },
  popularSearches: {
    kicker: "RICERCHE POPOLARI DI HOTEL A CHIOS",
    title: "Trova il soggiorno adatto per posizione, budget e stile di viaggio",
    items: [
      { id: "chios-hotels-near-airport", title: "Hotel vicino all’aeroporto di Chios", text: "Soggiornare vicino all’aeroporto facilita partenze mattutine, arrivi tardivi e visite brevi. Kambos è una delle zone vicine più pratiche e offre un ambiente più tranquillo del centro.", cta: "Vedi la posizione a Kambos", href: "#kambos-alternative" },
      { id: "chios-hotels-near-port", title: "Hotel e camere vicino al porto di Chios", text: "Il centro è la scelta più vicina per raggiungere il porto a piedi. Kambos è più distante, ma facilmente raggiungibile in auto o taxi e offre una base più calma.", cta: "Confronta città e Kambos", href: "#where-to-stay" },
      { id: "family-hotels-chios", title: "Hotel per famiglie e appartamenti a Chios", text: "Le famiglie spesso hanno bisogno di più di una camera standard. Gli appartamenti con cucina e zona giorno offrono maggiore spazio, mentre alcune camere più grandi sono adatte a famiglie piccole.", cta: "Vedi appartamenti familiari", href: "/it/stanze-a-chios/appartamenti-familiari-a-chios/" },
      { id: "cheap-hotels-chios", title: "Hotel economici e camere convenienti a Chios", text: "Un prezzo più basso non significa rinunciare a bagno privato, aria condizionata o posizione pratica. Le camere economy sono un’alternativa utile per le coppie che esplorano l’isola durante il giorno.", cta: "Vedi camere economy", href: "/it/stanze-a-chios/camera-doppia-economica-chios/" },
      { id: "hotels-in-kambos-chios", title: "Hotel e alloggi a Kambos", text: "Kambos è apprezzato per agrumeti, dimore storiche e posizione tra città, aeroporto e strade meridionali. Le strutture qui sono spesso più piccole e personali.", cta: "Scopri Kambos", href: "/it/chios/kampos-chios/" },
      { id: "chios-hotels-near-beach", title: "Hotel sul mare e alloggi vicino alle spiagge", text: "Karfas è una scelta nota per la spiaggia organizzata. Chi desidera vedere coste diverse può preferire una base centrale con buoni collegamenti stradali.", cta: "Esplora le spiagge di Chios", href: "/it/spiagge-chios/" },
    ],
  },
  kambosAlternative: {
    kicker: "UN MODO DIVERSO DI SOGGIORNARE",
    title: "Un’alternativa più tranquilla a un hotel tradizionale a Chios",
    paragraphs: [
      "Voulamandis House è pensato per chi apprezza tranquillità, comunicazione diretta e una base pratica per esplorare l’isola. La struttura familiare offre un’esperienza su scala ridotta tra gli agrumeti di Kambos.",
      "Puoi scegliere camere doppie economy, camere al piano terra senza scale, camere al piano superiore e appartamenti familiari con cucina completa. Tutte le opzioni includono bagno privato, aria condizionata, Wi-Fi e frigorifero.",
      "La struttura si trova a circa 3 km dall’aeroporto di Chios e 6 km dal porto: abbastanza vicina per arrivi comodi, ma fuori dalle strade più trafficate della città.",
    ],
    benefits: [
      "Camere e appartamenti familiari invece di un grande hotel",
      "Kambos storico con giardino e atmosfera di agrumeti",
      "Soluzioni al piano terra per evitare le scale",
      "Appartamenti familiari con cucina completa e zona giorno",
      "Aiuto diretto nella scelta della categoria più adatta",
      "Buon accesso stradale verso città, spiagge e villaggi meridionali",
    ],
    primaryCta: { label: "Vedi camere & appartamenti", href: "/it/camere-a-chios/" },
    secondaryCta: { label: "Verifica tariffe dirette", href: "/it/prezzi-hotel-chios/" },
  },
  roomCategories: {
    kicker: "SOLUZIONI REALI DI ALLOGGIO",
    title: "Camere e appartamenti al Voulamandis House",
    description: "Confronta le categorie principali prima di inserire le date. I risultati live si basano sui dati attuali di disponibilità della struttura.",
    items: [
      { title: "Camere doppie economy", label: "Scelta conveniente per due", text: "Camere rinnovate con letto matrimoniale, bagno privato, aria condizionata, Wi-Fi, TV e frigorifero.", facts: ["2 ospiti", "Circa 16 m²", "Bagno privato"], image: chiosHotelsGuide.roomCategories.items[0].image, href: "/it/stanze-a-chios/camera-doppia-economica-chios/" },
      { title: "Camere al piano terra", label: "Accesso facile e senza scale", text: "Camere doppie e triple con accesso diretto al cortile o giardino, adatte a chi preferisce il piano terra.", facts: ["2–3 ospiti", "Senza scale", "Accesso al giardino"], image: chiosHotelsGuide.roomCategories.items[1].image, href: "/it/stanze-a-chios/camere-doppie-standard-chios/" },
      { title: "Camere al piano superiore", label: "Terrazza e vista sugli agrumeti", text: "Camere doppie e triple luminose al piano superiore con terrazza comune e angolo cottura in alcune opzioni.", facts: ["2–4 ospiti", "Piano superiore", "Alcune con angolo cottura"], image: chiosHotelsGuide.roomCategories.items[2].image, href: "/it/stanze-a-chios/camere-doppie-standard-chios/" },
      { title: "Appartamenti familiari", label: "Più spazio e cucina completa", text: "Appartamenti indipendenti di 40–45 m² con camera separata, zona giorno e cucina per famiglie e soggiorni più lunghi.", facts: ["Fino a 4 ospiti", "40–45 m²", "Cucina completa"], image: chiosHotelsGuide.roomCategories.items[3].image, href: "/it/stanze-a-chios/appartamenti-familiari-a-chios/" },
    ],
  },
  planning: {
    kicker: "PIANIFICA OLTRE LA CAMERA",
    title: "Usa il tuo alloggio come base per tutta l’isola",
    description: "Una ricerca completa di hotel a Chios deve considerare anche gli spostamenti quotidiani. Queste guide locali spiegano distanze, itinerari ed esperienze raggiungibili da Kambos.",
    links: [
      { title: "Guida dell’isola di Chios", text: "Inizia dalle zone principali, dalle esperienze più importanti e dalle idee pratiche per esplorare l’isola.", href: "/it/chios-lisola-in-grecia/" },
      { title: "Spiagge di Chios", text: "Confronta spiagge organizzate, familiari e tranquille lungo coste diverse.", href: "/it/spiagge-chios/" },
      { title: "Villaggi di Chios", text: "Organizza itinerari tra villaggi medievali del mastice, montagna e costa.", href: "/it/villaggi-chios/" },
      { title: "Kambos storico", text: "Scopri gli agrumeti, le dimore in pietra e il paesaggio che circonda la struttura.", href: "/it/chios/kampos-chios/" },
    ],
  },
  faq: {
    kicker: "FAQ HOTEL A CHIOS",
    title: "Le domande prima di prenotare un alloggio a Chios",
    items: [
      { question: "Qual è la zona migliore dove soggiornare a Chios?", answer: "La città di Chios è pratica per porto, ristoranti e viaggiatori senza auto. Kambos è una base storica più tranquilla vicino alla città e all’aeroporto. Karfas è adatta a soggiorni balneari, mentre i villaggi del mastice sono ideali con un’auto." },
      { question: "Ci sono hotel vicino all’aeroporto di Chios?", answer: "Sì, diverse zone si trovano a breve distanza in auto. Kambos è particolarmente pratico perché è vicino all’aeroporto e più tranquillo del centro. Voulamandis House dista circa 3 km." },
      { question: "Dove soggiornare vicino al porto di Chios?", answer: "Per raggiungere il porto a piedi, il centro è la scelta più vicina. Kambos si trova a circa 6 km ed è adatto a chi preferisce una base tranquilla e utilizza auto o taxi." },
      { question: "Kambos è una buona zona per soggiornare?", answer: "Sì, soprattutto per chi cerca carattere storico, giardini e tranquillità rimanendo vicino alla città, all’aeroporto e alle strade verso sud." },
      { question: "Gli appartamenti sono migliori degli hotel per le famiglie?", answer: "Un appartamento è spesso più pratico quando servono più spazio, cucina e zona giorno separata. Un hotel tradizionale può essere più adatto a chi privilegia servizi più ampi in struttura." },
      { question: "Quanto costa un alloggio a Chios?", answer: "I prezzi cambiano secondo stagione, zona, tipo di camera, numero di ospiti e condizioni. Per Voulamandis House il metodo più affidabile è inserire le date reali nella ricerca live." },
      { question: "Serve un’auto a Chios?", answer: "Non è indispensabile per un breve soggiorno nel centro, ma è molto utile per spiagge, villaggi del mastice e diverse parti dell’isola." },
      { question: "Qual è la zona migliore per le spiagge?", answer: "Karfas è pratica per una spiaggia organizzata. Chi vuole visitare coste diverse può preferire una base centrale vicina alla rete stradale principale." },
      { question: "Ci sono camere economiche a Chios?", answer: "Sì. Camere economy e piccole strutture familiari possono offrire un’alternativa conveniente ai grandi hotel, soprattutto per le coppie." },
      { question: "Voulamandis House è un hotel?", answer: "No. Voulamandis House è una struttura ricettiva familiare a Kambos con camere private e appartamenti. Non si presenta come hotel tradizionale o resort." },
      { question: "Quanto distano aeroporto e porto?", answer: "Voulamandis House dista circa 3 km dall’aeroporto di Chios e circa 6 km dal porto, risultando pratico per arrivi in aereo o traghetto." },
      { question: "Come verifico la disponibilità live?", answer: "Inserisci arrivo, partenza e numero di ospiti nella ricerca della pagina. Puoi anche utilizzare l’AI Room Finder o contattare direttamente la struttura via WhatsApp." },
    ],
  },
  finalCta: {
    kicker: "DALLA RICERCA A UN’OPZIONE REALE",
    title: "Verifica un soggiorno tranquillo a Chios con date reali",
    text: "Confronta le zone, scegli il tipo di alloggio adatto al viaggio e usa la ricerca live per vedere quali camere o appartamenti sono disponibili.",
    primaryCta: { label: "Cerca disponibilità", href: "#live-availability" },
    secondaryCta: { label: "Vedi tutte le camere", href: "/it/camere-a-chios/" },
  },
};
