import { chiosHotelsGuide } from "@/content/chios-hotels-guide";
import type { ChiosHotelsGuideContent } from "@/content/chios-hotels-guide-types";

export const hotelesChiosGuideEs: ChiosHotelsGuideContent = {
  ...chiosHotelsGuide,
  seo: {
    canonicalPath: "/es/hoteles-chios/",
    title: "Hoteles en Chios | Dónde alojarse, precios & alternativas",
    description: "Compare hoteles en Chios, habitaciones y apartamentos por zona y estilo de viaje. Consulte disponibilidad real en Voulamandis House, Kambos.",
    image: chiosHotelsGuide.seo.image,
    imageAlt: "Habitaciones y apartamentos entre los jardines de cítricos de Kambos, Chios",
  },
  hero: {
    kicker: "HOTELES EN CHIOS & DÓNDE ALOJARSE",
    title: "Hoteles en Chios, habitaciones y apartamentos: dónde alojarse en la isla",
    description: "¿Busca hoteles en Chios? Esta guía local compara las principales zonas de la isla, explica las diferencias entre hoteles, alojamientos familiares, habitaciones y apartamentos y permite consultar disponibilidad real para una estancia tranquila en Kambos.",
    disclosure: "Voulamandis House no es un hotel. Es un alojamiento familiar con habitaciones privadas y apartamentos familiares en Kambos, Chios.",
    primaryCta: { label: "Buscar disponibilidad en directo", href: "#live-availability" },
    secondaryCta: { label: "Comparar zonas", href: "#where-to-stay" },
    aiCta: { label: "Preguntar al AI Room Finder", href: "/ai-assistant/?lang=es" },
  },
  trustPoints: [
    { label: "Base local", value: "Kambos histórico" },
    { label: "Aeropuerto de Chios", value: "Aprox. 3 km" },
    { label: "Puerto de Chios", value: "Aprox. 6 km" },
    { label: "Tipos de estancia", value: "Habitaciones y apartamentos" },
    { label: "Ideal para", value: "Parejas y familias" },
    { label: "Búsqueda en directo", value: "Disponibilidad real" },
  ],
  intro: {
    kicker: "EMPIECE POR LA ZONA ADECUADA",
    title: "Una buena búsqueda de hoteles en Chios empieza por decidir dónde alojarse",
    paragraphs: [
      "La búsqueda de hoteles en Chios suele reunir varias necesidades: cercanía al puerto, acceso sencillo al aeropuerto, playa próxima, espacio para una familia, una zona tranquila o una base práctica para recorrer la isla en coche. Por eso la ubicación importa tanto como la propia habitación.",
      "La ciudad de Chios resulta cómoda para el puerto, los restaurantes y quienes viajan sin coche. Kambos ofrece un entorno histórico más tranquilo cerca de la ciudad y del aeropuerto. Karfas y la costa próxima son adecuadas para una estancia de playa, mientras que los pueblos de la masilla ofrecen una experiencia más tradicional y alejada.",
      "Esta guía utiliza la expresión «hoteles en Chios» del modo amplio en que suelen buscarla los viajeros, pero diferencia claramente hoteles tradicionales, alojamientos familiares, habitaciones y apartamentos independientes. Voulamandis House pertenece a la categoría de alojamiento familiar y no afirma ofrecer el modelo de servicios de un hotel o resort.",
    ],
  },
  areas: {
    kicker: "DÓNDE ALOJARSE EN CHIOS",
    title: "Compare las principales zonas antes de elegir alojamiento",
    description: "Cada zona crea un tipo de viaje diferente. Compare acceso, ambiente y el perfil de viajero al que se adapta mejor.",
    items: [
      { id: "chios-town", title: "Ciudad de Chios", badge: "Puerto y vida urbana", text: "Una opción práctica para llegadas en ferry, restaurantes, tiendas y paseos por el paseo marítimo. Puede funcionar bien sin coche, aunque las calles centrales son naturalmente más animadas.", bestFor: "Estancias cortas, viajeros en ferry y huéspedes sin coche", link: "/es/chios-en-grecia/" },
      { id: "kambos", title: "Kambos", badge: "Histórico y tranquilo", text: "Los jardines de cítricos, los altos muros de piedra y las antiguas mansiones definen Kambos. La zona combina calma con acceso rápido a la ciudad, al aeropuerto y a las carreteras del sur.", bestFor: "Parejas, familias y viajeros con coche", link: "/es/chios/kampos-chios/" },
      { id: "karfas", title: "Karfas y costa cercana", badge: "Estancia de playa", text: "Zona costera conocida por su playa organizada y su ambiente veraniego. Adecuada para quienes desean tener el mar muy cerca del alojamiento.", bestFor: "Vacaciones de verano y playa", link: "/es/playas-chios/" },
      { id: "mastic-villages", title: "Pueblos de la masilla", badge: "Sur tradicional", text: "Pyrgi, Mesta y otros pueblos medievales ofrecen arquitectura singular y fuerte carácter local. El coche suele ser la forma más práctica de alojarse o recorrer la zona.", bestFor: "Rutas en coche, historia y vida de pueblo", link: "/es/pueblos-chios/" },
    ],
  },
  accommodationTypes: {
    kicker: "¿HOTEL, HABITACIÓN O APARTAMENTO?",
    title: "Elija el tipo de estancia que encaja con sus prioridades",
    description: "La palabra hotel se utiliza a menudo como búsqueda general, aunque los tipos reales de alojamiento disponibles en Chios pueden ser muy diferentes.",
    items: [
      { title: "Hotel tradicional", idealFor: "Viajeros que priorizan servicios dentro del establecimiento", features: "Recepción, zonas comunes y, según la propiedad, restaurante, piscina o servicios adicionales." },
      { title: "Alojamiento familiar", idealFor: "Una estancia más pequeña y personal", features: "Menos habitaciones, contacto directo con los anfitriones y un ambiente más tranquilo que un gran hotel o resort." },
      { title: "Habitación privada", idealFor: "Parejas y visitas cortas", features: "Baño privado y equipamiento esencial, normalmente con un modelo de servicio más sencillo y precio competitivo." },
      { title: "Apartamento familiar", idealFor: "Familias y estancias más largas", features: "Más espacio, dormitorio separado, zona de estar y cocina para mayor independencia." },
    ],
    note: "Voulamandis House es un alojamiento familiar con habitaciones privadas y apartamentos. Es una alternativa a un hotel tradicional en Chios y no se presenta como hotel con otro nombre.",
  },
  popularSearches: {
    kicker: "BÚSQUEDAS POPULARES DE HOTELES EN CHIOS",
    title: "Encuentre una estancia por ubicación, presupuesto y estilo de viaje",
    items: [
      { id: "chios-hotels-near-airport", title: "Hoteles cerca del aeropuerto de Chios", text: "Alojarse cerca del aeropuerto facilita salidas tempranas, llegadas tardías y visitas cortas. Kambos es una de las zonas próximas más prácticas y ofrece un ambiente más tranquilo que el centro.", cta: "Ver la ubicación en Kambos", href: "#kambos-alternative" },
      { id: "chios-hotels-near-port", title: "Hoteles y habitaciones cerca del puerto de Chios", text: "El centro es la opción más cercana para llegar andando al puerto. Kambos está más lejos, pero se alcanza fácilmente en coche o taxi y ofrece una base más calmada.", cta: "Comparar ciudad y Kambos", href: "#where-to-stay" },
      { id: "family-hotels-chios", title: "Hoteles familiares y apartamentos en Chios", text: "Las familias suelen necesitar más que una habitación estándar. Los apartamentos con cocina y zona de estar aportan más espacio, mientras que algunas habitaciones grandes pueden servir a familias pequeñas.", cta: "Ver apartamentos familiares", href: "/es/habitaciones-en-chios/apartamentos-familiares-en-chios/" },
      { id: "cheap-hotels-chios", title: "Hoteles baratos y habitaciones económicas en Chios", text: "Un precio más bajo no implica renunciar a baño privado, aire acondicionado o ubicación práctica. Las habitaciones económicas son una alternativa útil para parejas que recorren la isla durante el día.", cta: "Ver habitaciones económicas", href: "/es/habitaciones-en-chios/economicas-habitaciones-en-chios/" },
      { id: "hotels-in-kambos-chios", title: "Hoteles y alojamiento en Kambos", text: "Kambos destaca por sus jardines de cítricos, fincas históricas y ubicación entre la ciudad, el aeropuerto y las rutas del sur. Los alojamientos suelen ser más pequeños y personales.", cta: "Descubrir Kambos", href: "/es/chios/kampos-chios/" },
      { id: "chios-hotels-near-beach", title: "Hoteles de playa y alojamiento junto al mar", text: "Karfas es una opción conocida para una playa organizada. Quienes quieran conocer costas diferentes pueden preferir una base central con buenas conexiones por carretera.", cta: "Explorar las playas de Chios", href: "/es/playas-chios/" },
    ],
  },
  kambosAlternative: {
    kicker: "UNA FORMA DISTINTA DE ALOJARSE",
    title: "Una alternativa más tranquila a un hotel tradicional en Chios",
    paragraphs: [
      "Voulamandis House está pensado para viajeros que valoran la calma, la comunicación directa y una base práctica para explorar la isla. La propiedad familiar ofrece una experiencia a pequeña escala entre los jardines de cítricos de Kambos.",
      "Puede elegir habitaciones dobles económicas, habitaciones en planta baja sin escaleras, habitaciones en planta superior y apartamentos familiares con cocina completa. Todas las opciones incluyen baño privado, aire acondicionado, Wi-Fi y frigorífico.",
      "La propiedad está a unos 3 km del aeropuerto de Chios y 6 km del puerto: lo bastante cerca para facilitar las llegadas, pero fuera de las calles más concurridas del centro.",
    ],
    benefits: [
      "Habitaciones y apartamentos familiares en lugar de un gran hotel",
      "Kambos histórico con jardín y ambiente de cítricos",
      "Opciones en planta baja para evitar escaleras",
      "Apartamentos familiares con cocina completa y zona de estar",
      "Ayuda directa para elegir la categoría adecuada",
      "Buen acceso por carretera a ciudad, playas y pueblos del sur",
    ],
    primaryCta: { label: "Ver habitaciones y apartamentos", href: "/es/habitaciones-en-chios/" },
    secondaryCta: { label: "Consultar tarifas directas", href: "/es/los-mejores-precios-de-hotel-en-la-isla-chios/" },
  },
  roomCategories: {
    kicker: "OPCIONES REALES DE ALOJAMIENTO",
    title: "Habitaciones y apartamentos en Voulamandis House",
    description: "Compare las principales categorías antes de introducir sus fechas. Los resultados en directo se basan en los datos actuales de disponibilidad del alojamiento.",
    items: [
      { title: "Habitaciones dobles económicas", label: "Opción de mejor precio para dos", text: "Habitaciones renovadas con cama doble, baño privado, aire acondicionado, Wi-Fi, televisión y frigorífico.", facts: ["2 huéspedes", "Aprox. 16 m²", "Baño privado"], image: chiosHotelsGuide.roomCategories.items[0].image, href: "/es/habitaciones-en-chios/economicas-habitaciones-en-chios/" },
      { title: "Habitaciones en planta baja", label: "Acceso fácil y sin escaleras", text: "Habitaciones dobles y triples con acceso directo al patio o al jardín, adecuadas para quienes prefieren la planta baja.", facts: ["2–3 huéspedes", "Sin escaleras", "Acceso al jardín"], image: chiosHotelsGuide.roomCategories.items[1].image, href: "/es/habitaciones-en-chios/habitaciones-dobles-estandar/" },
      { title: "Habitaciones en planta superior", label: "Terraza y vistas a los cítricos", text: "Habitaciones dobles y triples luminosas en la planta superior, con terraza compartida y zona de cocina en algunas opciones.", facts: ["2–4 huéspedes", "Planta superior", "Algunas con cocina"], image: chiosHotelsGuide.roomCategories.items[2].image, href: "/es/habitaciones-en-chios/habitaciones-dobles-estandar/" },
      { title: "Apartamentos familiares", label: "Más espacio y cocina completa", text: "Apartamentos independientes de 40–45 m² con dormitorio separado, zona de estar y cocina para familias y estancias más largas.", facts: ["Hasta 4 huéspedes", "40–45 m²", "Cocina completa"], image: chiosHotelsGuide.roomCategories.items[3].image, href: "/es/habitaciones-en-chios/apartamentos-familiares-en-chios/" },
    ],
  },
  planning: {
    kicker: "PLANIFIQUE MÁS ALLÁ DE LA HABITACIÓN",
    title: "Utilice su alojamiento como base para toda la isla",
    description: "Una búsqueda completa de hoteles en Chios debe considerar también los desplazamientos diarios. Estas guías locales explican distancias, rutas y experiencias accesibles desde Kambos.",
    links: [
      { title: "Guía de la isla de Chios", text: "Empiece por las zonas principales, las experiencias destacadas y las ideas prácticas para conocer la isla.", href: "/es/chios-en-grecia/" },
      { title: "Playas de Chios", text: "Compare playas organizadas, familiares y tranquilas en diferentes costas.", href: "/es/playas-chios/" },
      { title: "Pueblos de Chios", text: "Organice rutas por pueblos medievales de la masilla, montaña y costa.", href: "/es/pueblos-chios/" },
      { title: "Kambos histórico", text: "Conozca los jardines de cítricos, las mansiones de piedra y el paisaje alrededor del alojamiento.", href: "/es/chios/kampos-chios/" },
    ],
  },
  faq: {
    kicker: "PREGUNTAS SOBRE HOTELES EN CHIOS",
    title: "Lo que preguntan los viajeros antes de reservar alojamiento en Chios",
    items: [
      { question: "¿Cuál es la mejor zona para alojarse en Chios?", answer: "La ciudad de Chios es práctica para el puerto, los restaurantes y quienes no tienen coche. Kambos es una base histórica más tranquila cerca de la ciudad y del aeropuerto. Karfas sirve para estancias de playa y los pueblos de la masilla son adecuados con coche." },
      { question: "¿Hay hoteles cerca del aeropuerto de Chios?", answer: "Sí, varias zonas están a poca distancia en coche. Kambos es especialmente práctico porque está cerca del aeropuerto y es más tranquilo que el centro. Voulamandis House está a unos 3 km." },
      { question: "¿Dónde alojarse cerca del puerto de Chios?", answer: "Para llegar andando al puerto, el centro es la opción más cercana. Kambos se encuentra a unos 6 km y conviene a quienes prefieren una base tranquila y utilizan coche o taxi." },
      { question: "¿Kambos es una buena zona para alojarse?", answer: "Sí, sobre todo para viajeros que buscan carácter histórico, jardines y tranquilidad sin alejarse de la ciudad, el aeropuerto y las carreteras del sur." },
      { question: "¿Los apartamentos son mejores que los hoteles para familias?", answer: "Un apartamento suele ser más práctico cuando se necesita más espacio, cocina y una zona de estar separada. Un hotel tradicional puede encajar mejor cuando se priorizan más servicios dentro del establecimiento." },
      { question: "¿Cuánto cuesta el alojamiento en Chios?", answer: "Los precios cambian según temporada, zona, tipo de habitación, huéspedes y condiciones. Para Voulamandis House, introduzca sus fechas reales en la búsqueda en directo para obtener el precio actual." },
      { question: "¿Necesito coche en Chios?", answer: "No es imprescindible para una estancia corta en el centro, pero es muy útil para playas, pueblos de la masilla y diferentes partes de la isla." },
      { question: "¿Qué zona es mejor para las playas?", answer: "Karfas es práctica para una playa organizada. Quienes quieran visitar varias costas pueden preferir una base central próxima a la red principal de carreteras." },
      { question: "¿Hay habitaciones económicas en Chios?", answer: "Sí. Las habitaciones económicas y los alojamientos familiares pequeños pueden ser una alternativa asequible a hoteles grandes, especialmente para parejas." },
      { question: "¿Voulamandis House es un hotel?", answer: "No. Voulamandis House es un alojamiento familiar en Kambos con habitaciones privadas y apartamentos. No se presenta como hotel tradicional ni resort." },
      { question: "¿A qué distancia están el aeropuerto y el puerto?", answer: "Voulamandis House está a unos 3 km del aeropuerto de Chios y unos 6 km del puerto, por lo que resulta práctico para llegadas en avión o ferry." },
      { question: "¿Cómo consulto disponibilidad en directo?", answer: "Introduzca entrada, salida y número de huéspedes en la búsqueda de esta página. También puede utilizar el AI Room Finder o contactar directamente por WhatsApp." },
    ],
  },
  finalCta: {
    kicker: "DE LA BÚSQUEDA A UNA OPCIÓN REAL",
    title: "Consulte una estancia tranquila en Chios con fechas reales",
    text: "Compare las zonas, elija el tipo de alojamiento adecuado y utilice la búsqueda en directo para ver qué habitaciones o apartamentos están disponibles.",
    primaryCta: { label: "Buscar disponibilidad", href: "#live-availability" },
    secondaryCta: { label: "Ver todas las habitaciones", href: "/es/habitaciones-en-chios/" },
  },
};
