import { chiosHotelsGuide } from "@/content/chios-hotels-guide";
import type { ChiosHotelsGuideContent } from "@/content/chios-hotels-guide-types";

export const hotelsAufChiosGuide: ChiosHotelsGuideContent = {
  ...chiosHotelsGuide,
  seo: {
    canonicalPath: "/de/hotels-auf-chios/",
    title: "Hotels auf Chios | Regionen, Preise & Alternativen",
    description: "Vergleichen Sie Hotels auf Chios, Zimmer und Apartments nach Lage und Reisestil. Prüfen Sie echte Verfügbarkeit im Voulamandis House in Kambos.",
    image: chiosHotelsGuide.seo.image,
    imageAlt: "Zimmer und Apartments zwischen den Zitrusgärten von Kambos auf Chios",
  },
  hero: {
    kicker: "HOTELS AUF CHIOS & WO ÜBERNACHTEN",
    title: "Hotels auf Chios, Zimmer und Apartments: Wo auf der Insel übernachten?",
    description: "Sie suchen Hotels auf Chios? Dieser lokale Guide vergleicht die wichtigsten Gebiete der Insel, erklärt den Unterschied zwischen Hotels, Gästeunterkünften, Zimmern und Apartments und bietet eine echte Verfügbarkeitssuche für einen ruhigen Aufenthalt in Kambos.",
    disclosure: "Voulamandis House ist kein Hotel. Es ist eine familiengeführte Gästeunterkunft mit privaten Zimmern und Familienapartments in Kambos auf Chios.",
    primaryCta: { label: "Live-Verfügbarkeit suchen", href: "#live-availability" },
    secondaryCta: { label: "Gebiete vergleichen", href: "#where-to-stay" },
    aiCta: { label: "AI Room Finder fragen", href: "/ai-assistant/?lang=de" },
  },
  trustPoints: [
    { label: "Lokale Basis", value: "Historisches Kambos" },
    { label: "Flughafen Chios", value: "Etwa 3 km" },
    { label: "Hafen Chios", value: "Etwa 6 km" },
    { label: "Unterkunftsarten", value: "Zimmer & Apartments" },
    { label: "Ideal für", value: "Paare & Familien" },
    { label: "Live-Suche", value: "Echte Verfügbarkeit" },
  ],
  intro: {
    kicker: "MIT DER RICHTIGEN LAGE BEGINNEN",
    title: "Eine gute Suche nach Hotels auf Chios beginnt mit der Wahl des Gebiets",
    paragraphs: [
      "Bei der Suche nach Hotels auf Chios treffen oft mehrere Wünsche zusammen: Nähe zum Hafen, schneller Weg zum Flughafen, Strandnähe, Platz für eine Familie, eine ruhige Umgebung oder eine praktische Basis für Inseltouren mit dem Auto. Deshalb ist die Lage mindestens so wichtig wie das Zimmer selbst.",
      "Chios-Stadt ist praktisch für Hafen, Restaurants und Reisende ohne Auto. Kambos bietet ein ruhigeres historisches Umfeld nahe Stadt und Flughafen. Karfas und die nahe Küste eignen sich für einen strandorientierten Aufenthalt, während die Mastixdörfer eine traditionellere und abgelegenere Erfahrung bieten.",
      "Dieser Guide verwendet den Begriff „Hotels auf Chios“ so, wie Reisende ihn häufig suchen, unterscheidet aber klar zwischen klassischen Hotels, Gästehäusern, privaten Zimmern und Apartments. Voulamandis House gehört zur Gästeunterkunft und behauptet nicht, das Servicemodell eines Hotels oder Resorts anzubieten.",
    ],
  },
  areas: {
    kicker: "WO AUF CHIOS ÜBERNACHTEN",
    title: "Vergleichen Sie die wichtigsten Gebiete vor der Unterkunftswahl",
    description: "Jedes Gebiet schafft eine andere Art von Urlaub. Vergleichen Sie Erreichbarkeit, Atmosphäre und die Reisenden, für die es besonders geeignet ist.",
    items: [
      { id: "chios-town", title: "Chios-Stadt", badge: "Hafen & Stadtleben", text: "Praktisch für Fährankünfte, Restaurants, Geschäfte und Abendspaziergänge an der Uferpromenade. Ein Aufenthalt ohne Auto ist möglich, die Innenstadt ist jedoch lebhafter als ländliche Gebiete.", bestFor: "Kurzaufenthalte, Fährreisende und Gäste ohne Auto", link: "/de/chios-insel/" },
      { id: "kambos", title: "Kambos", badge: "Historisch & ruhig", text: "Zitrusgärten, hohe Steinmauern und alte Herrenhäuser prägen Kambos. Das Gebiet verbindet ruhige Atmosphäre mit schneller Fahrt nach Chios-Stadt, zum Flughafen und in den Süden.", bestFor: "Paare, Familien und Reisende mit Mietwagen", link: "/de/chios/kampos-chios/" },
      { id: "karfas", title: "Karfas und nahe Küste", badge: "Strandorientiert", text: "Ein bekanntes Küstengebiet mit organisiertem Strand und sommerlicher Atmosphäre. Geeignet für Gäste, die das Meer direkt in der Nähe ihrer Unterkunft wünschen.", bestFor: "Sommerurlaub und Strandaufenthalte", link: "/de/straende-chios/" },
      { id: "mastic-villages", title: "Mastixdörfer", badge: "Traditioneller Süden", text: "Mittelalterliche Dörfer wie Pyrgi und Mesta bieten besondere Architektur und starken lokalen Charakter. Ein Auto ist meist die praktischste Möglichkeit, dort zu wohnen oder die Region zu erkunden.", bestFor: "Rundfahrten, Geschichte und Dorfleben", link: "/de/doerfer-chios/" },
    ],
  },
  accommodationTypes: {
    kicker: "HOTEL, ZIMMER ODER APARTMENT?",
    title: "Wählen Sie die Unterkunftsart passend zu Ihren Prioritäten",
    description: "Hotel wird häufig als allgemeiner Suchbegriff verwendet, obwohl sich die tatsächlichen Unterkunftsarten auf Chios deutlich unterscheiden.",
    items: [
      { title: "Klassisches Hotel", idealFor: "Reisende mit Fokus auf Leistungen im Haus", features: "Rezeption, Gemeinschaftsbereiche und je nach Betrieb Restaurant, Pool oder weitere Dienstleistungen." },
      { title: "Familiengeführte Gästeunterkunft", idealFor: "Kleinere und persönlichere Aufenthalte", features: "Weniger Zimmer, direkter Kontakt zu den Gastgebern und eine ruhigere Atmosphäre als in einem großen Hotel oder Resort." },
      { title: "Privatzimmer", idealFor: "Paare und kurze Aufenthalte", features: "Eigenes Bad und wichtige Zimmerausstattung, häufig mit einfacherem Service und günstigem Preis." },
      { title: "Familienapartment", idealFor: "Familien und längere Aufenthalte", features: "Mehr Platz, separates Schlafzimmer, Wohnbereich und Küche für größere Unabhängigkeit." },
    ],
    note: "Voulamandis House ist eine familiengeführte Gästeunterkunft mit privaten Zimmern und Familienapartments. Es ist eine Alternative zu einem klassischen Hotel auf Chios und wird nicht als Hotel unter anderem Namen dargestellt.",
  },
  popularSearches: {
    kicker: "BELIEBTE SUCHEN NACH HOTELS AUF CHIOS",
    title: "Finden Sie die passende Unterkunft nach Lage, Budget und Reisestil",
    items: [
      { id: "chios-hotels-near-airport", title: "Hotels nahe dem Flughafen Chios", text: "Eine Unterkunft nahe dem Flughafen erleichtert frühe Abflüge, späte Ankünfte und kurze Inselaufenthalte. Kambos ist eines der praktischsten nahe gelegenen Gebiete und zugleich ruhiger als die Innenstadt.", cta: "Lage in Kambos ansehen", href: "#kambos-alternative" },
      { id: "chios-hotels-near-port", title: "Hotels und Zimmer nahe dem Hafen Chios", text: "Chios-Stadt ist die nächstgelegene Wahl für einen Fußweg zum Hafen. Kambos liegt weiter entfernt, ist aber mit Auto oder Taxi schnell erreichbar und bietet eine ruhigere Basis.", cta: "Chios-Stadt und Kambos vergleichen", href: "#where-to-stay" },
      { id: "family-hotels-chios", title: "Familienhotels und Apartments auf Chios", text: "Familien benötigen oft mehr als ein Standardzimmer. Apartments mit Küche und Wohnbereich bieten zusätzlichen Platz, während größere Zimmer für kleinere Familien und kürzere Aufenthalte geeignet sein können.", cta: "Familienapartments ansehen", href: "/de/zimmer-chios/familienapartments-in-chios/" },
      { id: "cheap-hotels-chios", title: "Günstige Hotels und preiswerte Zimmer auf Chios", text: "Ein niedrigerer Preis muss nicht den Verzicht auf eigenes Bad, Klimaanlage oder gute Lage bedeuten. Economy-Zimmer sind eine praktische Alternative für Paare, die tagsüber die Insel erkunden.", cta: "Economy-Zimmer ansehen", href: "/de/zimmer-chios/economy-zimmer-auf-chios/" },
      { id: "hotels-in-kambos-chios", title: "Hotels und Unterkünfte in Kambos", text: "Kambos ist für Zitrusgärten, historische Anwesen und seine Lage zwischen Stadt, Flughafen und südlichen Routen bekannt. Unterkünfte sind hier häufig kleiner und persönlicher.", cta: "Kambos entdecken", href: "/de/chios/kampos-chios/" },
      { id: "chios-hotels-near-beach", title: "Strandhotels und Unterkünfte am Meer", text: "Karfas ist eine bekannte Wahl für einen organisierten Strand. Wer verschiedene Küsten sehen möchte, profitiert oft von einer zentralen Basis mit guter Straßenanbindung.", cta: "Strände auf Chios entdecken", href: "/de/straende-chios/" },
    ],
  },
  kambosAlternative: {
    kicker: "EINE ANDERE ART ZU ÜBERNACHTEN",
    title: "Eine ruhigere Alternative zu einem klassischen Hotel auf Chios",
    paragraphs: [
      "Voulamandis House richtet sich an Reisende, die ruhige Umgebung, persönliche Kommunikation und eine praktische Basis zum Erkunden schätzen. Der familiengeführte Betrieb liegt zwischen den Zitrusgärten von Kambos.",
      "Zur Auswahl stehen Economy-Doppelzimmer, Erdgeschosszimmer ohne Treppen, Zimmer im Obergeschoss und Familienapartments mit vollständiger Küche. Alle Optionen verfügen über eigenes Bad, Klimaanlage, WLAN und Kühlschrank.",
      "Die Unterkunft liegt etwa 3 km vom Flughafen Chios und 6 km vom Hafen entfernt. Damit sind Ankünfte bequem, während Sie außerhalb der belebtesten Straßen der Stadt wohnen.",
    ],
    benefits: [
      "Familiengeführte Zimmer und Apartments statt eines großen Hotels",
      "Historisches Kambos mit Garten und Zitrusatmosphäre",
      "Erdgeschossoptionen für Gäste, die Treppen vermeiden",
      "Familienapartments mit vollständiger Küche und Wohnbereich",
      "Direkte Hilfe bei der Wahl der passenden Zimmerkategorie",
      "Gute Straßenverbindung zu Stadt, Stränden und südlichen Dörfern",
    ],
    primaryCta: { label: "Zimmer & Apartments ansehen", href: "/de/chios-zimmer/" },
    secondaryCta: { label: "Direktpreise prüfen", href: "/de/hotelpreise-auf-der-insel-chios/" },
  },
  roomCategories: {
    kicker: "ECHTE UNTERKUNFTSOPTIONEN",
    title: "Zimmer und Apartments im Voulamandis House",
    description: "Vergleichen Sie die wichtigsten Kategorien, bevor Sie Reisedaten eingeben. Live-Ergebnisse basieren auf den aktuellen Verfügbarkeitsdaten der Unterkunft.",
    items: [
      { title: "Economy-Doppelzimmer", label: "Preiswerte Wahl für zwei", text: "Renovierte Zimmer mit Doppelbett, eigenem Bad, Klimaanlage, WLAN, TV und Kühlschrank.", facts: ["2 Gäste", "Ca. 16 m²", "Eigenes Bad"], image: chiosHotelsGuide.roomCategories.items[0].image, href: "/de/zimmer-chios/economy-zimmer-auf-chios/" },
      { title: "Zimmer im Erdgeschoss", label: "Einfacher Zugang ohne Treppen", text: "Doppel- und Dreibettzimmer mit direktem Zugang zum Hof oder Garten für Gäste, die das Erdgeschoss bevorzugen.", facts: ["2–3 Gäste", "Keine Treppen", "Gartenzugang"], image: chiosHotelsGuide.roomCategories.items[1].image, href: "/de/zimmer-chios/standard-doppelzimmer-auf-chios/" },
      { title: "Zimmer im Obergeschoss", label: "Terrasse und Blick auf das Anwesen", text: "Helle Doppel- und Dreibettzimmer im Obergeschoss mit gemeinsamer Terrasse und Küchenzeile in ausgewählten Zimmern.", facts: ["2–4 Gäste", "Obergeschoss", "Teilweise Küchenzeile"], image: chiosHotelsGuide.roomCategories.items[2].image, href: "/de/zimmer-chios/standard-doppelzimmer-auf-chios/" },
      { title: "Familienapartments", label: "Mehr Platz und vollständige Küche", text: "Unabhängige Apartments mit 40–45 m², separatem Schlafzimmer, Wohnbereich und Küche für Familien und längere Aufenthalte.", facts: ["Bis 4 Gäste", "40–45 m²", "Vollständige Küche"], image: chiosHotelsGuide.roomCategories.items[3].image, href: "/de/zimmer-chios/familienapartments-in-chios/" },
    ],
  },
  planning: {
    kicker: "MEHR ALS NUR DAS ZIMMER PLANEN",
    title: "Nutzen Sie Ihre Unterkunft als Basis für die ganze Insel",
    description: "Eine gute Suche nach Hotels auf Chios berücksichtigt auch tägliche Wege. Diese lokalen Guides erklären Entfernungen, Routen und Erlebnisse, die von Kambos aus erreichbar sind.",
    links: [
      { title: "Chios-Inselguide", text: "Beginnen Sie mit den wichtigsten Gebieten, Erlebnissen und praktischen Ideen für die Insel.", href: "/de/chios-insel/" },
      { title: "Strände auf Chios", text: "Vergleichen Sie organisierte, familienfreundliche und ruhige Strände an verschiedenen Küsten.", href: "/de/straende-chios/" },
      { title: "Dörfer auf Chios", text: "Planen Sie Routen durch Mastixdörfer, Bergorte und Küstensiedlungen.", href: "/de/doerfer-chios/" },
      { title: "Historisches Kambos", text: "Erfahren Sie mehr über Zitrusgärten, Steinhäuser und die Umgebung der Unterkunft.", href: "/de/chios/kampos-chios/" },
    ],
  },
  faq: {
    kicker: "FAQ ZU HOTELS AUF CHIOS",
    title: "Fragen vor der Buchung einer Unterkunft auf Chios",
    items: [
      { question: "Welches Gebiet ist am besten zum Übernachten auf Chios?", answer: "Chios-Stadt ist praktisch für Hafen, Restaurants und Reisende ohne Auto. Kambos ist eine ruhigere historische Basis nahe Stadt und Flughafen. Karfas eignet sich für Strandurlaub, während die Mastixdörfer für Reisende mit Auto interessant sind." },
      { question: "Gibt es Hotels nahe dem Flughafen Chios?", answer: "Ja, mehrere Unterkunftsgebiete liegen nur eine kurze Fahrt entfernt. Kambos ist besonders praktisch, weil es nah am Flughafen und ruhiger als das Zentrum ist. Voulamandis House liegt etwa 3 km entfernt." },
      { question: "Wo sollte ich nahe dem Hafen Chios übernachten?", answer: "Für einen Fußweg zum Hafen ist Chios-Stadt am nächsten. Kambos liegt etwa 6 km entfernt und eignet sich für Gäste, die eine ruhigere Basis bevorzugen und Auto oder Taxi nutzen." },
      { question: "Ist Kambos ein gutes Gebiet zum Übernachten?", answer: "Ja, besonders für Reisende, die historischen Charakter, Gärten und Ruhe suchen und dennoch nahe an Stadt, Flughafen und den südlichen Straßen bleiben möchten." },
      { question: "Sind Apartments besser als Hotels für Familien?", answer: "Ein Apartment ist oft praktischer, wenn mehr Platz, Küche und separater Wohnbereich wichtig sind. Ein klassisches Hotel kann besser passen, wenn umfangreiche Leistungen im Haus im Vordergrund stehen." },
      { question: "Was kostet eine Unterkunft auf Chios?", answer: "Die Preise hängen von Saison, Lage, Zimmerart, Gästezahl und Buchungsbedingungen ab. Für Voulamandis House erhalten Sie den zuverlässigsten Preis durch Eingabe Ihrer echten Daten in die Live-Suche." },
      { question: "Brauche ich auf Chios ein Auto?", answer: "Für einen kurzen Aufenthalt in Chios-Stadt ist es nicht zwingend erforderlich. Für Strände, Mastixdörfer und verschiedene Inselregionen ist ein Auto jedoch sehr hilfreich." },
      { question: "Welches Gebiet ist am besten für Strände?", answer: "Karfas ist praktisch für einen organisierten Strand. Wer mehrere Küsten besuchen möchte, profitiert von einer zentralen Basis nahe dem Hauptstraßennetz." },
      { question: "Gibt es günstige Zimmer auf Chios?", answer: "Ja. Economy-Zimmer und kleinere familiengeführte Unterkünfte können eine preiswerte Alternative zu größeren Hotels sein, besonders für Paare." },
      { question: "Ist Voulamandis House ein Hotel?", answer: "Nein. Voulamandis House ist eine familiengeführte Gästeunterkunft in Kambos mit privaten Zimmern und Familienapartments. Es stellt sich nicht als klassisches Hotel oder Resort dar." },
      { question: "Wie weit sind Flughafen und Hafen entfernt?", answer: "Voulamandis House liegt etwa 3 km vom Flughafen Chios und etwa 6 km vom Hafen entfernt und ist daher für Flug- und Fährankünfte praktisch." },
      { question: "Wie prüfe ich die Live-Verfügbarkeit?", answer: "Geben Sie Anreise, Abreise und Gästezahl in die Live-Suche dieser Seite ein. Alternativ können Sie den AI Room Finder nutzen oder direkt per WhatsApp Kontakt aufnehmen." },
    ],
  },
  finalCta: {
    kicker: "VON DER SUCHE ZUR ECHTEN OPTION",
    title: "Prüfen Sie einen ruhigen Aufenthalt auf Chios mit echten Reisedaten",
    text: "Vergleichen Sie die Gebiete, wählen Sie die passende Unterkunftsart und nutzen Sie die Live-Suche, um aktuell verfügbare Zimmer oder Apartments zu sehen.",
    primaryCta: { label: "Verfügbarkeit suchen", href: "#live-availability" },
    secondaryCta: { label: "Alle Zimmer ansehen", href: "/de/chios-zimmer/" },
  },
};
