import { chiosHotelsGuide } from "@/content/chios-hotels-guide";
import type { ChiosHotelsGuideContent } from "@/content/chios-hotels-guide-types";

export const hotelsChiosGuideFr: ChiosHotelsGuideContent = {
  ...chiosHotelsGuide,
  seo: {
    canonicalPath: "/fr/hotels-chios/",
    title: "Hôtels à Chios | Où séjourner, prix & alternatives",
    description: "Comparez hôtels à Chios, chambres et appartements par zone et style de voyage. Consultez les disponibilités réelles du Voulamandis House à Kambos.",
    image: chiosHotelsGuide.seo.image,
    imageAlt: "Chambres et appartements dans les jardins d’agrumes de Kambos à Chios",
  },
  hero: {
    kicker: "HÔTELS À CHIOS & OÙ SÉJOURNER",
    title: "Hôtels à Chios, chambres et appartements : où séjourner sur l’île",
    description: "Vous recherchez des hôtels à Chios ? Ce guide local compare les principales zones de l’île, explique les différences entre hôtels, maisons d’hôtes, chambres et appartements, puis permet de vérifier les disponibilités réelles pour un séjour paisible à Kambos.",
    disclosure: "Voulamandis House n’est pas un hôtel. C’est un hébergement familial proposant des chambres et des appartements familiaux à Kambos, sur l’île de Chios.",
    primaryCta: { label: "Rechercher les disponibilités", href: "#live-availability" },
    secondaryCta: { label: "Comparer les zones", href: "#where-to-stay" },
    aiCta: { label: "Demander à l’AI Room Finder", href: "/ai-assistant/?lang=fr" },
  },
  trustPoints: [
    { label: "Base locale", value: "Kambos historique" },
    { label: "Aéroport de Chios", value: "Environ 3 km" },
    { label: "Port de Chios", value: "Environ 6 km" },
    { label: "Types de séjour", value: "Chambres & appartements" },
    { label: "Idéal pour", value: "Couples & familles" },
    { label: "Recherche en direct", value: "Disponibilités réelles" },
  ],
  intro: {
    kicker: "COMMENCEZ PAR LA BONNE ZONE",
    title: "Une bonne recherche d’hôtels à Chios commence par le choix du quartier",
    paragraphs: [
      "Une recherche d’hôtels à Chios réunit souvent plusieurs besoins : être proche du port, rejoindre facilement l’aéroport, avoir une plage à proximité, disposer d’espace pour une famille, trouver un environnement calme ou choisir une base pratique pour parcourir l’île en voiture. La zone compte donc autant que la chambre elle-même.",
      "Chios-ville convient au port, aux restaurants et aux voyageurs sans voiture. Kambos offre un cadre historique plus calme tout en restant proche de la ville et de l’aéroport. Karfas et la côte voisine conviennent à un séjour tourné vers la plage, tandis que les villages du mastic offrent une expérience plus traditionnelle et éloignée.",
      "Ce guide emploie l’expression « hôtels à Chios » comme les voyageurs la recherchent couramment, tout en distinguant clairement hôtels traditionnels, maisons d’hôtes, chambres et appartements indépendants. Voulamandis House appartient à la catégorie de l’hébergement familial et ne revendique pas les services d’un hôtel ou d’un resort.",
    ],
  },
  areas: {
    kicker: "OÙ SÉJOURNER À CHIOS",
    title: "Comparez les principales zones avant de choisir votre hébergement",
    description: "Chaque secteur crée un séjour différent. Comparez l’accès, l’ambiance et le type de voyageur auquel il correspond le mieux.",
    items: [
      { id: "chios-town", title: "Chios-ville", badge: "Port & vie urbaine", text: "Un choix pratique pour les arrivées en ferry, les restaurants, les commerces et les promenades sur le front de mer. Le centre peut convenir sans voiture, mais il est naturellement plus animé que la campagne.", bestFor: "Courts séjours, voyageurs en ferry et visiteurs sans voiture", link: "/fr/chios-en-grece/" },
      { id: "kambos", title: "Kambos", badge: "Historique & paisible", text: "Avec ses jardins d’agrumes, ses hauts murs de pierre et ses anciennes demeures, Kambos associe une atmosphère calme à un accès facile vers Chios-ville, l’aéroport et le sud de l’île.", bestFor: "Couples, familles et voyageurs découvrant l’île en voiture", link: "/fr/chios/kampos-chios/" },
      { id: "karfas", title: "Karfas et la côte proche", badge: "Séjour balnéaire", text: "Une zone côtière connue pour sa plage organisée et son ambiance estivale. Elle convient aux voyageurs qui souhaitent avoir la mer à proximité immédiate de leur hébergement.", bestFor: "Vacances d’été orientées plage", link: "/fr/plages-de-chios/" },
      { id: "mastic-villages", title: "Villages du mastic", badge: "Sud traditionnel", text: "Pyrgi, Mesta et les autres villages médiévaux offrent une architecture remarquable et une forte identité locale. Une voiture reste le moyen le plus pratique pour y séjourner ou les explorer.", bestFor: "Circuits en voiture, histoire et vie villageoise", link: "/fr/villages-de-chios/" },
    ],
  },
  accommodationTypes: {
    kicker: "HÔTEL, CHAMBRE OU APPARTEMENT ?",
    title: "Choisissez le type de séjour qui correspond à vos priorités",
    description: "Le mot hôtel sert souvent de terme de recherche général, mais les formes d’hébergement disponibles à Chios sont très différentes.",
    items: [
      { title: "Hôtel traditionnel", idealFor: "Voyageurs privilégiant les services sur place", features: "Réception, espaces communs et, selon l’établissement, restaurant, piscine ou services supplémentaires." },
      { title: "Maison d’hôtes familiale", idealFor: "Un séjour plus petit et plus personnel", features: "Moins de chambres, contact direct avec les hôtes et atmosphère plus calme qu’un grand hôtel ou resort." },
      { title: "Chambre privée", idealFor: "Couples et courts séjours", features: "Salle de bains privée et équipements essentiels, avec un service plus simple et souvent un tarif compétitif." },
      { title: "Appartement familial", idealFor: "Familles et séjours plus longs", features: "Davantage d’espace, chambre séparée, coin salon et cuisine pour plus d’autonomie." },
    ],
    note: "Voulamandis House est un hébergement familial avec chambres privées et appartements. Il constitue une alternative à un hôtel traditionnel à Chios et ne se présente pas comme un hôtel sous une autre appellation.",
  },
  popularSearches: {
    kicker: "RECHERCHES POPULAIRES D’HÔTELS À CHIOS",
    title: "Trouvez le séjour adapté à votre localisation, votre budget et votre voyage",
    items: [
      { id: "chios-hotels-near-airport", title: "Hôtels près de l’aéroport de Chios", text: "Séjourner près de l’aéroport facilite les départs matinaux, les arrivées tardives et les courts séjours. Kambos est l’une des zones proches les plus pratiques, avec un environnement plus calme que le centre.", cta: "Voir la situation à Kambos", href: "#kambos-alternative" },
      { id: "chios-hotels-near-port", title: "Hôtels et chambres près du port de Chios", text: "Le centre-ville est le choix le plus proche pour rejoindre le port à pied. Kambos est plus éloigné, mais reste facilement accessible en voiture ou en taxi tout en offrant une base plus paisible.", cta: "Comparer Chios-ville et Kambos", href: "#where-to-stay" },
      { id: "family-hotels-chios", title: "Hôtels familiaux et appartements à Chios", text: "Les familles ont souvent besoin de plus qu’une chambre standard. Un appartement avec cuisine et espace salon apporte davantage de place, tandis que certaines grandes chambres conviennent aux petites familles.", cta: "Voir les appartements familiaux", href: "/fr/chambres-a-chios/appartements-familiaux-de-chios/" },
      { id: "cheap-hotels-chios", title: "Hôtels pas chers et chambres économiques à Chios", text: "Un tarif plus accessible ne signifie pas forcément renoncer à une salle de bains privée, à la climatisation ou à une bonne situation. Les chambres économiques sont une solution pratique pour les couples.", cta: "Voir les chambres économiques", href: "/fr/chambres-a-chios/chambres-doubles-economiques/" },
      { id: "hotels-in-kambos-chios", title: "Hôtels et hébergements à Kambos", text: "Kambos est apprécié pour ses jardins d’agrumes, ses demeures historiques et sa position entre la ville, l’aéroport et les routes du sud. Les hébergements y sont souvent plus petits et personnels.", cta: "Découvrir Kambos", href: "/fr/chios/kampos-chios/" },
      { id: "chios-hotels-near-beach", title: "Hôtels de plage et hébergements en bord de mer", text: "Karfas est une option connue pour une plage organisée, mais Chios possède aussi des criques calmes. Une base centrale facilite la découverte d’une plage différente chaque jour.", cta: "Explorer les plages de Chios", href: "/fr/plages-de-chios/" },
    ],
  },
  kambosAlternative: {
    kicker: "UNE AUTRE FAÇON DE SÉJOURNER",
    title: "Une alternative plus paisible à un hôtel traditionnel à Chios",
    paragraphs: [
      "Voulamandis House s’adresse aux voyageurs qui apprécient le calme, le contact direct et une base pratique pour explorer l’île. L’établissement familial propose une expérience à taille humaine parmi les jardins d’agrumes de Kambos.",
      "Vous pouvez choisir une chambre double économique, une chambre au rez-de-chaussée sans escaliers, une chambre à l’étage ou un appartement familial avec cuisine complète. Chaque option comprend salle de bains privée, climatisation, Wi-Fi et réfrigérateur.",
      "L’établissement se trouve à environ 3 km de l’aéroport de Chios et 6 km du port : assez proche pour faciliter les arrivées, mais à l’écart des rues les plus fréquentées du centre.",
    ],
    benefits: [
      "Chambres et appartements familiaux plutôt qu’un grand hôtel",
      "Cadre historique de Kambos avec jardin et agrumes",
      "Options au rez-de-chaussée pour éviter les escaliers",
      "Appartements familiaux avec cuisine complète et salon",
      "Aide directe pour choisir la bonne catégorie",
      "Accès routier pratique vers la ville, les plages et les villages du sud",
    ],
    primaryCta: { label: "Voir chambres & appartements", href: "/fr/chambres-a-chios/" },
    secondaryCta: { label: "Voir les tarifs directs", href: "/fr/tarifs-des-hotels-a-chios/" },
  },
  roomCategories: {
    kicker: "OPTIONS RÉELLES D’HÉBERGEMENT",
    title: "Chambres et appartements au Voulamandis House",
    description: "Comparez les principales catégories avant de saisir vos dates. Les résultats en direct reposent sur les données actuelles de disponibilité de l’établissement.",
    items: [
      { title: "Chambres doubles économiques", label: "Meilleur rapport qualité-prix pour deux", text: "Chambres rénovées avec lit double, salle de bains privée, climatisation, Wi-Fi, télévision et réfrigérateur.", facts: ["2 personnes", "Environ 16 m²", "Salle de bains privée"], image: chiosHotelsGuide.roomCategories.items[0].image, href: "/fr/chambres-a-chios/chambres-doubles-economiques/" },
      { title: "Chambres au rez-de-chaussée", label: "Accès facile et sans escaliers", text: "Chambres doubles et triples avec accès direct vers la cour ou le jardin, adaptées aux personnes préférant le rez-de-chaussée.", facts: ["2–3 personnes", "Sans escaliers", "Accès jardin"], image: chiosHotelsGuide.roomCategories.items[1].image, href: "/fr/chambres-a-chios/chambres-doubles-standard/" },
      { title: "Chambres à l’étage", label: "Terrasse et vue sur les agrumes", text: "Chambres doubles et triples lumineuses à l’étage, avec terrasse commune et kitchenette dans certaines options.", facts: ["2–4 personnes", "À l’étage", "Certaines avec kitchenette"], image: chiosHotelsGuide.roomCategories.items[2].image, href: "/fr/chambres-a-chios/chambres-doubles-standard/" },
      { title: "Appartements familiaux", label: "Plus d’espace et cuisine complète", text: "Appartements indépendants de 40–45 m² avec chambre séparée, salon et cuisine pour les familles et les séjours prolongés.", facts: ["Jusqu’à 4 personnes", "40–45 m²", "Cuisine complète"], image: chiosHotelsGuide.roomCategories.items[3].image, href: "/fr/chambres-a-chios/appartements-familiaux-de-chios/" },
    ],
  },
  planning: {
    kicker: "PLANIFIEZ AU-DELÀ DE LA CHAMBRE",
    title: "Utilisez votre hébergement comme base pour toute l’île",
    description: "Une recherche complète d’hôtels à Chios doit aussi tenir compte des déplacements quotidiens. Ces guides locaux présentent les distances, les routes et les expériences accessibles depuis Kambos.",
    links: [
      { title: "Guide de l’île de Chios", text: "Découvrez les principales zones, les expériences essentielles et des idées pratiques pour explorer l’île.", href: "/fr/chios-en-grece/" },
      { title: "Plages de Chios", text: "Comparez plages organisées, rivages familiaux, criques calmes et paysages côtiers.", href: "/fr/plages-de-chios/" },
      { title: "Villages de Chios", text: "Préparez des itinéraires à travers les villages médiévaux du mastic et les villages côtiers.", href: "/fr/villages-de-chios/" },
      { title: "Kambos historique", text: "Découvrez les jardins d’agrumes, les demeures de pierre et le paysage autour de l’hébergement.", href: "/fr/chios/kampos-chios/" },
    ],
  },
  faq: {
    kicker: "FAQ HÔTELS À CHIOS",
    title: "Les questions posées avant de réserver un hébergement à Chios",
    items: [
      { question: "Quelle est la meilleure zone où séjourner à Chios ?", answer: "Chios-ville est pratique pour le port, les restaurants et les voyageurs sans voiture. Kambos offre une base historique plus calme près de la ville et de l’aéroport. Karfas convient aux séjours de plage, tandis que les villages du mastic sont adaptés aux voyageurs motorisés." },
      { question: "Existe-t-il des hôtels près de l’aéroport de Chios ?", answer: "Oui, plusieurs zones se trouvent à courte distance en voiture. Kambos est particulièrement pratique car il est proche de l’aéroport tout en étant plus calme que le centre. Voulamandis House se situe à environ 3 km." },
      { question: "Où séjourner près du port de Chios ?", answer: "Pour rejoindre le port à pied, Chios-ville est le choix le plus proche. Kambos se trouve à environ 6 km et convient aux voyageurs qui préfèrent une base calme et utilisent voiture ou taxi." },
      { question: "Kambos est-il un bon endroit où séjourner ?", answer: "Oui, surtout pour les voyageurs recherchant caractère historique, jardins et calme tout en restant proches de Chios-ville, de l’aéroport et des routes vers le sud." },
      { question: "Un appartement est-il préférable à un hôtel pour une famille ?", answer: "Un appartement est souvent plus pratique lorsqu’une cuisine, davantage d’espace et un salon séparé sont importants. Un hôtel traditionnel peut mieux convenir aux familles recherchant davantage de services sur place." },
      { question: "Combien coûte un hébergement à Chios ?", answer: "Les prix varient selon la saison, la zone, le type de chambre, le nombre de voyageurs et les conditions. Pour Voulamandis House, saisissez vos vraies dates dans la recherche en direct afin d’obtenir le tarif actuel." },
      { question: "Faut-il une voiture à Chios ?", answer: "Elle n’est pas indispensable pour un court séjour dans le centre, mais elle est très utile pour découvrir les plages, les villages du mastic et les différentes régions de l’île." },
      { question: "Quelle zone est la meilleure pour les plages ?", answer: "Karfas est pratique pour une plage organisée. Les voyageurs souhaitant découvrir plusieurs côtes peuvent préférer une base centrale proche du réseau routier principal." },
      { question: "Y a-t-il des chambres abordables à Chios ?", answer: "Oui. Les chambres économiques et les petits hébergements familiaux peuvent être une alternative plus accessible aux grands hôtels, particulièrement pour les couples." },
      { question: "Voulamandis House est-il un hôtel ?", answer: "Non. Voulamandis House est un hébergement familial à Kambos proposant des chambres privées et des appartements. Il ne se présente pas comme un hôtel traditionnel ou un resort." },
      { question: "À quelle distance se trouvent l’aéroport et le port ?", answer: "Voulamandis House se trouve à environ 3 km de l’aéroport de Chios et 6 km du port, ce qui facilite les arrivées en avion ou en ferry." },
      { question: "Comment vérifier les disponibilités en direct ?", answer: "Saisissez vos dates d’arrivée et de départ ainsi que le nombre de voyageurs dans la recherche de cette page. Vous pouvez aussi utiliser l’AI Room Finder ou contacter directement l’hébergement par WhatsApp." },
    ],
  },
  finalCta: {
    kicker: "DE LA RECHERCHE À UNE OPTION RÉELLE",
    title: "Vérifiez un séjour paisible à Chios avec vos vraies dates",
    text: "Comparez les zones, choisissez le type d’hébergement adapté à votre voyage et utilisez la recherche en direct pour voir les chambres ou appartements actuellement disponibles.",
    primaryCta: { label: "Rechercher les disponibilités", href: "#live-availability" },
    secondaryCta: { label: "Voir toutes les chambres", href: "/fr/chambres-a-chios/" },
  },
};
