import type { LanguageCode } from "@/lib/languages";
import { absoluteUrl } from "@/lib/seo";
import type { OrganizedBeachesPageData, OrganizedBeachCard } from "@/content/organized-beaches";

const images = {
  hero: "/images/beaches/agia-fotia-beach-chios.webp",
  karfas: "/images/beaches/karfas-beach-chios.webp",
  glari: "/images/beaches/paralia-glaron-beach-chios.webp",
  agiaFotia: "/images/beaches/agia-fotia-beach-chios.webp",
  daskalopetra: "/images/beaches/daskalopetra-beach-chios.webp",
  stay: "/images/beaches/voulamandis-house-courtyard-chios.webp",
};

export const nearbyBeachPaths: Record<LanguageCode, string> = {
  en: "/beaches-near-voulamandis-house/",
  el: "/el/kontines-paralies-voulamandis-house/",
  fr: "/fr/plages-proches-voulamandis-house/",
  de: "/de/straende-nahe-voulamandis-house/",
  it: "/it/spiagge-vicine-voulamandis-house/",
  es: "/es/playas-cerca-voulamandis-house/",
  tr: "/tr/voulamandis-house-yakin-plajlar/",
};

export const nearbyBeachAlternates = {
  en: absoluteUrl(nearbyBeachPaths.en),
  el: absoluteUrl(nearbyBeachPaths.el),
  fr: absoluteUrl(nearbyBeachPaths.fr),
  de: absoluteUrl(nearbyBeachPaths.de),
  it: absoluteUrl(nearbyBeachPaths.it),
  es: absoluteUrl(nearbyBeachPaths.es),
  tr: absoluteUrl(nearbyBeachPaths.tr),
  "x-default": absoluteUrl(nearbyBeachPaths.en),
};

const hrefs = {
  en: { karfas: "/chios/chios-beaches/#nearby-beaches", glari: "/chios/chios-beaches/#nearby-beaches", agiaFotia: "/chios/chios-beaches/agia-fotia-beach/", daskalopetra: "/chios/chios-beaches/#nearby-beaches", rooms: "/chios-rooms/", beaches: "/chios/chios-beaches/" },
  el: { karfas: "/el/paralies-xios/#nearby-beaches", glari: "/el/paralies-xios/#nearby-beaches", agiaFotia: "/el/paralies-xios/paralia-agia-fotia/", daskalopetra: "/el/paralies-xios/#nearby-beaches", rooms: "/el/domatia-xios/", beaches: "/el/paralies-xios/" },
  fr: { karfas: "/fr/plages-de-chios/#nearby-beaches", glari: "/fr/plages-de-chios/#nearby-beaches", agiaFotia: "/fr/plages-de-chios/plage-agia-fotia/", daskalopetra: "/fr/plages-de-chios/#nearby-beaches", rooms: "/fr/chambres-a-chios/", beaches: "/fr/plages-de-chios/" },
  de: { karfas: "/de/straende-chios/#nearby-beaches", glari: "/de/straende-chios/#nearby-beaches", agiaFotia: "/de/straende-chios/agia-fotia-strand/", daskalopetra: "/de/straende-chios/#nearby-beaches", rooms: "/de/chios-zimmer/", beaches: "/de/straende-chios/" },
  it: { karfas: "/it/spiagge-chios/#nearby-beaches", glari: "/it/spiagge-chios/#nearby-beaches", agiaFotia: "/it/spiagge-chios/spiaggia-agia-fotia/", daskalopetra: "/it/spiagge-chios/#nearby-beaches", rooms: "/it/camere-a-chios/", beaches: "/it/spiagge-chios/" },
  es: { karfas: "/es/playas-chios/#nearby-beaches", glari: "/es/playas-chios/#nearby-beaches", agiaFotia: "/es/playas-chios/playa-agia-fotia/", daskalopetra: "/es/playas-chios/#nearby-beaches", rooms: "/es/habitaciones-en-chios/", beaches: "/es/playas-chios/" },
  tr: { karfas: "/tr/sakiz-adasi-plajlari/#nearby-beaches", glari: "/tr/sakiz-adasi-plajlari/#nearby-beaches", agiaFotia: "/tr/sakiz-adasi-plajlari/agia-fotia-plaji/", daskalopetra: "/tr/sakiz-adasi-plajlari/#nearby-beaches", rooms: "/tr/sakiz-adasi-odalari/", beaches: "/tr/sakiz-adasi-plajlari/" },
} as const;

const copy = {
  en: { names: ["Karfas", "Glari Beach", "Agia Fotia", "Daskalopetra"], tag: "Nearby", desc: "A practical beach choice when staying at Voulamandis House and planning an easier drive from Kambos.", why: "Good when you want less driving and a simpler day by the sea." },
  el: { names: ["Καρφάς", "Παραλία των Γλάρων", "Αγία Φωτιά", "Δασκαλόπετρα"], tag: "Κοντινή", desc: "Πρακτική επιλογή για επισκέπτες του Voulamandis House που θέλουν πιο εύκολη διαδρομή από τον Κάμπο.", why: "Καλή όταν θέλετε λιγότερη οδήγηση και πιο απλή μέρα στη θάλασσα." },
  fr: { names: ["Karfas", "Plage de Glari", "Agia Fotia", "Daskalopetra"], tag: "Proche", desc: "Un choix pratique depuis Voulamandis House pour un trajet plus simple depuis Kambos.", why: "Idéal pour moins conduire et organiser une journée plus facile." },
  de: { names: ["Karfas", "Glari Beach", "Agia Fotia", "Daskalopetra"], tag: "Nahe", desc: "Eine praktische Strandwahl von Voulamandis House aus mit einfacher Fahrt ab Kambos.", why: "Gut für weniger Fahrzeit und einen einfacheren Strandtag." },
  it: { names: ["Karfas", "Spiaggia di Glari", "Agia Fotia", "Daskalopetra"], tag: "Vicina", desc: "Una scelta pratica da Voulamandis House per un tragitto più semplice da Kambos.", why: "Ideale per guidare meno e organizzare una giornata più semplice." },
  es: { names: ["Karfas", "Playa de Glari", "Agia Fotia", "Daskalopetra"], tag: "Cercana", desc: "Una opción práctica desde Voulamandis House para una ruta más sencilla desde Kambos.", why: "Buena para conducir menos y tener un día de playa más simple." },
  tr: { names: ["Karfas", "Glari Plajı", "Agia Fotia", "Daskalopetra"], tag: "Yakın", desc: "Kambos’tan daha kolay rota isteyen Voulamandis House misafirleri için pratik seçenek.", why: "Daha az araç kullanmak ve daha kolay bir deniz günü için iyi." },
} as const;

function cards(locale: LanguageCode): OrganizedBeachCard[] {
  const h = hrefs[locale];
  const c = copy[locale];
  return [
    { name: c.names[0], image: images.karfas, href: h.karfas, tag: c.tag, description: c.desc, why: c.why },
    { name: c.names[1], image: images.glari, href: h.glari, tag: c.tag, description: c.desc, why: c.why },
    { name: c.names[2], image: images.agiaFotia, href: h.agiaFotia, tag: c.tag, description: c.desc, why: c.why },
    { name: c.names[3], image: images.daskalopetra, href: h.daskalopetra, tag: c.tag, description: c.desc, why: c.why },
  ];
}

const tips = {
  en: [{ icon: "🚗", title: "Car or taxi recommended", text: "Voulamandis House is in Kambos, so a car or taxi makes beach days easier." }, { icon: "🕒", title: "Choose by time", text: "Nearby beaches are useful for half-day swimming or arrival/departure days." }, { icon: "📍", title: "Ask before leaving", text: "We can suggest the best nearby option for the day’s wind and mood." }],
  el: [{ icon: "🚗", title: "Προτείνεται αυτοκίνητο ή ταξί", text: "Το Voulamandis House βρίσκεται στον Κάμπο, οπότε αυτοκίνητο ή ταξί κάνει τις παραλίες πιο εύκολες." }, { icon: "🕒", title: "Διαλέξτε ανάλογα με τον χρόνο", text: "Οι κοντινές παραλίες είναι χρήσιμες για μισή μέρα ή για μέρες άφιξης/αναχώρησης." }, { icon: "📍", title: "Ρωτήστε πριν φύγετε", text: "Μπορούμε να σας προτείνουμε την καλύτερη κοντινή επιλογή ανάλογα με αέρα και διάθεση." }],
  fr: [{ icon: "🚗", title: "Voiture ou taxi conseillé", text: "Depuis Kambos, voiture ou taxi facilitent les journées plage." }, { icon: "🕒", title: "Choisir selon le temps", text: "Les plages proches sont pratiques pour une demi-journée." }, { icon: "📍", title: "Demandez avant de partir", text: "Nous pouvons suggérer la meilleure option proche selon la météo." }],
  de: [{ icon: "🚗", title: "Auto oder Taxi empfohlen", text: "Von Kambos aus machen Auto oder Taxi Strandtage einfacher." }, { icon: "🕒", title: "Nach Zeit wählen", text: "Nahe Strände sind praktisch für halbe Tage." }, { icon: "📍", title: "Vor Abfahrt fragen", text: "Wir empfehlen je nach Wind die passende nahe Option." }],
  it: [{ icon: "🚗", title: "Auto o taxi consigliati", text: "Da Kambos, auto o taxi rendono le giornate al mare più facili." }, { icon: "🕒", title: "Scegliete in base al tempo", text: "Le spiagge vicine sono pratiche per mezza giornata." }, { icon: "📍", title: "Chiedete prima di partire", text: "Possiamo suggerire l’opzione vicina migliore." }],
  es: [{ icon: "🚗", title: "Coche o taxi recomendado", text: "Desde Kambos, coche o taxi facilitan los días de playa." }, { icon: "🕒", title: "Elige según el tiempo", text: "Las playas cercanas son prácticas para medio día." }, { icon: "📍", title: "Pregunta antes de salir", text: "Podemos sugerir la mejor opción cercana." }],
  tr: [{ icon: "🚗", title: "Araç veya taksi önerilir", text: "Kambos’tan plajlara araç veya taksiyle gitmek daha kolaydır." }, { icon: "🕒", title: "Zamana göre seçin", text: "Yakın plajlar yarım gün için pratiktir." }, { icon: "📍", title: "Çıkmadan önce sorun", text: "Günün rüzgârına göre en iyi yakın seçeneği önerebiliriz." }],
};

export const nearbyBeachesPages: Record<LanguageCode, OrganizedBeachesPageData> = {
  en: { locale: "en", path: nearbyBeachPaths.en, seo: { canonicalPath: nearbyBeachPaths.en, title: "Beaches Near Voulamandis House | Chios", description: "A local guide to practical beaches near Voulamandis House in Kambos: Karfas, Glari Beach, Agia Fotia and Daskalopetra.", ogImage: images.hero }, hero: { eyebrow: "Nearby beaches", title: "Beaches near Voulamandis House for easy days from Kambos", subtitle: "Choose practical beaches when you want a shorter route, less driving and a simpler sea day from Voulamandis House.", image: { src: images.hero, alt: "Beach near Voulamandis House in Chios" }, primaryCta: { label: "See nearby beaches", href: "#organized-beaches" }, secondaryCta: { label: "All Chios beaches", href: hrefs.en.beaches } }, intro: { title: "When to choose a nearby beach", text: ["Nearby beaches are useful when you want a lighter plan from Kambos, especially on arrival days, departure days or afternoons with limited time.", "For this category we start with Karfas, Glari Beach, Agia Fotia and Daskalopetra."] }, highlights: { title: "Nearby beaches to consider", subtitle: "A practical list for guests staying at Voulamandis House.", cards: cards("en") }, tips: { title: "Quick tips for nearby beaches", items: tips.en }, stay: { title: "Stay in Kambos and keep beach days simple", text: "Voulamandis House is a calm base for guests who want local advice and practical beach routes around Chios.", image: images.stay, primaryCta: { label: "View rooms", href: hrefs.en.rooms }, secondaryCta: { label: "All beaches", href: hrefs.en.beaches } }, finalCta: { title: "Need the easiest beach option today?", text: "Ask us during your stay and we will suggest the best nearby beach for your timing and the wind.", primaryCta: { label: "View rooms", href: hrefs.en.rooms }, secondaryCta: { label: "Explore beaches", href: hrefs.en.beaches } } },
  el: { locale: "el", path: nearbyBeachPaths.el, seo: { canonicalPath: nearbyBeachPaths.el, title: "Κοντινές παραλίες από Voulamandis House | Χίος", description: "Τοπικός οδηγός για κοντινές παραλίες από το Voulamandis House στον Κάμπο: Καρφάς, Παραλία των Γλάρων, Αγία Φωτιά και Δασκαλόπετρα.", ogImage: images.hero }, hero: { eyebrow: "Κοντινές παραλίες", title: "Κοντινές παραλίες από το Voulamandis House για εύκολες μέρες από τον Κάμπο", subtitle: "Διαλέξτε πρακτικές παραλίες όταν θέλετε πιο σύντομη διαδρομή, λιγότερη οδήγηση και πιο απλή μέρα στη θάλασσα.", image: { src: images.hero, alt: "Κοντινή παραλία από το Voulamandis House στη Χίο" }, primaryCta: { label: "Δείτε κοντινές", href: "#organized-beaches" }, secondaryCta: { label: "Όλες οι παραλίες", href: hrefs.el.beaches } }, intro: { title: "Πότε να επιλέξετε κοντινή παραλία", text: ["Οι κοντινές παραλίες είναι χρήσιμες όταν θέλετε πιο ελαφρύ πρόγραμμα από τον Κάμπο, ειδικά σε μέρες άφιξης, αναχώρησης ή όταν έχετε λιγότερο χρόνο.", "Για αυτή την κατηγορία ξεκινάμε με Καρφά, Παραλία των Γλάρων, Αγία Φωτιά και Δασκαλόπετρα."] }, highlights: { title: "Κοντινές παραλίες που αξίζει να δείτε", subtitle: "Πρακτική λίστα για επισκέπτες που μένουν στο Voulamandis House.", cards: cards("el") }, tips: { title: "Γρήγορες συμβουλές για κοντινές παραλίες", items: tips.el }, stay: { title: "Μείνετε στον Κάμπο και κρατήστε τις παραλίες εύκολες", text: "Το Voulamandis House είναι ήρεμη βάση για επισκέπτες που θέλουν τοπική συμβουλή και πρακτικές διαδρομές στη Χίο.", image: images.stay, primaryCta: { label: "Δείτε δωμάτια", href: hrefs.el.rooms }, secondaryCta: { label: "Όλες οι παραλίες", href: hrefs.el.beaches } }, finalCta: { title: "Θέλετε την πιο εύκολη επιλογή για σήμερα;", text: "Ρωτήστε μας στη διαμονή σας και θα σας προτείνουμε την καλύτερη κοντινή παραλία ανάλογα με χρόνο και αέρα.", primaryCta: { label: "Δείτε δωμάτια", href: hrefs.el.rooms }, secondaryCta: { label: "Παραλίες Χίου", href: hrefs.el.beaches } } },
  fr: { locale: "fr", path: nearbyBeachPaths.fr, seo: { canonicalPath: nearbyBeachPaths.fr, title: "Plages proches de Voulamandis House | Chios", description: "Guide local des plages proches de Voulamandis House : Karfas, Glari, Agia Fotia et Daskalopetra.", ogImage: images.hero }, hero: { eyebrow: "Plages proches", title: "Plages proches de Voulamandis House pour des journées faciles", subtitle: "Choisissez des plages pratiques quand vous voulez moins de route depuis Kambos.", image: { src: images.hero, alt: "Plage proche de Voulamandis House" }, primaryCta: { label: "Voir les plages", href: "#organized-beaches" }, secondaryCta: { label: "Toutes les plages", href: hrefs.fr.beaches } }, intro: { title: "Quand choisir une plage proche", text: ["Les plages proches sont pratiques pour une demi-journée ou une journée légère depuis Kambos.", "Pour cette catégorie, commencez par Karfas, Glari, Agia Fotia et Daskalopetra."] }, highlights: { title: "Plages proches à considérer", subtitle: "Une liste pratique pour les hôtes de Voulamandis House.", cards: cards("fr") }, tips: { title: "Conseils rapides", items: tips.fr }, stay: { title: "Séjourner à Kambos simplifie les plages", text: "Voulamandis House est une base calme avec conseils locaux pour vos routes plage.", image: images.stay, primaryCta: { label: "Voir chambres", href: hrefs.fr.rooms }, secondaryCta: { label: "Toutes les plages", href: hrefs.fr.beaches } }, finalCta: { title: "Besoin de l’option la plus simple ?", text: "Demandez-nous et nous vous suggérerons la meilleure plage proche.", primaryCta: { label: "Voir chambres", href: hrefs.fr.rooms }, secondaryCta: { label: "Plages de Chios", href: hrefs.fr.beaches } } },
  de: { locale: "de", path: nearbyBeachPaths.de, seo: { canonicalPath: nearbyBeachPaths.de, title: "Strände nahe Voulamandis House | Chios", description: "Lokaler Guide zu Stränden nahe Voulamandis House: Karfas, Glari Beach, Agia Fotia und Daskalopetra.", ogImage: images.hero }, hero: { eyebrow: "Nahe Strände", title: "Strände nahe Voulamandis House für einfache Tage", subtitle: "Wählen Sie praktische Strände mit kürzerer Fahrt ab Kambos.", image: { src: images.hero, alt: "Strand nahe Voulamandis House" }, primaryCta: { label: "Strände ansehen", href: "#organized-beaches" }, secondaryCta: { label: "Alle Strände", href: hrefs.de.beaches } }, intro: { title: "Wann ein naher Strand passt", text: ["Nahe Strände sind praktisch für halbe Tage und leichte Pläne ab Kambos.", "Für diese Kategorie starten wir mit Karfas, Glari Beach, Agia Fotia und Daskalopetra."] }, highlights: { title: "Nahe Strände zur Auswahl", subtitle: "Eine praktische Liste für Gäste von Voulamandis House.", cards: cards("de") }, tips: { title: "Kurze Tipps", items: tips.de }, stay: { title: "Von Kambos bleiben Strandtage einfach", text: "Voulamandis House ist eine ruhige Basis mit lokalen Tipps für Ihre Strandrouten.", image: images.stay, primaryCta: { label: "Zimmer ansehen", href: hrefs.de.rooms }, secondaryCta: { label: "Alle Strände", href: hrefs.de.beaches } }, finalCta: { title: "Die einfachste Option für heute?", text: "Fragen Sie uns nach dem passenden nahen Strand.", primaryCta: { label: "Zimmer ansehen", href: hrefs.de.rooms }, secondaryCta: { label: "Chios Strände", href: hrefs.de.beaches } } },
  it: { locale: "it", path: nearbyBeachPaths.it, seo: { canonicalPath: nearbyBeachPaths.it, title: "Spiagge vicine a Voulamandis House | Chios", description: "Guida locale alle spiagge vicine a Voulamandis House: Karfas, Glari, Agia Fotia e Daskalopetra.", ogImage: images.hero }, hero: { eyebrow: "Spiagge vicine", title: "Spiagge vicine a Voulamandis House per giornate semplici", subtitle: "Scegliete spiagge pratiche quando volete guidare meno da Kambos.", image: { src: images.hero, alt: "Spiaggia vicina a Voulamandis House" }, primaryCta: { label: "Vedi spiagge", href: "#organized-beaches" }, secondaryCta: { label: "Tutte le spiagge", href: hrefs.it.beaches } }, intro: { title: "Quando scegliere una spiaggia vicina", text: ["Le spiagge vicine sono pratiche per mezza giornata o per un piano semplice da Kambos.", "Per questa categoria partiamo da Karfas, Glari, Agia Fotia e Daskalopetra."] }, highlights: { title: "Spiagge vicine da considerare", subtitle: "Una lista pratica per gli ospiti di Voulamandis House.", cards: cards("it") }, tips: { title: "Consigli rapidi", items: tips.it }, stay: { title: "Da Kambos le giornate al mare restano semplici", text: "Voulamandis House è una base tranquilla con consigli locali.", image: images.stay, primaryCta: { label: "Vedi camere", href: hrefs.it.rooms }, secondaryCta: { label: "Tutte le spiagge", href: hrefs.it.beaches } }, finalCta: { title: "Serve l’opzione più facile?", text: "Chiedeteci e vi suggeriremo la spiaggia vicina migliore.", primaryCta: { label: "Vedi camere", href: hrefs.it.rooms }, secondaryCta: { label: "Spiagge di Chios", href: hrefs.it.beaches } } },
  es: { locale: "es", path: nearbyBeachPaths.es, seo: { canonicalPath: nearbyBeachPaths.es, title: "Playas cerca de Voulamandis House | Quíos", description: "Guía local de playas cerca de Voulamandis House: Karfas, Glari, Agia Fotia y Daskalopetra.", ogImage: images.hero }, hero: { eyebrow: "Playas cercanas", title: "Playas cerca de Voulamandis House para días fáciles", subtitle: "Elige playas prácticas cuando quieres conducir menos desde Kambos.", image: { src: images.hero, alt: "Playa cerca de Voulamandis House" }, primaryCta: { label: "Ver playas", href: "#organized-beaches" }, secondaryCta: { label: "Todas las playas", href: hrefs.es.beaches } }, intro: { title: "Cuándo elegir una playa cercana", text: ["Las playas cercanas son prácticas para medio día o para un plan sencillo desde Kambos.", "Para esta categoría empezamos con Karfas, Glari, Agia Fotia y Daskalopetra."] }, highlights: { title: "Playas cercanas para considerar", subtitle: "Una lista práctica para huéspedes de Voulamandis House.", cards: cards("es") }, tips: { title: "Consejos rápidos", items: tips.es }, stay: { title: "Desde Kambos los días de playa son más simples", text: "Voulamandis House es una base tranquila con consejos locales.", image: images.stay, primaryCta: { label: "Ver habitaciones", href: hrefs.es.rooms }, secondaryCta: { label: "Todas las playas", href: hrefs.es.beaches } }, finalCta: { title: "¿Necesitas la opción más fácil?", text: "Pregúntanos y te sugeriremos la mejor playa cercana.", primaryCta: { label: "Ver habitaciones", href: hrefs.es.rooms }, secondaryCta: { label: "Playas de Quíos", href: hrefs.es.beaches } } },
  tr: { locale: "tr", path: nearbyBeachPaths.tr, seo: { canonicalPath: nearbyBeachPaths.tr, title: "Voulamandis House Yakın Plajlar | Sakız Adası", description: "Voulamandis House yakınındaki pratik plajlar: Karfas, Glari, Agia Fotia ve Daskalopetra.", ogImage: images.hero }, hero: { eyebrow: "Yakın plajlar", title: "Kambos’tan kolay günler için Voulamandis House’a yakın plajlar", subtitle: "Daha az araç kullanmak ve daha kolay deniz günü için pratik seçenekler seçin.", image: { src: images.hero, alt: "Voulamandis House yakınında plaj" }, primaryCta: { label: "Plajları gör", href: "#organized-beaches" }, secondaryCta: { label: "Tüm plajlar", href: hrefs.tr.beaches } }, intro: { title: "Ne zaman yakın plaj seçilmeli", text: ["Yakın plajlar Kambos’tan yarım gün veya daha hafif planlar için pratiktir.", "Bu kategori için Karfas, Glari, Agia Fotia ve Daskalopetra ile başlıyoruz."] }, highlights: { title: "Değerlendirilecek yakın plajlar", subtitle: "Voulamandis House misafirleri için pratik liste.", cards: cards("tr") }, tips: { title: "Hızlı ipuçları", items: tips.tr }, stay: { title: "Kambos’tan plaj günlerini kolay tutun", text: "Voulamandis House yerel önerilerle sakin bir başlangıç noktasıdır.", image: images.stay, primaryCta: { label: "Odaları gör", href: hrefs.tr.rooms }, secondaryCta: { label: "Tüm plajlar", href: hrefs.tr.beaches } }, finalCta: { title: "Bugün en kolay seçenek lazım mı?", text: "Bize sorun; en iyi yakın plajı önerelim.", primaryCta: { label: "Odaları gör", href: hrefs.tr.rooms }, secondaryCta: { label: "Sakız plajları", href: hrefs.tr.beaches } } },
};

export function getNearbyBeachesPageByLocale(locale: LanguageCode) { return nearbyBeachesPages[locale]; }
export function getNearbyBeachesPageByPath(path: string) { return Object.values(nearbyBeachesPages).find((page) => page.path === path); }

