import type { LanguageCode } from "@/lib/languages";
import { absoluteUrl } from "@/lib/seo";

export type OrganizedBeachCard = { name: string; image: string; href: string; tag: string; description: string; why: string };
export type OrganizedBeachesPageData = {
  locale: LanguageCode;
  path: string;
  seo: { canonicalPath: string; title: string; description: string; ogImage: string };
  hero: { eyebrow: string; title: string; subtitle: string; image: { src: string; alt: string }; primaryCta: { label: string; href: string }; secondaryCta: { label: string; href: string } };
  intro: { title: string; text: string[] };
  highlights: { title: string; subtitle: string; cards: OrganizedBeachCard[] };
  tips: { title: string; items: { icon: string; title: string; text: string }[] };
  stay: { title: string; text: string; image: string; primaryCta: { label: string; href: string }; secondaryCta: { label: string; href: string } };
  finalCta: { title: string; text: string; primaryCta: { label: string; href: string }; secondaryCta: { label: string; href: string } };
};

const images = {
  hero: "/images/beaches/42ba5ae2ff96d99dfb12b1e06fa90b45-e1703437426681.webp",
  karfas: "/images/beaches/agia-fotia.jpg",
  agiaFotia: "/images/beaches/agia-fotia.jpg",
  komi: "/images/beaches/42ba5ae2ff96d99dfb12b1e06fa90b45-e1703437426681.webp",
  emporios: "/images/beaches/emporios3-e1702727598897.webp",
  lefkathia: "/images/beaches/lefkathia-2.jpg",
  lithi: "/images/beaches/2017-06-28-1024x768.webp",
  stay: "/images/beaches/voulamandis-house-chios-courtyard-hero-desktop.webp",
};

export const organizedBeachPaths: Record<LanguageCode, string> = {
  en: "/chios-organized-beaches/",
  el: "/el/organomenes-paralies-xios/",
  fr: "/fr/plages-organisees-chios/",
  de: "/de/organisierte-straende-chios/",
  it: "/it/spiagge-attrezzate-chios/",
  es: "/es/playas-organizadas-quios/",
  tr: "/tr/sakiz-adasi-duzenli-plajlar/",
};

export const organizedBeachAlternates = {
  en: absoluteUrl(organizedBeachPaths.en),
  el: absoluteUrl(organizedBeachPaths.el),
  fr: absoluteUrl(organizedBeachPaths.fr),
  de: absoluteUrl(organizedBeachPaths.de),
  it: absoluteUrl(organizedBeachPaths.it),
  es: absoluteUrl(organizedBeachPaths.es),
  tr: absoluteUrl(organizedBeachPaths.tr),
  "x-default": absoluteUrl(organizedBeachPaths.en),
};

const hrefs = {
  en: { karfas: "/chios/chios-beaches/agia-fotia-beach/", agiaFotia: "/chios/chios-beaches/agia-fotia-beach/", komi: "/chios/chios-beaches/komi-beach/", emporios: "/chios/chios-beaches/emporios-beach/", lefkathia: "/chios/chios-beaches/lefkathia-beach/", lithi: "/chios/chios-beaches/lithi-beach/", rooms: "/chios-rooms/", beaches: "/chios/chios-beaches/" },
  el: { karfas: "/el/paralies-xios/paralia-agia-fotia/", agiaFotia: "/el/paralies-xios/paralia-agia-fotia/", komi: "/el/paralies-xios/paralia-komi/", emporios: "/el/paralies-xios/paralia-mavra-volia/", lefkathia: "/el/paralies-xios/paralia-lefkathia/", lithi: "/el/paralies-xios/paralia-lithi/", rooms: "/el/domatia-xios/", beaches: "/el/paralies-xios/" },
  fr: { karfas: "/fr/plages-de-chios/plage-agia-fotia/", agiaFotia: "/fr/plages-de-chios/plage-agia-fotia/", komi: "/fr/plages-de-chios/plage-komi/", emporios: "/fr/plages-de-chios/plage-mavra-volia/", lefkathia: "/fr/plages-de-chios/plage-lefkathia/", lithi: "/fr/plages-de-chios/plage-lithi/", rooms: "/fr/chambres-a-chios/", beaches: "/fr/plages-de-chios/" },
  de: { karfas: "/de/straende-chios/agia-fotia-strand/", agiaFotia: "/de/straende-chios/agia-fotia-strand/", komi: "/de/straende-chios/komi-strand/", emporios: "/de/straende-chios/mavra-volia-strand/", lefkathia: "/de/straende-chios/lefkathia-strand/", lithi: "/de/straende-chios/lithi-strand/", rooms: "/de/chios-zimmer/", beaches: "/de/straende-chios/" },
  it: { karfas: "/it/spiagge-chios/spiaggia-agia-fotia/", agiaFotia: "/it/spiagge-chios/spiaggia-agia-fotia/", komi: "/it/spiagge-chios/spiaggia-komi/", emporios: "/it/spiagge-chios/spiaggia-mavra-volia/", lefkathia: "/it/spiagge-chios/spiaggia-lefkathia/", lithi: "/it/spiagge-chios/spiaggia-lithi/", rooms: "/it/camere-a-chios/", beaches: "/it/spiagge-chios/" },
  es: { karfas: "/es/playas-chios/playa-agia-fotia/", agiaFotia: "/es/playas-chios/playa-agia-fotia/", komi: "/es/playas-chios/playa-komi/", emporios: "/es/playas-chios/playa-mavra-volia/", lefkathia: "/es/playas-chios/playa-lefkathia/", lithi: "/es/playas-chios/playa-lithi/", rooms: "/es/habitaciones-en-chios/", beaches: "/es/playas-chios/" },
  tr: { karfas: "/tr/sakiz-adasi-plajlari/agia-fotia-plaji/", agiaFotia: "/tr/sakiz-adasi-plajlari/agia-fotia-plaji/", komi: "/tr/sakiz-adasi-plajlari/komi-plaji/", emporios: "/tr/sakiz-adasi-plajlari/mavra-volia-plaji/", lefkathia: "/tr/sakiz-adasi-plajlari/lefkathia-plaji/", lithi: "/tr/sakiz-adasi-plajlari/lithi-plaji/", rooms: "/tr/sakiz-adasi-odalari/", beaches: "/tr/sakiz-adasi-plajlari/" },
} as const;

const names: Record<LanguageCode, string[]> = {
  en: ["Karfas", "Agia Fotia", "Komi", "Emporios", "Lefkathia", "Lithi"],
  el: ["Καρφάς", "Αγία Φωτιά", "Κώμη", "Εμπορειός", "Λευκάθια", "Λιθί"],
  fr: ["Karfas", "Agia Fotia", "Komi", "Emporios", "Lefkathia", "Lithi"],
  de: ["Karfas", "Agia Fotia", "Komi", "Emporios", "Lefkathia", "Lithi"],
  it: ["Karfas", "Agia Fotia", "Komi", "Emporios", "Lefkathia", "Lithi"],
  es: ["Karfas", "Agia Fotia", "Komi", "Emporios", "Lefkathia", "Lithi"],
  tr: ["Karfas", "Agia Fotia", "Komi", "Emporios", "Lefkathia", "Lithi"],
};

const common = {
  en: { tag: "Organized", desc: "A practical choice for easier access, nearby services and a comfortable sea day.", why: "Best when you want comfort and simple planning." },
  el: { tag: "Οργανωμένη", desc: "Πρακτική επιλογή για πιο εύκολη πρόσβαση, κοντινές υπηρεσίες και άνετη μέρα στη θάλασσα.", why: "Καλή όταν θέλετε άνεση και απλό πρόγραμμα." },
  fr: { tag: "Organisée", desc: "Un choix pratique pour un accès simple, des services proches et une journée confortable.", why: "Idéale pour le confort et une organisation simple." },
  de: { tag: "Organisiert", desc: "Eine praktische Wahl für einfacheren Zugang, nahe Services und einen entspannten Strandtag.", why: "Gut für Komfort und einfache Planung." },
  it: { tag: "Attrezzata", desc: "Una scelta pratica per accesso semplice, servizi vicini e una giornata comoda.", why: "Ideale per comfort e organizzazione semplice." },
  es: { tag: "Organizada", desc: "Una opción práctica para acceso fácil, servicios cercanos y un día cómodo.", why: "Buena para comodidad y planificación sencilla." },
  tr: { tag: "Düzenli", desc: "Kolay ulaşım, yakın hizmetler ve rahat bir deniz günü için pratik seçenek.", why: "Konfor ve kolay planlama isteyenler için iyi." },
};

function cards(locale: LanguageCode): OrganizedBeachCard[] {
  const h = hrefs[locale];
  const c = common[locale];
  const n = names[locale];
  return [
    { name: n[0], image: images.karfas, href: h.karfas, tag: c.tag, description: c.desc, why: c.why },
    { name: n[1], image: images.agiaFotia, href: h.agiaFotia, tag: c.tag, description: c.desc, why: c.why },
    { name: n[2], image: images.komi, href: h.komi, tag: c.tag, description: c.desc, why: c.why },
    { name: n[3], image: images.emporios, href: h.emporios, tag: c.tag, description: c.desc, why: c.why },
    { name: n[4], image: images.lefkathia, href: h.lefkathia, tag: c.tag, description: c.desc, why: c.why },
    { name: n[5], image: images.lithi, href: h.lithi, tag: c.tag, description: c.desc, why: c.why },
  ];
}

const baseTips = {
  en: [{ icon: "⛱", title: "Arrive earlier", text: "Popular organized beaches can get busy in high season." }, { icon: "🚗", title: "Check parking", text: "Parking and access can change depending on the time of day." }, { icon: "🌬️", title: "Ask about wind", text: "Local advice helps you pick the best organized beach for the day." }],
  el: [{ icon: "⛱", title: "Πηγαίνετε νωρίτερα", text: "Οι δημοφιλείς οργανωμένες παραλίες γεμίζουν πιο εύκολα την υψηλή περίοδο." }, { icon: "🚗", title: "Δείτε την πρόσβαση", text: "Το parking και η πρόσβαση αλλάζουν ανάλογα με την ώρα." }, { icon: "🌬️", title: "Ρωτήστε για τον αέρα", text: "Η τοπική συμβουλή βοηθά να διαλέξετε σωστά ανάλογα με τη μέρα." }],
  fr: [{ icon: "⛱", title: "Arrivez plus tôt", text: "Les plages populaires peuvent se remplir en haute saison." }, { icon: "🚗", title: "Vérifiez l’accès", text: "Parking et accès changent selon l’heure." }, { icon: "🌬️", title: "Demandez pour le vent", text: "Un conseil local aide à choisir la bonne plage." }],
  de: [{ icon: "⛱", title: "Früher ankommen", text: "Beliebte Strände werden in der Hochsaison schnell voller." }, { icon: "🚗", title: "Zugang prüfen", text: "Parken und Zugang hängen von der Tageszeit ab." }, { icon: "🌬️", title: "Nach Wind fragen", text: "Lokale Tipps helfen bei der richtigen Wahl." }],
  it: [{ icon: "⛱", title: "Arrivate prima", text: "Le spiagge popolari possono riempirsi in alta stagione." }, { icon: "🚗", title: "Controllate l’accesso", text: "Parcheggio e accesso cambiano con l’orario." }, { icon: "🌬️", title: "Chiedete del vento", text: "I consigli locali aiutano a scegliere bene." }],
  es: [{ icon: "⛱", title: "Llega antes", text: "Las playas populares pueden llenarse en temporada alta." }, { icon: "🚗", title: "Comprueba el acceso", text: "Parking y acceso cambian según la hora." }, { icon: "🌬️", title: "Pregunta por el viento", text: "El consejo local ayuda a elegir bien." }],
  tr: [{ icon: "⛱", title: "Erken gidin", text: "Popüler düzenli plajlar yüksek sezonda kalabalık olabilir." }, { icon: "🚗", title: "Ulaşımı kontrol edin", text: "Park ve erişim günün saatine göre değişebilir." }, { icon: "🌬️", title: "Rüzgârı sorun", text: "Yerel öneriler doğru plajı seçmeye yardım eder." }],
};

export const organizedBeachesPages: Record<LanguageCode, OrganizedBeachesPageData> = {
  en: { locale: "en", path: organizedBeachPaths.en, seo: { canonicalPath: organizedBeachPaths.en, title: "Organized Beaches in Chios | Voulamandis House", description: "A local guide to organized beaches in Chios: Karfas, Agia Fotia, Komi, Emporios, Lefkathia and Lithi, with practical tips from Voulamandis House.", ogImage: images.hero }, hero: { eyebrow: "Organized beach guide", title: "Organized beaches in Chios for easy summer days", subtitle: "Choose practical beaches with easier access, beach service, cafés, taverns or a more comfortable setup for your day by the sea.", image: { src: images.hero, alt: "Organized beach in Chios" }, primaryCta: { label: "See beaches", href: "#organized-beaches" }, secondaryCta: { label: "All Chios beaches", href: hrefs.en.beaches } }, intro: { title: "When to choose an organized beach", text: ["Organized beaches are useful when you want less planning and more comfort: easier access, places for coffee or food and a more straightforward day by the sea.", "For this category we start with Karfas, Agia Fotia, Komi, Emporios, Lefkathia and Lithi."] }, highlights: { title: "Organized beaches to consider", subtitle: "A practical list for visitors who want comfort, services and easier planning.", cards: cards("en") }, tips: { title: "Quick tips for organized beaches", items: baseTips.en }, stay: { title: "Start your beach days from Kambos", text: "Voulamandis House is a practical base for organized beach days around Chios, with local advice before you drive.", image: images.stay, primaryCta: { label: "View rooms", href: hrefs.en.rooms }, secondaryCta: { label: "All beaches", href: hrefs.en.beaches } }, finalCta: { title: "Want the easiest beach day?", text: "Ask us during your stay and we will suggest the organized beach that fits the day’s weather and your route.", primaryCta: { label: "View rooms", href: hrefs.en.rooms }, secondaryCta: { label: "Explore beaches", href: hrefs.en.beaches } } },
  el: { locale: "el", path: organizedBeachPaths.el, seo: { canonicalPath: organizedBeachPaths.el, title: "Οργανωμένες παραλίες Χίου | Voulamandis House", description: "Τοπικός οδηγός για οργανωμένες παραλίες στη Χίο: Καρφάς, Αγία Φωτιά, Κώμη, Εμπορειός, Λευκάθια και Λιθί, με πρακτικές συμβουλές.", ogImage: images.hero }, hero: { eyebrow: "Οργανωμένες παραλίες", title: "Οργανωμένες παραλίες στη Χίο για εύκολες καλοκαιρινές μέρες", subtitle: "Διαλέξτε πρακτικές παραλίες με πιο εύκολη πρόσβαση, beach service, καφέ, ταβέρνες ή πιο άνετη οργάνωση για τη μέρα σας στη θάλασσα.", image: { src: images.hero, alt: "Οργανωμένη παραλία στη Χίο" }, primaryCta: { label: "Δείτε παραλίες", href: "#organized-beaches" }, secondaryCta: { label: "Όλες οι παραλίες", href: hrefs.el.beaches } }, intro: { title: "Πότε να επιλέξετε οργανωμένη παραλία", text: ["Οι οργανωμένες παραλίες είναι χρήσιμες όταν θέλετε λιγότερη ταλαιπωρία και περισσότερη άνεση: εύκολη πρόσβαση, επιλογές για καφέ ή φαγητό και πιο απλό πρόγραμμα.", "Για αυτή την κατηγορία ξεκινάμε με Καρφά, Αγία Φωτιά, Κώμη, Εμπορειό, Λευκάθια και Λιθί."] }, highlights: { title: "Οργανωμένες παραλίες που αξίζει να δείτε", subtitle: "Πρακτική λίστα για επισκέπτες που θέλουν άνεση, υπηρεσίες και πιο εύκολο πρόγραμμα.", cards: cards("el") }, tips: { title: "Γρήγορες συμβουλές", items: baseTips.el }, stay: { title: "Ξεκινήστε τις παραλίες από τον Κάμπο", text: "Το Voulamandis House είναι πρακτική βάση για οργανωμένες παραλίες στη Χίο, με τοπική καθοδήγηση πριν ξεκινήσετε.", image: images.stay, primaryCta: { label: "Δείτε δωμάτια", href: hrefs.el.rooms }, secondaryCta: { label: "Όλες οι παραλίες", href: hrefs.el.beaches } }, finalCta: { title: "Θέλετε την πιο εύκολη beach day;", text: "Ρωτήστε μας στη διαμονή σας και θα σας προτείνουμε την οργανωμένη παραλία που ταιριάζει στον καιρό και στη διαδρομή σας.", primaryCta: { label: "Δείτε δωμάτια", href: hrefs.el.rooms }, secondaryCta: { label: "Παραλίες Χίου", href: hrefs.el.beaches } } },
  fr: { locale: "fr", path: organizedBeachPaths.fr, seo: { canonicalPath: organizedBeachPaths.fr, title: "Plages organisées à Chios | Voulamandis House", description: "Guide local des plages organisées à Chios : Karfas, Agia Fotia, Komi, Emporios, Lefkathia et Lithi, avec conseils pratiques.", ogImage: images.hero }, hero: { eyebrow: "Plages organisées", title: "Plages organisées à Chios pour des journées faciles", subtitle: "Choisissez des plages pratiques avec accès plus simple, services, cafés, tavernes ou une organisation plus confortable.", image: { src: images.hero, alt: "Plage organisée à Chios" }, primaryCta: { label: "Voir les plages", href: "#organized-beaches" }, secondaryCta: { label: "Toutes les plages", href: hrefs.fr.beaches } }, intro: { title: "Quand choisir une plage organisée", text: ["Les plages organisées sont utiles si vous voulez moins de contraintes et plus de confort : accès simple, café ou repas proche et journée plus facile.", "Pour cette catégorie, commencez par Karfas, Agia Fotia, Komi, Emporios, Lefkathia et Lithi."] }, highlights: { title: "Plages organisées à considérer", subtitle: "Une liste pratique pour plus de confort et de services.", cards: cards("fr") }, tips: { title: "Conseils rapides", items: baseTips.fr }, stay: { title: "Commencez vos journées plage depuis Kambos", text: "Voulamandis House est une base pratique pour organiser vos plages à Chios avec conseils locaux.", image: images.stay, primaryCta: { label: "Voir chambres", href: hrefs.fr.rooms }, secondaryCta: { label: "Toutes les plages", href: hrefs.fr.beaches } }, finalCta: { title: "Envie d’une journée plage facile ?", text: "Demandez-nous pendant votre séjour et nous vous proposerons la plage adaptée à la météo.", primaryCta: { label: "Voir chambres", href: hrefs.fr.rooms }, secondaryCta: { label: "Plages de Chios", href: hrefs.fr.beaches } } },
  de: { locale: "de", path: organizedBeachPaths.de, seo: { canonicalPath: organizedBeachPaths.de, title: "Organisierte Strände auf Chios | Voulamandis House", description: "Lokaler Guide zu organisierten Stränden auf Chios: Karfas, Agia Fotia, Komi, Emporios, Lefkathia und Lithi, mit praktischen Tipps.", ogImage: images.hero }, hero: { eyebrow: "Organisierte Strände", title: "Organisierte Strände auf Chios für einfache Sommertage", subtitle: "Wählen Sie praktische Strände mit leichterem Zugang, Service, Cafés, Tavernen oder komfortabler Planung.", image: { src: images.hero, alt: "Organisierter Strand auf Chios" }, primaryCta: { label: "Strände ansehen", href: "#organized-beaches" }, secondaryCta: { label: "Alle Strände", href: hrefs.de.beaches } }, intro: { title: "Wann ein organisierter Strand sinnvoll ist", text: ["Organisierte Strände sind praktisch, wenn Sie weniger Planung und mehr Komfort wünschen: leichter Zugang, Kaffee oder Essen in der Nähe und ein einfacher Strandtag.", "Für diese Kategorie starten wir mit Karfas, Agia Fotia, Komi, Emporios, Lefkathia und Lithi."] }, highlights: { title: "Organisierte Strände zur Auswahl", subtitle: "Eine praktische Liste für Komfort, Services und einfache Planung.", cards: cards("de") }, tips: { title: "Kurze Tipps", items: baseTips.de }, stay: { title: "Strandtage von Kambos starten", text: "Voulamandis House ist eine praktische Basis für organisierte Strandtage auf Chios mit lokalen Tipps.", image: images.stay, primaryCta: { label: "Zimmer ansehen", href: hrefs.de.rooms }, secondaryCta: { label: "Alle Strände", href: hrefs.de.beaches } }, finalCta: { title: "Einfacher Strandtag gesucht?", text: "Fragen Sie uns während Ihres Aufenthalts nach der passenden organisierten Strandoption.", primaryCta: { label: "Zimmer ansehen", href: hrefs.de.rooms }, secondaryCta: { label: "Chios Strände", href: hrefs.de.beaches } } },
  it: { locale: "it", path: organizedBeachPaths.it, seo: { canonicalPath: organizedBeachPaths.it, title: "Spiagge attrezzate a Chios | Voulamandis House", description: "Guida locale alle spiagge attrezzate a Chios: Karfas, Agia Fotia, Komi, Emporios, Lefkathia e Lithi, con consigli pratici.", ogImage: images.hero }, hero: { eyebrow: "Spiagge attrezzate", title: "Spiagge attrezzate a Chios per giornate semplici", subtitle: "Scegliete spiagge pratiche con accesso più facile, servizi, caffè, taverne o una giornata più comoda.", image: { src: images.hero, alt: "Spiaggia attrezzata a Chios" }, primaryCta: { label: "Vedi spiagge", href: "#organized-beaches" }, secondaryCta: { label: "Tutte le spiagge", href: hrefs.it.beaches } }, intro: { title: "Quando scegliere una spiaggia attrezzata", text: ["Le spiagge attrezzate sono utili quando volete meno pianificazione e più comfort: accesso facile, caffè o cibo vicino e una giornata più semplice.", "Per questa categoria partiamo da Karfas, Agia Fotia, Komi, Emporios, Lefkathia e Lithi."] }, highlights: { title: "Spiagge attrezzate da considerare", subtitle: "Una lista pratica per comfort, servizi e pianificazione facile.", cards: cards("it") }, tips: { title: "Consigli rapidi", items: baseTips.it }, stay: { title: "Partite da Kambos per le giornate al mare", text: "Voulamandis House è una base pratica per spiagge attrezzate a Chios, con consigli locali.", image: images.stay, primaryCta: { label: "Vedi camere", href: hrefs.it.rooms }, secondaryCta: { label: "Tutte le spiagge", href: hrefs.it.beaches } }, finalCta: { title: "Volete una giornata al mare facile?", text: "Chiedeteci durante il soggiorno e vi suggeriremo la spiaggia più adatta.", primaryCta: { label: "Vedi camere", href: hrefs.it.rooms }, secondaryCta: { label: "Spiagge di Chios", href: hrefs.it.beaches } } },
  es: { locale: "es", path: organizedBeachPaths.es, seo: { canonicalPath: organizedBeachPaths.es, title: "Playas organizadas en Quíos | Voulamandis House", description: "Guía local de playas organizadas en Quíos: Karfas, Agia Fotia, Komi, Emporios, Lefkathia y Lithi, con consejos prácticos.", ogImage: images.hero }, hero: { eyebrow: "Playas organizadas", title: "Playas organizadas en Quíos para días fáciles", subtitle: "Elige playas prácticas con acceso más fácil, servicios, cafés, tabernas o una organización más cómoda.", image: { src: images.hero, alt: "Playa organizada en Quíos" }, primaryCta: { label: "Ver playas", href: "#organized-beaches" }, secondaryCta: { label: "Todas las playas", href: hrefs.es.beaches } }, intro: { title: "Cuándo elegir una playa organizada", text: ["Las playas organizadas son útiles si quieres menos planificación y más comodidad: acceso fácil, café o comida cerca y un día más sencillo.", "Para esta categoría empezamos con Karfas, Agia Fotia, Komi, Emporios, Lefkathia y Lithi."] }, highlights: { title: "Playas organizadas para considerar", subtitle: "Una lista práctica para comodidad, servicios y planificación fácil.", cards: cards("es") }, tips: { title: "Consejos rápidos", items: baseTips.es }, stay: { title: "Empieza los días de playa desde Kambos", text: "Voulamandis House es una base práctica para playas organizadas en Quíos, con consejos locales.", image: images.stay, primaryCta: { label: "Ver habitaciones", href: hrefs.es.rooms }, secondaryCta: { label: "Todas las playas", href: hrefs.es.beaches } }, finalCta: { title: "¿Quieres un día de playa fácil?", text: "Pregúntanos durante tu estancia y te sugeriremos la opción adecuada.", primaryCta: { label: "Ver habitaciones", href: hrefs.es.rooms }, secondaryCta: { label: "Playas de Quíos", href: hrefs.es.beaches } } },
  tr: { locale: "tr", path: organizedBeachPaths.tr, seo: { canonicalPath: organizedBeachPaths.tr, title: "Sakız Adası Düzenli Plajlar | Voulamandis House", description: "Sakız Adası’nda düzenli plajlar: Karfas, Agia Fotia, Komi, Emporios, Lefkathia ve Lithi. Voulamandis House’tan pratik öneriler.", ogImage: images.hero }, hero: { eyebrow: "Düzenli plajlar", title: "Kolay yaz günleri için Sakız Adası düzenli plajları", subtitle: "Daha kolay ulaşım, hizmet, kafe, taverna veya konforlu bir deniz günü için pratik plajlar seçin.", image: { src: images.hero, alt: "Sakız Adası’nda düzenli plaj" }, primaryCta: { label: "Plajları gör", href: "#organized-beaches" }, secondaryCta: { label: "Tüm plajlar", href: hrefs.tr.beaches } }, intro: { title: "Ne zaman düzenli plaj seçilmeli", text: ["Düzenli plajlar daha az planlama ve daha çok konfor istediğinizde kullanışlıdır: kolay ulaşım, yakın yemek veya kahve seçenekleri ve daha basit bir gün.", "Bu kategori için Karfas, Agia Fotia, Komi, Emporios, Lefkathia ve Lithi ile başlıyoruz."] }, highlights: { title: "Değerlendirilecek düzenli plajlar", subtitle: "Konfor, hizmet ve kolay planlama isteyenler için pratik liste.", cards: cards("tr") }, tips: { title: "Hızlı ipuçları", items: baseTips.tr }, stay: { title: "Plaj günlerine Kambos’tan başlayın", text: "Voulamandis House, Sakız Adası’ndaki düzenli plajlar için yerel önerilerle pratik bir başlangıç noktasıdır.", image: images.stay, primaryCta: { label: "Odaları gör", href: hrefs.tr.rooms }, secondaryCta: { label: "Tüm plajlar", href: hrefs.tr.beaches } }, finalCta: { title: "Kolay bir plaj günü ister misiniz?", text: "Konaklamanız sırasında bize sorun; hava ve rotanıza uygun düzenli plajı önerelim.", primaryCta: { label: "Odaları gör", href: hrefs.tr.rooms }, secondaryCta: { label: "Sakız plajları", href: hrefs.tr.beaches } } },
};

export function getOrganizedBeachesPageByLocale(locale: LanguageCode) { return organizedBeachesPages[locale]; }
export function getOrganizedBeachesPageByPath(path: string) { return Object.values(organizedBeachesPages).find((page) => page.path === path); }
