import type { LanguageCode } from "@/lib/languages";
import { absoluteUrl } from "@/lib/seo";
import type { OrganizedBeachesPageData, OrganizedBeachCard } from "@/content/organized-beaches";

const images = {
  hero: "/images/beaches/salagona-e1645969502155.webp",
  elinta: "/images/beaches/salagona-e1645969502155.webp",
  vroulidia: "/images/beaches/vroulidia-2-1.jpg",
  nagos: "/images/beaches/nagos-2.jpg",
  stay: "/images/beaches/voulamandis-house-chios-courtyard-hero-desktop.webp",
};

export const quietBeachPaths: Record<LanguageCode, string> = {
  en: "/chios-quiet-beaches/",
  el: "/el/isixes-paralies-xios/",
  fr: "/fr/plages-calmes-chios/",
  de: "/de/ruhige-straende-chios/",
  it: "/it/spiagge-tranquille-chios/",
  es: "/es/playas-tranquilas-quios/",
  tr: "/tr/sakiz-adasi-sakin-plajlar/",
};

export const quietBeachAlternates = {
  en: absoluteUrl(quietBeachPaths.en),
  el: absoluteUrl(quietBeachPaths.el),
  fr: absoluteUrl(quietBeachPaths.fr),
  de: absoluteUrl(quietBeachPaths.de),
  it: absoluteUrl(quietBeachPaths.it),
  es: absoluteUrl(quietBeachPaths.es),
  tr: absoluteUrl(quietBeachPaths.tr),
  "x-default": absoluteUrl(quietBeachPaths.en),
};

const hrefs = {
  en: { elinta: "/chios/chios-beaches/#quiet-beaches", vroulidia: "/chios/chios-beaches/vroulidia-beach/", nagos: "/chios/chios-beaches/nagos-beach/", rooms: "/chios-rooms/", beaches: "/chios/chios-beaches/" },
  el: { elinta: "/el/paralies-xios/#quiet-beaches", vroulidia: "/el/paralies-xios/paralia-vroulidia/", nagos: "/el/paralies-xios/paralia-nagos/", rooms: "/el/domatia-xios/", beaches: "/el/paralies-xios/" },
  fr: { elinta: "/fr/plages-de-chios/#quiet-beaches", vroulidia: "/fr/plages-de-chios/plage-vroulidia/", nagos: "/fr/plages-de-chios/plage-nagos/", rooms: "/fr/chambres-a-chios/", beaches: "/fr/plages-de-chios/" },
  de: { elinta: "/de/straende-chios/#quiet-beaches", vroulidia: "/de/straende-chios/vroulidia-strand/", nagos: "/de/straende-chios/nagos-strand/", rooms: "/de/chios-zimmer/", beaches: "/de/straende-chios/" },
  it: { elinta: "/it/spiagge-chios/#quiet-beaches", vroulidia: "/it/spiagge-chios/spiaggia-vroulidia/", nagos: "/it/spiagge-chios/spiaggia-nagos/", rooms: "/it/camere-a-chios/", beaches: "/it/spiagge-chios/" },
  es: { elinta: "/es/playas-chios/#quiet-beaches", vroulidia: "/es/playas-chios/playa-vroulidia/", nagos: "/es/playas-chios/playa-nagos/", rooms: "/es/habitaciones-en-chios/", beaches: "/es/playas-chios/" },
  tr: { elinta: "/tr/sakiz-adasi-plajlari/#quiet-beaches", vroulidia: "/tr/sakiz-adasi-plajlari/vroulidia-plaji/", nagos: "/tr/sakiz-adasi-plajlari/nagos-plaji/", rooms: "/tr/sakiz-adasi-odalari/", beaches: "/tr/sakiz-adasi-plajlari/" },
} as const;

const copy = {
  en: { names: ["Elinta", "Vroulidia", "Nagos"], tag: "Quiet", desc: "A calmer choice for travellers who want a more authentic, less busy beach day.", why: "Good when you prefer silence, natural scenery and fewer distractions." },
  el: { names: ["Ελίντα", "Βρουλίδια", "Ναγός"], tag: "Ήσυχη", desc: "Πιο ήρεμη επιλογή για επισκέπτες που θέλουν αυθεντική μέρα στη θάλασσα με λιγότερο κόσμο.", why: "Καλή όταν προτιμάτε ησυχία, φυσικό τοπίο και λιγότερη κίνηση." },
  fr: { names: ["Elinta", "Vroulidia", "Nagos"], tag: "Calme", desc: "Un choix plus paisible pour une journée de plage authentique et moins fréquentée.", why: "Idéale pour le silence, le paysage naturel et moins d’agitation." },
  de: { names: ["Elinta", "Vroulidia", "Nagos"], tag: "Ruhig", desc: "Eine ruhigere Wahl für einen authentischen Strandtag mit weniger Betrieb.", why: "Gut für Stille, Natur und weniger Ablenkung." },
  it: { names: ["Elinta", "Vroulidia", "Nagos"], tag: "Tranquilla", desc: "Una scelta più calma per una giornata autentica e meno affollata.", why: "Ideale per silenzio, natura e meno movimento." },
  es: { names: ["Elinta", "Vroulidia", "Nagos"], tag: "Tranquila", desc: "Una opción más calmada para un día de playa auténtico y menos concurrido.", why: "Buena para silencio, naturaleza y menos distracciones." },
  tr: { names: ["Elinta", "Vroulidia", "Nagos"], tag: "Sakin", desc: "Daha otantik ve daha az kalabalık bir deniz günü isteyenler için sakin seçenek.", why: "Sessizlik, doğal manzara ve daha az hareket isteyenler için iyi." },
} as const;

function cards(locale: LanguageCode): OrganizedBeachCard[] {
  const h = hrefs[locale];
  const c = copy[locale];
  return [
    { name: c.names[0], image: images.elinta, href: h.elinta, tag: c.tag, description: c.desc, why: c.why },
    { name: c.names[1], image: images.vroulidia, href: h.vroulidia, tag: c.tag, description: c.desc, why: c.why },
    { name: c.names[2], image: images.nagos, href: h.nagos, tag: c.tag, description: c.desc, why: c.why },
  ];
}

const tips = {
  en: [{ icon: "🧭", title: "Plan the route", text: "Quiet beaches may need more careful driving and timing." }, { icon: "🥤", title: "Bring supplies", text: "Take water and snacks, because services may be limited." }, { icon: "🌿", title: "Respect the place", text: "Keep these quiet places clean and calm for everyone." }],
  el: [{ icon: "🧭", title: "Οργανώστε τη διαδρομή", text: "Οι ήσυχες παραλίες θέλουν λίγο καλύτερο προγραμματισμό στη διαδρομή." }, { icon: "🥤", title: "Πάρτε τα απαραίτητα", text: "Νερό και κάτι πρόχειρο είναι χρήσιμα, γιατί οι υπηρεσίες μπορεί να είναι περιορισμένες." }, { icon: "🌿", title: "Σεβαστείτε το μέρος", text: "Κρατάμε τις ήσυχες παραλίες καθαρές και ήρεμες." }],
  fr: [{ icon: "🧭", title: "Planifiez la route", text: "Les plages calmes demandent parfois plus d’organisation." }, { icon: "🥤", title: "Prévoyez le nécessaire", text: "Eau et snacks sont utiles car les services peuvent être limités." }, { icon: "🌿", title: "Respectez le lieu", text: "Gardons ces endroits propres et calmes." }],
  de: [{ icon: "🧭", title: "Route planen", text: "Ruhige Strände brauchen oft etwas mehr Planung." }, { icon: "🥤", title: "Vorräte mitnehmen", text: "Wasser und Snacks sind sinnvoll, da Services begrenzt sein können." }, { icon: "🌿", title: "Ort respektieren", text: "Diese ruhigen Orte sauber und ruhig halten." }],
  it: [{ icon: "🧭", title: "Pianificate la strada", text: "Le spiagge tranquille richiedono un po’ più di organizzazione." }, { icon: "🥤", title: "Portate il necessario", text: "Acqua e snack sono utili perché i servizi possono essere limitati." }, { icon: "🌿", title: "Rispettate il luogo", text: "Manteniamo questi luoghi puliti e tranquilli." }],
  es: [{ icon: "🧭", title: "Planifica la ruta", text: "Las playas tranquilas pueden requerir más planificación." }, { icon: "🥤", title: "Lleva lo necesario", text: "Agua y snacks son útiles porque puede haber pocos servicios." }, { icon: "🌿", title: "Respeta el lugar", text: "Mantengamos estos lugares limpios y calmados." }],
  tr: [{ icon: "🧭", title: "Rotayı planlayın", text: "Sakin plajlar biraz daha planlama gerektirebilir." }, { icon: "🥤", title: "Gerekli şeyleri alın", text: "Su ve atıştırmalık alın; hizmetler sınırlı olabilir." }, { icon: "🌿", title: "Yere saygı gösterin", text: "Bu sakin yerleri temiz ve huzurlu tutalım." }],
};

export const quietBeachesPages: Record<LanguageCode, OrganizedBeachesPageData> = {
  en: { locale: "en", path: quietBeachPaths.en, seo: { canonicalPath: quietBeachPaths.en, title: "Quiet Beaches in Chios | Voulamandis House", description: "A local guide to quiet beaches in Chios: Elinta, Vroulidia and Nagos, for calmer and more authentic beach days.", ogImage: images.hero }, hero: { eyebrow: "Quiet beach guide", title: "Quiet beaches in Chios for slower, calmer days", subtitle: "Choose beaches with a more authentic, peaceful feeling when you want less noise and more sea.", image: { src: images.hero, alt: "Quiet beach in Chios" }, primaryCta: { label: "See quiet beaches", href: "#organized-beaches" }, secondaryCta: { label: "All Chios beaches", href: hrefs.en.beaches } }, intro: { title: "When to choose a quiet beach", text: ["Quiet beaches are best when the goal is not beach service or crowds, but calm, natural scenery and a slower rhythm.", "For this category we start with Elinta, Vroulidia and Nagos."] }, highlights: { title: "Quiet beaches to consider", subtitle: "A practical list for travellers who want a more peaceful Chios beach day.", cards: cards("en") }, tips: { title: "Quick tips for quiet beaches", items: tips.en }, stay: { title: "Return to a quiet garden after the beach", text: "Voulamandis House is a calm base for travellers who like peaceful beaches and slow evenings in Kambos.", image: images.stay, primaryCta: { label: "View rooms", href: hrefs.en.rooms }, secondaryCta: { label: "All beaches", href: hrefs.en.beaches } }, finalCta: { title: "Looking for a calmer beach day?", text: "Ask us during your stay and we will suggest the quiet beach that fits the day.", primaryCta: { label: "View rooms", href: hrefs.en.rooms }, secondaryCta: { label: "Explore beaches", href: hrefs.en.beaches } } },
  el: { locale: "el", path: quietBeachPaths.el, seo: { canonicalPath: quietBeachPaths.el, title: "Ήσυχες παραλίες Χίου | Voulamandis House", description: "Τοπικός οδηγός για ήσυχες παραλίες στη Χίο: Ελίντα, Βρουλίδια και Ναγός, για πιο ήρεμες και αυθεντικές μέρες στη θάλασσα.", ogImage: images.hero }, hero: { eyebrow: "Ήσυχες παραλίες", title: "Ήσυχες παραλίες στη Χίο για πιο ήρεμες μέρες", subtitle: "Διαλέξτε παραλίες με πιο αυθεντική και ήρεμη αίσθηση όταν θέλετε λιγότερο κόσμο και περισσότερη θάλασσα.", image: { src: images.hero, alt: "Ήσυχη παραλία στη Χίο" }, primaryCta: { label: "Δείτε ήσυχες", href: "#organized-beaches" }, secondaryCta: { label: "Όλες οι παραλίες", href: hrefs.el.beaches } }, intro: { title: "Πότε να επιλέξετε ήσυχη παραλία", text: ["Οι ήσυχες παραλίες είναι ιδανικές όταν δεν ζητάτε υπηρεσίες και πολυκοσμία, αλλά ηρεμία, φυσικό τοπίο και πιο αργό ρυθμό.", "Για αυτή την κατηγορία ξεκινάμε με Ελίντα, Βρουλίδια και Ναγό."] }, highlights: { title: "Ήσυχες παραλίες που αξίζει να δείτε", subtitle: "Πρακτική λίστα για επισκέπτες που θέλουν πιο ήρεμη beach day στη Χίο.", cards: cards("el") }, tips: { title: "Γρήγορες συμβουλές για ήσυχες παραλίες", items: tips.el }, stay: { title: "Επιστροφή σε ήρεμο κήπο μετά τη θάλασσα", text: "Το Voulamandis House είναι ήρεμη βάση για επισκέπτες που αγαπούν ήσυχες παραλίες και χαλαρά βράδια στον Κάμπο.", image: images.stay, primaryCta: { label: "Δείτε δωμάτια", href: hrefs.el.rooms }, secondaryCta: { label: "Όλες οι παραλίες", href: hrefs.el.beaches } }, finalCta: { title: "Θέλετε πιο ήρεμη μέρα στη θάλασσα;", text: "Ρωτήστε μας στη διαμονή σας και θα σας προτείνουμε την ήσυχη παραλία που ταιριάζει στη μέρα.", primaryCta: { label: "Δείτε δωμάτια", href: hrefs.el.rooms }, secondaryCta: { label: "Παραλίες Χίου", href: hrefs.el.beaches } } },
  fr: { locale: "fr", path: quietBeachPaths.fr, seo: { canonicalPath: quietBeachPaths.fr, title: "Plages calmes à Chios | Voulamandis House", description: "Guide local des plages calmes à Chios : Elinta, Vroulidia et Nagos, pour des journées plus paisibles.", ogImage: images.hero }, hero: { eyebrow: "Plages calmes", title: "Plages calmes à Chios pour des journées plus lentes", subtitle: "Choisissez des plages plus paisibles lorsque vous voulez moins de monde et plus de mer.", image: { src: images.hero, alt: "Plage calme à Chios" }, primaryCta: { label: "Voir les plages", href: "#organized-beaches" }, secondaryCta: { label: "Toutes les plages", href: hrefs.fr.beaches } }, intro: { title: "Quand choisir une plage calme", text: ["Les plages calmes sont idéales si vous cherchez nature, silence et rythme plus lent.", "Pour cette catégorie, commencez par Elinta, Vroulidia et Nagos."] }, highlights: { title: "Plages calmes à considérer", subtitle: "Une liste pratique pour une journée paisible à Chios.", cards: cards("fr") }, tips: { title: "Conseils rapides", items: tips.fr }, stay: { title: "Retour au calme après la plage", text: "Voulamandis House est une base paisible pour les amateurs de plages calmes.", image: images.stay, primaryCta: { label: "Voir chambres", href: hrefs.fr.rooms }, secondaryCta: { label: "Toutes les plages", href: hrefs.fr.beaches } }, finalCta: { title: "Envie d’une journée plus calme ?", text: "Demandez-nous et nous vous suggérerons une plage adaptée.", primaryCta: { label: "Voir chambres", href: hrefs.fr.rooms }, secondaryCta: { label: "Plages de Chios", href: hrefs.fr.beaches } } },
  de: { locale: "de", path: quietBeachPaths.de, seo: { canonicalPath: quietBeachPaths.de, title: "Ruhige Strände auf Chios | Voulamandis House", description: "Lokaler Guide zu ruhigen Stränden auf Chios: Elinta, Vroulidia und Nagos, für entspannte Strandtage.", ogImage: images.hero }, hero: { eyebrow: "Ruhige Strände", title: "Ruhige Strände auf Chios für langsamere Tage", subtitle: "Wählen Sie Strände mit mehr Ruhe, Natur und weniger Betrieb.", image: { src: images.hero, alt: "Ruhiger Strand auf Chios" }, primaryCta: { label: "Strände ansehen", href: "#organized-beaches" }, secondaryCta: { label: "Alle Strände", href: hrefs.de.beaches } }, intro: { title: "Wann ein ruhiger Strand passt", text: ["Ruhige Strände sind ideal, wenn Natur, Stille und ein langsamer Rhythmus wichtiger sind als Service.", "Für diese Kategorie starten wir mit Elinta, Vroulidia und Nagos."] }, highlights: { title: "Ruhige Strände zur Auswahl", subtitle: "Eine praktische Liste für einen ruhigeren Strandtag.", cards: cards("de") }, tips: { title: "Kurze Tipps", items: tips.de }, stay: { title: "Nach dem Strand in den ruhigen Garten zurück", text: "Voulamandis House ist eine ruhige Basis für Gäste, die stille Strände mögen.", image: images.stay, primaryCta: { label: "Zimmer ansehen", href: hrefs.de.rooms }, secondaryCta: { label: "Alle Strände", href: hrefs.de.beaches } }, finalCta: { title: "Einen ruhigeren Strandtag suchen?", text: "Fragen Sie uns während Ihres Aufenthalts nach einer passenden Option.", primaryCta: { label: "Zimmer ansehen", href: hrefs.de.rooms }, secondaryCta: { label: "Chios Strände", href: hrefs.de.beaches } } },
  it: { locale: "it", path: quietBeachPaths.it, seo: { canonicalPath: quietBeachPaths.it, title: "Spiagge tranquille a Chios | Voulamandis House", description: "Guida locale alle spiagge tranquille a Chios: Elinta, Vroulidia e Nagos, per giornate più calme.", ogImage: images.hero }, hero: { eyebrow: "Spiagge tranquille", title: "Spiagge tranquille a Chios per giornate lente", subtitle: "Scegliete spiagge più autentiche e calme quando volete meno folla e più mare.", image: { src: images.hero, alt: "Spiaggia tranquilla a Chios" }, primaryCta: { label: "Vedi spiagge", href: "#organized-beaches" }, secondaryCta: { label: "Tutte le spiagge", href: hrefs.it.beaches } }, intro: { title: "Quando scegliere una spiaggia tranquilla", text: ["Le spiagge tranquille sono ideali quando cercate natura, silenzio e ritmo lento.", "Per questa categoria partiamo da Elinta, Vroulidia e Nagos."] }, highlights: { title: "Spiagge tranquille da considerare", subtitle: "Una lista pratica per una giornata più calma a Chios.", cards: cards("it") }, tips: { title: "Consigli rapidi", items: tips.it }, stay: { title: "Ritorno al giardino tranquillo dopo il mare", text: "Voulamandis House è una base tranquilla per chi ama spiagge calme.", image: images.stay, primaryCta: { label: "Vedi camere", href: hrefs.it.rooms }, secondaryCta: { label: "Tutte le spiagge", href: hrefs.it.beaches } }, finalCta: { title: "Cercate una giornata più calma?", text: "Chiedeteci durante il soggiorno e vi suggeriremo l’opzione adatta.", primaryCta: { label: "Vedi camere", href: hrefs.it.rooms }, secondaryCta: { label: "Spiagge di Chios", href: hrefs.it.beaches } } },
  es: { locale: "es", path: quietBeachPaths.es, seo: { canonicalPath: quietBeachPaths.es, title: "Playas tranquilas en Quíos | Voulamandis House", description: "Guía local de playas tranquilas en Quíos: Elinta, Vroulidia y Nagos, para días más calmados.", ogImage: images.hero }, hero: { eyebrow: "Playas tranquilas", title: "Playas tranquilas en Quíos para días más lentos", subtitle: "Elige playas más auténticas y calmadas cuando buscas menos gente y más mar.", image: { src: images.hero, alt: "Playa tranquila en Quíos" }, primaryCta: { label: "Ver playas", href: "#organized-beaches" }, secondaryCta: { label: "Todas las playas", href: hrefs.es.beaches } }, intro: { title: "Cuándo elegir una playa tranquila", text: ["Las playas tranquilas son ideales si buscas naturaleza, silencio y ritmo lento.", "Para esta categoría empezamos con Elinta, Vroulidia y Nagos."] }, highlights: { title: "Playas tranquilas para considerar", subtitle: "Una lista práctica para un día más calmado en Quíos.", cards: cards("es") }, tips: { title: "Consejos rápidos", items: tips.es }, stay: { title: "Vuelve a un jardín tranquilo después del mar", text: "Voulamandis House es una base tranquila para quienes aman playas calmadas.", image: images.stay, primaryCta: { label: "Ver habitaciones", href: hrefs.es.rooms }, secondaryCta: { label: "Todas las playas", href: hrefs.es.beaches } }, finalCta: { title: "¿Buscas un día más tranquilo?", text: "Pregúntanos durante tu estancia y te sugeriremos la opción adecuada.", primaryCta: { label: "Ver habitaciones", href: hrefs.es.rooms }, secondaryCta: { label: "Playas de Quíos", href: hrefs.es.beaches } } },
  tr: { locale: "tr", path: quietBeachPaths.tr, seo: { canonicalPath: quietBeachPaths.tr, title: "Sakız Adası Sakin Plajlar | Voulamandis House", description: "Sakız Adası’nda sakin plajlar: Elinta, Vroulidia ve Nagos. Daha huzurlu deniz günleri için yerel rehber.", ogImage: images.hero }, hero: { eyebrow: "Sakin plajlar", title: "Daha yavaş günler için Sakız Adası sakin plajları", subtitle: "Daha az kalabalık ve daha çok deniz istediğinizde sakin ve doğal seçenekler seçin.", image: { src: images.hero, alt: "Sakız Adası’nda sakin plaj" }, primaryCta: { label: "Plajları gör", href: "#organized-beaches" }, secondaryCta: { label: "Tüm plajlar", href: hrefs.tr.beaches } }, intro: { title: "Ne zaman sakin plaj seçilmeli", text: ["Sakin plajlar doğa, sessizlik ve yavaş ritim istediğinizde idealdir.", "Bu kategori için Elinta, Vroulidia ve Nagos ile başlıyoruz."] }, highlights: { title: "Değerlendirilecek sakin plajlar", subtitle: "Sakız’da daha huzurlu bir deniz günü için pratik liste.", cards: cards("tr") }, tips: { title: "Hızlı ipuçları", items: tips.tr }, stay: { title: "Denizden sonra sakin bahçeye dönün", text: "Voulamandis House sakin plajları seven misafirler için huzurlu bir başlangıç noktasıdır.", image: images.stay, primaryCta: { label: "Odaları gör", href: hrefs.tr.rooms }, secondaryCta: { label: "Tüm plajlar", href: hrefs.tr.beaches } }, finalCta: { title: "Daha sakin bir deniz günü ister misiniz?", text: "Konaklamanız sırasında bize sorun; uygun sakin plajı önerelim.", primaryCta: { label: "Odaları gör", href: hrefs.tr.rooms }, secondaryCta: { label: "Sakız plajları", href: hrefs.tr.beaches } } },
};

export function getQuietBeachesPageByLocale(locale: LanguageCode) { return quietBeachesPages[locale]; }
export function getQuietBeachesPageByPath(path: string) { return Object.values(quietBeachesPages).find((page) => page.path === path); }
