import { chiosHotelsGuide } from "@/content/chios-hotels-guide";
import type { ChiosHotelsGuideContent } from "@/content/chios-hotels-guide-types";

export const sakizAdasiOtelleriGuide: ChiosHotelsGuideContent = {
  ...chiosHotelsGuide,
  seo: {
    canonicalPath: "/tr/sakiz-adasi-otelleri/",
    title: "Sakız Adası Otelleri | Bölgeler, fiyatlar & alternatifler",
    description: "Sakız Adası otelleri, odaları ve dairelerini bölgeye ve seyahat tarzına göre karşılaştırın. Voulamandis House Kambos canlı müsaitliğini görün.",
    image: chiosHotelsGuide.seo.image,
    imageAlt: "Sakız Adası Kambos narenciye bahçeleri arasında oda ve daireler",
  },
  hero: {
    kicker: "SAKIZ ADASI OTELLERİ & NEREDE KALINIR",
    title: "Sakız Adası otelleri, odalar ve daireler: adada nerede kalınır?",
    description: "Sakız Adası otelleri mi arıyorsunuz? Bu yerel rehber adanın başlıca bölgelerini karşılaştırır, otel, aile işletmesi, oda ve daire arasındaki farkları açıklar ve Kambos’taki sakin bir konaklama için gerçek müsaitliği kontrol etmenizi sağlar.",
    disclosure: "Voulamandis House bir otel değildir. Kambos, Sakız Adası’nda özel odalar ve aile daireleri sunan aile işletmesi bir konaklama tesisidir.",
    primaryCta: { label: "Canlı müsaitlik ara", href: "#live-availability" },
    secondaryCta: { label: "Bölgeleri karşılaştır", href: "#where-to-stay" },
    aiCta: { label: "AI Room Finder’a sor", href: "/ai-assistant/?lang=tr" },
  },
  trustPoints: [
    { label: "Yerel üs", value: "Tarihi Kambos" },
    { label: "Sakız Havalimanı", value: "Yaklaşık 3 km" },
    { label: "Sakız Limanı", value: "Yaklaşık 6 km" },
    { label: "Konaklama türleri", value: "Odalar & daireler" },
    { label: "Kimler için", value: "Çiftler & aileler" },
    { label: "Canlı arama", value: "Gerçek müsaitlik" },
  ],
  intro: {
    kicker: "DOĞRU BÖLGEDEN BAŞLAYIN",
    title: "Sakız Adası otelleri için doğru arama, nerede kalacağınıza karar vermekle başlar",
    paragraphs: [
      "Sakız Adası otelleri araması çoğu zaman birden fazla ihtiyacı içerir: limana yakınlık, havalimanına kolay ulaşım, yakında plaj, aile için daha fazla alan, sakin çevre veya adayı araçla keşfetmek için pratik bir üs. Bu nedenle bölge seçimi oda kadar önemlidir.",
      "Sakız merkezi liman, restoranlar ve araçsız seyahat edenler için pratiktir. Kambos şehir ve havalimanına yakın daha sakin tarihi bir ortam sunar. Karfas ve yakın kıyılar deniz odaklı konaklamaya uygundur; mastik köyleri ise daha geleneksel ve uzak bir deneyim sağlar.",
      "Bu rehber «Sakız Adası otelleri» ifadesini kullanıcıların internette yaygın biçimde aradığı geniş anlamıyla kullanır; ancak klasik otelleri, aile işletmelerini, özel odaları ve bağımsız daireleri açıkça ayırır. Voulamandis House aile işletmesi konaklama kategorisindedir ve otel ya da resort hizmet modeli sunduğunu iddia etmez.",
    ],
  },
  areas: {
    kicker: "SAKIZ ADASI’NDA NEREDE KALINIR",
    title: "Konaklama seçmeden önce ana bölgeleri karşılaştırın",
    description: "Her bölge farklı bir tatil deneyimi sunar. Ulaşımı, atmosferi ve hangi seyahat tarzına uygun olduğunu karşılaştırın.",
    items: [
      { id: "chios-town", title: "Sakız merkezi", badge: "Liman & şehir hayatı", text: "Feribotla gelenler, restoranlar, mağazalar ve sahil yürüyüşleri için pratik bir seçenektir. Araç olmadan da uygundur; ancak merkez sokakları kırsal bölgelere göre daha hareketlidir.", bestFor: "Kısa konaklamalar, feribot yolcuları ve araçsız misafirler", link: "/tr/sakiz-adasi/" },
      { id: "kambos", title: "Kambos", badge: "Tarihi & huzurlu", text: "Narenciye bahçeleri, yüksek taş duvarları ve eski konaklarıyla Kambos; sakin atmosferi şehir merkezine, havalimanına ve güney yollarına kolay ulaşım ile birleştirir.", bestFor: "Çiftler, aileler ve araçla adayı gezenler", link: "/tr/chios/kampos-chios/" },
      { id: "karfas", title: "Karfas ve yakın kıyılar", badge: "Plaj odaklı", text: "Düzenli plajı ve yaz atmosferiyle bilinen bir kıyı bölgesidir. Denizin konaklama noktasına çok yakın olmasını isteyenler için uygundur.", bestFor: "Yaz tatili ve plaj konaklaması", link: "/tr/sakiz-adasi-plajlari/" },
      { id: "mastic-villages", title: "Mastik köyleri", badge: "Geleneksel güney", text: "Pyrgi, Mesta ve diğer Orta Çağ köyleri özgün mimari ve güçlü yerel karakter sunar. Bölgede kalmak veya gezmek için araç genellikle en pratik seçenektir.", bestFor: "Araçlı rotalar, tarih ve köy yaşamı", link: "/tr/sakiz-adasi-koyleri/" },
    ],
  },
  accommodationTypes: {
    kicker: "OTEL, ODA YOKSA DAİRE Mİ?",
    title: "Önceliklerinize uygun konaklama türünü seçin",
    description: "Otel kelimesi çoğu zaman genel bir arama olarak kullanılır; ancak Sakız Adası’ndaki gerçek konaklama türleri birbirinden oldukça farklıdır.",
    items: [
      { title: "Klasik otel", idealFor: "Tesis içi hizmetlere öncelik verenler", features: "Resepsiyon, ortak alanlar ve tesise göre restoran, havuz veya ek hizmetler." },
      { title: "Aile işletmesi konaklama", idealFor: "Daha küçük ve kişisel bir deneyim", features: "Daha az oda, işletmecilerle doğrudan iletişim ve büyük otel veya resortlara göre daha sakin atmosfer." },
      { title: "Özel oda", idealFor: "Çiftler ve kısa konaklamalar", features: "Özel banyo ve temel oda olanakları; genellikle daha sade hizmet modeli ve rekabetçi fiyat." },
      { title: "Aile dairesi", idealFor: "Aileler ve uzun konaklamalar", features: "Daha fazla alan, ayrı yatak odası, oturma bölümü ve bağımsızlık sağlayan mutfak." },
    ],
    note: "Voulamandis House özel odalar ve aile daireleri sunan aile işletmesi bir konaklama yeridir. Klasik Sakız Adası otellerine alternatiftir ve başka bir ad altında otel gibi tanıtılmaz.",
  },
  popularSearches: {
    kicker: "POPÜLER SAKIZ ADASI OTEL ARAMALARI",
    title: "Konum, bütçe ve seyahat tarzına uygun konaklamayı bulun",
    items: [
      { id: "chios-hotels-near-airport", title: "Sakız Havalimanı yakınındaki oteller", text: "Havalimanına yakın konaklama erken uçuşlar, geç varışlar ve kısa ziyaretler için kolaylık sağlar. Kambos yakın ve pratik bölgelerden biridir; merkeze göre daha sakin bir ortam sunar.", cta: "Kambos konumunu görün", href: "#kambos-alternative" },
      { id: "chios-hotels-near-port", title: "Sakız Limanı yakınındaki otel ve odalar", text: "Limana yürüyerek ulaşmak için şehir merkezi en yakın seçenektir. Kambos daha uzakta olsa da araç veya taksiyle kolayca ulaşılır ve daha huzurlu bir üs sunar.", cta: "Merkez ile Kambos’u karşılaştırın", href: "#where-to-stay" },
      { id: "family-hotels-chios", title: "Sakız Adası aile otelleri ve daireleri", text: "Aileler çoğu zaman standart odadan daha fazlasına ihtiyaç duyar. Mutfak ve oturma alanı olan daireler daha fazla alan sağlar; bazı büyük odalar da küçük ailelere uygundur.", cta: "Aile dairelerini inceleyin", href: "/tr/chios-odalari/sakiz-adasinda-buyuk-aile-daireleri/" },
      { id: "cheap-hotels-chios", title: "Ucuz Sakız Adası otelleri ve ekonomik odalar", text: "Daha düşük fiyat özel banyo, klima veya pratik konumdan vazgeçmek anlamına gelmez. Ekonomik odalar gün boyunca adayı gezen çiftler için kullanışlı bir alternatiftir.", cta: "Ekonomik odaları görün", href: "/tr/chios-odalari/sakiz-adasindaki-ekonomi-cift-kisilik-oda/" },
      { id: "hotels-in-kambos-chios", title: "Kambos otelleri ve konaklama seçenekleri", text: "Kambos narenciye bahçeleri, tarihi konakları ve şehir, havalimanı ile güney rotaları arasındaki konumuyla öne çıkar. Buradaki tesisler çoğunlukla daha küçük ve kişiseldir.", cta: "Kambos’u keşfedin", href: "/tr/chios/kampos-chios/" },
      { id: "chios-hotels-near-beach", title: "Sakız Adası sahil otelleri ve plaja yakın konaklama", text: "Karfas düzenli plaj isteyenler için bilinen bir seçenektir. Farklı kıyıları görmek isteyenler ise ana yol ağına yakın merkezi bir üs tercih edebilir.", cta: "Sakız Adası plajlarını keşfedin", href: "/tr/sakiz-adasi-plajlari/" },
    ],
  },
  kambosAlternative: {
    kicker: "FARKLI BİR KONAKLAMA DENEYİMİ",
    title: "Klasik bir Sakız Adası oteline daha sakin bir alternatif",
    paragraphs: [
      "Voulamandis House sakin çevreyi, doğrudan iletişimi ve adayı keşfetmek için pratik bir üssü önemseyen misafirler içindir. Aile işletmesi tesis Kambos’un narenciye bahçeleri arasında küçük ölçekli bir deneyim sunar.",
      "Ekonomik çift kişilik odalar, merdivensiz zemin kat odaları, üst kat odaları ve tam mutfaklı aile daireleri arasından seçim yapabilirsiniz. Tüm seçeneklerde özel banyo, klima, Wi-Fi ve buzdolabı bulunur.",
      "Tesis Sakız Havalimanı’na yaklaşık 3 km, limana ise yaklaşık 6 km uzaklıktadır. Böylece varışlar pratiktir, ancak merkezin en yoğun sokaklarının dışında kalırsınız.",
    ],
    benefits: [
      "Büyük otel yerine aile işletmesi oda ve daireler",
      "Bahçe ve narenciye atmosferiyle tarihi Kambos",
      "Merdiven kullanmak istemeyenler için zemin kat seçenekleri",
      "Tam mutfak ve oturma alanlı aile daireleri",
      "Doğru oda kategorisini seçmek için doğrudan yardım",
      "Şehir, plajlar ve güney köylerine kolay yol bağlantısı",
    ],
    primaryCta: { label: "Oda ve daireleri inceleyin", href: "/tr/sakiz-adasi-odalari/" },
    secondaryCta: { label: "Doğrudan fiyatları görün", href: "/tr/sakiz-adasi-rezervasyon/" },
  },
  roomCategories: {
    kicker: "GERÇEK KONAKLAMA SEÇENEKLERİ",
    title: "Voulamandis House oda ve daireleri",
    description: "Tarihleri girmeden önce ana kategorileri karşılaştırın. Canlı sonuçlar tesisin güncel müsaitlik verilerine dayanır.",
    items: [
      { title: "Ekonomik çift kişilik odalar", label: "İki kişi için avantajlı seçim", text: "Çift kişilik yatak, özel banyo, klima, Wi-Fi, televizyon ve buzdolabı bulunan yenilenmiş odalar.", facts: ["2 misafir", "Yaklaşık 16 m²", "Özel banyo"], image: chiosHotelsGuide.roomCategories.items[0].image, href: "/tr/chios-odalari/sakiz-adasindaki-ekonomi-cift-kisilik-oda/" },
      { title: "Zemin kat odaları", label: "Kolay erişim ve merdivensiz", text: "Avluya veya bahçeye doğrudan erişimli çift ve üç kişilik odalar; zemin kat tercih eden misafirler için uygundur.", facts: ["2–3 misafir", "Merdivensiz", "Bahçe erişimi"], image: chiosHotelsGuide.roomCategories.items[1].image, href: "/tr/chios-odalari/standart-cift-kisilik-odalar/" },
      { title: "Üst kat odaları", label: "Teras ve narenciye manzarası", text: "Ortak terasa erişimi bulunan aydınlık çift ve üç kişilik odalar; bazı seçeneklerde mini mutfak vardır.", facts: ["2–4 misafir", "Üst kat", "Bazılarında mini mutfak"], image: chiosHotelsGuide.roomCategories.items[2].image, href: "/tr/chios-odalari/standart-cift-kisilik-odalar/" },
      { title: "Aile daireleri", label: "Daha fazla alan ve tam mutfak", text: "Ayrı yatak odası, oturma alanı ve mutfağı bulunan 40–45 m² bağımsız daireler; aileler ve uzun konaklamalar için uygundur.", facts: ["4 misafire kadar", "40–45 m²", "Tam mutfak"], image: chiosHotelsGuide.roomCategories.items[3].image, href: "/tr/chios-odalari/sakiz-adasinda-buyuk-aile-daireleri/" },
    ],
  },
  planning: {
    kicker: "ODADAN FAZLASINI PLANLAYIN",
    title: "Konaklamanızı tüm ada için bir üs olarak kullanın",
    description: "Güçlü bir Sakız Adası otel araması günlük ulaşımı da hesaba katmalıdır. Bu yerel rehberler Kambos’tan ulaşılabilecek mesafeleri, rotaları ve deneyimleri açıklar.",
    links: [
      { title: "Sakız Adası rehberi", text: "Adanın ana bölgeleri, öne çıkan deneyimleri ve pratik gezi fikirleriyle başlayın.", href: "/tr/sakiz-adasi/" },
      { title: "Sakız Adası plajları", text: "Düzenli, aile dostu ve sakin plajları farklı kıyılarda karşılaştırın.", href: "/tr/sakiz-adasi-plajlari/" },
      { title: "Sakız Adası köyleri", text: "Mastik köyleri, dağ yerleşimleri ve kıyı köyleri arasında rotalar planlayın.", href: "/tr/sakiz-adasi-koyleri/" },
      { title: "Tarihi Kambos", text: "Narenciye bahçeleri, taş konaklar ve tesis çevresindeki özgün peyzajı keşfedin.", href: "/tr/chios/kampos-chios/" },
    ],
  },
  faq: {
    kicker: "SAKIZ ADASI OTELLERİ SIK SORULAN SORULAR",
    title: "Sakız Adası konaklaması öncesinde sorulan sorular",
    items: [
      { question: "Sakız Adası’nda kalmak için en iyi bölge hangisi?", answer: "Sakız merkezi liman, restoranlar ve araçsız seyahat edenler için pratiktir. Kambos şehir ve havalimanına yakın daha sakin tarihi bir üstür. Karfas plaj odaklı tatil için uygundur; mastik köyleri ise araçla gezenler için idealdir." },
      { question: "Sakız Havalimanı yakınında oteller var mı?", answer: "Evet, çeşitli konaklama bölgeleri kısa sürüş mesafesindedir. Kambos havalimanına yakın ve merkezden daha sakin olduğu için özellikle pratiktir. Voulamandis House yaklaşık 3 km uzaklıktadır." },
      { question: "Sakız Limanı yakınında nerede kalınır?", answer: "Limana yürüyerek ulaşmak için şehir merkezi en yakın seçenektir. Kambos yaklaşık 6 km uzaklıktadır ve araç veya taksi kullanarak daha sakin bir bölgede kalmak isteyenlere uygundur." },
      { question: "Kambos kalmak için iyi bir bölge mi?", answer: "Evet. Tarihi karakter, bahçeler ve sakinlik isteyen; aynı zamanda şehir, havalimanı ve güney yollarına yakın kalmak isteyen misafirler için güçlü bir seçenektir." },
      { question: "Aileler için daire mi otel mi daha iyi?", answer: "Daha fazla alan, mutfak ve ayrı oturma bölümü önemliyse daire genellikle daha pratiktir. Tesis içi geniş hizmetlere öncelik veren aileler klasik oteli tercih edebilir." },
      { question: "Sakız Adası konaklama fiyatları ne kadar?", answer: "Fiyatlar sezon, bölge, oda tipi, misafir sayısı ve koşullara göre değişir. Voulamandis House için güncel fiyatı görmek üzere gerçek tarihlerinizi canlı aramaya girin." },
      { question: "Sakız Adası’nda araç gerekli mi?", answer: "Merkezde kısa konaklama için şart değildir; ancak plajlar, mastik köyleri ve adanın farklı bölgelerini görmek için araç çok faydalıdır." },
      { question: "Plajlar için en iyi bölge hangisi?", answer: "Karfas düzenli plaj için pratiktir. Birden fazla kıyıyı görmek isteyenler ana yol ağına yakın merkezi bir üs tercih edebilir." },
      { question: "Sakız Adası’nda ekonomik odalar var mı?", answer: "Evet. Ekonomik odalar ve küçük aile işletmeleri, özellikle çiftler için büyük otellere göre daha uygun fiyatlı alternatif olabilir." },
      { question: "Voulamandis House otel mi?", answer: "Hayır. Voulamandis House Kambos’ta özel odalar ve aile daireleri sunan aile işletmesi bir konaklama tesisidir. Kendini klasik otel veya resort olarak tanıtmaz." },
      { question: "Havalimanı ve liman ne kadar uzakta?", answer: "Voulamandis House Sakız Havalimanı’na yaklaşık 3 km, limana yaklaşık 6 km uzaklıktadır ve uçak ya da feribotla gelenler için pratiktir." },
      { question: "Canlı müsaitliği nasıl kontrol ederim?", answer: "Bu sayfadaki aramaya giriş, çıkış ve misafir sayısını girin. Ayrıca AI Room Finder’ı kullanabilir veya WhatsApp üzerinden doğrudan iletişim kurabilirsiniz." },
    ],
  },
  finalCta: {
    kicker: "ARAMADAN GERÇEK BİR SEÇENEĞE",
    title: "Gerçek tarihlerle sakin bir Sakız Adası konaklamasını kontrol edin",
    text: "Bölgeleri karşılaştırın, seyahatinize uygun konaklama türünü seçin ve hangi oda veya dairelerin müsait olduğunu görmek için canlı aramayı kullanın.",
    primaryCta: { label: "Müsaitlik ara", href: "#live-availability" },
    secondaryCta: { label: "Tüm odaları görün", href: "/tr/sakiz-adasi-odalari/" },
  },
};
