import type { LanguageCode } from "@/lib/languages";
import { absoluteUrl } from "@/lib/seo";
import type { OrganizedBeachesPageData, OrganizedBeachCard } from "@/content/organized-beaches";

const images = {
  hero: "/images/beaches/lithi-beach-chios.webp",
  lithi: "/images/beaches/lithi-beach-chios.webp",
  karfas: "/images/beaches/agia-fotia-beach-chios.webp",
  komi: "/images/beaches/komi-sandy-beach-chios.webp",
  stay: "/images/beaches/voulamandis-house-courtyard-chios.webp",
};

export const sandyBeachPaths: Record<LanguageCode, string> = {
  en: "/chios-sandy-beaches/",
  el: "/el/paralies-me-ammo-xios/",
  fr: "/fr/plages-de-sable-chios/",
  de: "/de/sandstraende-chios/",
  it: "/it/spiagge-di-sabbia-chios/",
  es: "/es/playas-de-arena-quios/",
  tr: "/tr/sakiz-adasi-kumlu-plajlar/",
};

export const sandyBeachAlternates = {
  en: absoluteUrl(sandyBeachPaths.en),
  el: absoluteUrl(sandyBeachPaths.el),
  fr: absoluteUrl(sandyBeachPaths.fr),
  de: absoluteUrl(sandyBeachPaths.de),
  it: absoluteUrl(sandyBeachPaths.it),
  es: absoluteUrl(sandyBeachPaths.es),
  tr: absoluteUrl(sandyBeachPaths.tr),
  "x-default": absoluteUrl(sandyBeachPaths.en),
};

const hrefs = {
  en: { lithi: "/chios/chios-beaches/lithi-beach/", karfas: "/chios/chios-beaches/#sandy-beaches", komi: "/chios/chios-beaches/komi-beach/", rooms: "/chios-rooms/", beaches: "/chios/chios-beaches/" },
  el: { lithi: "/el/paralies-xios/paralia-lithi/", karfas: "/el/paralies-xios/#sandy-beaches", komi: "/el/paralies-xios/paralia-komi/", rooms: "/el/domatia-xios/", beaches: "/el/paralies-xios/" },
  fr: { lithi: "/fr/plages-de-chios/plage-lithi/", karfas: "/fr/plages-de-chios/#sandy-beaches", komi: "/fr/plages-de-chios/plage-komi/", rooms: "/fr/chambres-a-chios/", beaches: "/fr/plages-de-chios/" },
  de: { lithi: "/de/straende-chios/lithi-strand/", karfas: "/de/straende-chios/#sandy-beaches", komi: "/de/straende-chios/komi-strand/", rooms: "/de/chios-zimmer/", beaches: "/de/straende-chios/" },
  it: { lithi: "/it/spiagge-chios/spiaggia-lithi/", karfas: "/it/spiagge-chios/#sandy-beaches", komi: "/it/spiagge-chios/spiaggia-komi/", rooms: "/it/camere-a-chios/", beaches: "/it/spiagge-chios/" },
  es: { lithi: "/es/playas-chios/playa-lithi/", karfas: "/es/playas-chios/#sandy-beaches", komi: "/es/playas-chios/playa-komi/", rooms: "/es/habitaciones-en-chios/", beaches: "/es/playas-chios/" },
  tr: { lithi: "/tr/sakiz-adasi-plajlari/lithi-plaji/", karfas: "/tr/sakiz-adasi-plajlari/#sandy-beaches", komi: "/tr/sakiz-adasi-plajlari/komi-plaji/", rooms: "/tr/sakiz-adasi-odalari/", beaches: "/tr/sakiz-adasi-plajlari/" },
} as const;

const copy = {
  en: { names: ["Lithi", "Karfas", "Komi"], tag: "Sandy", desc: "A practical sandy choice with easier sea entry and a softer beach feeling.", why: "Good when you prefer sand, comfort and an easier beach day." },
  el: { names: ["Λιθί", "Καρφάς", "Κώμη"], tag: "Με άμμο", desc: "Πρακτική επιλογή με άμμο, πιο εύκολη είσοδο στη θάλασσα και πιο άνετη αίσθηση παραλίας.", why: "Καλή όταν προτιμάτε άμμο, άνεση και πιο εύκολη μέρα στη θάλασσα." },
  fr: { names: ["Lithi", "Karfas", "Komi"], tag: "Sable", desc: "Un choix pratique avec sable, entrée plus facile dans l’eau et sensation plus douce.", why: "Idéale si vous préférez le sable, le confort et une journée simple." },
  de: { names: ["Lithi", "Karfas", "Komi"], tag: "Sand", desc: "Eine praktische Wahl mit Sand, leichterem Einstieg ins Meer und angenehmem Strandgefühl.", why: "Gut, wenn Sie Sand, Komfort und einen einfachen Strandtag bevorzugen." },
  it: { names: ["Lithi", "Karfas", "Komi"], tag: "Sabbia", desc: "Una scelta pratica con sabbia, ingresso in mare più semplice e una sensazione più comoda.", why: "Ideale se preferite sabbia, comfort e una giornata facile." },
  es: { names: ["Lithi", "Karfas", "Komi"], tag: "Arena", desc: "Una opción práctica con arena, entrada al mar más fácil y una sensación cómoda.", why: "Buena si prefieres arena, comodidad y un día de playa sencillo." },
  tr: { names: ["Lithi", "Karfas", "Komi"], tag: "Kumlu", desc: "Kumlu yapısı, kolay deniz girişi ve rahat plaj hissiyle pratik bir seçenek.", why: "Kum, konfor ve kolay bir deniz günü isteyenler için iyi." },
} as const;

function cards(locale: LanguageCode): OrganizedBeachCard[] {
  const h = hrefs[locale];
  const c = copy[locale];
  return [
    { name: c.names[0], image: images.lithi, href: h.lithi, tag: c.tag, description: c.desc, why: c.why },
    { name: c.names[1], image: images.karfas, href: h.karfas, tag: c.tag, description: c.desc, why: c.why },
    { name: c.names[2], image: images.komi, href: h.komi, tag: c.tag, description: c.desc, why: c.why },
  ];
}

const tips = {
  en: [{ icon: "👣", title: "Easy entry", text: "Sandy beaches are often more comfortable for slow sea entry." }, { icon: "👨‍👩‍👧", title: "Family friendly", text: "They can be easier for families and relaxed beach days." }, { icon: "🌬️", title: "Check the wind", text: "Wind can change the best sandy choice for the day." }],
  el: [{ icon: "👣", title: "Εύκολη είσοδος", text: "Οι αμμώδεις παραλίες είναι συχνά πιο άνετες για ήπια είσοδο στη θάλασσα." }, { icon: "👨‍👩‍👧", title: "Φιλικές για οικογένειες", text: "Μπορούν να είναι πιο πρακτικές για παιδιά και χαλαρή μέρα." }, { icon: "🌬️", title: "Δείτε τον αέρα", text: "Ο αέρας αλλάζει ποια αμμώδης παραλία είναι καλύτερη κάθε μέρα." }],
  fr: [{ icon: "👣", title: "Entrée facile", text: "Les plages de sable sont souvent plus confortables pour entrer dans l’eau." }, { icon: "👨‍👩‍👧", title: "Pratique en famille", text: "Elles conviennent bien aux journées simples et détendues." }, { icon: "🌬️", title: "Vérifiez le vent", text: "Le vent peut changer le meilleur choix du jour." }],
  de: [{ icon: "👣", title: "Einfacher Einstieg", text: "Sandstrände sind oft angenehmer für einen ruhigen Einstieg ins Meer." }, { icon: "👨‍👩‍👧", title: "Familienfreundlich", text: "Sie passen gut zu entspannten Strandtagen." }, { icon: "🌬️", title: "Wind prüfen", text: "Wind kann die beste Sandstrand-Wahl verändern." }],
  it: [{ icon: "👣", title: "Ingresso facile", text: "Le spiagge sabbiose sono spesso più comode per entrare in mare." }, { icon: "👨‍👩‍👧", title: "Adatte alle famiglie", text: "Sono pratiche per giornate semplici e rilassate." }, { icon: "🌬️", title: "Controllate il vento", text: "Il vento può cambiare la scelta migliore." }],
  es: [{ icon: "👣", title: "Entrada fácil", text: "Las playas de arena suelen ser más cómodas para entrar al mar." }, { icon: "👨‍👩‍👧", title: "Para familias", text: "Funcionan bien para días sencillos y relajados." }, { icon: "🌬️", title: "Comprueba el viento", text: "El viento puede cambiar la mejor opción del día." }],
  tr: [{ icon: "👣", title: "Kolay giriş", text: "Kumlu plajlar denize yavaş ve rahat giriş için uygundur." }, { icon: "👨‍👩‍👧", title: "Ailelere uygun", text: "Sakin ve kolay plaj günleri için pratiktir." }, { icon: "🌬️", title: "Rüzgârı kontrol edin", text: "Rüzgâr günün en iyi kumlu plajını değiştirebilir." }],
};

export const sandyBeachesPages: Record<LanguageCode, OrganizedBeachesPageData> = {
  en: { locale: "en", path: sandyBeachPaths.en, seo: { canonicalPath: sandyBeachPaths.en, title: "Sandy Beaches in Chios | Voulamandis House", description: "A local guide to sandy beaches in Chios: Lithi, Karfas and Komi, with practical tips from Voulamandis House.", ogImage: images.hero }, hero: { eyebrow: "Sandy beach guide", title: "Sandy beaches in Chios for easy sea days", subtitle: "Choose Lithi, Karfas or Komi when you want sand, easier sea entry and a relaxed beach day.", image: { src: images.hero, alt: "Sandy beach in Chios" }, primaryCta: { label: "See sandy beaches", href: "#organized-beaches" }, secondaryCta: { label: "All Chios beaches", href: hrefs.en.beaches } }, intro: { title: "When to choose a sandy beach", text: ["Sandy beaches are useful when you want comfort, easier sea entry and a softer beach feeling.", "For this category we start with Lithi, Karfas and Komi."] }, highlights: { title: "Sandy beaches to consider", subtitle: "A simple list for travellers who prefer sand and easy beach planning.", cards: cards("en") }, tips: { title: "Quick tips for sandy beaches", items: tips.en }, stay: { title: "Start your sandy beach days from Kambos", text: "Voulamandis House is a practical base for choosing the right sandy beach depending on the day.", image: images.stay, primaryCta: { label: "View rooms", href: hrefs.en.rooms }, secondaryCta: { label: "All beaches", href: hrefs.en.beaches } }, finalCta: { title: "Looking for sand and easy access?", text: "Ask us during your stay and we will suggest the sandy beach that fits the weather and your route.", primaryCta: { label: "View rooms", href: hrefs.en.rooms }, secondaryCta: { label: "Explore beaches", href: hrefs.en.beaches } } },
  el: { locale: "el", path: sandyBeachPaths.el, seo: { canonicalPath: sandyBeachPaths.el, title: "Παραλίες με άμμο στη Χίο | Voulamandis House", description: "Τοπικός οδηγός για παραλίες με άμμο στη Χίο: Λιθί, Καρφάς και Κώμη, με πρακτικές συμβουλές από το Voulamandis House.", ogImage: images.hero }, hero: { eyebrow: "Παραλίες με άμμο", title: "Παραλίες με άμμο στη Χίο για εύκολες μέρες στη θάλασσα", subtitle: "Διαλέξτε Λιθί, Καρφά ή Κώμη όταν θέλετε άμμο, πιο εύκολη είσοδο στη θάλασσα και χαλαρή παραλία.", image: { src: images.hero, alt: "Παραλία με άμμο στη Χίο" }, primaryCta: { label: "Δείτε παραλίες", href: "#organized-beaches" }, secondaryCta: { label: "Όλες οι παραλίες", href: hrefs.el.beaches } }, intro: { title: "Πότε να επιλέξετε παραλία με άμμο", text: ["Οι παραλίες με άμμο είναι πρακτικές όταν θέλετε άνεση, πιο εύκολη είσοδο στη θάλασσα και πιο μαλακή αίσθηση παραλίας.", "Για αυτή την κατηγορία ξεκινάμε με Λιθί, Καρφά και Κώμη."] }, highlights: { title: "Παραλίες με άμμο που αξίζει να δείτε", subtitle: "Απλή λίστα για επισκέπτες που προτιμούν άμμο και πιο εύκολο πρόγραμμα.", cards: cards("el") }, tips: { title: "Γρήγορες συμβουλές", items: tips.el }, stay: { title: "Ξεκινήστε από τον Κάμπο", text: "Το Voulamandis House είναι πρακτική βάση για να διαλέξετε σωστά αμμώδη παραλία ανάλογα με τη μέρα.", image: images.stay, primaryCta: { label: "Δείτε δωμάτια", href: hrefs.el.rooms }, secondaryCta: { label: "Όλες οι παραλίες", href: hrefs.el.beaches } }, finalCta: { title: "Θέλετε άμμο και εύκολη πρόσβαση;", text: "Ρωτήστε μας στη διαμονή σας και θα σας προτείνουμε την παραλία που ταιριάζει στον καιρό και στη διαδρομή σας.", primaryCta: { label: "Δείτε δωμάτια", href: hrefs.el.rooms }, secondaryCta: { label: "Παραλίες Χίου", href: hrefs.el.beaches } } },
  fr: { locale: "fr", path: sandyBeachPaths.fr, seo: { canonicalPath: sandyBeachPaths.fr, title: "Plages de sable à Chios | Voulamandis House", description: "Guide local des plages de sable à Chios : Lithi, Karfas et Komi, avec conseils pratiques.", ogImage: images.hero }, hero: { eyebrow: "Plages de sable", title: "Plages de sable à Chios pour des journées faciles", subtitle: "Choisissez Lithi, Karfas ou Komi pour le sable, un accès simple à la mer et une journée détendue.", image: { src: images.hero, alt: "Plage de sable à Chios" }, primaryCta: { label: "Voir les plages", href: "#organized-beaches" }, secondaryCta: { label: "Toutes les plages", href: hrefs.fr.beaches } }, intro: { title: "Quand choisir une plage de sable", text: ["Les plages de sable sont pratiques pour plus de confort et une entrée plus simple dans l’eau.", "Pour cette catégorie, commencez par Lithi, Karfas et Komi."] }, highlights: { title: "Plages de sable à considérer", subtitle: "Une liste simple pour ceux qui préfèrent le sable.", cards: cards("fr") }, tips: { title: "Conseils rapides", items: tips.fr }, stay: { title: "Commencez depuis Kambos", text: "Voulamandis House est une base pratique pour choisir la bonne plage de sable selon la journée.", image: images.stay, primaryCta: { label: "Voir chambres", href: hrefs.fr.rooms }, secondaryCta: { label: "Toutes les plages", href: hrefs.fr.beaches } }, finalCta: { title: "Envie de sable et d’un accès simple ?", text: "Demandez-nous pendant votre séjour et nous vous conseillerons la plage adaptée.", primaryCta: { label: "Voir chambres", href: hrefs.fr.rooms }, secondaryCta: { label: "Plages de Chios", href: hrefs.fr.beaches } } },
  de: { locale: "de", path: sandyBeachPaths.de, seo: { canonicalPath: sandyBeachPaths.de, title: "Sandstrände auf Chios | Voulamandis House", description: "Lokaler Guide zu Sandstränden auf Chios: Lithi, Karfas und Komi, mit praktischen Tipps.", ogImage: images.hero }, hero: { eyebrow: "Sandstrände", title: "Sandstrände auf Chios für einfache Strandtage", subtitle: "Wählen Sie Lithi, Karfas oder Komi, wenn Sie Sand und einfachen Zugang zum Meer möchten.", image: { src: images.hero, alt: "Sandstrand auf Chios" }, primaryCta: { label: "Strände ansehen", href: "#organized-beaches" }, secondaryCta: { label: "Alle Strände", href: hrefs.de.beaches } }, intro: { title: "Wann ein Sandstrand sinnvoll ist", text: ["Sandstrände sind praktisch, wenn Sie Komfort und einen leichteren Einstieg ins Meer möchten.", "Für diese Kategorie starten wir mit Lithi, Karfas und Komi."] }, highlights: { title: "Sandstrände zur Auswahl", subtitle: "Eine einfache Liste für Reisende, die Sand bevorzugen.", cards: cards("de") }, tips: { title: "Kurze Tipps", items: tips.de }, stay: { title: "Von Kambos starten", text: "Voulamandis House ist eine praktische Basis, um den passenden Sandstrand zu wählen.", image: images.stay, primaryCta: { label: "Zimmer ansehen", href: hrefs.de.rooms }, secondaryCta: { label: "Alle Strände", href: hrefs.de.beaches } }, finalCta: { title: "Sand und einfachen Zugang gesucht?", text: "Fragen Sie uns während Ihres Aufenthalts nach der passenden Option.", primaryCta: { label: "Zimmer ansehen", href: hrefs.de.rooms }, secondaryCta: { label: "Chios Strände", href: hrefs.de.beaches } } },
  it: { locale: "it", path: sandyBeachPaths.it, seo: { canonicalPath: sandyBeachPaths.it, title: "Spiagge di sabbia a Chios | Voulamandis House", description: "Guida locale alle spiagge di sabbia a Chios: Lithi, Karfas e Komi, con consigli pratici.", ogImage: images.hero }, hero: { eyebrow: "Spiagge di sabbia", title: "Spiagge di sabbia a Chios per giornate semplici", subtitle: "Scegliete Lithi, Karfas o Komi per sabbia, ingresso facile in mare e una giornata rilassata.", image: { src: images.hero, alt: "Spiaggia di sabbia a Chios" }, primaryCta: { label: "Vedi spiagge", href: "#organized-beaches" }, secondaryCta: { label: "Tutte le spiagge", href: hrefs.it.beaches } }, intro: { title: "Quando scegliere una spiaggia di sabbia", text: ["Le spiagge sabbiose sono pratiche per comfort e ingresso più semplice in mare.", "Per questa categoria partiamo da Lithi, Karfas e Komi."] }, highlights: { title: "Spiagge di sabbia da considerare", subtitle: "Una lista semplice per chi preferisce la sabbia.", cards: cards("it") }, tips: { title: "Consigli rapidi", items: tips.it }, stay: { title: "Partite da Kambos", text: "Voulamandis House è una base pratica per scegliere la spiaggia sabbiosa giusta.", image: images.stay, primaryCta: { label: "Vedi camere", href: hrefs.it.rooms }, secondaryCta: { label: "Tutte le spiagge", href: hrefs.it.beaches } }, finalCta: { title: "Cercate sabbia e accesso facile?", text: "Chiedeteci durante il soggiorno e vi consiglieremo la spiaggia adatta.", primaryCta: { label: "Vedi camere", href: hrefs.it.rooms }, secondaryCta: { label: "Spiagge di Chios", href: hrefs.it.beaches } } },
  es: { locale: "es", path: sandyBeachPaths.es, seo: { canonicalPath: sandyBeachPaths.es, title: "Playas de arena en Quíos | Voulamandis House", description: "Guía local de playas de arena en Quíos: Lithi, Karfas y Komi, con consejos prácticos.", ogImage: images.hero }, hero: { eyebrow: "Playas de arena", title: "Playas de arena en Quíos para días fáciles", subtitle: "Elige Lithi, Karfas o Komi si quieres arena, entrada fácil al mar y un día relajado.", image: { src: images.hero, alt: "Playa de arena en Quíos" }, primaryCta: { label: "Ver playas", href: "#organized-beaches" }, secondaryCta: { label: "Todas las playas", href: hrefs.es.beaches } }, intro: { title: "Cuándo elegir una playa de arena", text: ["Las playas de arena son prácticas para más comodidad y entrada sencilla al mar.", "Para esta categoría empezamos con Lithi, Karfas y Komi."] }, highlights: { title: "Playas de arena para considerar", subtitle: "Una lista simple para quienes prefieren arena.", cards: cards("es") }, tips: { title: "Consejos rápidos", items: tips.es }, stay: { title: "Empieza desde Kambos", text: "Voulamandis House es una base práctica para elegir la playa de arena adecuada.", image: images.stay, primaryCta: { label: "Ver habitaciones", href: hrefs.es.rooms }, secondaryCta: { label: "Todas las playas", href: hrefs.es.beaches } }, finalCta: { title: "¿Buscas arena y acceso fácil?", text: "Pregúntanos durante tu estancia y te recomendaremos la playa adecuada.", primaryCta: { label: "Ver habitaciones", href: hrefs.es.rooms }, secondaryCta: { label: "Playas de Quíos", href: hrefs.es.beaches } } },
  tr: { locale: "tr", path: sandyBeachPaths.tr, seo: { canonicalPath: sandyBeachPaths.tr, title: "Sakız Adası Kumlu Plajlar | Voulamandis House", description: "Sakız Adası’nda kumlu plajlar: Lithi, Karfas ve Komi. Voulamandis House’tan pratik öneriler.", ogImage: images.hero }, hero: { eyebrow: "Kumlu plajlar", title: "Kolay deniz günleri için Sakız Adası kumlu plajları", subtitle: "Kum, kolay deniz girişi ve rahat bir plaj günü için Lithi, Karfas veya Komi’yi seçin.", image: { src: images.hero, alt: "Sakız Adası kumlu plaj" }, primaryCta: { label: "Plajları gör", href: "#organized-beaches" }, secondaryCta: { label: "Tüm plajlar", href: hrefs.tr.beaches } }, intro: { title: "Ne zaman kumlu plaj seçilmeli", text: ["Kumlu plajlar konfor ve denize kolay giriş istediğinizde pratiktir.", "Bu kategori için Lithi, Karfas ve Komi ile başlıyoruz."] }, highlights: { title: "Değerlendirilecek kumlu plajlar", subtitle: "Kum tercih edenler için basit bir liste.", cards: cards("tr") }, tips: { title: "Hızlı ipuçları", items: tips.tr }, stay: { title: "Kambos’tan başlayın", text: "Voulamandis House, doğru kumlu plajı seçmek için pratik bir başlangıç noktasıdır.", image: images.stay, primaryCta: { label: "Odaları gör", href: hrefs.tr.rooms }, secondaryCta: { label: "Tüm plajlar", href: hrefs.tr.beaches } }, finalCta: { title: "Kum ve kolay ulaşım mı arıyorsunuz?", text: "Konaklamanız sırasında bize sorun; size uygun plajı önerelim.", primaryCta: { label: "Odaları gör", href: hrefs.tr.rooms }, secondaryCta: { label: "Sakız plajları", href: hrefs.tr.beaches } } },
};

export function getSandyBeachesPageByLocale(locale: LanguageCode) { return sandyBeachesPages[locale]; }
export function getSandyBeachesPageByPath(path: string) { return Object.values(sandyBeachesPages).find((page) => page.path === path); }
