import type { LanguageCode } from "@/lib/languages";
import { absoluteUrl } from "@/lib/seo";
import type { OrganizedBeachesPageData, OrganizedBeachCard } from "@/content/organized-beaches";

const images = {
  hero: "/images/beaches/salagona-e1645969502155.webp",
  salagona: "/images/beaches/salagona-e1645969502155.webp",
  agiaDynami: "/images/beaches/691-e1645969589226.webp",
  vroulidia: "/images/beaches/vroulidia-2-1.jpg",
  katoFana: "/images/beaches/kato-fana-3.jpg",
  elinta: "/images/beaches/salagona-e1645969502155.webp",
  stay: "/images/beaches/voulamandis-house-chios-courtyard-hero-desktop.webp",
};

export const shelteredBeachPaths: Record<LanguageCode, string> = {
  en: "/chios-sheltered-beaches/",
  el: "/el/apanemes-paralies-xios/",
  fr: "/fr/plages-abritees-chios/",
  de: "/de/geschuetzte-straende-chios/",
  it: "/it/spiagge-riparate-chios/",
  es: "/es/playas-resguardadas-quios/",
  tr: "/tr/sakiz-adasi-korunakli-plajlar/",
};

export const shelteredBeachAlternates = {
  en: absoluteUrl(shelteredBeachPaths.en),
  el: absoluteUrl(shelteredBeachPaths.el),
  fr: absoluteUrl(shelteredBeachPaths.fr),
  de: absoluteUrl(shelteredBeachPaths.de),
  it: absoluteUrl(shelteredBeachPaths.it),
  es: absoluteUrl(shelteredBeachPaths.es),
  tr: absoluteUrl(shelteredBeachPaths.tr),
  "x-default": absoluteUrl(shelteredBeachPaths.en),
};

const hrefs = {
  en: { salagona: "/chios/chios-beaches/salagona-beach/", agiaDynami: "/chios/chios-beaches/agia-dynami-beach-chios/", category: "/chios/chios-beaches/#sheltered-beaches", rooms: "/chios-rooms/", beaches: "/chios/chios-beaches/" },
  el: { salagona: "/el/paralies-xios/paralia-salagona/", agiaDynami: "/el/paralies-xios/paralia-agia-dynami/", category: "/el/paralies-xios/#sheltered-beaches", rooms: "/el/domatia-xios/", beaches: "/el/paralies-xios/" },
  fr: { salagona: "/fr/plages-de-chios/plage-salagona/", agiaDynami: "/fr/plages-de-chios/plage-agia-dynami/", category: "/fr/plages-de-chios/#sheltered-beaches", rooms: "/fr/chambres-a-chios/", beaches: "/fr/plages-de-chios/" },
  de: { salagona: "/de/straende-chios/salagona-strand/", agiaDynami: "/de/straende-chios/agia-dynami-strand/", category: "/de/straende-chios/#sheltered-beaches", rooms: "/de/chios-zimmer/", beaches: "/de/straende-chios/" },
  it: { salagona: "/it/spiagge-chios/spiaggia-salagona/", agiaDynami: "/it/spiagge-chios/spiaggia-agia-dynami/", category: "/it/spiagge-chios/#sheltered-beaches", rooms: "/it/camere-a-chios/", beaches: "/it/spiagge-chios/" },
  es: { salagona: "/es/playas-chios/playa-salagona/", agiaDynami: "/es/playas-chios/playa-agia-dynami/", category: "/es/playas-chios/#sheltered-beaches", rooms: "/es/habitaciones-en-chios/", beaches: "/es/playas-chios/" },
  tr: { salagona: "/tr/sakiz-adasi-plajlari/salagona-plaji/", agiaDynami: "/tr/sakiz-adasi-plajlari/agia-dynami-plaji/", category: "/tr/sakiz-adasi-plajlari/#sheltered-beaches", rooms: "/tr/sakiz-adasi-odalari/", beaches: "/tr/sakiz-adasi-plajlari/" },
} as const;

const labels = {
  en: { names: ["Salagona", "Agia Dynami", "Vroulidia", "Kato Fana", "Elinta"], tag: "Sheltered", desc: "A local choice to consider when you want calmer conditions and a more protected beach plan.", why: "Useful when wind makes the beach choice more important." },
  el: { names: ["Σαλάγωνα", "Αγία Δύναμη", "Βρουλίδια", "Κάτω Φανά", "Ελίντα"], tag: "Απάνεμη", desc: "Τοπική επιλογή όταν θέλετε πιο ήρεμες συνθήκες και πιο προστατευμένο πλάνο για μπάνιο.", why: "Χρήσιμη όταν ο αέρας κάνει την επιλογή παραλίας πιο σημαντική." },
  fr: { names: ["Salagona", "Agia Dynami", "Vroulidia", "Kato Fana", "Elinta"], tag: "Abritée", desc: "Un choix local à considérer pour des conditions plus calmes et une journée plus protégée.", why: "Utile lorsque le vent rend le choix de plage plus important." },
  de: { names: ["Salagona", "Agia Dynami", "Vroulidia", "Kato Fana", "Elinta"], tag: "Geschützt", desc: "Eine lokale Wahl für ruhigere Bedingungen und einen besser geschützten Strandtag.", why: "Hilfreich, wenn Wind die Strandwahl wichtiger macht." },
  it: { names: ["Salagona", "Agia Dynami", "Vroulidia", "Kato Fana", "Elinta"], tag: "Riparata", desc: "Una scelta locale per condizioni più tranquille e una giornata al mare più protetta.", why: "Utile quando il vento rende più importante scegliere bene." },
  es: { names: ["Salagona", "Agia Dynami", "Vroulidia", "Kato Fana", "Elinta"], tag: "Resguardada", desc: "Una opción local para condiciones más tranquilas y un plan de playa más protegido.", why: "Útil cuando el viento hace más importante elegir bien." },
  tr: { names: ["Salagona", "Agia Dynami", "Vroulidia", "Kato Fana", "Elinta"], tag: "Korunaklı", desc: "Daha sakin koşullar ve daha korunaklı bir deniz günü için yerel seçenek.", why: "Rüzgâr plaj seçimini önemli hale getirdiğinde kullanışlıdır." },
} as const;

function cards(locale: LanguageCode): OrganizedBeachCard[] {
  const h = hrefs[locale];
  const l = labels[locale];
  return [
    { name: l.names[0], image: images.salagona, href: h.salagona, tag: l.tag, description: l.desc, why: l.why },
    { name: l.names[1], image: images.agiaDynami, href: h.agiaDynami, tag: l.tag, description: l.desc, why: l.why },
    { name: l.names[2], image: images.vroulidia, href: h.category, tag: l.tag, description: l.desc, why: l.why },
    { name: l.names[3], image: images.katoFana, href: h.category, tag: l.tag, description: l.desc, why: l.why },
    { name: l.names[4], image: images.elinta, href: h.category, tag: l.tag, description: l.desc, why: l.why },
  ];
}

const tips = {
  en: [{ icon: "🌬️", title: "Check wind direction", text: "A sheltered beach can be a better choice on windy days." }, { icon: "🚗", title: "Keep alternatives", text: "Have two options ready before leaving, especially with children." }, { icon: "🧭", title: "Ask locally", text: "Local advice is the safest way to match the beach to the day." }],
  el: [{ icon: "🌬️", title: "Ελέγξτε τον άνεμο", text: "Μια απάνεμη παραλία μπορεί να είναι καλύτερη επιλογή όταν φυσάει." }, { icon: "🚗", title: "Κρατήστε εναλλακτική", text: "Έχετε δύο επιλογές πριν ξεκινήσετε, ειδικά αν είστε με παιδιά." }, { icon: "🧭", title: "Ρωτήστε τοπικά", text: "Η τοπική συμβουλή είναι ο ασφαλέστερος τρόπος να ταιριάξετε παραλία και μέρα." }],
  fr: [{ icon: "🌬️", title: "Vérifiez le vent", text: "Une plage abritée peut être meilleure par temps venteux." }, { icon: "🚗", title: "Gardez une alternative", text: "Préparez deux options avant de partir." }, { icon: "🧭", title: "Demandez localement", text: "Le conseil local aide à choisir selon la journée." }],
  de: [{ icon: "🌬️", title: "Wind prüfen", text: "Ein geschützter Strand kann bei Wind die bessere Wahl sein." }, { icon: "🚗", title: "Alternative behalten", text: "Planen Sie vor der Abfahrt zwei Optionen." }, { icon: "🧭", title: "Lokal fragen", text: "Lokale Tipps helfen, Strand und Tag richtig abzustimmen." }],
  it: [{ icon: "🌬️", title: "Controllate il vento", text: "Una spiaggia riparata può essere migliore quando c’è vento." }, { icon: "🚗", title: "Tenete un’alternativa", text: "Preparate due opzioni prima di partire." }, { icon: "🧭", title: "Chiedete localmente", text: "I consigli locali aiutano a scegliere bene." }],
  es: [{ icon: "🌬️", title: "Comprueba el viento", text: "Una playa resguardada puede ser mejor con viento." }, { icon: "🚗", title: "Ten alternativa", text: "Prepara dos opciones antes de salir." }, { icon: "🧭", title: "Pregunta localmente", text: "El consejo local ayuda a elegir según el día." }],
  tr: [{ icon: "🌬️", title: "Rüzgârı kontrol edin", text: "Rüzgârlı günlerde korunaklı plaj daha iyi olabilir." }, { icon: "🚗", title: "Alternatif tutun", text: "Yola çıkmadan önce iki seçenek hazırlayın." }, { icon: "🧭", title: "Yerel olarak sorun", text: "Yerel öneriler doğru günü doğru plajla eşleştirir." }],
};

export const shelteredBeachesPages: Record<LanguageCode, OrganizedBeachesPageData> = {
  en: { locale: "en", path: shelteredBeachPaths.en, seo: { canonicalPath: shelteredBeachPaths.en, title: "Sheltered Beaches in Chios | Voulamandis House", description: "A local guide to sheltered beaches in Chios: Salagona, Agia Dynami, Vroulidia, Kato Fana and Elinta, with wind-aware beach tips.", ogImage: images.hero }, hero: { eyebrow: "Sheltered beach guide", title: "Sheltered beaches in Chios for wind-aware beach days", subtitle: "Choose local beach options that are useful when the wind matters and you want a calmer, more protected swim plan.", image: { src: images.hero, alt: "Sheltered beach in Chios" }, primaryCta: { label: "See sheltered beaches", href: "#organized-beaches" }, secondaryCta: { label: "All Chios beaches", href: hrefs.en.beaches } }, intro: { title: "When to choose a sheltered beach", text: ["On Chios, the wind can change the best beach choice of the day. Sheltered beaches are useful when you want a calmer, more protected plan.", "For this category we start with Salagona, Agia Dynami, Vroulidia, Kato Fana and Elinta."] }, highlights: { title: "Sheltered beaches to consider", subtitle: "A practical list for wind-aware beach planning in Chios.", cards: cards("en") }, tips: { title: "Quick tips for sheltered beaches", items: tips.en }, stay: { title: "Ask locally before you drive", text: "Voulamandis House can help you choose a beach based on the wind, your route and the kind of day you want.", image: images.stay, primaryCta: { label: "View rooms", href: hrefs.en.rooms }, secondaryCta: { label: "All beaches", href: hrefs.en.beaches } }, finalCta: { title: "Want the best beach for today’s wind?", text: "Ask us during your stay and we will suggest the most suitable beach for the day.", primaryCta: { label: "View rooms", href: hrefs.en.rooms }, secondaryCta: { label: "Explore beaches", href: hrefs.en.beaches } } },
  el: { locale: "el", path: shelteredBeachPaths.el, seo: { canonicalPath: shelteredBeachPaths.el, title: "Απάνεμες παραλίες Χίου | Voulamandis House", description: "Τοπικός οδηγός για απάνεμες παραλίες στη Χίο: Σαλάγωνα, Αγία Δύναμη, Βρουλίδια, Κάτω Φανά και Ελίντα, με πρακτικές συμβουλές.", ogImage: images.hero }, hero: { eyebrow: "Απάνεμες παραλίες", title: "Απάνεμες παραλίες στη Χίο για μέρες με αέρα", subtitle: "Διαλέξτε τοπικές επιλογές που βοηθούν όταν ο αέρας επηρεάζει το μπάνιο και θέλετε πιο ήρεμο, προστατευμένο πλάνο.", image: { src: images.hero, alt: "Απάνεμη παραλία στη Χίο" }, primaryCta: { label: "Δείτε απάνεμες", href: "#organized-beaches" }, secondaryCta: { label: "Όλες οι παραλίες", href: hrefs.el.beaches } }, intro: { title: "Πότε να επιλέξετε απάνεμη παραλία", text: ["Στη Χίο ο αέρας μπορεί να αλλάξει την καλύτερη επιλογή παραλίας για τη μέρα. Οι απάνεμες παραλίες είναι χρήσιμες όταν θέλετε πιο ήρεμο και προστατευμένο πλάνο.", "Για αυτή την κατηγορία ξεκινάμε με Σαλάγωνα, Αγία Δύναμη, Βρουλίδια, Κάτω Φανά και Ελίντα."] }, highlights: { title: "Απάνεμες παραλίες που αξίζει να δείτε", subtitle: "Πρακτική λίστα για καλύτερο προγραμματισμό όταν φυσάει στη Χίο.", cards: cards("el") }, tips: { title: "Γρήγορες συμβουλές για απάνεμες παραλίες", items: tips.el }, stay: { title: "Ρωτήστε τοπικά πριν ξεκινήσετε", text: "Το Voulamandis House μπορεί να σας βοηθήσει να διαλέξετε παραλία ανάλογα με τον αέρα, τη διαδρομή και τη μέρα που θέλετε.", image: images.stay, primaryCta: { label: "Δείτε δωμάτια", href: hrefs.el.rooms }, secondaryCta: { label: "Όλες οι παραλίες", href: hrefs.el.beaches } }, finalCta: { title: "Θέλετε την καλύτερη παραλία για τον σημερινό αέρα;", text: "Ρωτήστε μας στη διαμονή σας και θα σας προτείνουμε την πιο κατάλληλη επιλογή για τη μέρα.", primaryCta: { label: "Δείτε δωμάτια", href: hrefs.el.rooms }, secondaryCta: { label: "Παραλίες Χίου", href: hrefs.el.beaches } } },
  fr: { locale: "fr", path: shelteredBeachPaths.fr, seo: { canonicalPath: shelteredBeachPaths.fr, title: "Plages abritées à Chios | Voulamandis House", description: "Guide local des plages abritées à Chios : Salagona, Agia Dynami, Vroulidia, Kato Fana et Elinta, avec conseils pratiques.", ogImage: images.hero }, hero: { eyebrow: "Plages abritées", title: "Plages abritées à Chios pour les journées venteuses", subtitle: "Choisissez des options locales utiles quand le vent compte et que vous souhaitez une baignade plus calme.", image: { src: images.hero, alt: "Plage abritée à Chios" }, primaryCta: { label: "Voir les plages", href: "#organized-beaches" }, secondaryCta: { label: "Toutes les plages", href: hrefs.fr.beaches } }, intro: { title: "Quand choisir une plage abritée", text: ["À Chios, le vent peut changer le meilleur choix de plage. Les plages abritées sont utiles pour une journée plus calme.", "Pour cette catégorie, commencez par Salagona, Agia Dynami, Vroulidia, Kato Fana et Elinta."] }, highlights: { title: "Plages abritées à considérer", subtitle: "Une liste pratique pour organiser la plage selon le vent.", cards: cards("fr") }, tips: { title: "Conseils rapides", items: tips.fr }, stay: { title: "Demandez localement avant de partir", text: "Voulamandis House peut vous aider à choisir selon le vent, votre route et le type de journée souhaité.", image: images.stay, primaryCta: { label: "Voir chambres", href: hrefs.fr.rooms }, secondaryCta: { label: "Toutes les plages", href: hrefs.fr.beaches } }, finalCta: { title: "Besoin de la meilleure plage selon le vent ?", text: "Demandez-nous pendant votre séjour et nous vous proposerons l’option adaptée.", primaryCta: { label: "Voir chambres", href: hrefs.fr.rooms }, secondaryCta: { label: "Plages de Chios", href: hrefs.fr.beaches } } },
  de: { locale: "de", path: shelteredBeachPaths.de, seo: { canonicalPath: shelteredBeachPaths.de, title: "Geschützte Strände auf Chios | Voulamandis House", description: "Lokaler Guide zu geschützten Stränden auf Chios: Salagona, Agia Dynami, Vroulidia, Kato Fana und Elinta, mit praktischen Tipps.", ogImage: images.hero }, hero: { eyebrow: "Geschützte Strände", title: "Geschützte Strände auf Chios für windige Tage", subtitle: "Wählen Sie lokale Optionen, wenn Wind wichtig ist und Sie einen ruhigeren Badeplan möchten.", image: { src: images.hero, alt: "Geschützter Strand auf Chios" }, primaryCta: { label: "Strände ansehen", href: "#organized-beaches" }, secondaryCta: { label: "Alle Strände", href: hrefs.de.beaches } }, intro: { title: "Wann ein geschützter Strand sinnvoll ist", text: ["Auf Chios kann der Wind die beste Strandwahl verändern. Geschützte Strände sind hilfreich für ruhigere Tage.", "Für diese Kategorie starten wir mit Salagona, Agia Dynami, Vroulidia, Kato Fana und Elinta."] }, highlights: { title: "Geschützte Strände zur Auswahl", subtitle: "Eine praktische Liste für windbewusste Strandplanung.", cards: cards("de") }, tips: { title: "Kurze Tipps", items: tips.de }, stay: { title: "Fragen Sie lokal vor der Abfahrt", text: "Voulamandis House hilft Ihnen, je nach Wind, Route und Tagesplan zu wählen.", image: images.stay, primaryCta: { label: "Zimmer ansehen", href: hrefs.de.rooms }, secondaryCta: { label: "Alle Strände", href: hrefs.de.beaches } }, finalCta: { title: "Den besten Strand für den Wind finden?", text: "Fragen Sie uns während Ihres Aufenthalts nach der passenden Option.", primaryCta: { label: "Zimmer ansehen", href: hrefs.de.rooms }, secondaryCta: { label: "Chios Strände", href: hrefs.de.beaches } } },
  it: { locale: "it", path: shelteredBeachPaths.it, seo: { canonicalPath: shelteredBeachPaths.it, title: "Spiagge riparate a Chios | Voulamandis House", description: "Guida locale alle spiagge riparate a Chios: Salagona, Agia Dynami, Vroulidia, Kato Fana ed Elinta, con consigli pratici.", ogImage: images.hero }, hero: { eyebrow: "Spiagge riparate", title: "Spiagge riparate a Chios per giornate ventose", subtitle: "Scegliete opzioni locali utili quando il vento conta e desiderate una giornata più calma.", image: { src: images.hero, alt: "Spiaggia riparata a Chios" }, primaryCta: { label: "Vedi spiagge", href: "#organized-beaches" }, secondaryCta: { label: "Tutte le spiagge", href: hrefs.it.beaches } }, intro: { title: "Quando scegliere una spiaggia riparata", text: ["A Chios il vento può cambiare la scelta migliore. Le spiagge riparate aiutano a pianificare una giornata più tranquilla.", "Per questa categoria partiamo da Salagona, Agia Dynami, Vroulidia, Kato Fana ed Elinta."] }, highlights: { title: "Spiagge riparate da considerare", subtitle: "Una lista pratica per scegliere in base al vento.", cards: cards("it") }, tips: { title: "Consigli rapidi", items: tips.it }, stay: { title: "Chiedete localmente prima di partire", text: "Voulamandis House può aiutarvi a scegliere in base a vento, percorso e tipo di giornata.", image: images.stay, primaryCta: { label: "Vedi camere", href: hrefs.it.rooms }, secondaryCta: { label: "Tutte le spiagge", href: hrefs.it.beaches } }, finalCta: { title: "Volete la spiaggia giusta per il vento?", text: "Chiedeteci durante il soggiorno e vi suggeriremo l’opzione più adatta.", primaryCta: { label: "Vedi camere", href: hrefs.it.rooms }, secondaryCta: { label: "Spiagge di Chios", href: hrefs.it.beaches } } },
  es: { locale: "es", path: shelteredBeachPaths.es, seo: { canonicalPath: shelteredBeachPaths.es, title: "Playas resguardadas en Quíos | Voulamandis House", description: "Guía local de playas resguardadas en Quíos: Salagona, Agia Dynami, Vroulidia, Kato Fana y Elinta, con consejos prácticos.", ogImage: images.hero }, hero: { eyebrow: "Playas resguardadas", title: "Playas resguardadas en Quíos para días con viento", subtitle: "Elige opciones locales útiles cuando el viento importa y buscas un baño más tranquilo.", image: { src: images.hero, alt: "Playa resguardada en Quíos" }, primaryCta: { label: "Ver playas", href: "#organized-beaches" }, secondaryCta: { label: "Todas las playas", href: hrefs.es.beaches } }, intro: { title: "Cuándo elegir una playa resguardada", text: ["En Quíos, el viento puede cambiar la mejor elección de playa. Las playas resguardadas ayudan a planificar un día más tranquilo.", "Para esta categoría empezamos con Salagona, Agia Dynami, Vroulidia, Kato Fana y Elinta."] }, highlights: { title: "Playas resguardadas para considerar", subtitle: "Una lista práctica para planificar según el viento.", cards: cards("es") }, tips: { title: "Consejos rápidos", items: tips.es }, stay: { title: "Pregunta localmente antes de salir", text: "Voulamandis House puede ayudarte a elegir según el viento, la ruta y el tipo de día.", image: images.stay, primaryCta: { label: "Ver habitaciones", href: hrefs.es.rooms }, secondaryCta: { label: "Todas las playas", href: hrefs.es.beaches } }, finalCta: { title: "¿Quieres la mejor playa para el viento?", text: "Pregúntanos durante tu estancia y te sugeriremos la opción adecuada.", primaryCta: { label: "Ver habitaciones", href: hrefs.es.rooms }, secondaryCta: { label: "Playas de Quíos", href: hrefs.es.beaches } } },
  tr: { locale: "tr", path: shelteredBeachPaths.tr, seo: { canonicalPath: shelteredBeachPaths.tr, title: "Sakız Adası Korunaklı Plajlar | Voulamandis House", description: "Sakız Adası’nda korunaklı plajlar: Salagona, Agia Dynami, Vroulidia, Kato Fana ve Elinta. Pratik yerel öneriler.", ogImage: images.hero }, hero: { eyebrow: "Korunaklı plajlar", title: "Rüzgârlı günler için Sakız Adası korunaklı plajları", subtitle: "Rüzgâr önemli olduğunda ve daha sakin bir deniz planı istediğinizde yerel seçenekleri değerlendirin.", image: { src: images.hero, alt: "Sakız Adası’nda korunaklı plaj" }, primaryCta: { label: "Plajları gör", href: "#organized-beaches" }, secondaryCta: { label: "Tüm plajlar", href: hrefs.tr.beaches } }, intro: { title: "Ne zaman korunaklı plaj seçilmeli", text: ["Sakız Adası’nda rüzgâr günün en iyi plaj seçimini değiştirebilir. Korunaklı plajlar daha sakin plan için yardımcıdır.", "Bu kategori için Salagona, Agia Dynami, Vroulidia, Kato Fana ve Elinta ile başlıyoruz."] }, highlights: { title: "Değerlendirilecek korunaklı plajlar", subtitle: "Rüzgâra göre plaj planlamak için pratik liste.", cards: cards("tr") }, tips: { title: "Hızlı ipuçları", items: tips.tr }, stay: { title: "Yola çıkmadan önce yerel öneri alın", text: "Voulamandis House rüzgâr, rota ve gün planınıza göre plaj seçmenize yardımcı olabilir.", image: images.stay, primaryCta: { label: "Odaları gör", href: hrefs.tr.rooms }, secondaryCta: { label: "Tüm plajlar", href: hrefs.tr.beaches } }, finalCta: { title: "Rüzgâra göre en iyi plajı ister misiniz?", text: "Konaklamanız sırasında bize sorun; en uygun seçeneği önerelim.", primaryCta: { label: "Odaları gör", href: hrefs.tr.rooms }, secondaryCta: { label: "Sakız plajları", href: hrefs.tr.beaches } } },
};

export function getShelteredBeachesPageByLocale(locale: LanguageCode) { return shelteredBeachesPages[locale]; }
export function getShelteredBeachesPageByPath(path: string) { return Object.values(shelteredBeachesPages).find((page) => page.path === path); }
