import type { ChiosVillagesPageData } from "@/content/chios-villages";
import {
  chiosVillagesPageDe,
  chiosVillagesPageEl,
  chiosVillagesPageEn,
  chiosVillagesPageEs,
  chiosVillagesPageFr,
  chiosVillagesPageIt,
  chiosVillagesPageTr,
} from "@/content/chios-villages";
import { absoluteUrl } from "@/lib/seo";

type LanguageCode = "en" | "el" | "fr" | "de" | "it" | "es" | "tr";
export type VillageCategoryKey = "mastic" | "medieval" | "seaside";

const basePages: Record<LanguageCode, ChiosVillagesPageData> = {
  en: chiosVillagesPageEn,
  el: chiosVillagesPageEl,
  fr: chiosVillagesPageFr,
  de: chiosVillagesPageDe,
  it: chiosVillagesPageIt,
  es: chiosVillagesPageEs,
  tr: chiosVillagesPageTr,
};

export const villageCategoryPaths: Record<VillageCategoryKey, Record<LanguageCode, string>> = {
  mastic: {
    en: "/chios-mastic-villages/",
    el: "/el/mastichochoria-xios/",
    fr: "/fr/villages-du-mastic-chios/",
    de: "/de/mastixdoerfer-chios/",
    it: "/it/villaggi-del-mastice-chios/",
    es: "/es/pueblos-del-mastiha-quios/",
    tr: "/tr/sakiz-adasi-mastik-koyleri/",
  },
  medieval: {
    en: "/chios-medieval-villages/",
    el: "/el/mesaionika-xoria-xios/",
    fr: "/fr/villages-medievaux-chios/",
    de: "/de/mittelalterliche-doerfer-chios/",
    it: "/it/villaggi-medievali-chios/",
    es: "/es/pueblos-medievales-quios/",
    tr: "/tr/sakiz-adasi-orta-cag-koyleri/",
  },
  seaside: {
    en: "/chios-seaside-villages/",
    el: "/el/parathalassia-xoria-xios/",
    fr: "/fr/villages-en-bord-de-mer-chios/",
    de: "/de/kuestendoerfer-chios/",
    it: "/it/villaggi-sul-mare-chios/",
    es: "/es/pueblos-costeros-quios/",
    tr: "/tr/sakiz-adasi-sahil-koyleri/",
  },
};

function buildAlternates(paths: Record<LanguageCode, string>) {
  return {
    en: absoluteUrl(paths.en),
    el: absoluteUrl(paths.el),
    fr: absoluteUrl(paths.fr),
    de: absoluteUrl(paths.de),
    it: absoluteUrl(paths.it),
    es: absoluteUrl(paths.es),
    tr: absoluteUrl(paths.tr),
    "x-default": absoluteUrl(paths.en),
  };
}

export const villageCategoryAlternates = {
  mastic: buildAlternates(villageCategoryPaths.mastic),
  medieval: buildAlternates(villageCategoryPaths.medieval),
  seaside: buildAlternates(villageCategoryPaths.seaside),
};

const categoryVillageIds: Record<VillageCategoryKey, string[]> = {
  mastic: ["pyrgi", "mesta", "olympoi", "armolia", "vessa"],
  medieval: ["pyrgi", "mesta", "vessa", "olympoi", "volissos"],
  seaside: ["lagada", "volissos"],
};

const categoryCopy: Record<VillageCategoryKey, Record<LanguageCode, {
  seoTitle: string;
  seoDescription: string;
  kicker: string;
  title: string;
  description: string;
  introKicker: string;
  introTitle: string;
  introDescription: string;
  listKicker: string;
  listTitle: string;
  listText: string;
  planningTitle: string;
  planningDescription: string;
}>> = {
  mastic: {
    en: {
      seoTitle: "Mastic Villages of Chios | Voulamandis House",
      seoDescription: "Explore the mastic villages of Chios, including Pyrgi, Mesta, Olympoi, Armolia and Vessa, with local planning tips from Voulamandis House.",
      kicker: "Chios village routes",
      title: "Mastic villages of Chios",
      description: "Plan a southern Chios route through villages shaped by mastic culture, medieval layouts, decorated houses and local craft traditions.",
      introKicker: "Mastic village planning",
      introTitle: "The most distinctive village route in southern Chios",
      introDescription: "The mastic villages are among the strongest cultural experiences in Chios. They combine medieval architecture, local traditions, narrow streets and everyday village life in the south of the island.",
      listKicker: "Mastic villages",
      listTitle: "Villages to include in a mastic route",
      listText: "Use these villages as the core of a southern Chios day, then combine them with nearby beaches, food stops or Chios Town on the way back.",
      planningTitle: "How to plan a mastic village day",
      planningDescription: "Start with one or two headline villages, then add quieter stops so the route feels relaxed rather than rushed.",
    },
    el: {
      seoTitle: "Μαστιχοχώρια Χίου | Voulamandis House",
      seoDescription: "Ανακαλύψτε τα Μαστιχοχώρια της Χίου, όπως Πυργί, Μεστά, Ολύμποι, Αρμόλια και Βέσσα, με πρακτικές συμβουλές διαδρομής.",
      kicker: "Διαδρομές χωριών Χίου",
      title: "Μαστιχοχώρια Χίου",
      description: "Οργανώστε μια διαδρομή στη νότια Χίο μέσα από χωριά με μαστιχική παράδοση, μεσαιωνική δομή, ξυστά και τοπική χειροτεχνία.",
      introKicker: "Οργάνωση Μαστιχοχωρίων",
      introTitle: "Η πιο χαρακτηριστική διαδρομή χωριών στη νότια Χίο",
      introDescription: "Τα Μαστιχοχώρια είναι από τις πιο δυνατές πολιτιστικές εμπειρίες της Χίου. Συνδυάζουν μεσαιωνική αρχιτεκτονική, τοπικές παραδόσεις, στενά σοκάκια και αυθεντική ζωή χωριού.",
      listKicker: "Μαστιχοχώρια",
      listTitle: "Χωριά που αξίζει να βάλετε στη διαδρομή",
      listText: "Χρησιμοποιήστε αυτά τα χωριά ως βασικό κορμό για μια μέρα στη νότια Χίο και συνδυάστε τα με παραλίες, φαγητό ή επιστροφή από την πόλη.",
      planningTitle: "Πώς να οργανώσετε τη μέρα στα Μαστιχοχώρια",
      planningDescription: "Ξεκινήστε με ένα ή δύο βασικά χωριά και προσθέστε πιο ήσυχες στάσεις ώστε η διαδρομή να μη γίνει βιαστική.",
    },
    fr: {
      seoTitle: "Villages du mastic à Chios | Voulamandis House",
      seoDescription: "Découvrez les villages du mastic à Chios, dont Pyrgi, Mesta, Olympoi, Armolia et Vessa, avec des conseils de visite.",
      kicker: "Itinéraires de villages",
      title: "Villages du mastic à Chios",
      description: "Organisez une route dans le sud de Chios entre culture du mastic, architecture médiévale, maisons décorées et artisanat local.",
      introKicker: "Préparer les villages du mastic",
      introTitle: "L’itinéraire villageois le plus caractéristique du sud de Chios",
      introDescription: "Les villages du mastic font partie des expériences culturelles les plus fortes de Chios, avec architecture médiévale, traditions locales et ruelles étroites.",
      listKicker: "Villages du mastic",
      listTitle: "Villages à inclure dans votre route",
      listText: "Utilisez ces villages comme base d’une journée dans le sud de Chios, puis ajoutez plages ou haltes gourmandes.",
      planningTitle: "Comment organiser une journée villages du mastic",
      planningDescription: "Commencez par un ou deux villages majeurs, puis ajoutez des arrêts plus calmes pour garder un rythme agréable.",
    },
    de: {
      seoTitle: "Mastixdörfer auf Chios | Voulamandis House",
      seoDescription: "Entdecken Sie die Mastixdörfer auf Chios, darunter Pyrgi, Mesta, Olympoi, Armolia und Vessa, mit lokalen Planungstipps.",
      kicker: "Dörfer-Routen auf Chios",
      title: "Mastixdörfer auf Chios",
      description: "Planen Sie eine Route im Süden von Chios mit Mastixkultur, mittelalterlichen Dorfstrukturen, dekorierten Häusern und lokalem Handwerk.",
      introKicker: "Mastixdörfer planen",
      introTitle: "Die charakteristischste Dörfer-Route im Süden von Chios",
      introDescription: "Die Mastixdörfer gehören zu den stärksten Kulturerlebnissen der Insel und verbinden mittelalterliche Architektur, lokale Traditionen und enge Gassen.",
      listKicker: "Mastixdörfer",
      listTitle: "Dörfer für Ihre Mastix-Route",
      listText: "Diese Dörfer bilden den Kern eines Tages im Süden von Chios und lassen sich gut mit Stränden oder Essensstopps kombinieren.",
      planningTitle: "So planen Sie einen Tag in den Mastixdörfern",
      planningDescription: "Beginnen Sie mit ein oder zwei Hauptdörfern und ergänzen Sie ruhigere Stopps, damit die Route entspannt bleibt.",
    },
    it: {
      seoTitle: "Villaggi del mastice a Chios | Voulamandis House",
      seoDescription: "Scopri i villaggi del mastice a Chios, tra cui Pyrgi, Mesta, Olympoi, Armolia e Vessa, con consigli pratici.",
      kicker: "Itinerari nei villaggi",
      title: "Villaggi del mastice a Chios",
      description: "Organizza un itinerario nel sud di Chios tra cultura del mastice, architettura medievale, case decorate e artigianato locale.",
      introKicker: "Pianificare i villaggi del mastice",
      introTitle: "L’itinerario più caratteristico del sud di Chios",
      introDescription: "I villaggi del mastice sono tra le esperienze culturali più forti di Chios, con architettura medievale, tradizioni locali e vicoli stretti.",
      listKicker: "Villaggi del mastice",
      listTitle: "Villaggi da includere nell’itinerario",
      listText: "Usa questi villaggi come base per una giornata nel sud di Chios, aggiungendo spiagge o soste gastronomiche.",
      planningTitle: "Come organizzare una giornata nei villaggi del mastice",
      planningDescription: "Inizia con uno o due villaggi principali e aggiungi tappe più tranquille per mantenere un ritmo piacevole.",
    },
    es: {
      seoTitle: "Pueblos del mastiha en Chios | Voulamandis House",
      seoDescription: "Descubre los pueblos del mastiha en Chios, como Pyrgi, Mesta, Olympoi, Armolia y Vessa, con consejos prácticos.",
      kicker: "Rutas por pueblos",
      title: "Pueblos del mastiha en Chios",
      description: "Organiza una ruta por el sur de Chios entre cultura del mastiha, arquitectura medieval, casas decoradas y artesanía local.",
      introKicker: "Planificar los pueblos del mastiha",
      introTitle: "La ruta de pueblos más característica del sur de Chios",
      introDescription: "Los pueblos del mastiha son una de las experiencias culturales más fuertes de Chios, con arquitectura medieval, tradiciones locales y calles estrechas.",
      listKicker: "Pueblos del mastiha",
      listTitle: "Pueblos para incluir en la ruta",
      listText: "Usa estos pueblos como base para un día en el sur de Chios y combínalos con playas o paradas gastronómicas.",
      planningTitle: "Cómo organizar un día en los pueblos del mastiha",
      planningDescription: "Empieza por uno o dos pueblos principales y añade paradas más tranquilas para no ir con prisas.",
    },
    tr: {
      seoTitle: "Sakız Adası Mastik Köyleri | Voulamandis House",
      seoDescription: "Pyrgi, Mesta, Olympoi, Armolia ve Vessa dahil Sakız Adası mastik köylerini yerel önerilerle keşfedin.",
      kicker: "Köy rotaları",
      title: "Sakız Adası mastik köyleri",
      description: "Mastik kültürü, Orta Çağ dokusu, süslü evler ve yerel zanaatlarla Sakız’ın güneyinde bir köy rotası planlayın.",
      introKicker: "Mastik köyleri planı",
      introTitle: "Güney Sakız’ın en karakteristik köy rotası",
      introDescription: "Mastik köyleri, Orta Çağ mimarisi, yerel gelenekler ve dar sokaklarıyla Sakız Adası’nın en güçlü kültürel deneyimlerindendir.",
      listKicker: "Mastik köyleri",
      listTitle: "Rotaya eklenebilecek köyler",
      listText: "Bu köyleri güney Sakız günü için temel alın; plajlar ve yemek molalarıyla birleştirin.",
      planningTitle: "Mastik köylerinde bir gün nasıl planlanır",
      planningDescription: "Bir veya iki ana köyle başlayın, sonra daha sakin duraklar ekleyerek rotayı rahat tutun.",
    },
  },
  medieval: {
    en: {
      seoTitle: "Medieval Villages of Chios | Voulamandis House",
      seoDescription: "Explore medieval villages in Chios, including Mesta, Pyrgi, Vessa, Olympoi and Volissos, with route ideas from Voulamandis House.",
      kicker: "Historic Chios routes",
      title: "Medieval villages of Chios",
      description: "Follow Chios through fortified villages, stone alleys, castle views and traditional architecture.",
      introKicker: "Medieval village planning",
      introTitle: "Stone alleys, fortress layouts and living history",
      introDescription: "Several Chios villages still preserve a medieval feeling through narrow streets, defensive layouts, stone houses and historic squares.",
      listKicker: "Medieval villages",
      listTitle: "Villages with strong historic character",
      listText: "These stops are ideal when you want architecture, history, photography and a slower village walk.",
      planningTitle: "How to plan a medieval village route",
      planningDescription: "Combine the southern villages in one route, or leave Volissos for a separate northwest Chios day.",
    },
    el: {
      seoTitle: "Μεσαιωνικά χωριά Χίου | Voulamandis House",
      seoDescription: "Ανακαλύψτε μεσαιωνικά χωριά της Χίου, όπως Μεστά, Πυργί, Βέσσα, Ολύμποι και Βολισσός, με ιδέες διαδρομής.",
      kicker: "Ιστορικές διαδρομές Χίου",
      title: "Μεσαιωνικά χωριά Χίου",
      description: "Ακολουθήστε τη Χίο μέσα από καστροχώρια, πέτρινα σοκάκια, κάστρα και παραδοσιακή αρχιτεκτονική.",
      introKicker: "Οργάνωση μεσαιωνικών χωριών",
      introTitle: "Πέτρινα σοκάκια, καστροχωρίτικη δομή και ζωντανή ιστορία",
      introDescription: "Αρκετά χωριά της Χίου κρατούν ακόμη έντονη μεσαιωνική αίσθηση μέσα από στενά σοκάκια, αμυντική διάταξη, πέτρινα σπίτια και ιστορικές πλατείες.",
      listKicker: "Μεσαιωνικά χωριά",
      listTitle: "Χωριά με έντονο ιστορικό χαρακτήρα",
      listText: "Ιδανικές στάσεις όταν θέλετε αρχιτεκτονική, ιστορία, φωτογραφίες και ήρεμη βόλτα μέσα στο χωριό.",
      planningTitle: "Πώς να οργανώσετε διαδρομή στα μεσαιωνικά χωριά",
      planningDescription: "Συνδυάστε τα νότια χωριά σε μία διαδρομή ή κρατήστε τη Βολισσό για ξεχωριστή μέρα στη βορειοδυτική Χίο.",
    },
    fr: {
      seoTitle: "Villages médiévaux de Chios | Voulamandis House",
      seoDescription: "Explorez les villages médiévaux de Chios, dont Mesta, Pyrgi, Vessa, Olympoi et Volissos.",
      kicker: "Routes historiques",
      title: "Villages médiévaux de Chios",
      description: "Découvrez Chios à travers villages fortifiés, ruelles de pierre, vues de château et architecture traditionnelle.",
      introKicker: "Préparer les villages médiévaux",
      introTitle: "Ruelles de pierre, formes fortifiées et histoire vivante",
      introDescription: "Plusieurs villages de Chios conservent une atmosphère médiévale avec ruelles étroites, maisons en pierre et places historiques.",
      listKicker: "Villages médiévaux",
      listTitle: "Villages au fort caractère historique",
      listText: "Des arrêts parfaits pour l’architecture, l’histoire, les photos et une promenade calme.",
      planningTitle: "Comment organiser une route médiévale",
      planningDescription: "Combinez les villages du sud ou gardez Volissos pour une journée au nord-ouest.",
    },
    de: {
      seoTitle: "Mittelalterliche Dörfer auf Chios | Voulamandis House",
      seoDescription: "Entdecken Sie mittelalterliche Dörfer auf Chios, darunter Mesta, Pyrgi, Vessa, Olympoi und Volissos.",
      kicker: "Historische Chios-Routen",
      title: "Mittelalterliche Dörfer auf Chios",
      description: "Erleben Sie Chios mit Wehrdörfern, Steingassen, Burgenblicken und traditioneller Architektur.",
      introKicker: "Mittelalterliche Dörfer planen",
      introTitle: "Steingassen, Wehrstrukturen und lebendige Geschichte",
      introDescription: "Mehrere Dörfer auf Chios bewahren ein mittelalterliches Gefühl durch enge Gassen, Steinarchitektur und historische Plätze.",
      listKicker: "Mittelalterliche Dörfer",
      listTitle: "Dörfer mit starkem historischen Charakter",
      listText: "Ideal für Architektur, Geschichte, Fotos und einen ruhigen Spaziergang durch das Dorf.",
      planningTitle: "So planen Sie eine mittelalterliche Dorfroute",
      planningDescription: "Kombinieren Sie die südlichen Dörfer oder planen Sie Volissos separat für den Nordwesten.",
    },
    it: {
      seoTitle: "Villaggi medievali di Chios | Voulamandis House",
      seoDescription: "Scopri i villaggi medievali di Chios, tra cui Mesta, Pyrgi, Vessa, Olympoi e Volissos.",
      kicker: "Itinerari storici",
      title: "Villaggi medievali di Chios",
      description: "Segui Chios tra villaggi fortificati, vicoli in pietra, castelli e architettura tradizionale.",
      introKicker: "Pianificare i villaggi medievali",
      introTitle: "Vicoli in pietra, forme fortificate e storia viva",
      introDescription: "Diversi villaggi di Chios conservano un’atmosfera medievale con strade strette, case in pietra e piazze storiche.",
      listKicker: "Villaggi medievali",
      listTitle: "Villaggi dal forte carattere storico",
      listText: "Ideali per architettura, storia, fotografie e una passeggiata lenta nel villaggio.",
      planningTitle: "Come organizzare una rotta medievale",
      planningDescription: "Combina i villaggi del sud o tieni Volissos per una giornata separata nel nord-ovest.",
    },
    es: {
      seoTitle: "Pueblos medievales de Chios | Voulamandis House",
      seoDescription: "Explora pueblos medievales de Chios, como Mesta, Pyrgi, Vessa, Olympoi y Volissos.",
      kicker: "Rutas históricas",
      title: "Pueblos medievales de Chios",
      description: "Recorre Chios a través de pueblos fortaleza, callejones de piedra, castillos y arquitectura tradicional.",
      introKicker: "Planificar pueblos medievales",
      introTitle: "Callejones de piedra, trazados fortificados e historia viva",
      introDescription: "Varios pueblos de Chios conservan una atmósfera medieval con calles estrechas, casas de piedra y plazas históricas.",
      listKicker: "Pueblos medievales",
      listTitle: "Pueblos con fuerte carácter histórico",
      listText: "Ideales para arquitectura, historia, fotografías y un paseo tranquilo.",
      planningTitle: "Cómo organizar una ruta medieval",
      planningDescription: "Combina los pueblos del sur o deja Volissos para un día aparte en el noroeste.",
    },
    tr: {
      seoTitle: "Sakız Adası Orta Çağ Köyleri | Voulamandis House",
      seoDescription: "Mesta, Pyrgi, Vessa, Olympoi ve Volissos dahil Sakız Adası’nın Orta Çağ köylerini keşfedin.",
      kicker: "Tarihi rotalar",
      title: "Sakız Adası Orta Çağ köyleri",
      description: "Kale köyleri, taş sokaklar, kale manzaraları ve geleneksel mimariyle Sakız’ı keşfedin.",
      introKicker: "Orta Çağ köyleri planı",
      introTitle: "Taş sokaklar, savunma dokusu ve yaşayan tarih",
      introDescription: "Sakız’daki birçok köy dar sokaklar, taş evler ve tarihi meydanlarla Orta Çağ atmosferini korur.",
      listKicker: "Orta Çağ köyleri",
      listTitle: "Tarihi karakteri güçlü köyler",
      listText: "Mimari, tarih, fotoğraf ve sakin bir köy yürüyüşü isteyenler için uygundur.",
      planningTitle: "Orta Çağ köy rotası nasıl planlanır",
      planningDescription: "Güney köylerini tek rotada birleştirin veya Volissos’u kuzeybatı günü için ayırın.",
    },
  },
  seaside: {
    en: {
      seoTitle: "Seaside Villages of Chios | Voulamandis House",
      seoDescription: "Explore seaside villages in Chios, including Lagada and Volissos, for harbor views, taverns and relaxed coastal routes.",
      kicker: "Coastal village routes",
      title: "Seaside villages of Chios",
      description: "Plan village stops with harbor views, fish taverns, coastal scenery and slower local food experiences.",
      introKicker: "Seaside village planning",
      introTitle: "Village life close to the sea",
      introDescription: "The seaside villages of Chios are ideal for relaxed routes, local food, harbor walks and combining village character with coastal scenery.",
      listKicker: "Seaside villages",
      listTitle: "Village stops near the coast",
      listText: "Use these villages for slower days with food, views and easy combinations with beaches.",
      planningTitle: "How to plan a seaside village day",
      planningDescription: "Keep the route light and allow time for a meal or coffee by the water.",
    },
    el: {
      seoTitle: "Παραθαλάσσια χωριά Χίου | Voulamandis House",
      seoDescription: "Ανακαλύψτε παραθαλάσσια χωριά της Χίου, όπως Λαγκάδα και Βολισσός, για λιμανάκια, ταβέρνες και χαλαρές διαδρομές.",
      kicker: "Παραθαλάσσιες διαδρομές",
      title: "Παραθαλάσσια χωριά Χίου",
      description: "Οργανώστε στάσεις σε χωριά με θέα στη θάλασσα, ψαροταβέρνες, λιμανάκια και πιο χαλαρό τοπικό ρυθμό.",
      introKicker: "Οργάνωση παραθαλάσσιων χωριών",
      introTitle: "Ζωή χωριού κοντά στη θάλασσα",
      introDescription: "Τα παραθαλάσσια χωριά της Χίου είναι ιδανικά για πιο ήρεμες διαδρομές, φαγητό, βόλτα στο λιμάνι και συνδυασμό χωριού με θάλασσα.",
      listKicker: "Παραθαλάσσια χωριά",
      listTitle: "Στάσεις χωριών κοντά στην ακτή",
      listText: "Χρησιμοποιήστε αυτά τα χωριά για πιο αργές μέρες με φαγητό, θέα και εύκολο συνδυασμό με παραλίες.",
      planningTitle: "Πώς να οργανώσετε μια μέρα στα παραθαλάσσια χωριά",
      planningDescription: "Κρατήστε τη διαδρομή ελαφριά και αφήστε χρόνο για φαγητό ή καφέ δίπλα στο νερό.",
    },
    fr: {
      seoTitle: "Villages en bord de mer à Chios | Voulamandis House",
      seoDescription: "Découvrez les villages en bord de mer de Chios, comme Lagada et Volissos, avec ports, tavernes et routes côtières.",
      kicker: "Routes côtières",
      title: "Villages en bord de mer à Chios",
      description: "Planifiez des haltes avec vues sur le port, tavernes de poisson, paysages côtiers et rythme local plus lent.",
      introKicker: "Préparer les villages côtiers",
      introTitle: "La vie de village près de la mer",
      introDescription: "Les villages côtiers de Chios sont parfaits pour des routes détendues, des repas locaux et des promenades près du port.",
      listKicker: "Villages côtiers",
      listTitle: "Haltes villageoises près de la mer",
      listText: "Idéal pour des journées lentes avec repas, vues et combinaisons faciles avec les plages.",
      planningTitle: "Comment organiser une journée côtière",
      planningDescription: "Gardez l’itinéraire léger et laissez du temps pour un café ou un repas au bord de l’eau.",
    },
    de: {
      seoTitle: "Küstendörfer auf Chios | Voulamandis House",
      seoDescription: "Entdecken Sie Küstendörfer auf Chios wie Lagada und Volissos mit Hafenblick, Tavernen und entspannten Routen.",
      kicker: "Küstenrouten",
      title: "Küstendörfer auf Chios",
      description: "Planen Sie Dorfstopps mit Hafenblick, Fischtavernen, Küstenlandschaft und ruhigerem lokalen Rhythmus.",
      introKicker: "Küstendörfer planen",
      introTitle: "Dorfleben nahe am Meer",
      introDescription: "Die Küstendörfer auf Chios eignen sich für entspannte Routen, lokales Essen, Hafenwege und Kombinationen mit Stränden.",
      listKicker: "Küstendörfer",
      listTitle: "Dorfstopps nahe der Küste",
      listText: "Gut für ruhigere Tage mit Essen, Ausblicken und einfachen Strandkombinationen.",
      planningTitle: "So planen Sie einen Tag in Küstendörfern",
      planningDescription: "Halten Sie die Route leicht und lassen Sie Zeit für Essen oder Kaffee am Wasser.",
    },
    it: {
      seoTitle: "Villaggi sul mare a Chios | Voulamandis House",
      seoDescription: "Scopri i villaggi sul mare di Chios, come Lagada e Volissos, con porto, taverne e percorsi costieri.",
      kicker: "Itinerari costieri",
      title: "Villaggi sul mare a Chios",
      description: "Organizza soste con viste sul porto, taverne di pesce, paesaggi costieri e ritmo locale più lento.",
      introKicker: "Pianificare i villaggi sul mare",
      introTitle: "Vita di villaggio vicino al mare",
      introDescription: "I villaggi sul mare di Chios sono ideali per itinerari rilassati, cibo locale, passeggiate al porto e abbinamenti con le spiagge.",
      listKicker: "Villaggi sul mare",
      listTitle: "Soste vicino alla costa",
      listText: "Perfetti per giornate lente con cibo, viste e combinazioni facili con le spiagge.",
      planningTitle: "Come organizzare una giornata nei villaggi sul mare",
      planningDescription: "Mantieni l’itinerario leggero e lascia tempo per un pasto o un caffè sull’acqua.",
    },
    es: {
      seoTitle: "Pueblos costeros de Chios | Voulamandis House",
      seoDescription: "Descubre pueblos costeros de Chios, como Lagada y Volissos, con puerto, tabernas y rutas tranquilas.",
      kicker: "Rutas costeras",
      title: "Pueblos costeros de Chios",
      description: "Organiza paradas con vistas al puerto, tabernas de pescado, paisaje costero y ritmo local relajado.",
      introKicker: "Planificar pueblos costeros",
      introTitle: "Vida de pueblo cerca del mar",
      introDescription: "Los pueblos costeros de Chios son ideales para rutas relajadas, comida local, paseos por el puerto y combinaciones con playas.",
      listKicker: "Pueblos costeros",
      listTitle: "Paradas cerca de la costa",
      listText: "Perfectos para días tranquilos con comida, vistas y combinaciones fáciles con playas.",
      planningTitle: "Cómo organizar un día de pueblos costeros",
      planningDescription: "Mantén la ruta ligera y deja tiempo para comer o tomar café junto al agua.",
    },
    tr: {
      seoTitle: "Sakız Adası Sahil Köyleri | Voulamandis House",
      seoDescription: "Lagada ve Volissos gibi Sakız Adası sahil köylerini liman manzaraları, tavernalar ve sakin rotalarla keşfedin.",
      kicker: "Sahil köy rotaları",
      title: "Sakız Adası sahil köyleri",
      description: "Liman manzaraları, balık tavernaları, kıyı doğası ve daha sakin yerel yemek deneyimleriyle köy durakları planlayın.",
      introKicker: "Sahil köyleri planı",
      introTitle: "Denize yakın köy yaşamı",
      introDescription: "Sakız’ın sahil köyleri rahat rotalar, yerel yemek, liman yürüyüşleri ve plajlarla kolay birleşimler için idealdir.",
      listKicker: "Sahil köyleri",
      listTitle: "Kıyıya yakın köy durakları",
      listText: "Yemek, manzara ve plajlarla kolay kombinasyon isteyen sakin günler için uygundur.",
      planningTitle: "Sahil köylerinde bir gün nasıl planlanır",
      planningDescription: "Rotayı hafif tutun ve su kenarında yemek ya da kahve için zaman bırakın.",
    },
  },
};

export function getVillageCategoryPage(category: VillageCategoryKey, locale: LanguageCode): ChiosVillagesPageData {
  const base = basePages[locale];
  const copy = categoryCopy[category][locale];
  const ids = categoryVillageIds[category];
  const villages = ids
    .map((id) => base.villages.find((village) => village.id === id))
    .filter((village): village is ChiosVillagesPageData["villages"][number] => Boolean(village))
    .map((village, index) => ({
      ...village,
      size: index === 0 ? "large" : index === 1 ? "tall" : index === 2 ? "wide" : "normal",
    }));

  const heroImage = villages[0]?.image || base.hero.image;

  return {
    ...base,
    seo: {
      canonicalPath: villageCategoryPaths[category][locale],
      title: copy.seoTitle,
      description: copy.seoDescription,
      ogImage: heroImage,
    },
    hero: {
      ...base.hero,
      kicker: copy.kicker,
      title: copy.title,
      description: copy.description,
      image: heroImage,
      primaryCta: {
        label: base.hero.primaryCta.label,
        href: "#villages",
      },
    },
    intro: {
      ...base.intro,
      kicker: copy.introKicker,
      title: copy.introTitle,
      description: copy.introDescription,
    },
    villages,
    planning: {
      ...base.planning,
      title: copy.planningTitle,
      description: copy.planningDescription,
    },
  };
}
