import Image from "next/image";
import { HomeReviews } from "@/components/home/HomeReviews";
import { LazyPolishChiosHotelsLiveSearch } from "@/components/home/LazyPolishChiosHotelsLiveSearch";

const heroImage = "/images/activities/chios.hotels.voulamandis.house_.hero_.image_.webp";

function SectionTitle({ kicker, title, subtitle, icon }: { kicker: string; title: string; subtitle?: string; icon?: string }) {
  return (
    <header className="mx-auto mb-7 max-w-3xl text-center md:mb-10">
      <p className="mb-3 break-words text-xs font-black uppercase tracking-[0.20em] text-amber-700">{kicker}</p>
      <h2 className="text-balance break-words font-serif text-[2rem] font-bold leading-tight text-stone-900 md:text-5xl">{icon ? <span className="mr-2" aria-hidden="true">{icon}</span> : null}{title}</h2>
      {subtitle ? <p className="mt-3 text-sm leading-7 text-stone-600 md:mt-4 md:text-lg md:leading-8">{subtitle}</p> : null}
    </header>
  );
}

const rooms = [
  { title: "Ekonomiczny pokój dwuosobowy", href: "/pl/pokoje-na-chios/pokoj-dwuosobowy-economy/", image: "/images/rooms/received_1753964631359257.webp", badge: "2 gości", text: "Korzystna opcja dla pary lub dwóch osób, z prywatną łazienką, klimatyzacją, Wi-Fi i lodówką.", meta: ["Economy", "ok. 16 m²", "Kambos"] },
  { title: "Pokoje na parterze", href: "/pl/pokoje-na-chios/pokoje-standardowe/", image: "/images/rooms/double-triple-room.jpg", badge: "2–3 gości", text: "Wygodne pokoje z łatwym dostępem do dziedzińca i ogrodu, dobre dla osób, które wolą unikać schodów.", meta: ["Parter", "Bez schodów", "Ogród"] },
  { title: "Pokoje na piętrze", href: "/pl/pokoje-na-chios/pokoje-standardowe/", image: "/images/rooms/DSC07776-2-e1675109942622.webp", badge: "2–4 gości", text: "Jasne pokoje z dostępem do tarasu i widokiem na historyczny, cytrusowy krajobraz Kambos.", meta: ["Piętro", "Taras", "Wybrane aneksy"] },
  { title: "Apartamenty rodzinne", href: "/pl/apartamenty-na-chios/", image: "/images/rooms/chios-apartments-voulamandis.webp", badge: "Do 4 gości", text: "Więcej przestrzeni dla rodzin: osobna sypialnia, część dzienna i pełna kuchnia w apartamentach 40–45 m².", meta: ["Kuchnia", "Salon", "Rodzina"] },
];

const amenities = [
  ["📶", "Wi-Fi"], ["❄️", "Klimatyzacja"], ["🔥", "Ogrzewanie"], ["📺", "TV"], ["🧊", "Lodówka"], ["☕", "Kawa i herbata"], ["🧼", "Codzienne sprzątanie"], ["🌿", "Ogród"], ["🚗", "Parking"], ["🥐", "Śniadanie na życzenie"], ["🏡", "Kameralny pobyt"], ["📍", "Kambos Chios"],
];

export function PolishHomePageTailwind() {
  return (
    <>
      <main className="overflow-x-hidden bg-[#fffaf3] text-stone-900">
        <section className="relative flex min-h-[680px] items-end overflow-hidden bg-stone-950 text-white md:min-h-[82vh]" aria-label="Noclegi na Chios w Kambos">
          <Image src={heroImage} alt="Voulamandis House w Kambos na Chios — pokoje i apartamenty" fill priority fetchPriority="high" sizes="100vw" quality={62} className="object-cover object-center" />
          <div className="absolute inset-0 bg-gradient-to-t from-black via-black/35 to-black/10 md:bg-gradient-to-l md:from-black/75 md:via-black/25 md:to-transparent" />
          <div className="relative z-10 mx-auto flex w-full max-w-7xl justify-end px-4 pb-10 pt-28 md:px-8 md:pb-14 md:pt-32">
            <div className="w-full max-w-xl rounded-[1.6rem] border border-white/15 bg-stone-950/55 p-5 shadow-2xl shadow-black/30 backdrop-blur-md md:rounded-[2rem] md:p-8">
              <div className="mb-5 inline-flex items-center gap-3 rounded-full bg-white px-4 py-2 text-sm font-bold text-stone-800 shadow-lg"><span>4.8 / 5</span><span className="text-amber-400" aria-hidden="true">★★★★★</span><span className="text-stone-500">143 opinie</span></div>
              <p className="mb-3 break-words text-xs font-black uppercase tracking-[0.22em] text-white/85">KAMBOS CHIOS • VOULAMANDIS HOUSE</p>
              <h1 className="text-balance text-4xl font-black leading-none tracking-[-0.04em] md:text-6xl">Noclegi na Chios — pokoje i apartamenty w Kambos</h1>
              <p className="mt-5 text-base leading-8 text-white/90 md:text-lg">Szukasz <strong>noclegu na Chios</strong>, pokoju dla dwojga albo rodzinnego apartamentu? Voulamandis House oferuje spokojny pobyt w historycznym Kambos, blisko lotniska, miasta i plaż.</p>
              <div className="mt-7 grid grid-cols-2 gap-3">
                <a href="/pl/pokoje-na-chios/" className="inline-flex min-h-14 items-center justify-center rounded-2xl bg-orange-700 px-4 text-center text-xs font-black uppercase tracking-[0.08em] text-white shadow-lg shadow-orange-900/25 transition hover:bg-orange-800 md:rounded-full">✨ Znajdź pokój</a>
                <a href="/pl/rezerwacja/" className="inline-flex min-h-14 items-center justify-center rounded-2xl border border-white/35 bg-white/10 px-4 text-center text-xs font-black uppercase tracking-[0.08em] text-white backdrop-blur transition hover:bg-white/20 md:rounded-full">🔥 Sprawdź ceny</a>
              </div>
            </div>
          </div>
        </section>

        <a href="#vh-lastminute-title" className="relative z-20 mx-auto -mt-5 flex w-[min(1120px,92vw)] items-center justify-between gap-4 rounded-3xl bg-white px-5 py-4 text-stone-800 shadow-xl shadow-stone-900/10 ring-1 ring-amber-900/10 md:px-7"><span className="text-2xl" aria-hidden="true">🔥</span><span className="flex-1 text-sm font-semibold md:text-base">Planujesz Chios? <strong className="text-amber-800">Sprawdź aktualną dostępność pokoi i apartamentów.</strong></span><span className="text-amber-700" aria-hidden="true">→</span></a>

        <section className="px-4 py-8 md:px-8 md:py-14"><div className="mx-auto grid max-w-7xl gap-4 lg:grid-cols-[1fr_1.05fr]">
          <article className="rounded-[1.5rem] bg-white p-5 shadow-lg shadow-stone-900/5 ring-1 ring-amber-900/10 md:rounded-[2rem] md:p-8"><p className="mb-3 text-xs font-black uppercase tracking-[0.20em] text-amber-700">Kameralna gościnność w Kambos</p><h2 className="font-serif text-[2rem] font-bold leading-tight text-stone-900 md:text-5xl">🏡 Pobyt na Chios w Voulamandis House</h2><p className="mt-4 text-sm leading-7 text-stone-600 md:text-base md:leading-8">Jeśli porównujesz <strong>hotele na Chios</strong>, pokoje lub apartamenty, warto zwrócić uwagę nie tylko na nazwę kategorii, ale też na lokalizację i styl pobytu. Voulamandis House nie jest hotelem — to rodzinny obiekt z pokojami i apartamentami w spokojnym Kambos.</p><div className="mt-5 grid grid-cols-2 gap-2 sm:flex sm:flex-wrap">{["🍊 Kambos Chios", "🛏️ Pokoje i apartamenty", "🌿 Spokojne otoczenie", "💎 Rezerwacja bezpośrednia"].map((pill) => <span key={pill} className="inline-flex min-h-10 items-center justify-center rounded-full bg-amber-50 px-3 py-2 text-center text-[12px] font-bold leading-tight text-amber-800 ring-1 ring-amber-900/10 sm:min-h-0 sm:px-4 sm:text-sm">{pill}</span>)}</div></article>
          <article className="rounded-[1.5rem] bg-white p-5 shadow-lg shadow-stone-900/5 ring-1 ring-amber-900/10 md:rounded-[2rem] md:p-8"><p className="mb-3 text-xs font-black uppercase tracking-[0.20em] text-amber-700">Co wyróżnia pobyt</p><h3 className="font-serif text-[2rem] font-bold leading-tight text-stone-900 md:text-5xl">6 powodów, by wybrać Kambos</h3><div className="mt-5 grid grid-cols-2 gap-2 md:grid-cols-3 md:gap-3">{[["🥐 Śniadanie", "Dostępne na życzenie."], ["🌿 Ogród i cisza", "Spokojna atmosfera Kambos."], ["🛏️ Różne typy pokoi", "Od economy po apartamenty."], ["📍 Lokalizacja", "Blisko miasta i lotniska."], ["🛎️ Rezerwacja direct", "Bezpośredni kontakt z obiektem."], ["🍊 Lokalny charakter", "Historyczne otoczenie i cytrusy."]].map(([title, text], index) => <div key={title} className={index === 0 ? "col-span-2 rounded-2xl bg-[#2f241d] p-4 text-white md:col-span-1" : "rounded-2xl bg-amber-50 p-3 ring-1 ring-amber-900/10"}><strong className="block text-sm leading-5">{title}</strong><span className={index === 0 ? "mt-2 block text-xs leading-5 text-white/78" : "mt-2 block text-xs leading-5 text-stone-600"}>{text}</span></div>)}</div></article>
        </div></section>

        <section className="px-4 py-9 md:px-8 md:py-16"><div className="mx-auto max-w-7xl"><div className="grid gap-4 lg:grid-cols-[0.95fr_1.05fr] lg:items-end"><article className="rounded-[1.5rem] bg-[#2f241d] p-5 text-white shadow-lg shadow-stone-900/10 md:rounded-[2rem] md:p-9"><p className="mb-3 text-xs font-black uppercase tracking-[0.20em] text-amber-200">Pokoje i noclegi na Chios</p><h2 className="font-serif text-[2rem] font-bold leading-tight md:text-5xl">🛏️ Wybierz odpowiedni pokój lub apartament</h2><p className="mt-4 text-sm leading-7 text-white/80 md:text-lg md:leading-8">Porównaj dostęp, piętro, przestrzeń i wyposażenie. Każda karta prowadzi do szczegółów właściwej kategorii.</p><div className="mt-5 flex flex-wrap gap-3"><a href="/pl/pokoje-na-chios/" className="inline-flex min-h-12 items-center justify-center rounded-full bg-amber-700 px-6 text-sm font-black uppercase tracking-[0.08em] text-white shadow-lg">Wszystkie pokoje</a><a href="/pl/noclegi-chios/" className="inline-flex min-h-12 items-center justify-center rounded-full border border-white/25 bg-white/10 px-6 text-sm font-black uppercase tracking-[0.08em] text-white">Noclegi na Chios</a></div></article><article className="hidden rounded-[2rem] bg-white p-7 shadow-lg shadow-stone-900/5 ring-1 ring-amber-900/10 lg:block"><p className="text-xs font-black uppercase tracking-[0.20em] text-amber-700">Od par po rodziny</p><h3 className="mt-3 font-serif text-3xl font-bold text-stone-900">Od ekonomicznego pokoju po rodzinny apartament</h3><p className="mt-4 leading-8 text-stone-600">Wybierz kategorię według liczby gości, piętra i tego, czy potrzebujesz kuchni lub większej przestrzeni.</p></article></div>
          <div className="mt-5 flex snap-x snap-mandatory gap-4 overflow-x-auto pb-5 pr-10 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden md:grid md:grid-cols-2 md:overflow-visible md:pr-0 xl:grid-cols-4">{rooms.map((room) => <a key={room.title} href={room.href} className="group w-[84vw] max-w-[380px] flex-none snap-start overflow-hidden rounded-[1.5rem] bg-white shadow-lg shadow-stone-900/5 ring-1 ring-amber-900/10 transition hover:shadow-xl md:w-auto md:max-w-none md:rounded-[2rem]"><div className="relative aspect-[4/3] overflow-hidden"><Image src={room.image} alt={room.title} fill sizes="(max-width: 768px) 84vw, (max-width: 1280px) 50vw, 25vw" className="object-cover transition duration-500 group-hover:scale-105" loading="lazy" /><div className="absolute left-3 top-3 rounded-full bg-emerald-700 px-3 py-1.5 text-xs font-black text-white">{room.badge}</div><div className="absolute right-3 top-3 rounded-full bg-white/95 px-3 py-1.5 text-xs font-black text-emerald-700">Direct</div></div><div className="p-5"><h3 className="font-serif text-2xl font-bold leading-tight text-amber-800">{room.title}</h3><p className="mt-3 text-sm leading-7 text-stone-600">{room.text}</p><div className="mt-4 flex flex-wrap gap-2">{room.meta.map((item) => <span key={item} className="rounded-full bg-amber-50 px-3 py-1.5 text-[11px] font-bold text-amber-800">{item}</span>)}</div><span className="mt-5 inline-flex rounded-full border border-amber-800/20 px-4 py-2 text-xs font-black uppercase text-amber-800">Zobacz szczegóły</span></div></a>)}</div>
        </div></section>

        <LazyPolishChiosHotelsLiveSearch />

        <section className="px-4 py-9 md:px-8 md:py-16"><article className="relative mx-auto max-w-7xl overflow-hidden rounded-[1.5rem] border border-amber-900/10 bg-[#fff8ea] shadow-lg shadow-amber-900/10 md:rounded-[2rem]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(251,191,36,0.18),transparent_36%)]" /><div className="relative grid gap-0 lg:grid-cols-[1fr_0.9fr]"><div className="p-5 md:p-9"><span className="inline-flex rounded-full bg-white/85 px-4 py-2 text-xs font-black uppercase tracking-[0.16em] text-orange-800 shadow-sm ring-1 ring-amber-900/10">REZERWACJA BEZPOŚREDNIA</span><h3 className="mt-5 max-w-xl font-serif text-[2rem] font-bold leading-tight text-stone-950 md:text-5xl">Sprawdź aktualne ceny bezpośrednio</h3><p className="mt-4 max-w-2xl text-sm leading-7 text-stone-700 md:text-lg md:leading-8">Zobacz dostępność, wybierz kategorię i przejdź do bezpiecznej strony rezerwacji Voulamandis House.</p><ul className="mt-5 grid gap-2 sm:grid-cols-3">{["Aktualna dostępność", "Bezpośredni kontakt", "Kod WELCOME10"].map((benefit, index) => <li key={benefit} className="rounded-2xl bg-white/90 p-3 text-sm font-black leading-6 text-stone-800 shadow-sm ring-1 ring-amber-900/10"><span className="mr-2 text-amber-700">0{index + 1}</span>{benefit}</li>)}</ul></div><div className="flex items-center p-5 pt-0 lg:p-8"><a href="/pl/rezerwacja/" className="inline-flex min-h-14 w-full items-center justify-center rounded-[1.5rem] bg-gradient-to-br from-[#3a271b] via-[#7a3f11] to-[#d97706] px-6 text-center text-sm font-black uppercase tracking-[0.08em] text-white shadow-xl shadow-orange-900/20">Sprawdź rezerwację i ceny →</a></div></div></article></section>

        <section className="px-4 py-9 md:px-8 md:py-16"><article className="mx-auto grid max-w-7xl overflow-hidden rounded-[1.5rem] bg-white shadow-lg shadow-stone-900/5 ring-1 ring-amber-900/10 md:grid-cols-[0.95fr_1.05fr] md:rounded-[2rem]"><div className="relative min-h-[220px] md:min-h-[430px]"><Image src="/images/kampos/kampos-chios-mansion-garden.webp" alt="Historyczny Kambos na Chios" fill sizes="(max-width: 768px) 100vw, 46vw" className="object-cover" loading="lazy" /><div className="absolute inset-0 bg-gradient-to-t from-black/35 to-transparent md:hidden" /></div><div className="p-5 md:p-9 lg:p-11"><p className="mb-3 text-xs font-black uppercase tracking-[0.20em] text-amber-700">KAMBOS CHIOS</p><h2 className="font-serif text-[2rem] font-bold leading-tight text-stone-900 md:text-5xl">Historyczna dzielnica ogrodów cytrusowych</h2><div className="mt-5 space-y-4 text-sm leading-7 text-stone-600 md:text-base md:leading-8"><p>Kambos to kamienne mury, dawne rezydencje, ogrody cytrusowe i spokojne uliczki. Pobyt tutaj daje inne doświadczenie niż nocleg w najbardziej ruchliwej części miasta.</p><p>Voulamandis House leży około 3 km od lotniska i 6 km od portu, dlatego Kambos łączy atmosferę z praktycznym dostępem do miasta, plaż i południowych wiosek.</p></div><a href="/pl/kambos-chios/" className="mt-6 inline-flex rounded-full border border-amber-800/20 bg-amber-50 px-5 py-3 text-sm font-black text-amber-800">Poznaj Kambos →</a></div></article></section>

        <section className="px-4 py-9 md:px-8 md:py-16"><div className="mx-auto max-w-7xl"><SectionTitle kicker="Lokalizacja i kontakt" icon="🗺️" title="Wszystko, czego potrzebujesz przed pobytem" subtitle="Kambos, krótkie odległości i bezpośredni kontakt z Voulamandis House." /><div className="grid gap-5 lg:grid-cols-[1.05fr_0.95fr]"><article className="overflow-hidden rounded-[1.5rem] bg-white shadow-lg shadow-stone-900/5 ring-1 ring-amber-900/10 md:rounded-[2rem]"><div className="relative min-h-[220px] md:min-h-[330px]"><Image src="/images/site/voulamandis.house_.google.maps_.webp" alt="Lokalizacja Voulamandis House w Kambos" fill sizes="(max-width: 1024px) 100vw, 52vw" className="object-cover" loading="lazy" /><a href="https://www.google.com/maps/search/?api=1&query=Voulamandis+House+Chios" className="absolute bottom-4 left-4 rounded-full bg-white px-5 py-3 text-sm font-black uppercase text-amber-800 shadow-lg">Mapa</a></div><div className="grid grid-cols-3 gap-2 p-3 sm:p-5">{[["✈️ Lotnisko", "3 km"], ["⛴️ Port", "6 km"], ["🏖️ Plaża", "1,5 km"]].map(([label, value]) => <div key={label} className="rounded-2xl bg-amber-50 p-3 text-center"><span className="block text-xs leading-4 text-stone-600 sm:text-sm">{label}</span><strong className="mt-1 block text-base text-amber-800 sm:text-xl">{value}</strong></div>)}</div></article><article className="rounded-[1.5rem] bg-white p-5 shadow-lg shadow-stone-900/5 ring-1 ring-amber-900/10 md:rounded-[2rem] md:p-8"><p className="text-xs font-black uppercase tracking-[0.20em] text-amber-700">Bezpośredni kontakt</p><h3 className="mt-3 font-serif text-3xl font-bold text-amber-800">Voulamandis House</h3><address className="mt-4 not-italic text-sm leading-7 text-stone-600 md:text-base md:leading-8">Dimarchou Kalvokoressi 117<br />Kambos, Chios 82100<br />Tel: <a href="tel:+302271031733" className="font-bold text-amber-800">+30 22710 31733</a><br />Email: <a href="mailto:info@chioshotel.gr" className="font-bold text-amber-800">info@chioshotel.gr</a></address><p className="mt-4 text-sm leading-7 text-stone-600 md:text-base md:leading-8">Napisz z datami i liczbą gości, jeśli potrzebujesz pomocy w wyborze piętra, układu łóżek lub apartamentu.</p><a href="/pl/rezerwacja/" className="mt-5 inline-flex min-h-12 items-center justify-center rounded-full bg-amber-700 px-6 text-sm font-black uppercase tracking-[0.08em] text-white">Sprawdź dostępność</a></article></div></div></section>

        <section className="px-4 py-10 md:px-8 md:py-16"><div className="mx-auto max-w-5xl rounded-[1.5rem] bg-white p-6 text-center shadow-lg shadow-stone-900/5 ring-1 ring-amber-900/10 md:rounded-[2rem] md:p-10"><SectionTitle kicker="Opinie gości" icon="💬" title="Co mówią nasi goście" /><HomeReviews loaderUrl="https://cdn.trustindex.io/loader.js?eee5e55655b69937bc662de8425" /></div></section>

        <section className="px-4 py-8 md:px-8 md:py-14"><div className="mx-auto max-w-7xl"><SectionTitle kicker="Udogodnienia" icon="🛋️" title="Wygodny pobyt na Chios" /><div className="grid grid-cols-3 gap-2 sm:grid-cols-3 lg:grid-cols-4">{amenities.map(([icon, label]) => <div key={label} className="flex min-h-[108px] flex-col items-center justify-center gap-2 rounded-2xl bg-white p-3 text-center shadow-sm ring-1 ring-amber-900/10"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-amber-50 text-lg">{icon}</span><span className="text-[12px] font-black leading-4 text-stone-700 sm:text-sm">{label}</span></div>)}</div></div></section>

        <section className="px-4 py-8 md:px-8 md:py-14"><div className="mx-auto max-w-7xl"><SectionTitle kicker="Zaplanuj pobyt" icon="🧭" title="Najważniejsze strony po polsku" subtitle="Porównaj noclegi, hotele, Kambos i opcje rezerwacji bezpośredniej." /><div className="flex snap-x snap-mandatory gap-4 overflow-x-auto pb-5 pr-10 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden md:grid md:grid-cols-2 md:overflow-visible md:pr-0 xl:grid-cols-4">{[["Noclegi na Chios", "Porównaj pokoje i apartamenty w Kambos.", "/pl/noclegi-chios/"], ["Hotele Chios", "Zobacz przewodnik po rejonach i typach noclegów.", "/pl/hotele-chios/"], ["Kambos Chios", "Poznaj historyczne otoczenie Voulamandis House.", "/pl/kambos-chios/"], ["Rezerwacja", "Sprawdź bezpośrednią dostępność i ceny.", "/pl/rezerwacja/"]].map(([title, text, href]) => <a key={href} href={href} className="w-[84vw] max-w-[380px] flex-none snap-start rounded-[1.5rem] bg-white p-5 shadow-lg shadow-stone-900/5 ring-1 ring-amber-900/10 transition hover:shadow-xl md:w-auto md:max-w-none md:rounded-[2rem]"><h3 className="font-serif text-2xl font-bold text-stone-900">{title}</h3><p className="mt-3 text-sm leading-7 text-stone-600">{text}</p><span className="mt-5 inline-flex rounded-full border border-amber-800/20 px-4 py-2 text-xs font-black uppercase text-amber-800">Zobacz więcej →</span></a>)}</div></div></section>

        <section className="px-4 py-8 md:px-8 md:py-14"><div className="mx-auto max-w-5xl"><SectionTitle kicker="Najczęstsze pytania" icon="❓" title="Co warto wiedzieć przed rezerwacją" /><div className="grid gap-3">{[["Czy Voulamandis House jest hotelem?", "Nie. To rodzinny obiekt oferujący pokoje i apartamenty w Kambos. Osoby szukające hoteli na Chios mogą porównać go jako kameralną alternatywę."], ["Czy są pokoje dla par i apartamenty dla rodzin?", "Tak. Dostępne są pokoje economy, pokoje na parterze i piętrze oraz rodzinne apartamenty z kuchnią."], ["Jak daleko jest lotnisko i port?", "Lotnisko znajduje się około 3 km, a port i centrum miasta Chios około 6 km od Voulamandis House."], ["Czy śniadanie jest dostępne?", "Tak, śniadanie jest dostępne na życzenie i może być serwowane w ogrodzie."], ["Jak sprawdzić dostępność?", "Skorzystaj z wyszukiwarki na stronie lub przejdź do polskiej strony rezerwacji bezpośredniej."]].map(([question, answer]) => <details key={question} className="group rounded-3xl bg-white p-5 shadow-sm ring-1 ring-amber-900/10"><summary className="cursor-pointer list-none font-bold text-stone-900">{question}</summary><p className="mt-4 leading-8 text-stone-600">{answer}</p></details>)}</div></div></section>

        <section className="px-4 pb-16 pt-4 md:px-8 md:pb-20"><div className="relative mx-auto max-w-7xl overflow-hidden rounded-[1.8rem] bg-stone-950 text-white shadow-2xl shadow-stone-900/20 md:rounded-[2.5rem]"><Image src="/images/site/Screenshot_2026-04-25-14-11-19-166_com.instagram.android-edit-1.webp" alt="" fill sizes="(max-width: 768px) 100vw, 1280px" className="object-cover object-center" loading="lazy" aria-hidden="true" /><div className="absolute inset-0 bg-gradient-to-r from-black/78 via-black/48 to-black/10" /><div className="relative z-10 max-w-3xl p-8 md:p-14"><p className="mb-3 text-xs font-black uppercase tracking-[0.22em] text-amber-200">ZAREZERWUJ POBYT</p><h2 className="font-serif text-4xl font-bold leading-tight md:text-6xl">✈️ Twoja podróż na Chios zaczyna się tutaj</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-white/85">Spokojny Kambos, kameralna gościnność i wygodna baza do odkrywania wyspy.</p><div className="mt-8 flex flex-wrap gap-3"><a href="/pl/rezerwacja/" className="inline-flex min-h-12 items-center justify-center rounded-full bg-amber-700 px-6 text-sm font-black uppercase tracking-[0.08em] text-white">Rezerwuj bezpośrednio</a><a href="/pl/pokoje-na-chios/" className="inline-flex min-h-12 items-center justify-center rounded-full border border-white/25 bg-white/10 px-6 text-sm font-black uppercase tracking-[0.08em] text-white">Zobacz pokoje</a></div></div></div></section>
      </main>

      <div className="fixed inset-x-0 bottom-0 z-50 border-t border-amber-900/10 bg-white/95 p-3 shadow-2xl backdrop-blur md:hidden"><div className="grid grid-cols-2 gap-3"><a href="tel:+302271031733" className="inline-flex min-h-12 items-center justify-center rounded-full border border-amber-800/20 bg-white px-6 text-sm font-black uppercase tracking-[0.08em] text-amber-800">📞 Zadzwoń</a><a href="https://wa.me/306944474226" className="inline-flex min-h-12 items-center justify-center rounded-full bg-green-600 px-6 text-sm font-black uppercase tracking-[0.08em] text-white shadow-lg shadow-green-900/20">💬 WhatsApp</a></div></div>
    </>
  );
}
