"use client";

import Image from "next/image";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";

type Language = "el" | "en" | "de" | "fr" | "it" | "es" | "tr";
type Step = "checkin" | "checkout" | "rooms" | "guests" | "preferences" | "searching" | "selecting" | "breakfast" | "complete" | "unavailable";
type Filter = "economy" | "noStairs" | "ground" | "first" | "kitchen" | "garden" | "balcony" | "family";
type Feedback = "idle" | "happy" | "different";
type Reaction = "👍" | "❤️";
type MessageKind = "date" | "room" | "guest" | "normal";
type Message = { id: string; role: "assistant" | "user"; content: string; kind?: MessageKind; reaction?: Reaction };
type Offer = { roomId: string; unitId: string; roomNumber?: number; name: string; category: string; floor: string; maxGuests: number; features: string[]; image: string; gallery?: string[]; nights: number; originalTotal: number; directTotal: number; saving: number; splitStay?: boolean };
type Choice = { group: number; guests: number; offer: Offer };
type InterpreterAction = { type: string; roomCount?: number; guests?: number; checkin?: string; checkout?: string; query?: string; missingFields?: string[] };
type InterpreterCommand = { language: Language; replyMode: "answer" | "execute" | "clarify"; actions: InterpreterAction[] };

const LANGUAGES: Array<[Language, string]> = [["el","Ελληνικά"],["en","English"],["de","Deutsch"],["fr","Français"],["it","Italiano"],["es","Español"],["tr","Türkçe"]];
const WHATSAPP_NUMBER = "306944474226";
const BREAKFAST_IMAGE = "/images/welcome/voulamandis-breakfast.jpg";
const FILTER_KEYS: Filter[] = ["economy","noStairs","ground","first","kitchen","garden","balcony","family"];
const REACTION_DELAY_MS = 950;
const REPLY_DELAY_MS = 550;
const wait = (ms:number) => new Promise(resolve => window.setTimeout(resolve, ms));

const COPY: Record<Language, any> = {
  el: { welcome:"Καλώς ήρθατε στο Voulamandis House 👋 Είμαι εδώ για να σας βοηθήσω να βρείτε το καλύτερο διαθέσιμο δωμάτιο για τη διαμονή σας στη Χίο. Πότε θα θέλατε να κάνετε check-in;", checkout:"Τέλεια! 😊 Ποια ημερομηνία θα θέλατε για check-out;", rooms:"Ωραία! 😊 Πόσα δωμάτια χρειάζεστε;", guests:(n:number)=>`Πόσα άτομα θα μείνουν στο δωμάτιο ${n};`, preferences:"Υπάρχει κάτι σημαντικό για τη διαμονή σας; Επιλέξτε όσες προτιμήσεις θέλετε.", searching:"Τέλεια! 😊 Σας ευχαριστούμε πολύ. Ψάχνω αμέσως τις καλύτερες διαθέσιμες επιλογές για εσάς 🔎✨", choose:(g:number,n:number)=>`Βρήκα αυτές τις επιλογές για την ομάδα ${g} · ${n} ${n===1?"άτομο":"άτομα"}.`, breakfast:"Θα θέλατε να προσθέσετε σπιτικό πρωινό με 12€ ανά άτομο, ανά ημέρα; ☕🥐", summary:"Όλα είναι έτοιμα. Αυτή είναι η αίτηση διαμονής σας.", online:"Διαθέσιμοι τώρα", details:"Λεπτομέρειες", select:"Επιλογή", selected:"Η επιλογή σας", saving:"Εξοικονομείτε", total:"Σύνολο", yesBreakfast:"Ναι, προσθήκη", noBreakfast:"Όχι, ευχαριστώ", noPreference:"Χωρίς προτίμηση", showRooms:"Προβολή δωματίων", newSearch:"Νέα αναζήτηση", back:"Επιστροφή στο site", placeholder:"Γράψτε ημερομηνία ή απάντηση…", chooseAbove:"Επιλέξτε μία επιλογή", invalidDate:"Πείτε μου μία συγκεκριμένη ημερομηνία για να συνεχίσουμε 😊", invalidCheckout:"Το check-out πρέπει να είναι μετά το check-in. Ποια ακριβώς ημερομηνία θέλετε για check-out;", unavailable:"Δεν βρήκα διαθέσιμη επιλογή. Μπορούμε να το ελέγξουμε μαζί μέσω WhatsApp.", contactTitle:"Στείλτε την αίτηση στην ομάδα μας", contactHelp:"Γράψτε το όνομά σας και ένα τηλέφωνο ή email.", name:"Όνομα", phone:"Τηλέφωνο", email:"Email", send:"Αποστολή αιτήματος", sent:"✓ Το αίτημά σας στάλθηκε. Θα επικοινωνήσουμε μαζί σας το συντομότερο δυνατό. 😊", sendError:"Δεν ήταν δυνατή η αποστολή. Δοκιμάστε μέσω WhatsApp.", whatsapp:"WhatsApp", breakfastLabel:"Πρωινό", roomLabel:(n:number)=>`${n} ${n===1?"δωμάτιο":"δωμάτια"}`, guestLabel:(n:number)=>`${n} ${n===1?"άτομο":"άτομα"}`, nightLabel:(n:number)=>`${n} ${n===1?"βραδιά":"βραδιές"}`, feedbackQ:"Σας αρέσουν οι προτάσεις μας; 😊", feedbackYes:"👍 Ναι, μου αρέσουν", feedbackDifferent:"🤔 Θα ήθελα κάτι διαφορετικό", feedbackYesReply:"Τέλεια! 😊 Χαιρόμαστε πολύ. Επιλέξτε το δωμάτιο που προτιμάτε ♥️", changePrompt:"Φυσικά 😊 Πείτε μου τι θα θέλατε να αλλάξουμε στις προτάσεις μας.", roomType:"🛏️ Άλλο είδος δωματίου", floor:"📍 Διαφορετικός όροφος / χωρίς σκάλες", group:"👨‍👩‍👧 Κάτι πιο κατάλληλο για την παρέα σας", info:"ℹ️ Θέλω περισσότερες πληροφορίες", other:"💬 Κάτι άλλο", filters:{economy:"Οικονομικό",noStairs:"Χωρίς σκάλες",ground:"Ισόγειο",first:"Πρώτος όροφος",kitchen:"Κουζίνα",garden:"Κήπος",balcony:"Μπαλκόνι",family:"Οικογενειακό"} },
  en: { welcome:"Welcome to Voulamandis House 👋 I’m here to help you find the best available room for your stay in Chios. When would you like to check in?", checkout:"Perfect! 😊 What date would you like to check out?", rooms:"Great! 😊 How many rooms do you need?", guests:(n:number)=>`How many guests will stay in room ${n}?`, preferences:"Anything important for your stay? Choose as many preferences as you like.", searching:"Perfect! 😊 Thank you very much. I’ll immediately look for the best available options for you 🔎✨", choose:(g:number,n:number)=>`I found these options for group ${g} · ${n} ${n===1?"guest":"guests"}.`, breakfast:"Would you like to add homemade breakfast for €12 per guest, per day? ☕🥐", summary:"Everything is ready. Here is your stay request.", online:"Online now", details:"Details", select:"Select", selected:"Your selection", saving:"You save", total:"Total", yesBreakfast:"Yes, add breakfast", noBreakfast:"No, thank you", noPreference:"No preference", showRooms:"Show rooms", newSearch:"New search", back:"Back to site", placeholder:"Type a date or answer…", chooseAbove:"Choose one option", invalidDate:"Please give me one specific date so we can continue 😊", invalidCheckout:"Check-out must be after check-in. What exact check-out date would you like?", unavailable:"I couldn’t find an available option. We can check it together on WhatsApp.", contactTitle:"Send this request to our team", contactHelp:"Enter your name and either a phone number or email.", name:"Name", phone:"Phone", email:"Email", send:"Send request", sent:"✓ Your request was sent. We’ll contact you as soon as possible. 😊", sendError:"The request could not be sent. Try WhatsApp.", whatsapp:"WhatsApp", breakfastLabel:"Breakfast", roomLabel:(n:number)=>`${n} ${n===1?"room":"rooms"}`, guestLabel:(n:number)=>`${n} ${n===1?"guest":"guests"}`, nightLabel:(n:number)=>`${n} ${n===1?"night":"nights"}`, feedbackQ:"Are you happy with our suggestions? 😊", feedbackYes:"👍 Yes, I like them", feedbackDifferent:"🤔 I’d like something different", feedbackYesReply:"Wonderful! 😊 We’re glad. Choose the room you prefer ♥️", changePrompt:"Of course 😊 Tell me what you would like us to change.", roomType:"🛏️ A different room type", floor:"📍 Different floor / no stairs", group:"👨‍👩‍👧 Something better for our group", info:"ℹ️ I’d like more information", other:"💬 Something else", filters:{economy:"Economy",noStairs:"No stairs",ground:"Ground floor",first:"First floor",kitchen:"Kitchen",garden:"Garden",balcony:"Balcony",family:"Family"} },
  de: {} as any, fr: {} as any, it: {} as any, es: {} as any, tr: {} as any,
};
for (const lang of ["de","fr","it","es","tr"] as Language[]) COPY[lang] = { ...COPY.en, welcome: ({de:"Willkommen im Voulamandis House 👋 Ich helfe Ihnen, das beste verfügbare Zimmer für Ihren Aufenthalt auf Chios zu finden. Wann möchten Sie einchecken?",fr:"Bienvenue à Voulamandis House 👋 Je suis là pour vous aider à trouver la meilleure chambre disponible pour votre séjour à Chios. Quand souhaitez-vous effectuer votre check-in ?",it:"Benvenuti a Voulamandis House 👋 Sono qui per aiutarvi a trovare la migliore camera disponibile per il vostro soggiorno a Chios. Quando desiderate effettuare il check-in?",es:"Bienvenidos a Voulamandis House 👋 Estoy aquí para ayudarles a encontrar la mejor habitación disponible para su estancia en Quíos. ¿Cuándo les gustaría hacer el check-in?",tr:"Voulamandis House’a hoş geldiniz 👋 Sakız Adası’ndaki konaklamanız için en uygun müsait odayı bulmanıza yardımcı olmak için buradayım. Ne zaman giriş yapmak istersiniz?"} as any)[lang] };

function detectLanguage(): Language { if (typeof window === "undefined") return "en"; const supported=LANGUAGES.map(([v])=>v); const q=new URLSearchParams(window.location.search).get("lang")?.toLowerCase().split("-")[0]; const p=window.location.pathname.split("/").filter(Boolean)[0]?.toLowerCase(); const d=document.documentElement.lang?.toLowerCase().split("-")[0]; return ([q,p,d].find(v=>supported.includes(v as Language)) as Language)||"en"; }
function id(){return `${Date.now()}-${Math.random().toString(36).slice(2)}`;}
function nightsBetween(a:string,b:string){return Math.round((new Date(`${b}T12:00:00Z`).getTime()-new Date(`${a}T12:00:00Z`).getTime())/86400000);}
function money(v:number,l:Language){const locale=({el:"el-GR",en:"en-GB",de:"de-DE",fr:"fr-FR",it:"it-IT",es:"es-ES",tr:"tr-TR"} as any)[l];return new Intl.NumberFormat(locale,{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(v);}
function offerRoomNumber(o:Offer){const n=Number(o.roomNumber);if(Number.isInteger(n)&&n>0)return n;return Number(o.name.match(/(\d{1,2})/)?.[1]||99);}
function roomRank(o:Offer){const order=[2,6,5,7,1,3,4,8,9,10];const i=order.indexOf(offerRoomNumber(o));return i<0?99:i;}
function matches(o:Offer,f:Filter){const n=offerRoomNumber(o);const text=`${o.name} ${o.category} ${o.floor} ${(o.features||[]).join(" ")}`.toLowerCase(); if(f==="economy")return [2,6].includes(n)||/econom|οικονομ/.test(text); if(f==="noStairs"||f==="ground")return [5,6,7].includes(n)||/ground|ισόγ|no stairs|χωρίς σκάλ/.test(text); if(f==="first")return [1,2,3,4].includes(n)||/first|πρώτ/.test(text); if(f==="kitchen")return n>=8&&n<=10||/kitchen|κουζ/.test(text); if(f==="family")return n>=8&&n<=10||/family|οικογεν/.test(text); if(f==="balcony")return [1,4].includes(n)||/balcon|μπαλκόν/.test(text); return /garden|κήπ|αυλ/.test(text);}

export function AiRoomFinderFlow(){
  const [language,setLanguage]=useState<Language>("en"); const copy=COPY[language];
  const [step,setStep]=useState<Step>("checkin"); const [messages,setMessages]=useState<Message[]>([]); const [input,setInput]=useState("");
  const [checkin,setCheckin]=useState(""); const [checkout,setCheckout]=useState(""); const [roomCount,setRoomCount]=useState(1); const [groups,setGroups]=useState<number[]>([]); const [guestIndex,setGuestIndex]=useState(0);
  const [filters,setFilters]=useState<Filter[]>([]); const [offers,setOffers]=useState<Offer[][]>([]); const [activeGroup,setActiveGroup]=useState(0); const [choices,setChoices]=useState<Choice[]>([]); const [cardIndex,setCardIndex]=useState(0);
  const [feedback,setFeedback]=useState<Feedback>("idle"); const [breakfast,setBreakfast]=useState(false); const [typing,setTyping]=useState(false); const [error,setError]=useState(""); const [detail,setDetail]=useState<Offer|null>(null);
  const [contact,setContact]=useState({name:"",phone:"",email:""}); const [sendStatus,setSendStatus]=useState<"idle"|"sending"|"sent"|"error">("idle"); const feedRef=useRef<HTMLDivElement>(null); const carouselRef=useRef<HTMLDivElement>(null); const turnLocked=useRef(false);
  const guestTotal=groups.reduce((a,b)=>a+b,0); const nights=checkin&&checkout?Math.max(0,nightsBetween(checkin,checkout)):0; const roomTotal=choices.reduce((a,c)=>a+c.offer.directTotal,0); const breakfastTotal=breakfast?guestTotal*nights*12:0;
  const chosenKeys=useMemo(()=>new Set(choices.map(c=>`${c.offer.roomId}:${c.offer.unitId}`)),[choices]);
  const visibleOffers=useMemo(()=>[...(offers[activeGroup]||[])].filter(o=>!chosenKeys.has(`${o.roomId}:${o.unitId}`)).filter(o=>!o.maxGuests||o.maxGuests>=(groups[activeGroup]||0)).sort((a,b)=>{const fa=filters.reduce((s,f)=>s+(matches(a,f)?1:0),0),fb=filters.reduce((s,f)=>s+(matches(b,f)?1:0),0);return fb-fa||a.directTotal-b.directTotal||roomRank(a)-roomRank(b);}),[offers,activeGroup,groups,filters,chosenKeys]);

  useEffect(()=>{const l=detectLanguage();setLanguage(l);setMessages([{id:id(),role:"assistant",content:COPY[l].welcome}]);},[]);
  useEffect(()=>{const f=requestAnimationFrame(()=>feedRef.current?.scrollTo({top:feedRef.current.scrollHeight,behavior:"smooth"}));return()=>cancelAnimationFrame(f);},[messages,step,typing,feedback,choices,sendStatus]);
  const add=(role:Message["role"],content:string,kind:MessageKind="normal")=>setMessages(m=>[...m,{id:id(),role,content,kind}]);
  async function beginUserTurn(content:string,kind:MessageKind="normal",reaction:Reaction="👍"){
    if(turnLocked.current)return false;
    turnLocked.current=true;
    const messageId=id();
    setMessages(current=>[...current,{id:messageId,role:"user",content,kind}]);
    await wait(REACTION_DELAY_MS);
    setMessages(current=>current.map(message=>message.id===messageId?{...message,reaction}:message));
    await wait(REPLY_DELAY_MS);
    return true;
  }
  function endUserTurn(){turnLocked.current=false;}
  const restart=(next=language)=>{turnLocked.current=false;setLanguage(next);setStep("checkin");setMessages([{id:id(),role:"assistant",content:COPY[next].welcome}]);setInput("");setCheckin("");setCheckout("");setRoomCount(1);setGroups([]);setGuestIndex(0);setFilters([]);setOffers([]);setActiveGroup(0);setChoices([]);setFeedback("idle");setBreakfast(false);setError("");setDetail(null);setContact({name:"",phone:"",email:""});setSendStatus("idle");};
  const changeLanguage=(l:Language)=>{const u=new URL(window.location.href);u.searchParams.set("lang",l);history.replaceState(history.state,"",u);restart(l);};

  async function interpretFreeText(value:string,current:Step):Promise<InterpreterCommand>{
    const recentMessages=messages.map(({role,content})=>({role,content}));
    const response=await fetch("/api/ai-assistant/interpret",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:value,context:{language,currentStep:current,checkin:checkin||undefined,checkout:checkout||undefined,roomCount,guestGroups:groups,currentRoom:current==="guests"?guestIndex+1:undefined,recentMessages}})});
    const data=await response.json();
    if(!response.ok||!data?.command)throw new Error(data?.error||"interpretation_failed");
    return data.command as InterpreterCommand;
  }

  async function submit(e:FormEvent){
    e.preventDefault();
    const value=input.trim();
    if(!value||turnLocked.current)return;
    const current=step;
    if(current!=="checkin"&&current!=="checkout"&&current!=="rooms"&&current!=="guests")return;
    setInput("");setError("");
    const interpretationPromise=interpretFreeText(value,current);
    const started=await beginUserTurn(value,current==="checkin"||current==="checkout"?"date":current==="rooms"?"room":current==="guests"?"guest":"normal",current==="rooms"?"❤️":"👍");
    if(!started)return;
    setTyping(true);
    try{
      const command=await interpretationPromise;
      setTyping(false);
      const action=command.actions?.[0];
      if(!action){add("assistant",copy.invalidDate);return;}
      if(action.type==="restart_search"){restart(command.language||language);return;}
      if(action.type==="ask_clarification"){add("assistant",action.query||copy.invalidDate);return;}
      if(action.type==="set_room_count"&&action.roomCount){await applyRoomCount(action.roomCount,false);return;}
      if(action.type==="set_guest_count"&&action.guests){await applyGuestCount(action.guests,false);return;}
      if(action.type==="search_availability"){
        const nextCheckin=action.checkin||checkin;
        const nextCheckout=action.checkout||checkout;
        if(action.checkin&&action.checkin!==checkin){setCheckin(action.checkin);if(!action.checkout)setCheckout("");}
        if(current==="checkin"){
          if(!action.checkin){add("assistant",copy.invalidDate);return;}
          if(action.checkout&&nightsBetween(action.checkin,action.checkout)>0){setCheckout(action.checkout);setStep("rooms");add("assistant",copy.rooms);return;}
          setStep("checkout");add("assistant",copy.checkout);return;
        }
        if(current==="checkout"){
          if(action.checkin&&!action.checkout){setStep("checkout");add("assistant",copy.checkout);return;}
          if(!action.checkout){add("assistant",copy.invalidDate);return;}
          if(!nextCheckin||nightsBetween(nextCheckin,nextCheckout)<1){add("assistant",copy.invalidCheckout);return;}
          setCheckout(action.checkout);setStep("rooms");add("assistant",copy.rooms);return;
        }
      }
      add("assistant",action.query||copy.invalidDate);
    }catch{
      setTyping(false);
      add("assistant",copy.invalidDate);
    }finally{endUserTurn();}
  }

  async function applyRoomCount(n:number,createTurn=true){if(createTurn){const started=await beginUserTurn(copy.roomLabel(n),"room","❤️");if(!started)return;}setRoomCount(n);setGroups([]);setGuestIndex(0);setStep("guests");add("assistant",copy.guests(1));if(createTurn)endUserTurn();}
  async function applyGuestCount(n:number,createTurn=true){if(createTurn){const started=await beginUserTurn(copy.guestLabel(n),"guest","👍");if(!started)return;}const next=[...groups,n];setGroups(next);if(guestIndex+1<roomCount){setGuestIndex(i=>i+1);add("assistant",copy.guests(guestIndex+2));}else{setStep("preferences");add("assistant",copy.preferences);}if(createTurn)endUserTurn();}
  async function searchRooms(userLabel?:string){if(userLabel){const started=await beginUserTurn(userLabel,"normal","❤️");if(!started)return;}setFeedback("idle");setStep("searching");add("assistant",copy.searching);setTyping(true);try{const result=await Promise.all(groups.map(async guests=>{const r=await fetch("/api/ai-assistant/smart",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:[{role:"user",content:`Check live availability from ${checkin} to ${checkout} for ${guests} guests.`}],search:{checkin,checkout,guests},language})});const p=await r.json();if(!r.ok)throw new Error();return Array.isArray(p.offers)?p.offers as Offer[]:[];}));setOffers(result);setActiveGroup(0);setCardIndex(0);if(!(result[0]||[]).length){setStep("unavailable");add("assistant",copy.unavailable);}else{setStep("selecting");add("assistant",copy.choose(1,groups[0]));}}catch{setStep("unavailable");add("assistant",copy.unavailable);}finally{setTyping(false);if(userLabel)endUserTurn();}}
  async function selectOffer(offer:Offer){const started=await beginUserTurn(`${copy.select}: ${offer.name}`,"room","❤️");if(!started)return;const next=[...choices,{group:activeGroup+1,guests:groups[activeGroup],offer}];setChoices(next);setDetail(null);if(activeGroup+1<roomCount){const ng=activeGroup+1;setActiveGroup(ng);setCardIndex(0);setFeedback("idle");add("assistant",copy.choose(ng+1,groups[ng]));endUserTurn();return;}setStep("breakfast");setFeedback("idle");endUserTurn();}
  async function chooseBreakfast(v:boolean){const started=await beginUserTurn(v?copy.yesBreakfast:copy.noBreakfast,"normal",v?"❤️":"👍");if(!started)return;setBreakfast(v);setStep("complete");add("assistant",copy.summary);endUserTurn();}
  async function handleHappy(){const started=await beginUserTurn(copy.feedbackYes,"normal","❤️");if(!started)return;setFeedback("happy");add("assistant",copy.feedbackYesReply);endUserTurn();}
  async function handleDifferent(){const started=await beginUserTurn(copy.feedbackDifferent,"normal","👍");if(!started)return;setFeedback("different");endUserTurn();}
  function whatsappContext(base:string){const current=visibleOffers[cardIndex]||choices.at(-1)?.offer;const room=current?`\n${current.name} · ${money(current.directTotal,language)}`:"";return `${base}\n${checkin} → ${checkout}\n${copy.guestLabel(guestTotal)}${room}`;}
  function openWhatsApp(text:string){window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(text)}`,"_blank","noopener,noreferrer");}
  async function sendRequest(){if(!contact.name.trim()||(!contact.phone.trim()&&!contact.email.trim()))return;setSendStatus("sending");const summary=[`${checkin} → ${checkout}`,copy.guestLabel(guestTotal),...choices.map(c=>`${c.offer.name}: ${money(c.offer.directTotal,language)}`),...(breakfast?[`${copy.breakfastLabel}: ${money(breakfastTotal,language)}`]:[]),`${copy.total}: ${money(roomTotal+breakfastTotal,language)}`].join("\n");try{const r=await fetch("/api/ai-assistant/summary-email",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subject:`AI Room Finder — ${contact.name}`,message:`${copy.contactTitle}\n\n${summary}\n\n${copy.name}: ${contact.name}\n${copy.phone}: ${contact.phone||"—"}\n${copy.email}: ${contact.email||"—"}`,guest:contact})});if(!r.ok)throw new Error();setSendStatus("sent");}catch{setSendStatus("error");}}
  const homeHref=language==="en"?"/":`/${language}/`; const inputEnabled=["checkin","checkout","rooms","guests"].includes(step)&&!typing&&!turnLocked.current;

  return <main className="flex h-[100dvh] flex-col overflow-hidden bg-[#f6f2eb] text-[#29251f]">
    <style jsx global>{`@keyframes msg{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}@keyframes react{from{opacity:0;transform:translateY(2px) scale(.82)}to{opacity:1;transform:none}}.msg{animation:msg .22s ease-out both}.reaction{animation:react .22s ease-out both}.hide-scroll::-webkit-scrollbar{display:none}.hide-scroll{scrollbar-width:none}`}</style>
    <header className="shrink-0 border-b border-[#ddd4c8] bg-[#fbf8f3]/95"><div className="mx-auto flex h-[68px] max-w-3xl items-center gap-2 px-3"><a href={homeHref} className="flex h-10 w-10 items-center justify-center rounded-full text-xl">←</a><div className="relative h-11 w-11 overflow-hidden rounded-full ring-2 ring-white"><Image src="/images/welcome/voulamandis-welcome-hero.webp" alt="Voulamandis House" fill sizes="44px" className="object-cover"/></div><div className="min-w-0 flex-1"><h1 className="truncate text-[16px] font-bold">Voulamandis House</h1><div className="flex items-center gap-1.5 text-xs text-[#746b60]"><span className="h-2 w-2 rounded-full bg-[#718b52]"/>{copy.online}</div></div><select value={language} onChange={e=>changeLanguage(e.target.value as Language)} className="h-9 w-[92px] rounded-full border border-[#d8cec1] bg-white px-2 text-xs font-bold">{LANGUAGES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button onClick={()=>restart()} className="h-10 w-10 rounded-full text-lg">↻</button></div></header>
    {(checkin||groups.length>0)&&<div className="shrink-0 border-b border-[#e5ddd2] bg-[#f9f5ef] px-3 py-2"><div className="hide-scroll mx-auto flex max-w-3xl gap-2 overflow-x-auto text-xs font-semibold text-[#625b52]">{checkin&&<span className="whitespace-nowrap rounded-full border border-[#ddd3c6] bg-white px-3 py-1.5">📅 {checkin}{checkout?` → ${checkout}`:""}</span>}{groups.length>0&&<span className="whitespace-nowrap rounded-full border border-[#ddd3c6] bg-white px-3 py-1.5">👥 {copy.guestLabel(guestTotal)}</span>}{groups.length>0&&<span className="whitespace-nowrap rounded-full border border-[#ddd3c6] bg-white px-3 py-1.5">🛏️ {copy.roomLabel(roomCount)}</span>}</div></div>}
    <div ref={feedRef} className="min-h-0 flex-1 overflow-y-auto"><div className="mx-auto flex min-h-full max-w-3xl flex-col px-3 pb-7 pt-5"><div className="space-y-3.5">
      {messages.map(m=><div key={m.id} className={`msg flex items-end gap-2 ${m.role==="user"?"justify-end":"justify-start"}`}>{m.role==="assistant"&&<div className="relative mb-1 h-8 w-8 shrink-0 overflow-hidden rounded-full ring-1 ring-[#d7cdc0]"><Image src="/images/welcome/voulamandis-welcome-hero.webp" alt="" fill sizes="32px" className="object-cover"/></div>}<div className={`relative max-w-[84%] ${m.role==="user"?"pb-2":""}`}><div className={`whitespace-pre-line px-4 py-3 text-[15px] leading-6 shadow-sm ${m.role==="user"?"rounded-[20px] rounded-br-[6px] bg-[#6b604f] text-white":"rounded-[20px] rounded-bl-[6px] border border-[#dfd6ca] bg-white"}`}>{m.kind==="date"&&m.role==="user"?"📅 ":m.kind==="room"&&m.role==="user"?"🛏️ ":m.kind==="guest"&&m.role==="user"?"👤 ":""}{m.content}</div>{m.role==="user"&&m.reaction&&<span className="reaction absolute -bottom-1 right-1 flex h-7 min-w-7 items-center justify-center rounded-full border border-[#ddd4c8] bg-white px-1.5 text-sm shadow-sm">{m.reaction}</span>}</div></div>)}
      {typing&&<div className="msg ml-10 w-fit rounded-[20px] border border-[#dfd6ca] bg-white px-4 py-3 shadow-sm">•••</div>}
      {step==="rooms"&&<IconReplies values={[1,2,3]} icon="🛏️" label={copy.roomLabel} onSelect={n=>void applyRoomCount(n)}/>} {step==="guests"&&<IconReplies values={[1,2,3,4,5]} icon="👤" label={copy.guestLabel} onSelect={n=>void applyGuestCount(n)}/>} 
      {step==="preferences"&&<section className="msg ml-10 rounded-[22px] border border-[#dfd6ca] bg-white p-4 shadow-sm"><div className="flex flex-wrap gap-2">{FILTER_KEYS.map(f=><button key={f} onClick={()=>setFilters(v=>v.includes(f)?v.filter(x=>x!==f):[...v,f])} className={`rounded-full border px-3 py-2 text-xs font-bold ${filters.includes(f)?"border-[#66714f] bg-[#66714f] text-white":"border-[#d9cfc2] bg-[#fbf9f6]"}`}>{copy.filters[f]}</button>)}</div><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>{setFilters([]);void searchRooms(copy.noPreference);}} className="min-h-12 rounded-2xl border border-[#d9cfc2] font-bold">{copy.noPreference}</button><button onClick={()=>void searchRooms(copy.showRooms)} className="min-h-12 rounded-2xl bg-[#66714f] font-bold text-white">{copy.showRooms}</button></div></section>}
      {step==="selecting"&&visibleOffers.length>0&&<><section className="msg relative -mx-3 sm:mx-0 sm:ml-10"><div ref={carouselRef} className="hide-scroll flex snap-x snap-mandatory gap-3 overflow-x-auto px-3 pb-2 sm:px-10">{visibleOffers.map((o,i)=><article key={`${o.roomId}:${o.unitId}`} className="min-w-[88%] snap-center overflow-hidden rounded-[24px] border border-[#dcd2c5] bg-white shadow-[0_14px_38px_rgba(70,55,35,.10)] sm:min-w-[68%]"><div className="relative h-44 sm:h-56"><Image src={o.image} alt={o.name} fill sizes="88vw" className="object-cover"/><span className="absolute right-3 top-3 rounded-full bg-white/90 px-2.5 py-1 text-xs font-bold">{i+1}/{visibleOffers.length}</span></div><div className="p-3.5"><div className="flex justify-between gap-3"><div><h2 className="text-[1.35rem] font-bold">{o.name}</h2><p className="text-sm text-[#746b60]">{o.category} · {o.floor}</p></div><div className="text-right"><p className="text-xs text-[#b05252] line-through">{money(o.originalTotal,language)}</p><p className="text-xl font-black text-[#5f7448]">{money(o.directTotal,language)}</p></div></div><div className="mt-2 flex flex-wrap gap-1.5">{(o.features||[]).slice(0,4).map(x=><span key={x} className="rounded-full bg-[#f1ede7] px-2.5 py-1 text-[11px] font-semibold">{x}</span>)}</div>{o.saving>0&&<p className="mt-2 text-sm font-bold text-[#5f7448]">{copy.saving}: {money(o.saving,language)}</p>}<div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>setDetail(o)} className="min-h-11 rounded-2xl border border-[#d8cec1] font-bold">{copy.details}</button><button onClick={()=>void selectOffer(o)} className="min-h-11 rounded-2xl bg-[#66714f] font-bold text-white">{copy.select}</button></div></div></article>)}</div></section><FeedbackBlock copy={copy} feedback={feedback} onHappy={()=>void handleHappy()} onDifferent={()=>void handleDifferent()} onInfo={()=>openWhatsApp(whatsappContext(language==="el"?"Γεια σας, θα ήθελα περισσότερες πληροφορίες για μία από τις προτάσεις του AI Room Finder.":"Hello, I would like more information about one of the AI Room Finder suggestions."))} onOther={()=>openWhatsApp(whatsappContext(language==="el"?"Γεια σας, χρησιμοποιώ το AI Room Finder και θα ήθελα βοήθεια με τη διαμονή μου.":"Hello, I’m using the AI Room Finder and would like help with my stay."))} onFilter={(f:Filter)=>{setFilters(v=>v.includes(f)?v:[...v,f]);setFeedback("idle");}}/></>}
      {step==="breakfast"&&<><SelectedCard choices={choices} copy={copy} language={language} checkin={checkin} checkout={checkout}/><div className="msg ml-10 rounded-[20px] rounded-bl-[6px] border border-[#dfd6ca] bg-white px-4 py-3 text-[15px] shadow-sm">{copy.breakfast}</div><section className="msg ml-10 overflow-hidden rounded-[22px] border border-[#dcd2c5] bg-white shadow-sm"><div className="relative h-36"><Image src={BREAKFAST_IMAGE} alt={copy.breakfastLabel} fill sizes="600px" className="object-cover"/></div><div className="flex gap-2 p-3"><button onClick={()=>void chooseBreakfast(true)} className="rounded-full bg-[#66714f] px-4 py-2.5 text-sm font-bold text-white">{copy.yesBreakfast}</button><button onClick={()=>void chooseBreakfast(false)} className="rounded-full border border-[#d8cec1] px-4 py-2.5 text-sm font-bold">{copy.noBreakfast}</button></div></section></>}
      {step==="unavailable"&&<section className="ml-10 grid grid-cols-2 gap-2 rounded-[22px] border border-[#dfd6ca] bg-white p-4"><button onClick={()=>restart()} className="min-h-12 rounded-2xl border font-bold">{copy.newSearch}</button><button onClick={()=>openWhatsApp(copy.unavailable)} className="min-h-12 rounded-2xl bg-[#287d4f] font-bold text-white">{copy.whatsapp}</button></section>}
      {step==="complete"&&<section className="msg overflow-hidden rounded-[26px] border border-[#dcd2c5] bg-white shadow-[0_16px_45px_rgba(70,55,35,.10)] sm:ml-10"><div className="border-b bg-[#faf7f2] p-4"><div className="flex justify-between"><h2 className="text-lg font-black">{copy.summary}</h2><button onClick={()=>restart()} className="text-xs font-bold underline">{copy.newSearch}</button></div><p className="mt-2 text-sm text-[#746b60]">📅 {checkin} → {checkout} · {copy.nightLabel(nights)}</p></div><div className="p-4">{choices.map(c=><div key={c.group} className="flex items-center gap-3 border-b py-3"><div className="relative h-14 w-[72px] overflow-hidden rounded-xl"><Image src={c.offer.image} alt={c.offer.name} fill sizes="72px" className="object-cover"/></div><div className="flex-1"><p className="font-bold">{c.offer.name}</p><p className="text-xs text-[#746b60]">{copy.guestLabel(c.guests)}</p></div><strong className="text-[#5f7448]">{money(c.offer.directTotal,language)}</strong></div>)}{breakfast&&<div className="flex justify-between border-b py-3"><span>🥐 {copy.breakfastLabel}</span><strong>{money(breakfastTotal,language)}</strong></div>}<div className="mt-4 flex justify-between rounded-2xl bg-[#f1ede7] p-4 text-lg"><b>{copy.total}</b><strong className="text-xl text-[#5f7448]">{money(roomTotal+breakfastTotal,language)}</strong></div><div className="mt-5"><h3 className="text-lg font-black">{copy.contactTitle}</h3><p className="mt-1 text-sm text-[#746b60]">{copy.contactHelp}</p><div className="mt-3 space-y-2"><input value={contact.name} onChange={e=>setContact({...contact,name:e.target.value})} placeholder={copy.name} className="h-12 w-full rounded-2xl border border-[#d8cec1] px-4"/><input value={contact.phone} onChange={e=>setContact({...contact,phone:e.target.value})} placeholder={copy.phone} className="h-12 w-full rounded-2xl border border-[#d8cec1] px-4"/><input value={contact.email} onChange={e=>setContact({...contact,email:e.target.value})} placeholder={copy.email} className="h-12 w-full rounded-2xl border border-[#d8cec1] px-4"/></div><div className="mt-3 grid grid-cols-2 gap-2"><button disabled={sendStatus==="sending"} onClick={()=>void sendRequest()} className="min-h-12 rounded-2xl bg-[#66714f] font-bold text-white disabled:opacity-40">{copy.send}</button><button onClick={()=>openWhatsApp(whatsappContext(copy.contactTitle))} className="min-h-12 rounded-2xl bg-[#287d4f] font-bold text-white">{copy.whatsapp}</button></div>{sendStatus==="sent"&&<p className="mt-3 rounded-2xl bg-[#eef4e7] p-3 font-bold text-[#5f7448]">{copy.sent}</p>}{sendStatus==="error"&&<p className="mt-3 rounded-2xl bg-red-50 p-3 text-sm text-red-700">{copy.sendError}</p>}</div></div></section>}
    </div></div></div>
    <form onSubmit={submit} className="shrink-0 border-t border-[#e2d9cd] bg-[#fbf8f3]/95 p-3"><div className="mx-auto flex max-w-3xl items-center gap-2 rounded-[24px] border border-[#d8cec1] bg-white p-2 shadow-sm"><input value={input} onChange={e=>setInput(e.target.value)} disabled={!inputEnabled} placeholder={inputEnabled?copy.placeholder:copy.chooseAbove} className="min-w-0 flex-1 bg-transparent px-3 py-2 text-[15px] outline-none disabled:text-[#a9a197]"/><button disabled={!inputEnabled||!input.trim()} className="flex h-11 w-11 items-center justify-center rounded-full bg-[#6b604f] text-white disabled:bg-[#d7d0c6]">↑</button></div></form>
    {detail&&<div className="fixed inset-0 z-50 flex items-end bg-black/35 p-3 sm:items-center sm:justify-center"><section className="max-h-[88dvh] w-full overflow-hidden rounded-[26px] bg-white sm:max-w-xl"><div className="relative h-60"><Image src={detail.image} alt={detail.name} fill sizes="600px" className="object-cover"/><button onClick={()=>setDetail(null)} className="absolute right-3 top-3 h-10 w-10 rounded-full bg-white/90 text-xl">×</button></div><div className="p-5"><h2 className="text-2xl font-black">{detail.name}</h2><p className="mt-1 text-sm text-[#746b60]">{detail.category} · {detail.floor}</p><div className="mt-3 flex flex-wrap gap-2">{(detail.features||[]).map(x=><span key={x} className="rounded-full bg-[#f1ede7] px-3 py-1.5 text-xs font-semibold">{x}</span>)}</div><button onClick={()=>void selectOffer(detail)} className="mt-5 w-full rounded-2xl bg-[#66714f] p-3.5 font-black text-white">{copy.select}</button></div></section></div>}
  </main>;
}

function IconReplies({values,icon,label,onSelect}:{values:number[];icon:string;label:(n:number)=>string;onSelect:(n:number)=>void}){return <div className="hide-scroll msg ml-10 flex gap-2 overflow-x-auto pb-1">{values.map(v=><button key={v} onClick={()=>onSelect(v)} className="flex min-w-[104px] flex-1 flex-col items-center justify-center rounded-[20px] border border-[#d8cec1] bg-white px-2 py-3 text-center shadow-sm"><div className="mb-1 text-xl" aria-hidden>{Array.from({length:v},(_,i)=><span key={i}>{icon}</span>)}</div><span className="whitespace-nowrap text-xs font-bold">{label(v)}</span></button>)}</div>}
function FeedbackBlock({copy,feedback,onHappy,onDifferent,onInfo,onOther,onFilter}:{copy:any;feedback:Feedback;onHappy:()=>void;onDifferent:()=>void;onInfo:()=>void;onOther:()=>void;onFilter:(f:Filter)=>void}){return <section className="msg ml-10 rounded-[22px] border border-[#dfd6ca] bg-white p-4 shadow-sm"><p className="font-bold">{feedback==="different"?copy.changePrompt:copy.feedbackQ}</p>{feedback!=="different"?<div className="mt-3 grid grid-cols-1 gap-2 sm:grid-cols-2"><button onClick={onHappy} className="rounded-2xl bg-[#66714f] px-3 py-3 text-sm font-bold text-white">{copy.feedbackYes}</button><button onClick={onDifferent} className="rounded-2xl border border-[#d8cec1] px-3 py-3 text-sm font-bold">{copy.feedbackDifferent}</button></div>:<div className="mt-3 grid gap-2"><button onClick={()=>onFilter("family")} className="rounded-2xl border p-3 text-left text-sm font-bold">{copy.roomType}</button><button onClick={()=>onFilter("noStairs")} className="rounded-2xl border p-3 text-left text-sm font-bold">{copy.floor}</button><button onClick={()=>onFilter("family")} className="rounded-2xl border p-3 text-left text-sm font-bold">{copy.group}</button><button onClick={onInfo} className="rounded-2xl border p-3 text-left text-sm font-bold">{copy.info}</button><button onClick={onOther} className="rounded-2xl border p-3 text-left text-sm font-bold">{copy.other}</button></div>}</section>}
function SelectedCard({choices,copy,language,checkin,checkout}:{choices:Choice[];copy:any;language:Language;checkin:string;checkout:string}){return <section className="msg ml-10 rounded-[22px] border border-[#d9cfc2] bg-[#fffdfa] p-3.5 shadow-sm"><div className="mb-3 flex items-center justify-between"><div className="font-black text-[#5f7448]">♥ {copy.selected}</div><strong className="text-[#5f7448]">{money(choices.reduce((s,c)=>s+c.offer.directTotal,0),language)}</strong></div><div className="space-y-2">{choices.map(c=><div key={c.group} className="flex items-center gap-3 rounded-2xl bg-[#f5f1eb] p-2.5"><div className="relative h-16 w-20 shrink-0 overflow-hidden rounded-xl"><Image src={c.offer.image} alt={c.offer.name} fill sizes="80px" className="object-cover"/></div><div className="min-w-0 flex-1"><div className="truncate font-bold">{c.offer.name}</div><div className="text-xs text-[#746b60]">{c.offer.category} · {c.offer.floor}</div><div className="mt-1 text-xs font-semibold text-[#625b52]">📅 {checkin} → {checkout} · 👥 {copy.guestLabel(c.guests)}</div></div><strong className="text-sm text-[#5f7448]">{money(c.offer.directTotal,language)}</strong></div>)}</div></section>}
