"use client";

import Image from "next/image";
import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";

type Language = "el" | "en" | "de" | "fr" | "it" | "es" | "tr";
type Segment = { roomNumber:number; checkin:string; checkout:string; nights:number; name:string };
type SplitView = { article:HTMLElement; selectButton:HTMLButtonElement|null; original:string; direct:string; segments:Segment[]; language:Language };

const COPY:Record<Language,{title:string;intro:string;stay:string;room:string;extra:string;select:string}>={
 el:{title:"Βρέθηκε διαθεσιμότητα",intro:"Βρέθηκε διαθεσιμότητα για ολόκληρη τη διαμονή σας 😊 Θα χρειαστεί μόνο μία αλλαγή δωματίου και για αυτή την αλλαγή σας προσφέρουμε επιπλέον έκπτωση 10%.",stay:"Διαμονή",room:"Δωμάτιο",extra:"Επιπλέον έκπτωση split stay 10%",select:"Επιλογή αυτής της διαμονής"},
 en:{title:"Availability found",intro:"We found availability for your full stay 😊 Only one room change is needed, and we are offering an additional 10% discount for the change.",stay:"Stay",room:"Room",extra:"Extra split-stay discount 10%",select:"Choose this stay"},
 de:{title:"Verfügbarkeit gefunden",intro:"Wir haben Verfügbarkeit für Ihren gesamten Aufenthalt gefunden 😊 Es ist nur ein Zimmerwechsel nötig, dafür erhalten Sie zusätzlich 10% Rabatt.",stay:"Aufenthalt",room:"Zimmer",extra:"Zusätzlicher Split-Stay-Rabatt 10%",select:"Diesen Aufenthalt wählen"},
 fr:{title:"Disponibilité trouvée",intro:"Nous avons trouvé une disponibilité pour tout votre séjour 😊 Un seul changement de chambre sera nécessaire et nous vous offrons 10% de réduction supplémentaire.",stay:"Séjour",room:"Chambre",extra:"Réduction split stay supplémentaire 10%",select:"Choisir ce séjour"},
 it:{title:"Disponibilità trovata",intro:"Abbiamo trovato disponibilità per tutto il soggiorno 😊 Sarà necessario un solo cambio camera e per questo offriamo un ulteriore sconto del 10%.",stay:"Soggiorno",room:"Camera",extra:"Sconto split stay extra 10%",select:"Scegli questo soggiorno"},
 es:{title:"Disponibilidad encontrada",intro:"Hemos encontrado disponibilidad para toda tu estancia 😊 Solo será necesario un cambio de habitación y te ofrecemos un 10% de descuento adicional.",stay:"Estancia",room:"Habitación",extra:"Descuento split stay adicional 10%",select:"Elegir esta estancia"},
 tr:{title:"Müsaitlik bulundu",intro:"Tüm konaklamanız için müsaitlik bulduk 😊 Yalnızca bir oda değişikliği gerekecek ve bunun için ek %10 indirim sunuyoruz.",stay:"Konaklama",room:"Oda",extra:"Ek split stay indirimi %10",select:"Bu konaklamayı seç"}
};

const IMAGES:Record<number,string>={1:"/images/rooms/DSC07776-2-e1675109942622.webp",2:"/images/rooms/DSC07803-1.webp",3:"/images/rooms/DSC07867-1.webp",4:"/images/rooms/received_1748354861920234.webp",5:"/images/rooms/voulamandis-house-rooms.webp",6:"/images/rooms/received_1753964631359257.webp",7:"/images/rooms/double-triple-room.jpg",8:"/images/rooms/chios-apartments-voulamandis.webp",9:"/images/rooms/chios-apartments-voulamandis.webp",10:"/images/rooms/DSC07899.webp"};

function languageFromUrl():Language{const v=new URLSearchParams(window.location.search).get("lang")||"el";return (["el","en","de","fr","it","es","tr"] as Language[]).includes(v as Language)?v as Language:"el"}
function formatDate(value:string,language:Language){const d=new Date(value+"T12:00:00Z");return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat({el:"el-GR",en:"en-GB",de:"de-DE",fr:"fr-FR",it:"it-IT",es:"es-ES",tr:"tr-TR"}[language],{day:"numeric",month:"short"}).format(d)}
function parseSegments(text:string):Segment[]{const re=/Room\s*(\d+)\s*:\s*(\d{4}-\d{2}-\d{2})\s*→\s*(\d{4}-\d{2}-\d{2})/gi;const found:Array<Omit<Segment,"nights"|"name">>=[];let m:RegExpExecArray|null;while((m=re.exec(text)))found.push({roomNumber:Number(m[1]),checkin:m[2],checkout:m[3]});return found.slice(0,2).map(s=>({...s,nights:Math.max(1,Math.round((new Date(s.checkout+"T12:00:00Z").getTime()-new Date(s.checkin+"T12:00:00Z").getTime())/86400000)),name:""}))}

export function AiSplitStayPresentation(){
 const [view,setView]=useState<SplitView|null>(null);
 useEffect(()=>{const scan=()=>{const article=Array.from(document.querySelectorAll<HTMLElement>("article")).find(a=>/Split Stay:\s*Room\s*\d+\s*→\s*Room\s*\d+/i.test(a.querySelector("h2")?.textContent||""));if(!article){setView(null);return}const text=article.innerText||"";const segments=parseSegments(text);if(segments.length!==2){setView(null);return}const buttons=Array.from(article.querySelectorAll<HTMLButtonElement>("button"));const selectButton=buttons.at(-1)||null;const prices=Array.from(article.querySelectorAll<HTMLElement>("p,strong")).map(n=>(n.textContent||"").trim()).filter(t=>/€/.test(t));const original=prices.find(t=>article.querySelector(".line-through")?.textContent?.trim()===t)||prices[0]||"";const direct=prices.find(t=>t!==original)||prices.at(-1)||"";article.style.display="none";setView({article,selectButton,original,direct,segments,language:languageFromUrl()})};scan();const observer=new MutationObserver(scan);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()},[]);
 const host=useMemo(()=>view?.article.parentElement||null,[view]);
 useEffect(()=>{const compact=()=>{for(const heading of Array.from(document.querySelectorAll<HTMLElement>("p"))){if(!/Παροχές δωματίου|Room amenities|Zimmerausstattung|Équipements de la chambre|Servizi della camera|Servicios de la habitación|Oda olanakları/i.test(heading.textContent||""))continue;const box=heading.nextElementSibling as HTMLElement|null;if(!box)continue;box.style.display="grid";box.style.gridTemplateColumns="repeat(3,minmax(0,1fr))";box.style.gap="6px";box.style.maxHeight=box.style.maxHeight||"92px";for(const badge of Array.from(box.children) as HTMLElement[]){badge.style.fontSize="9px";badge.style.padding="6px";badge.style.lineHeight="1.15";badge.style.textAlign="center";badge.style.justifyContent="center";badge.style.minWidth="0"}}};compact();const o=new MutationObserver(compact);o.observe(document.body,{childList:true,subtree:true});return()=>o.disconnect()},[]);
 if(!view||!host)return null;const c=COPY[view.language];
 return createPortal(<div className="mx-auto w-full max-w-xl space-y-3" data-ai-split-stay>
  <div className="rounded-[18px] border border-[#ffd1da] bg-[#fff4f6] px-4 py-3"><p className="text-[11px] font-bold uppercase tracking-[.14em] text-[#c1354f]">{c.title}</p><p className="mt-1 text-[15px] font-semibold leading-6 text-[#222]">{c.intro}</p></div>
  {view.segments.map((s,i)=><article key={s.roomNumber+"-"+i} className="overflow-hidden rounded-[22px] border border-stone-200 bg-white shadow-sm"><div className="grid grid-cols-[112px_1fr] sm:grid-cols-[160px_1fr]"><div className="relative min-h-[138px]"><Image src={IMAGES[s.roomNumber]||"/images/rooms/double-triple-room.jpg"} alt={c.room+" "+s.roomNumber} fill sizes="160px" className="object-cover"/></div><div className="p-4"><p className="text-[11px] font-black uppercase tracking-[.12em] text-[#c1354f]">{c.stay} {i+1}</p><h3 className="mt-1 text-lg font-black">{c.room} {s.roomNumber}</h3><p className="mt-1 text-sm text-stone-600">{s.nights} {view.language==="el"?(s.nights===1?"βραδιά":"βραδιές"):view.language==="en"?(s.nights===1?"night":"nights"):""}</p><p className="mt-2 text-xs font-semibold text-stone-500">{formatDate(s.checkin,view.language)} → {formatDate(s.checkout,view.language)}</p></div></div></article>)}
  <div className="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-800">✓ {c.extra}</div>
  <div className="flex items-center justify-between rounded-2xl bg-white p-4 shadow-sm ring-1 ring-stone-200"><div>{view.original?<p className="text-xs text-red-500 line-through">{view.original}</p>:null}<p className="text-2xl font-black text-emerald-700">{view.direct}</p></div><button type="button" onClick={()=>view.selectButton?.click()} className="rounded-xl bg-[#ff385c] px-5 py-3 text-sm font-bold text-white">{c.select}</button></div>
 </div>,host);
}
