"use client";

import Image from "next/image";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Language = "el" | "en" | "de" | "fr" | "it" | "es" | "tr";
type Step = "language" | "checkin" | "checkout" | "rooms" | "guests" | "preferences" | "interpreting" | "searching" | "selecting" | "breakfast" | "complete";
type Filter = "economy" | "noStairs" | "ground" | "first" | "kitchen" | "garden" | "balcony" | "family";
type Offer = { roomId:string; unitId:string; name:string; category:string; floor:string; maxGuests:number; features:string[]; image:string; gallery?:string[]; nights:number; originalTotal:number; directTotal:number; saving:number; recommendationRole?:"recommended"|"budget"|"comfort"|"alternative"; recommendationTitle?:string; recommendationReason?:string };
type Choice = { group:number; guests:number; offer:Offer };
type Msg = { role:"assistant" | "user"; content:string };

const LANGS:[Language,string][] = [["el","Ελληνικά"],["en","English"],["de","Deutsch"],["fr","Français"],["it","Italiano"],["es","Español"],["tr","Türkçe"]];
const LANGUAGE_PROMPTS: Record<Language, string> = {
 el:"👋 Σε ποια γλώσσα θα θέλατε να συνεχίσουμε;", en:"👋 Which language would you prefer?", de:"👋 In welcher Sprache möchten Sie fortfahren?", fr:"👋 Dans quelle langue souhaitez-vous continuer ?", it:"👋 In quale lingua preferisci continuare?", es:"👋 ¿En qué idioma prefieres continuar?", tr:"👋 Hangi dilde devam etmek istersiniz?"
};

function detectEntryLanguage(): Language {
 if (typeof window === "undefined") return "en";
 const supported: Language[] = ["el", "en", "de", "fr", "it", "es", "tr"];
 const queryLanguage = new URLSearchParams(window.location.search).get("lang")?.toLowerCase().split("-")[0];
 const pathLanguage = window.location.pathname.split("/").filter(Boolean)[0]?.toLowerCase();
 const documentLanguage = document.documentElement.lang?.toLowerCase().split("-")[0];
 let referrerLanguage = "";
 try { referrerLanguage = document.referrer ? new URL(document.referrer).pathname.split("/").filter(Boolean)[0]?.toLowerCase() || "" : ""; } catch {}
 const detected = [queryLanguage, pathLanguage, documentLanguage, referrerLanguage].find(value => supported.includes(value as Language));
 return (detected as Language) || "en";
}

const CURRENT_CHOICE_LABEL: Record<Language,string> = { el:"✨ Πρόταση για εσάς", en:"✨ A good match for you", de:"✨ Eine passende Option", fr:"✨ Une option adaptée", it:"✨ Una buona scelta", es:"✨ Una buena opción", tr:"✨ Size uygun bir seçenek" };
const BREAKFAST_IMAGE = "/images/welcome/voulamandis-breakfast.jpg";

const T:Record<Language,any> = {
 el:{welcome:"👋 Καλώς ήρθατε στο Voulamandis House! Θα σας βοηθήσω να βρείτε το κατάλληλο δωμάτιο με live διαθεσιμότητα και direct τιμές 😊\n\n📅 Πότε θα θέλατε να έρθετε στη Χίο; Μπορείτε να γράψετε και «είκοσι Ιουλίου».",checkout:"Τέλεια 😊 📅 Και ποια ημέρα θα γίνει το check-out;",rooms:"🛏️ Πόσα δωμάτια χρειάζεστε; Μπορείτε να ζητήσετε από 1 έως 3.",guests:(n:number)=>`👥 Πόσα άτομα θα μείνουν στο δωμάτιο ${n};`,prefs:"✨ Ψάχνετε κάτι συγκεκριμένο; Επιλέξτε όσα φίλτρα θέλετε ή συνεχίστε χωρίς προτίμηση.",continue:"Προβολή προτάσεων",nonePref:"Χωρίς προτίμηση",interpreting:"🤖 Καταλαβαίνω την ημερομηνία σας…",searching:"🔎 Ελέγχω τώρα τη live διαθεσιμότητα και τις καλύτερες direct τιμές για εσάς…",choose:(g:number,p:number)=>`🛏️ Επιλέξτε δωμάτιο για την ομάδα ${g} · ${p} άτομα`,details:"Προβολή λεπτομερειών",select:"Επιλογή",close:"Κλείσιμο",amenities:"Παροχές",total:"Τελικό σύνολο",perNight:"ανά βραδιά",saving:"Εξοικονόμηση",breakfast:"🥐 Θα θέλατε να προσθέσετε σπιτικό πρωινό με 12€ ανά άτομο, ανά ημέρα;",yes:"Ναι, προσθήκη πρωινού",no:"Χωρίς πρωινό",summary:"✅ Η επιλογή σας",newSearch:"Νέα αναζήτηση",invalidDate:"Δεν κατάφερα να καταλάβω την ημερομηνία. Γράψτε την ξανά, π.χ. «20 Ιουλίου» ή «20/07».",invalidCheckout:"Το check-out πρέπει να είναι μετά το check-in.",invalidRooms:"Γράψτε 1, 2 ή 3 δωμάτια.",invalidGuests:"Γράψτε αριθμό ατόμων από 1 έως 5.",send:"Αποστολή",placeholder:"Γράψτε την απάντησή σας…",filters:{economy:"Οικονομικό",noStairs:"Χωρίς σκάλες",ground:"Ισόγειο",first:"Πρώτος όροφος",kitchen:"Κουζίνα / kitchenette",garden:"Κήπος / αυλή",balcony:"Μπαλκόνι",family:"Οικογενειακό"}},
 en:{welcome:"👋 Welcome to Voulamandis House! I’ll help you find the right room with live availability and direct prices 😊\n\n📅 When would you like to arrive in Chios? You can also write a date in words.",checkout:"Perfect 😊 📅 What date would you like to check out?",rooms:"🛏️ How many rooms do you need? You can request 1 to 3.",guests:(n:number)=>`👥 How many guests will stay in room ${n}?`,prefs:"✨ Are you looking for anything specific? Choose any filters or continue with no preference.",continue:"Show recommendations",nonePref:"No preference",interpreting:"🤖 Understanding your date…",searching:"🔎 Checking live availability and the best direct prices for you…",choose:(g:number,p:number)=>`🛏️ Choose a room for group ${g} · ${p} guests`,details:"View details",select:"Select",close:"Close",amenities:"Amenities",total:"Grand total",perNight:"per night",saving:"Saving",breakfast:"🥐 Would you like to add homemade breakfast for €12 per guest, per day?",yes:"Yes, add breakfast",no:"No breakfast",summary:"✅ Your selection",newSearch:"New search",invalidDate:"I could not understand the date. Please write it again, for example “20 July” or “20/07”.",invalidCheckout:"Check-out must be after check-in.",invalidRooms:"Enter 1, 2 or 3 rooms.",invalidGuests:"Enter 1 to 5 guests.",send:"Send",placeholder:"Type your answer…",filters:{economy:"Economy",noStairs:"No stairs",ground:"Ground floor",first:"First floor",kitchen:"Kitchen / kitchenette",garden:"Garden / courtyard",balcony:"Balcony",family:"Family"}},
 de:{welcome:"👋 Willkommen im Voulamandis House! Ich helfe Ihnen mit Live-Verfügbarkeit und Direktpreisen 😊\n\n📅 Wann möchten Sie anreisen? Sie können das Datum auch ausschreiben.",checkout:"Perfekt 😊 📅 Wann möchten Sie abreisen?",rooms:"🛏️ Wie viele Zimmer benötigen Sie? 1 bis 3 sind möglich.",guests:(n:number)=>`👥 Wie viele Gäste übernachten in Zimmer ${n}?`,prefs:"✨ Suchen Sie etwas Bestimmtes? Wählen Sie Filter oder fahren Sie ohne Präferenz fort.",continue:"Empfehlungen anzeigen",nonePref:"Keine Präferenz",interpreting:"🤖 Ich verstehe Ihr Datum…",searching:"🔎 Live-Verfügbarkeit und Direktpreise werden geprüft…",choose:(g:number,p:number)=>`🛏️ Wählen Sie ein Zimmer für Gruppe ${g} · ${p} Gäste`,details:"Details ansehen",select:"Auswählen",close:"Schließen",amenities:"Ausstattung",total:"Gesamtsumme",perNight:"pro Nacht",saving:"Ersparnis",breakfast:"🥐 Möchten Sie hausgemachtes Frühstück für 12 € pro Person und Tag hinzufügen?",yes:"Ja, Frühstück hinzufügen",no:"Ohne Frühstück",summary:"✅ Ihre Auswahl",newSearch:"Neue Suche",invalidDate:"Ich konnte das Datum nicht verstehen. Bitte erneut eingeben.",invalidCheckout:"Check-out muss nach Check-in liegen.",invalidRooms:"Bitte 1, 2 oder 3 Zimmer eingeben.",invalidGuests:"Bitte 1 bis 5 Gäste eingeben.",send:"Senden",placeholder:"Antwort eingeben…",filters:{economy:"Preisgünstig",noStairs:"Keine Treppen",ground:"Erdgeschoss",first:"Erster Stock",kitchen:"Küche / Küchenzeile",garden:"Garten / Hof",balcony:"Balkon",family:"Familienfreundlich"}},
 fr:{welcome:"👋 Bienvenue au Voulamandis House ! Je vais vous aider avec les disponibilités en direct et les tarifs directs 😊\n\n📅 Quand souhaitez-vous arriver ? Vous pouvez aussi écrire la date en toutes lettres.",checkout:"Parfait 😊 📅 Quelle est votre date de départ ?",rooms:"🛏️ Combien de chambres souhaitez-vous ? De 1 à 3.",guests:(n:number)=>`👥 Combien de personnes séjourneront dans la chambre ${n} ?`,prefs:"✨ Recherchez-vous quelque chose de précis ? Choisissez vos filtres ou continuez sans préférence.",continue:"Voir les recommandations",nonePref:"Sans préférence",interpreting:"🤖 Je comprends votre date…",searching:"🔎 Je vérifie les disponibilités et les meilleurs tarifs directs…",choose:(g:number,p:number)=>`🛏️ Choisissez une chambre pour le groupe ${g} · ${p} personnes`,details:"Voir les détails",select:"Choisir",close:"Fermer",amenities:"Équipements",total:"Total général",perNight:"par nuit",saving:"Économie",breakfast:"🥐 Souhaitez-vous ajouter le petit-déjeuner maison à 12 € par personne et par jour ?",yes:"Oui, ajouter",no:"Sans petit-déjeuner",summary:"✅ Votre sélection",newSearch:"Nouvelle recherche",invalidDate:"Je n’ai pas compris la date. Merci de la saisir à nouveau.",invalidCheckout:"Le départ doit être après l’arrivée.",invalidRooms:"Saisissez 1, 2 ou 3 chambres.",invalidGuests:"Saisissez de 1 à 5 personnes.",send:"Envoyer",placeholder:"Écrivez votre réponse…",filters:{economy:"Économique",noStairs:"Sans escaliers",ground:"Rez-de-chaussée",first:"Premier étage",kitchen:"Cuisine / kitchenette",garden:"Jardin / cour",balcony:"Balcon",family:"Familial"}},
 it:{welcome:"👋 Benvenuti a Voulamandis House! Ti aiuterò con disponibilità live e prezzi diretti 😊\n\n📅 Quando desideri arrivare? Puoi scrivere la data anche in lettere.",checkout:"Perfetto 😊 📅 Qual è la data di check-out?",rooms:"🛏️ Quante camere ti servono? Da 1 a 3.",guests:(n:number)=>`👥 Quante persone soggiorneranno nella camera ${n}?`,prefs:"✨ Cerchi qualcosa di specifico? Seleziona i filtri oppure continua senza preferenze.",continue:"Mostra le proposte",nonePref:"Nessuna preferenza",interpreting:"🤖 Sto comprendendo la data…",searching:"🔎 Controllo disponibilità live e migliori prezzi diretti…",choose:(g:number,p:number)=>`🛏️ Scegli una camera per il gruppo ${g} · ${p} persone`,details:"Vedi dettagli",select:"Seleziona",close:"Chiudi",amenities:"Servizi",total:"Totale finale",perNight:"a notte",saving:"Risparmio",breakfast:"🥐 Vuoi aggiungere la colazione fatta in casa a 12 € per persona al giorno?",yes:"Sì, aggiungi",no:"Senza colazione",summary:"✅ La tua selezione",newSearch:"Nuova ricerca",invalidDate:"Non ho capito la data. Scrivila di nuovo.",invalidCheckout:"Il check-out deve essere dopo il check-in.",invalidRooms:"Inserisci 1, 2 o 3 camere.",invalidGuests:"Inserisci da 1 a 5 persone.",send:"Invia",placeholder:"Scrivi la risposta…",filters:{economy:"Economica",noStairs:"Senza scale",ground:"Piano terra",first:"Primo piano",kitchen:"Cucina / angolo cottura",garden:"Giardino / cortile",balcony:"Balcone",family:"Familiare"}},
 es:{welcome:"👋 ¡Bienvenido a Voulamandis House! Te ayudaré con disponibilidad en vivo y precios directos 😊\n\n📅 ¿Cuándo deseas llegar? También puedes escribir la fecha con palabras.",checkout:"Perfecto 😊 📅 ¿Cuál es la fecha de salida?",rooms:"🛏️ ¿Cuántas habitaciones necesitas? De 1 a 3.",guests:(n:number)=>`👥 ¿Cuántas personas se alojarán en la habitación ${n}?`,prefs:"✨ ¿Buscas algo específico? Elige filtros o continúa sin preferencias.",continue:"Ver recomendaciones",nonePref:"Sin preferencia",interpreting:"🤖 Estoy entendiendo la fecha…",searching:"🔎 Compruebo disponibilidad en vivo y los mejores precios directos…",choose:(g:number,p:number)=>`🛏️ Elige una habitación para el grupo ${g} · ${p} personas`,details:"Ver detalles",select:"Seleccionar",close:"Cerrar",amenities:"Servicios",total:"Total final",perNight:"por noche",saving:"Ahorro",breakfast:"🥐 ¿Quieres añadir desayuno casero por 12 € por persona y día?",yes:"Sí, añadir",no:"Sin desayuno",summary:"✅ Tu selección",newSearch:"Nueva búsqueda",invalidDate:"No pude entender la fecha. Escríbela de nuevo.",invalidCheckout:"La salida debe ser posterior a la entrada.",invalidRooms:"Introduce 1, 2 o 3 habitaciones.",invalidGuests:"Introduce de 1 a 5 personas.",send:"Enviar",placeholder:"Escribe tu respuesta…",filters:{economy:"Económica",noStairs:"Sin escaleras",ground:"Planta baja",first:"Primera planta",kitchen:"Cocina / kitchenette",garden:"Jardín / patio",balcony:"Balcón",family:"Familiar"}},
 tr:{welcome:"👋 Voulamandis House’a hoş geldiniz! Canlı müsaitlik ve direkt fiyatlarla size yardımcı olacağım 😊\n\n📅 Ne zaman gelmek istersiniz? Tarihi yazıyla da yazabilirsiniz.",checkout:"Harika 😊 📅 Çıkış tarihiniz nedir?",rooms:"🛏️ Kaç odaya ihtiyacınız var? 1 ile 3 arasında.",guests:(n:number)=>`👥 ${n}. odada kaç kişi kalacak?`,prefs:"✨ Özel bir tercihiniz var mı? Filtreleri seçin veya tercihsiz devam edin.",continue:"Önerileri göster",nonePref:"Tercihim yok",interpreting:"🤖 Tarihinizi anlıyorum…",searching:"🔎 Canlı müsaitlik ve en iyi direkt fiyatlar kontrol ediliyor…",choose:(g:number,p:number)=>`🛏️ ${g}. grup için oda seçin · ${p} kişi`,details:"Detayları gör",select:"Seç",close:"Kapat",amenities:"Olanaklar",total:"Genel toplam",perNight:"gecelik",saving:"Tasarruf",breakfast:"🥐 Kişi başı günlük 12 € karşılığında ev yapımı kahvaltı eklemek ister misiniz?",yes:"Evet, ekle",no:"Kahvaltısız",summary:"✅ Seçiminiz",newSearch:"Yeni arama",invalidDate:"Tarihi anlayamadım. Lütfen yeniden yazın.",invalidCheckout:"Çıkış tarihi giriş tarihinden sonra olmalıdır.",invalidRooms:"1, 2 veya 3 oda yazın.",invalidGuests:"1 ile 5 arasında kişi sayısı yazın.",send:"Gönder",placeholder:"Cevabınızı yazın…",filters:{economy:"Ekonomik",noStairs:"Merdivensiz",ground:"Zemin kat",first:"Birinci kat",kitchen:"Mutfak / mini mutfak",garden:"Bahçe / avlu",balcony:"Balkon",family:"Aile"}}
};

const nightsBetween=(a:string,b:string)=>Math.round((new Date(`${b}T12:00:00Z`).getTime()-new Date(`${a}T12:00:00Z`).getTime())/86400000);
const money=(n:number,l:Language)=>new Intl.NumberFormat({el:"el-GR",en:"en-GB",de:"de-DE",fr:"fr-FR",it:"it-IT",es:"es-ES",tr:"tr-TR"}[l],{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(n);
function score(o:Offer,filters:Filter[]){const text=`${o.name} ${o.category} ${o.floor} ${(o.features||[]).join(" ")}`.toLowerCase();return filters.reduce((s,f)=>s+({economy:/econom|οικονομ|économ|preisgünst|ekonom/.test(text),noStairs:/χωρίς σκάλ|no stairs|keine treppen|sans escaliers|senza scale|sin escaleras|merdivensiz/.test(text),ground:/ισόγει|ground floor|erdgeschoss|rez-de-chaussée|piano terra|planta baja|zemin kat/.test(text),first:/πρώτ|first floor|erster stock|premier étage|primo piano|primera planta|birinci kat/.test(text),kitchen:/kitchen|κουζ|küche|cuisine|cucina|mutfak/.test(text),garden:/garden|κήπ|αυλ|garten|jardin|giardino|patio|bahçe|avlu/.test(text),balcony:/balcon|μπαλκόν|balkon/.test(text),family:/family|οικογεν|familien|familial|familiare|familiar|aile/.test(text)}[f]?10:0),0)}

export function ConversationalRoomSalesEnhanced(){
 const [language,setLanguage]=useState<Language>("en"),t=T[language];
 const [step,setStep]=useState<Step>("language");
 const [messages,setMessages]=useState<Msg[]>([{role:"assistant",content:LANGUAGE_PROMPTS.en}]);
 const [input,setInput]=useState("");
 const [checkin,setCheckin]=useState(""),[checkout,setCheckout]=useState("");
 const [roomCount,setRoomCount]=useState(1),[groups,setGroups]=useState<number[]>([]),[guestIndex,setGuestIndex]=useState(0);
 const [filters,setFilters]=useState<Filter[]>([]),[offers,setOffers]=useState<Offer[][]>([]),[activeGroup,setActiveGroup]=useState(0),[index,setIndex]=useState(0),[choices,setChoices]=useState<Choice[]>([]);
 const [detail,setDetail]=useState<Offer|null>(null),[photo,setPhoto]=useState(0),[breakfast,setBreakfast]=useState<boolean|null>(null),[error,setError]=useState("");

 useEffect(()=>{const supported:Language[]=["el","en","de","fr","it","es","tr"];const requested=new URLSearchParams(window.location.search).get("lang")?.toLowerCase().split("-")[0]||"";const detected=supported.includes(requested as Language)?requested as Language:detectEntryLanguage();setLanguage(detected);const explicit=supported.includes(requested as Language);setStep(explicit?"checkin":"language");setMessages([{role:"assistant",content:explicit?T[detected].welcome:LANGUAGE_PROMPTS[detected]}])},[]);
 const nights=checkin&&checkout?nightsBetween(checkin,checkout):0;
 const recommendationRank:Record<NonNullable<Offer["recommendationRole"]>,number>={recommended:0,budget:1,comfort:2,alternative:3};
 const visible=useMemo(()=>[...(offers[activeGroup]||[])].filter(o=>!choices.some(c=>c.offer.roomId===o.roomId&&c.offer.unitId===o.unitId)).sort((a,b)=>(recommendationRank[a.recommendationRole||"alternative"]-recommendationRank[b.recommendationRole||"alternative"])||score(b,filters)-score(a,filters)||a.directTotal-b.directTotal),[offers,activeGroup,choices,filters]);
 const current=visible[index]||visible[0];
 const addA=(c:string)=>setMessages(m=>[...m,{role:"assistant",content:c}]);
 const addU=(c:string)=>setMessages(m=>[...m,{role:"user",content:c}]);

 function chooseLanguage(l:Language){setLanguage(l);setStep("checkin");setMessages([{role:"user",content:LANGS.find(x=>x[0]===l)?.[1]||l},{role:"assistant",content:T[l].welcome}])}

 async function interpretDate(value:string){
  const conversation=[...messages,{role:"user" as const,content:value}];
  const response=await fetch("/api/ai-assistant/smart",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:conversation,search:{checkin:checkin||undefined,checkout:checkout||undefined},language})});
  const payload=await response.json().catch(()=>null);
  if(!response.ok||!payload)throw new Error(payload?.error||"AI date interpretation failed");
  return payload as {answer?:string;search?:{checkin?:string;checkout?:string}};
 }

 async function submit(e:FormEvent){
  e.preventDefault();const v=input.trim();if(!v)return;setError("");addU(v);setInput("");
  if(step==="checkin"||step==="checkout"){
   const previousStep=step;setStep("interpreting");
   try{
    const result=await interpretDate(v);const nextCheckin=result.search?.checkin||checkin;const nextCheckout=result.search?.checkout||checkout;
    if(previousStep==="checkin"&&!nextCheckin){setStep("checkin");setError(t.invalidDate);return}
    if(previousStep==="checkout"&&!nextCheckout){setStep("checkout");setError(t.invalidDate);return}
    if(nextCheckin)setCheckin(nextCheckin);if(nextCheckout)setCheckout(nextCheckout);
    if(nextCheckin&&nextCheckout){if(nightsBetween(nextCheckin,nextCheckout)<1){setStep("checkout");setError(t.invalidCheckout);return}setStep("rooms");addA(t.rooms)}
    else{setStep("checkout");addA(result.answer||t.checkout)}
   }catch{setStep(previousStep);setError(t.invalidDate)}
   return;
  }
  if(step==="rooms"){const n=Number(v.match(/\d+/)?.[0]);if(!Number.isInteger(n)||n<1||n>3)return setError(t.invalidRooms);setRoomCount(n);setGroups([]);setGuestIndex(0);setStep("guests");addA(t.guests(1));return}
  if(step==="guests"){const n=Number(v.match(/\d+/)?.[0]);if(!Number.isInteger(n)||n<1||n>5)return setError(t.invalidGuests);const next=[...groups,n];setGroups(next);if(guestIndex+1<roomCount){setGuestIndex(i=>i+1);addA(t.guests(guestIndex+2))}else{setStep("preferences");addA(t.prefs)}}
 }

 async function search(){setStep("searching");addA(t.searching);try{const all:Offer[][]=[];const recommendationAnswers:string[]=[];for(const guests of groups){const r=await fetch("/api/ai-assistant/smart",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:[{role:"user",content:`Check live availability from ${checkin} to ${checkout} for ${guests} guests.`}],search:{checkin,checkout,guests},language})});const p=await r.json();all.push(Array.isArray(p?.offers)?p.offers:[]);if(typeof p?.answer==="string"&&p.answer.trim())recommendationAnswers.push(p.answer.trim())}setOffers(all);setActiveGroup(0);setIndex(0);setStep("selecting");if(recommendationAnswers[0])addA(recommendationAnswers[0]);addA(t.choose(1,groups[0]))}catch{setError("Live availability error");setStep("preferences")}}
 function select(o:Offer){const next=[...choices,{group:activeGroup+1,guests:groups[activeGroup],offer:o}];setChoices(next);setDetail(null);if(activeGroup+1<roomCount){setActiveGroup(g=>g+1);setIndex(0);addA(t.choose(activeGroup+2,groups[activeGroup+1]))}else{setStep("breakfast");addA(t.breakfast)}}
 function reset(){setStep("language");setMessages([{role:"assistant",content:LANGUAGE_PROMPTS[language]}]);setInput("");setCheckin("");setCheckout("");setRoomCount(1);setGroups([]);setGuestIndex(0);setFilters([]);setOffers([]);setChoices([]);setBreakfast(null);setError("")}
 const roomTotal=choices.reduce((s,c)=>s+c.offer.directTotal,0),breakfastTotal=breakfast?groups.reduce((s,n)=>s+n,0)*nights*12:0;

 return <main className="min-h-[100dvh] bg-[#f7f7f7] text-[#222222]">
  <header className="sticky top-0 z-30 border-b border-stone-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-3xl items-center gap-3 px-4 py-3.5"><div className="relative h-11 w-11 overflow-hidden rounded-full ring-1 ring-stone-200"><Image src="/images/welcome/voulamandis-welcome-hero.webp" alt="Voulamandis House" fill sizes="44px" className="object-cover"/></div><div className="min-w-0 flex-1"><h1 className="truncate text-[17px] font-semibold">Voulamandis House</h1><div className="mt-0.5 flex items-center gap-1.5 text-xs text-stone-500"><span className="h-2 w-2 rounded-full bg-emerald-500"/>AI Room Finder · Live availability</div></div>{step!=="language"?<button onClick={reset} className="rounded-full border border-stone-300 bg-white px-3 py-2 text-xs font-semibold shadow-sm">↻</button>:null}</div></header>
  <div className="mx-auto max-w-3xl px-3 pb-28 pt-5 sm:px-5"><div className="space-y-4">
   {messages.map((m,i)=><div key={i} className={`flex items-end gap-2 ${m.role==="user"?"justify-end":"justify-start"}`}>{m.role==="assistant"?<div className="relative mb-1 h-8 w-8 shrink-0 overflow-hidden rounded-full ring-1 ring-stone-200"><Image src="/images/welcome/voulamandis-welcome-hero.webp" alt="Voulamandis House" fill sizes="32px" className="object-cover"/></div>:null}<div className={`max-w-[82%] whitespace-pre-line rounded-[20px] px-4 py-3 text-[15px] leading-6 shadow-sm ${m.role==="user"?"rounded-br-md bg-[#222] text-white":"rounded-bl-md border border-stone-200 bg-white"}`}>{m.content}</div></div>)}
   {step==="interpreting"?<div className="ml-10 rounded-[20px] border border-stone-200 bg-white px-4 py-3 text-sm text-stone-600 shadow-sm">{t.interpreting}</div>:null}
   {step==="language"?<div className="ml-10 grid grid-cols-2 gap-2 sm:grid-cols-4">{LANGS.map(([l,label])=><button key={l} onClick={()=>chooseLanguage(l)} className="rounded-2xl border border-stone-300 bg-white px-3 py-3 text-sm font-semibold shadow-sm transition active:scale-[.98]">{label}</button>)}</div>:null}
   {step==="preferences"?<div className="ml-0 rounded-[22px] border border-stone-200 bg-white p-4 shadow-sm sm:ml-10"><div className="flex flex-wrap gap-2">{(Object.keys(t.filters) as Filter[]).map(f=><button key={f} onClick={()=>setFilters(v=>v.includes(f)?v.filter(x=>x!==f):[...v,f])} className={`rounded-full border px-3 py-2 text-xs font-semibold transition ${filters.includes(f)?"border-[#222] bg-[#222] text-white":"border-stone-300 bg-white text-stone-700"}`}>{t.filters[f]}</button>)}</div><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>{setFilters([]);void search()}} className="rounded-xl border border-stone-300 px-4 py-3 text-sm font-semibold">{t.nonePref}</button><button onClick={()=>void search()} className="rounded-xl bg-[#ff385c] px-4 py-3 text-sm font-semibold text-white">{t.continue}</button></div></div>:null}
   {step==="selecting"&&current?<><div className="ml-0 rounded-[18px] border border-[#ffd1da] bg-[#fff4f6] px-4 py-3 sm:ml-10"><p className="text-[11px] font-bold uppercase tracking-[.14em] text-[#c1354f]">{current.recommendationTitle || CURRENT_CHOICE_LABEL[language]}</p><p className="mt-1 text-[15px] font-semibold text-[#222]">{t.choose(activeGroup+1,groups[activeGroup])}</p></div><article className="mx-auto max-w-xl overflow-hidden rounded-[24px] border border-stone-200 bg-white shadow-[0_8px_30px_rgba(0,0,0,.08)]"><div className="relative h-52 sm:h-64"><Image src={current.image} alt={current.name} fill sizes="(max-width:640px) 100vw, 640px" className="object-cover"/><div className="absolute bottom-3 right-3 rounded-full bg-white/95 px-3 py-1.5 text-xs font-semibold shadow">{index+1}/{visible.length}</div></div><div className="p-4"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-semibold">{current.name}</h2><p className="mt-1 text-sm text-stone-500">{current.category}</p><div className="mt-3 flex flex-wrap gap-1.5">{[current.floor,...(current.features||[]).slice(0,3)].filter(Boolean).map(x=><span key={x} className="rounded-full bg-stone-100 px-2.5 py-1 text-[11px] font-medium text-stone-700">{x}</span>)}</div></div><div className="text-right"><p className="text-xs text-red-500 line-through">{money(current.originalTotal,language)}</p><p className="text-xl font-semibold text-emerald-700">{money(current.directTotal,language)}</p>{current.saving>0?<p className="mt-1 text-xs font-semibold text-emerald-700">{t.saving}: {money(current.saving,language)}</p>:null}</div></div><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>{setDetail(current);setPhoto(0)}} className="rounded-xl border border-stone-300 px-4 py-3 text-sm font-semibold">{t.details}</button><button onClick={()=>select(current)} className="rounded-xl bg-[#ff385c] px-4 py-3 text-sm font-semibold text-white">{t.select}</button></div></div></article>{visible.length>1?<div className="flex items-center justify-center gap-3"><button aria-label="Previous room" onClick={()=>setIndex(i=>(i-1+visible.length)%visible.length)} className="flex h-11 w-11 items-center justify-center rounded-full border border-stone-300 bg-white text-2xl shadow-sm">‹</button><div className="flex gap-1.5">{visible.map((_,i)=><span key={i} className={`h-1.5 rounded-full transition-all ${i===index?"w-5 bg-[#222]":"w-1.5 bg-stone-300"}`}/>)}</div><button aria-label="Next room" onClick={()=>setIndex(i=>(i+1)%visible.length)} className="flex h-11 w-11 items-center justify-center rounded-full border border-stone-300 bg-white text-2xl shadow-sm">›</button></div>:null}</>:null}
   {step==="breakfast"?<div className="overflow-hidden rounded-[24px] border border-stone-200 bg-white shadow-sm"><div className="relative h-40 sm:h-48"><Image src={BREAKFAST_IMAGE} alt="Homemade breakfast" fill sizes="(max-width:640px) 100vw, 640px" className="object-cover"/></div><div className="p-4"><p className="mb-4 text-[15px] leading-6">{t.breakfast}</p><div className="grid grid-cols-2 gap-2"><button onClick={()=>{setBreakfast(true);setStep("complete")}} className="rounded-xl bg-[#ff385c] px-4 py-3 font-semibold text-white">{t.yes}</button><button onClick={()=>{setBreakfast(false);setStep("complete")}} className="rounded-xl border border-stone-300 px-4 py-3 font-semibold">{t.no}</button></div></div></div>:null}
   {step==="complete"?<div className="rounded-[24px] border border-stone-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">{t.summary}</h2><button onClick={reset} className="text-xs font-semibold underline">{t.newSearch}</button></div>{choices.map(c=><div key={c.group} className="mt-4 flex items-center gap-3 border-b border-stone-100 pb-4"><div className="relative h-16 w-20 shrink-0 overflow-hidden rounded-xl"><Image src={c.offer.image} alt={c.offer.name} fill sizes="80px" className="object-cover"/></div><div className="min-w-0 flex-1"><p className="font-semibold">{c.offer.name}</p><p className="text-xs text-stone-500">{c.offer.category}</p><p className="mt-1 text-sm text-stone-500">{nights} × {money(c.offer.directTotal/Math.max(1,nights),language)} = {money(c.offer.directTotal,language)}</p></div><div className="text-right"><span className="block text-xs text-red-500 line-through">{money(c.offer.originalTotal,language)}</span><strong className="text-emerald-700">{money(c.offer.directTotal,language)}</strong></div></div>)}{breakfast?<div className="mt-4 flex items-center gap-3 border-b border-stone-100 pb-4"><div className="relative h-16 w-20 shrink-0 overflow-hidden rounded-xl"><Image src={BREAKFAST_IMAGE} alt="Homemade breakfast" fill sizes="80px" className="object-cover"/></div><div className="flex-1"><p className="font-semibold">🥐 {t.breakfast}</p><p className="text-sm text-stone-500">{groups.reduce((s,n)=>s+n,0)} × {nights} × 12€</p></div><strong>{money(breakfastTotal,language)}</strong></div>:null}<div className="mt-5 flex justify-between rounded-2xl bg-stone-100 p-4 text-xl"><span>{t.total}</span><strong>{money(roomTotal+breakfastTotal,language)}</strong></div></div>:null}
  </div>
  {!['language','preferences','interpreting','searching','selecting','breakfast','complete'].includes(step)?<form onSubmit={submit} className="fixed inset-x-0 bottom-0 z-20 border-t border-stone-200 bg-white/95 p-3 backdrop-blur"><div className="mx-auto flex max-w-3xl gap-2"><input value={input} onChange={e=>setInput(e.target.value)} placeholder={t.placeholder} className="min-w-0 flex-1 rounded-full border border-stone-300 bg-white px-5 py-3.5 outline-none focus:border-[#222]"/><button className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-[#ff385c] text-lg font-bold text-white shadow">↑</button></div></form>:null}
  {error?<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>:null}</div>
  {detail?<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/55 p-0 sm:items-center sm:p-5" onClick={()=>setDetail(null)}><div className="flex h-[94dvh] w-full max-w-2xl flex-col overflow-hidden rounded-t-[28px] bg-white sm:h-auto sm:max-h-[88dvh] sm:rounded-[28px]" onClick={e=>e.stopPropagation()}><div className="relative h-[38dvh] shrink-0 sm:h-72"><Image src={(detail.gallery?.length?detail.gallery:[detail.image])[photo]||detail.image} alt={detail.name} fill sizes="(max-width:640px) 100vw, 720px" className="object-cover"/><button onClick={()=>setDetail(null)} className="absolute right-3 top-3 flex h-10 w-10 items-center justify-center rounded-full bg-white text-xl shadow">×</button>{(detail.gallery?.length||0)>1?<><button onClick={()=>setPhoto(i=>(i-1+(detail.gallery?.length||1))%(detail.gallery?.length||1))} className="absolute left-3 top-1/2 flex h-10 w-10 -translate-y-1/2 items-center justify-center rounded-full bg-white text-2xl shadow">‹</button><button onClick={()=>setPhoto(i=>(i+1)%(detail.gallery?.length||1))} className="absolute right-3 top-1/2 flex h-10 w-10 -translate-y-1/2 items-center justify-center rounded-full bg-white text-2xl shadow">›</button></>:null}<div className="absolute bottom-3 right-3 rounded-full bg-white/95 px-3 py-1.5 text-xs font-semibold shadow">{photo+1}/{Math.max(1,detail.gallery?.length||1)}</div></div><div className="flex min-h-0 flex-1 flex-col p-4 sm:p-5"><div><h2 className="text-2xl font-semibold">{detail.name}</h2><p className="mt-1 text-sm text-stone-500">{detail.category}</p><div className="mt-3 flex flex-wrap gap-1.5">{[detail.floor,...(detail.features||[])].filter(Boolean).slice(0,5).map(x=><span key={x} className="rounded-full bg-stone-100 px-2.5 py-1 text-[11px] font-medium">{x}</span>)}</div></div><div className="mt-auto pt-4"><div className="rounded-2xl bg-stone-100 p-4"><div className="flex justify-between text-sm"><span>{nights} × {money(detail.directTotal/Math.max(1,nights),language)} {t.perNight}</span><strong className="text-emerald-700">{money(detail.directTotal,language)}</strong></div>{detail.originalTotal>detail.directTotal?<div className="mt-2 flex justify-between text-sm text-red-500"><span>Original</span><span className="line-through">{money(detail.originalTotal,language)}</span></div>:null}{detail.saving>0?<div className="mt-2 flex justify-between text-sm text-[#63752d]"><span>{t.saving}</span><strong>{money(detail.saving,language)}</strong></div>:null}</div><button onClick={()=>select(detail)} className="mt-3 w-full rounded-xl bg-[#ff385c] px-5 py-3.5 font-semibold text-white">{t.select}</button></div></div></div></div>:null}
 </main>
}
