"use client";

import Image from "next/image";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { RoomCarousel } from "@/components/ui/RoomCarousel";

type Language = "el" | "en" | "fr" | "de" | "it" | "es" | "tr";
type Offer = {
  roomId: string;
  unitId: string;
  name: string;
  category: string;
  floor: string;
  maxGuests: number;
  features: string[];
  image: string;
  nights: number;
  originalTotal: number;
  directTotal: number;
  saving: number;
  preview?: boolean;
};
type KnowledgeCard = { id: string; kind: string; title: string; summary: string; facts?: string[]; image?: string; url?: string };
type SearchState = { checkin?: string; checkout?: string; guests?: number };
type Message = { role: "user" | "assistant"; content: string; offers?: Offer[]; knowledge?: KnowledgeCard[] };

const COPY: Record<Language, any> = {
  el: { title: "AI concierge Χίου", badge: "Live τιμές · απευθείας", welcome: "Είμαι ο ψηφιακός concierge του Voulamandis House. Ρωτήστε με για δωμάτια, παροχές, πραγματικές τιμές και διαθεσιμότητα ή για παραλίες, χωριά, μουσεία και οικογενειακές διακοπές στη Χίο.", quick: ["Πρότεινέ μου δωμάτιο χωρίς σκάλες", "Τι μπορούμε να κάνουμε με παιδιά στη Χίο;", "Ποιες παραλίες είναι κοντά;", "Θέλω να ελέγξω διαθεσιμότητα"], placeholder: "Ρωτήστε για διαμονή ή για τη Χίο…", send: "Αποστολή", loading: "Αναζητώ τις καλύτερες επιβεβαιωμένες επιλογές…", live: "Live τιμή", photos: "Φωτογραφίες", viewRoom: "Δείτε το δωμάτιο", gallery: "Gallery & παροχές", upTo: "έως", people: "άτομα", more: "Δείτε περισσότερα", close: "Κλείσιμο", direct: "Τιμή απευθείας", interested: "Ενδιαφέρομαι", requestTitle: "Αίτημα προς reception", directBooking: "Τιμή απευθείας κράτησης", name: "Ονοματεπώνυμο", contact: "Τηλέφωνο ή email", message: "Μήνυμα", optional: "προαιρετικό", submitRequest: "Στείλε αίτημα στη reception", sending: "Αποστολή…", noAuto: "Δεν ολοκληρώνεται αυτόματα κράτηση ή πληρωμή.", confirmedOnly: "Οι τιμές και η διαθεσιμότητα ελέγχονται ζωντανά. Η κράτηση επιβεβαιώνεται από τη reception.", successTitle: "Το αίτημα καταχωρήθηκε.", success: "Το αίτημά σας στάλθηκε στη reception. Θα επικοινωνήσουμε μαζί σας για επιβεβαίωση.", error: "Κάτι πήγε στραβά.", nights: ["νύχτα", "νύχτες"] },
  en: { title: "Chios AI concierge", badge: "Live rates · direct", welcome: "I am the digital concierge for Voulamandis House. Ask me about rooms, amenities, live rates and availability, or about beaches, villages, museums and family holidays in Chios.", quick: ["Recommend a room without stairs", "What can we do with children in Chios?", "Which beaches are nearby?", "Check live availability"], placeholder: "Ask about your stay or Chios…", send: "Send", loading: "Finding the best verified options…", live: "Live rate", photos: "Photos", viewRoom: "View room", gallery: "Gallery & amenities", upTo: "up to", people: "guests", more: "View more", close: "Close", direct: "Direct rate", interested: "I'm interested", requestTitle: "Request to reception", directBooking: "Direct booking rate", name: "Full name", contact: "Phone or email", message: "Message", optional: "optional", submitRequest: "Send request to reception", sending: "Sending…", noAuto: "No booking or payment is completed automatically.", confirmedOnly: "Rates and availability are checked live. Bookings are confirmed by reception.", successTitle: "Request submitted.", success: "Your request was sent to reception. We will contact you to confirm.", error: "Something went wrong.", nights: ["night", "nights"] },
  fr: { title: "Concierge IA de Chios", badge: "Tarifs en direct · direct", welcome: "Je suis le concierge numérique de Voulamandis House. Demandez-moi des informations sur les chambres, les équipements, les tarifs et disponibilités en direct, ou sur les plages, villages, musées et vacances en famille à Chios.", quick: ["Recommandez une chambre sans escaliers", "Que faire avec des enfants à Chios ?", "Quelles plages sont proches ?", "Vérifier les disponibilités"], placeholder: "Posez une question sur votre séjour ou Chios…", send: "Envoyer", loading: "Je recherche les meilleures options vérifiées…", live: "Tarif en direct", photos: "Photos", viewRoom: "Voir la chambre", gallery: "Galerie et équipements", upTo: "jusqu’à", people: "personnes", more: "Voir plus", close: "Fermer", direct: "Tarif direct", interested: "Je suis intéressé(e)", requestTitle: "Demande à la réception", directBooking: "Tarif de réservation directe", name: "Nom complet", contact: "Téléphone ou e-mail", message: "Message", optional: "facultatif", submitRequest: "Envoyer la demande", sending: "Envoi…", noAuto: "Aucune réservation ni aucun paiement n’est effectué automatiquement.", confirmedOnly: "Les tarifs et disponibilités sont vérifiés en direct. La réservation est confirmée par la réception.", successTitle: "Demande enregistrée.", success: "Votre demande a été envoyée à la réception. Nous vous contacterons pour confirmation.", error: "Une erreur s’est produite.", nights: ["nuit", "nuits"] },
  de: { title: "Chios KI-Concierge", badge: "Live-Preise · direkt", welcome: "Ich bin der digitale Concierge von Voulamandis House. Fragen Sie mich nach Zimmern, Ausstattung, Live-Preisen und Verfügbarkeit oder nach Stränden, Dörfern, Museen und Familienurlaub auf Chios.", quick: ["Empfehlen Sie ein Zimmer ohne Treppen", "Was können wir mit Kindern auf Chios machen?", "Welche Strände sind in der Nähe?", "Live-Verfügbarkeit prüfen"], placeholder: "Fragen Sie zu Ihrem Aufenthalt oder Chios…", send: "Senden", loading: "Ich suche die besten bestätigten Optionen…", live: "Live-Preis", photos: "Fotos", viewRoom: "Zimmer ansehen", gallery: "Galerie & Ausstattung", upTo: "bis zu", people: "Gäste", more: "Mehr erfahren", close: "Schließen", direct: "Direktpreis", interested: "Ich bin interessiert", requestTitle: "Anfrage an die Rezeption", directBooking: "Direktbuchungspreis", name: "Vollständiger Name", contact: "Telefon oder E-Mail", message: "Nachricht", optional: "optional", submitRequest: "Anfrage senden", sending: "Wird gesendet…", noAuto: "Es wird nicht automatisch gebucht oder bezahlt.", confirmedOnly: "Preise und Verfügbarkeit werden live geprüft. Die Buchung wird von der Rezeption bestätigt.", successTitle: "Anfrage gespeichert.", success: "Ihre Anfrage wurde an die Rezeption gesendet. Wir kontaktieren Sie zur Bestätigung.", error: "Etwas ist schiefgelaufen.", nights: ["Nacht", "Nächte"] },
  it: { title: "Concierge AI di Chios", badge: "Tariffe live · dirette", welcome: "Sono il concierge digitale di Voulamandis House. Chiedimi informazioni su camere, servizi, prezzi e disponibilità in tempo reale oppure su spiagge, villaggi, musei e vacanze in famiglia a Chios.", quick: ["Consigliami una camera senza scale", "Cosa possiamo fare con i bambini a Chios?", "Quali spiagge sono vicine?", "Controlla la disponibilità"], placeholder: "Chiedi del soggiorno o di Chios…", send: "Invia", loading: "Cerco le migliori opzioni verificate…", live: "Tariffa live", photos: "Foto", viewRoom: "Vedi camera", gallery: "Galleria e servizi", upTo: "fino a", people: "ospiti", more: "Scopri di più", close: "Chiudi", direct: "Tariffa diretta", interested: "Sono interessato", requestTitle: "Richiesta alla reception", directBooking: "Tariffa di prenotazione diretta", name: "Nome e cognome", contact: "Telefono o e-mail", message: "Messaggio", optional: "facoltativo", submitRequest: "Invia richiesta", sending: "Invio…", noAuto: "La prenotazione o il pagamento non vengono completati automaticamente.", confirmedOnly: "Prezzi e disponibilità sono verificati in tempo reale. La prenotazione è confermata dalla reception.", successTitle: "Richiesta registrata.", success: "La richiesta è stata inviata alla reception. Ti contatteremo per la conferma.", error: "Si è verificato un errore.", nights: ["notte", "notti"] },
  es: { title: "Conserje IA de Quíos", badge: "Tarifas en directo · directas", welcome: "Soy el conserje digital de Voulamandis House. Pregúntame sobre habitaciones, servicios, precios y disponibilidad en directo, o sobre playas, pueblos, museos y vacaciones familiares en Quíos.", quick: ["Recomiéndame una habitación sin escaleras", "¿Qué podemos hacer con niños en Quíos?", "¿Qué playas están cerca?", "Comprobar disponibilidad"], placeholder: "Pregunta sobre tu estancia o Quíos…", send: "Enviar", loading: "Buscando las mejores opciones verificadas…", live: "Tarifa en directo", photos: "Fotos", viewRoom: "Ver habitación", gallery: "Galería y servicios", upTo: "hasta", people: "huéspedes", more: "Ver más", close: "Cerrar", direct: "Tarifa directa", interested: "Me interesa", requestTitle: "Solicitud a recepción", directBooking: "Tarifa de reserva directa", name: "Nombre completo", contact: "Teléfono o correo", message: "Mensaje", optional: "opcional", submitRequest: "Enviar solicitud", sending: "Enviando…", noAuto: "La reserva o el pago no se completan automáticamente.", confirmedOnly: "Los precios y la disponibilidad se comprueban en directo. La reserva la confirma recepción.", successTitle: "Solicitud registrada.", success: "Tu solicitud se envió a recepción. Nos pondremos en contacto para confirmar.", error: "Algo salió mal.", nights: ["noche", "noches"] },
  tr: { title: "Sakız AI concierge", badge: "Canlı fiyatlar · direkt", welcome: "Voulamandis House dijital concierge hizmetiyim. Odalar, olanaklar, canlı fiyatlar ve müsaitlik ya da Sakız Adası'ndaki plajlar, köyler, müzeler ve aile tatilleri hakkında sorabilirsiniz.", quick: ["Merdivensiz bir oda öner", "Sakız'da çocuklarla ne yapabiliriz?", "Hangi plajlar yakın?", "Canlı müsaitliği kontrol et"], placeholder: "Konaklama veya Sakız hakkında sorun…", send: "Gönder", loading: "En iyi doğrulanmış seçenekleri arıyorum…", live: "Canlı fiyat", photos: "Fotoğraflar", viewRoom: "Odayı gör", gallery: "Galeri ve olanaklar", upTo: "en fazla", people: "kişi", more: "Daha fazla", close: "Kapat", direct: "Direkt fiyat", interested: "İlgileniyorum", requestTitle: "Resepsiyona talep", directBooking: "Direkt rezervasyon fiyatı", name: "Ad soyad", contact: "Telefon veya e-posta", message: "Mesaj", optional: "isteğe bağlı", submitRequest: "Talebi gönder", sending: "Gönderiliyor…", noAuto: "Rezervasyon veya ödeme otomatik olarak tamamlanmaz.", confirmedOnly: "Fiyatlar ve müsaitlik canlı kontrol edilir. Rezervasyon resepsiyon tarafından onaylanır.", successTitle: "Talep kaydedildi.", success: "Talebiniz resepsiyona gönderildi. Onay için sizinle iletişime geçeceğiz.", error: "Bir hata oluştu.", nights: ["gece", "gece"] },
};

const LOCALES: Record<Language, string> = { el: "el-GR", en: "en-GB", fr: "fr-FR", de: "de-DE", it: "it-IT", es: "es-ES", tr: "tr-TR" };
const ROOM_GALLERIES: Record<string, string[]> = {
  "267788:1": ["/images/rooms/DSC07776-2-e1675109942622.webp", "/images/rooms/DSC07769-1.webp"],
  "268803:1": ["/images/rooms/DSC07803-1.webp", "/images/rooms/DSC07839.webp"],
  "267788:2": ["/images/rooms/DSC07867-1.webp", "/images/rooms/DSC07860-1.webp"],
  "267788:3": ["/images/rooms/received_1748354861920234.webp", "/images/rooms/received_1748358935253160.webp"],
  "626129:1": ["/images/rooms/voulamandis-house-rooms.webp", "/images/rooms/chios-hotels-triple-rooms_1646x1080.webp"],
  "268803:2": ["/images/rooms/received_1753964631359257.webp", "/images/rooms/received_1753964581359262.webp"],
  "626129:2": ["/images/rooms/double-triple-room.jpg", "/images/rooms/view-double-room-chios-hotels.webp"],
  "265595:1": ["/images/rooms/chios-apartments-voulamandis.webp", "/images/rooms/chios-hotels-family-apartments.webp"],
  "265595:2": ["/images/rooms/chios-apartments-voulamandis.webp", "/images/rooms/family-room.webp"],
  "265595:3": ["/images/rooms/DSC07899.webp", "/images/rooms/DSC07909.webp"],
};

function detectLanguage(): Language {
  if (typeof navigator === "undefined") return "el";
  const code = navigator.language.slice(0, 2) as Language;
  return code in COPY ? code : "en";
}

export function GuestAssistantMultilingual() {
  const [language, setLanguage] = useState<Language>("el");
  const t = COPY[language];
  const [messages, setMessages] = useState<Message[]>([]);
  const [search, setSearch] = useState<SearchState>({});
  const [selectedRoom, setSelectedRoom] = useState<number | undefined>();
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [detailsOffer, setDetailsOffer] = useState<Offer | null>(null);
  const [selectedOffer, setSelectedOffer] = useState<Offer | null>(null);
  const [requestName, setRequestName] = useState("");
  const [requestContact, setRequestContact] = useState("");
  const [requestMessage, setRequestMessage] = useState("");
  const [requestSending, setRequestSending] = useState(false);
  const [requestSuccess, setRequestSuccess] = useState("");
  const inputRef = useRef<HTMLInputElement>(null);
  const endRef = useRef<HTMLDivElement>(null);

  useEffect(() => { const detected = detectLanguage(); setLanguage(detected); setMessages([{ role: "assistant", content: COPY[detected].welcome }]); }, []);
  useEffect(() => { if (messages.length === 1 && messages[0].role === "assistant") setMessages([{ role: "assistant", content: t.welcome }]); }, [language]);
  useEffect(() => { document.body.style.overflow = detailsOffer || selectedOffer ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [detailsOffer, selectedOffer]);

  const gallery = useMemo(() => detailsOffer ? Array.from(new Set([detailsOffer.image, ...(ROOM_GALLERIES[`${detailsOffer.roomId}:${detailsOffer.unitId}`] || [])])) : [], [detailsOffer]);
  const euro = (value: number) => new Intl.NumberFormat(LOCALES[language], { style: "currency", currency: "EUR", maximumFractionDigits: 2 }).format(value);
  const date = (value?: string) => value ? new Intl.DateTimeFormat(LOCALES[language], { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${value}T12:00:00`)) : "";

  async function sendMessage(text: string) {
    const trimmed = text.trim(); if (!trimmed || loading) return;
    const next = [...messages, { role: "user" as const, content: trimmed }]; setMessages(next); setInput(""); setError(""); setLoading(true);
    try {
      const response = await fetch("/api/ai-assistant/smart", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ messages: next.map(({ role, content }) => ({ role, content })), search, language, selectedRoom }) });
      const data = await response.json(); if (!response.ok || !data?.answer) throw new Error(data?.error || t.error);
      if (data.search) setSearch(data.search); if (data.language && data.language in COPY) setLanguage(data.language); if (typeof data.selectedRoom === "number") setSelectedRoom(data.selectedRoom);
      setMessages((current) => [...current, { role: "assistant", content: data.answer, offers: Array.isArray(data.offers) ? data.offers : [], knowledge: Array.isArray(data.knowledge) ? data.knowledge.slice(0, 4) : [] }]);
      requestAnimationFrame(() => endRef.current?.scrollIntoView({ behavior: "smooth", block: "end" }));
    } catch (e) { setError(e instanceof Error ? e.message : t.error); } finally { setLoading(false); inputRef.current?.focus(); }
  }

  async function submitRequest(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!selectedOffer || !search.checkin || !search.checkout || !search.guests) { setError(t.error); return; }
    setRequestSending(true); setError("");
    try {
      const response = await fetch("/api/ai-assistant/request", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: requestName, contact: requestContact, message: requestMessage, checkin: search.checkin, checkout: search.checkout, guests: search.guests, roomId: selectedOffer.roomId, unitId: selectedOffer.unitId, roomName: selectedOffer.name, originalTotal: selectedOffer.originalTotal, directTotal: selectedOffer.directTotal, conversation: messages.slice(-18).map(({ role, content }) => ({ role, content })) }) });
      const data = await response.json(); if (!response.ok || !data?.ok) throw new Error(data?.error || t.error); setRequestSuccess(t.success);
    } catch (e) { setError(e instanceof Error ? e.message : t.error); } finally { setRequestSending(false); }
  }

  return <main className="min-h-[100dvh] bg-[#fbfaf7] text-stone-950">
    <header className="border-b border-stone-200 bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between gap-3 px-4 py-4 sm:px-8"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-emerald-700">Voulamandis House</p><h1 className="mt-1 text-xl font-semibold sm:text-2xl">{t.title}</h1></div><div className="flex items-center gap-2"><select aria-label="Language" value={language} onChange={(e) => setLanguage(e.target.value as Language)} className="rounded-xl border border-stone-300 bg-white px-2 py-2 text-sm"><option value="el">EL</option><option value="en">EN</option><option value="fr">FR</option><option value="de">DE</option><option value="it">IT</option><option value="es">ES</option><option value="tr">TR</option></select><span className="hidden rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-800 sm:block">{t.badge}</span></div></div></header>
    <section className="mx-auto flex min-h-[calc(100dvh-82px)] max-w-5xl flex-col px-4 sm:px-8"><div className="flex-1 space-y-6 py-8" aria-live="polite">
      {messages.map((m, i) => <div key={`${m.role}-${i}`}><div className={`flex ${m.role === "user" ? "justify-end" : "justify-start"}`}><div className={`max-w-[92%] whitespace-pre-line rounded-[1.4rem] px-4 py-3 text-[15px] leading-6 sm:max-w-[75%] ${m.role === "user" ? "rounded-br-md bg-stone-950 text-white" : "rounded-bl-md border border-stone-200 bg-white text-stone-800 shadow-sm"}`}>{m.content}</div></div>
        {i === 0 && messages.length === 1 ? <div className="mt-4 flex flex-wrap gap-2">{t.quick.map((q: string) => <button key={q} onClick={() => void sendMessage(q)} className="rounded-full border border-stone-300 bg-white px-3 py-2 text-xs font-medium text-stone-700 shadow-sm">{q}</button>)}</div> : null}
        {m.offers?.length ? <div className="mt-5 space-y-3">{m.offers.map((o) => <button key={`${o.roomId}:${o.unitId}`} onClick={() => setDetailsOffer(o)} className="flex w-full overflow-hidden rounded-2xl border border-stone-200 bg-white text-left shadow-sm"><div className="relative w-28 shrink-0 bg-stone-100 sm:w-40"><Image src={o.image} alt={o.name} fill sizes="160px" className="object-cover" /></div><div className="flex min-w-0 flex-1 items-center justify-between gap-3 p-4"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold sm:text-lg">{o.name}</h2><span className="rounded-full bg-emerald-100 px-2 py-0.5 text-[11px] font-semibold text-emerald-800">{o.preview ? t.photos : t.live}</span></div><p className="mt-1 text-xs text-stone-500">{o.category} · {t.upTo} {o.maxGuests} {t.people}</p></div><div className="shrink-0 text-right">{o.preview ? <><p className="text-sm font-semibold text-emerald-800">{t.viewRoom}</p><p className="text-xs text-stone-500">{t.gallery}</p></> : <><p className="text-xs text-stone-400 line-through">{euro(o.originalTotal)}</p><p className="text-xl font-bold text-emerald-800">{euro(o.directTotal)}</p><p className="text-xs text-emerald-700">{o.nights} {t.nights[o.nights === 1 ? 0 : 1]}</p></>}</div></div></button>)}</div> : null}
        {m.knowledge?.length ? <div className="mt-5 grid gap-3 sm:grid-cols-2">{m.knowledge.map((k) => <article key={k.id} className="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm">{k.image ? <div className="relative aspect-[16/8]"><Image src={k.image} alt={k.title} fill sizes="50vw" className="object-cover" /></div> : null}<div className="p-4"><p className="text-[11px] font-semibold uppercase tracking-wide text-emerald-700">{k.kind}</p><h2 className="mt-1 text-lg font-semibold">{k.title}</h2><p className="mt-2 text-sm leading-6 text-stone-600">{k.summary}</p>{k.url ? <a href={k.url} className="mt-4 inline-flex rounded-xl bg-stone-950 px-4 py-2.5 text-sm font-semibold text-white">{t.more}</a> : null}</div></article>)}</div> : null}
      </div>)}
      {loading ? <div className="rounded-2xl border border-stone-200 bg-white px-4 py-3 text-sm text-stone-600 shadow-sm">{t.loading}</div> : null}<div ref={endRef} />
    </div><div className="sticky bottom-0 border-t border-stone-200 bg-[#fbfaf7]/95 py-4 backdrop-blur">{error ? <p className="mb-3 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p> : null}<form onSubmit={(e) => { e.preventDefault(); void sendMessage(input); }} className="flex gap-2 rounded-2xl border border-stone-300 bg-white p-2 shadow-lg"><input ref={inputRef} value={input} onChange={(e) => setInput(e.target.value)} placeholder={t.placeholder} className="min-w-0 flex-1 bg-transparent px-3 py-2.5 outline-none" /><button disabled={loading || !input.trim()} className="rounded-xl bg-emerald-700 px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">{t.send}</button></form><p className="mt-2 text-center text-xs text-stone-400">{t.confirmedOnly}</p></div></section>
    {detailsOffer ? <div className="fixed inset-0 z-40 flex items-end justify-center bg-stone-950/60 sm:items-center sm:p-5" role="dialog" aria-modal="true"><div className="relative flex max-h-[96dvh] w-full max-w-3xl flex-col overflow-hidden rounded-t-[2rem] bg-white shadow-2xl sm:rounded-[2rem]"><div className="relative"><RoomCarousel images={gallery} roomName={detailsOffer.name} /><button onClick={() => setDetailsOffer(null)} className="absolute right-4 top-4 z-10 grid h-12 w-12 place-items-center rounded-full bg-white text-xl shadow" aria-label={t.close}>✕</button></div><div className="overflow-y-auto p-5 pb-28"><h2 className="text-2xl font-semibold">{detailsOffer.name}</h2><p className="mt-1 text-sm text-stone-600">{detailsOffer.category} · {t.upTo} {detailsOffer.maxGuests} {t.people}</p><div className="mt-4 flex flex-wrap gap-2">{[detailsOffer.floor, ...detailsOffer.features].map((f) => <span key={f} className="rounded-full border border-stone-200 bg-stone-50 px-3 py-1.5 text-xs">{f}</span>)}</div>{!detailsOffer.preview && search.checkin && search.checkout ? <div className="mt-5 rounded-2xl bg-emerald-50 p-4 text-sm"><strong>{date(search.checkin)} → {date(search.checkout)}</strong><br />{search.guests} {t.people}</div> : null}</div><div className="absolute inset-x-0 bottom-0 flex items-center justify-between border-t bg-white/95 p-4"><div>{!detailsOffer.preview ? <p className="text-xl font-bold text-emerald-800">{euro(detailsOffer.directTotal)}</p> : <p className="font-semibold">{t.viewRoom}</p>}</div>{detailsOffer.preview ? <button onClick={() => setDetailsOffer(null)} className="rounded-2xl bg-stone-950 px-5 py-3 text-sm font-semibold text-white">{t.close}</button> : <button onClick={() => { setDetailsOffer(null); setSelectedOffer(detailsOffer); setRequestSuccess(""); }} className="rounded-2xl bg-stone-950 px-5 py-3 text-sm font-semibold text-white">{t.interested}</button>}</div></div></div> : null}
    {selectedOffer ? <div className="fixed inset-0 z-50 flex items-end justify-center bg-stone-950/55 sm:items-center sm:p-5" role="dialog" aria-modal="true"><div className="max-h-[92dvh] w-full max-w-lg overflow-y-auto rounded-t-[2rem] bg-white p-5 shadow-2xl sm:rounded-[2rem]"><div className="flex justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wide text-emerald-700">{t.requestTitle}</p><h2 className="mt-1 text-2xl font-semibold">{selectedOffer.name}</h2></div><button onClick={() => setSelectedOffer(null)} className="rounded-full border px-3 py-2">✕</button></div><div className="mt-4 rounded-2xl bg-emerald-50 p-4"><p className="text-sm text-stone-500">{t.directBooking}</p><p className="mt-1 text-2xl font-bold text-emerald-800">{euro(selectedOffer.directTotal)}</p></div>{requestSuccess ? <div className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><p className="font-semibold">{t.successTitle}</p><p className="mt-1 text-sm">{requestSuccess}</p></div> : <form onSubmit={submitRequest} className="mt-5 space-y-4"><label className="block text-sm font-medium">{t.name}<input required value={requestName} onChange={(e) => setRequestName(e.target.value)} className="mt-1.5 w-full rounded-2xl border px-4 py-3" /></label><label className="block text-sm font-medium">{t.contact}<input required value={requestContact} onChange={(e) => setRequestContact(e.target.value)} className="mt-1.5 w-full rounded-2xl border px-4 py-3" /></label><label className="block text-sm font-medium">{t.message} <span className="font-normal text-stone-400">({t.optional})</span><textarea rows={3} value={requestMessage} onChange={(e) => setRequestMessage(e.target.value)} className="mt-1.5 w-full rounded-2xl border px-4 py-3" /></label><button disabled={requestSending} className="w-full rounded-2xl bg-stone-950 px-5 py-3.5 text-sm font-semibold text-white disabled:opacity-50">{requestSending ? t.sending : t.submitRequest}</button><p className="text-center text-xs text-stone-500">{t.noAuto}</p></form>}</div></div> : null}
  </main>;
}
