"use client";
import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import { ROOM_FINDER_COPY, ROOM_FINDER_LANGUAGES, type RoomFinderFilter, type RoomFinderLanguage } from "./room-finder-copy";
import { ChatMessage, IconReplies } from "./room-finder-chat-ui";
import { RoomCarousel, type RoomOffer } from "./room-finder-carousel";
import { SelectedRoomCard } from "./room-finder-selected-card";
import { useRoomFinder } from "./use-room-finder";

const FILTERS:RoomFinderFilter[]=["economy","noStairs","ground","first","kitchen","garden","balcony","family"];
const WHATSAPP_NUMBER="306944474226";
const BREAKFAST_IMAGE="/images/welcome/voulamandis-breakfast.jpg";
const wait=(ms:number)=>new Promise<void>(resolve=>window.setTimeout(resolve,ms));
function detectLanguage():RoomFinderLanguage{if(typeof window==="undefined")return"en";const supported=ROOM_FINDER_LANGUAGES.map(([v])=>v);const q=new URLSearchParams(window.location.search).get("lang")?.toLowerCase().split("-")[0];const p=window.location.pathname.split("/").filter(Boolean)[0]?.toLowerCase();const d=document.documentElement.lang?.toLowerCase().split("-")[0];return([q,p,d].find(v=>supported.includes(v as RoomFinderLanguage))as RoomFinderLanguage)||"en";}
function money(value:number,language:RoomFinderLanguage){const locale=({el:"el-GR",en:"en-GB",de:"de-DE",fr:"fr-FR",it:"it-IT",es:"es-ES",tr:"tr-TR"}as const)[language];return new Intl.NumberFormat(locale,{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(value);}

export function RoomFinderProduction(){
 const [language,setLanguage]=useState<RoomFinderLanguage>("en");
 const finder=useRoomFinder(language); const copy=ROOM_FINDER_COPY[language];
 const [detail,setDetail]=useState<RoomOffer|null>(null); const [handoff,setHandoff]=useState("");
 const [contact,setContact]=useState({name:"",phone:"",email:""}); const [sendStatus,setSendStatus]=useState<"idle"|"sending"|"sent"|"error">("idle");
 const feedRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{const detected=detectLanguage();if(detected!==language)setLanguage(detected);},[]);
 useEffect(()=>{finder.reset();setDetail(null);setHandoff("");setContact({name:"",phone:"",email:""});setSendStatus("idle");},[language]);
 useEffect(()=>{const frame=requestAnimationFrame(()=>feedRef.current?.scrollTo({top:feedRef.current.scrollHeight,behavior:"smooth"}));return()=>cancelAnimationFrame(frame);},[finder.messages,finder.step,finder.typing,finder.feedback,finder.choices,handoff,sendStatus]);
 function changeLanguage(next:RoomFinderLanguage){const url=new URL(window.location.href);url.searchParams.set("lang",next);history.replaceState(history.state,"",url);setLanguage(next);}
 function openWhatsApp(text:string){window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(text)}`,"_blank","noopener,noreferrer");}
 function whatsappContext(base:string){const offer=finder.visibleOffers[0]||finder.choices.at(-1)?.offer;const room=offer?`\n${offer.name} · ${money(offer.directTotal,language)}`:"";return`${base}\n${finder.checkin} → ${finder.checkout}\n${copy.guestLabel(finder.guestTotal)}${room}`;}
 async function whatsappTurn(kind:"info"|"other"){const label=kind==="info"?copy.info:copy.other;if(!await finder.beginUserTurn(label,"normal","❤️"))return;setHandoff(kind==="info"?copy.whatsappInfoReply:copy.whatsappOtherReply);await wait(300);openWhatsApp(whatsappContext(label));finder.endUserTurn();}
 async function sendRequest(){if(!contact.name.trim()||(!contact.phone.trim()&&!contact.email.trim()))return;setSendStatus("sending");const breakfastTotal=finder.breakfast?finder.guestTotal*finder.nights*12:0;const roomTotal=finder.choices.reduce((s,c)=>s+c.offer.directTotal,0);const summary=[`${finder.checkin} → ${finder.checkout}`,copy.guestLabel(finder.guestTotal),...finder.choices.map(c=>`${c.offer.name}: ${money(c.offer.directTotal,language)}`),...(finder.breakfast?[`${copy.breakfastLabel}: ${money(breakfastTotal,language)}`]:[]),`${copy.total}: ${money(roomTotal+breakfastTotal,language)}`].join("\n");try{const r=await fetch("/api/ai-assistant/summary-email",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subject:`AI Room Finder — ${contact.name}`,message:`${copy.contactTitle}\n\n${summary}\n\n${copy.name}: ${contact.name}\n${copy.phone}: ${contact.phone||"—"}\n${copy.email}: ${contact.email||"—"}`,guest:contact})});if(!r.ok)throw new Error();setSendStatus("sent");}catch{setSendStatus("error");}}
 const homeHref=language==="en"?"/":`/${language}/`; const inputEnabled=["checkin","checkout","rooms","guests"].includes(finder.step)&&!finder.typing;
 const breakfastTotal=finder.breakfast?finder.guestTotal*finder.nights*12:0; const roomTotal=finder.choices.reduce((s,c)=>s+c.offer.directTotal,0);
 return <main className="flex h-[100dvh] flex-col overflow-hidden bg-[#f6f2eb] text-[#29251f]">
  <style jsx global>{`@keyframes msg{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}@keyframes react{from{opacity:0;transform:translateY(2px) scale(.82)}to{opacity:1;transform:none}}.msg{animation:msg .22s ease-out both}.reaction{animation:react .22s ease-out both}.hide-scroll::-webkit-scrollbar{display:none}.hide-scroll{scrollbar-width:none}`}</style>
  <header className="shrink-0 border-b border-[#ddd4c8] bg-[#fbf8f3]/95"><div className="mx-auto flex h-[68px] max-w-3xl items-center gap-2 px-3"><a href={homeHref} className="flex h-10 w-10 items-center justify-center rounded-full text-xl">←</a><div className="relative h-11 w-11 overflow-hidden rounded-full ring-2 ring-white"><Image src="/images/welcome/voulamandis-welcome-hero.webp" alt="Voulamandis House" fill sizes="44px" className="object-cover"/></div><div className="min-w-0 flex-1"><h1 className="truncate text-[16px] font-bold">Voulamandis House</h1><div className="flex items-center gap-1.5 text-xs text-[#746b60]"><span className="h-2 w-2 rounded-full bg-[#718b52]"/>{copy.online}</div></div><select value={language} onChange={e=>changeLanguage(e.target.value as RoomFinderLanguage)} className="h-9 w-[100px] rounded-full border border-[#d8cec1] bg-white px-2 text-xs font-bold">{ROOM_FINDER_LANGUAGES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button onClick={()=>finder.reset()} className="h-10 w-10 rounded-full text-lg">↻</button></div></header>
  {(finder.checkin||finder.groups.length>0)&&<div className="shrink-0 border-b border-[#e5ddd2] bg-[#f9f5ef] px-3 py-2"><div className="hide-scroll mx-auto flex max-w-3xl gap-2 overflow-x-auto text-xs font-semibold text-[#625b52]">{finder.checkin&&<span className="whitespace-nowrap rounded-full border border-[#ddd3c6] bg-white px-3 py-1.5">📅 {finder.checkin}{finder.checkout?` → ${finder.checkout}`:""}</span>}{finder.groups.length>0&&<span className="whitespace-nowrap rounded-full border border-[#ddd3c6] bg-white px-3 py-1.5">👥 {copy.guestLabel(finder.guestTotal)}</span>}{finder.roomCount&&<span className="whitespace-nowrap rounded-full border border-[#ddd3c6] bg-white px-3 py-1.5">🛏️ {copy.roomLabel(finder.roomCount)}</span>}</div></div>}
  <div ref={feedRef} className="min-h-0 flex-1 overflow-y-auto"><div className="mx-auto flex min-h-full max-w-3xl flex-col px-3 pb-7 pt-5"><div className="space-y-3.5">
   {finder.messages.map(message=><ChatMessage key={message.id} message={message}/>)}{finder.typing&&<div className="msg ml-10 w-fit rounded-[20px] border border-[#dfd6ca] bg-white px-4 py-3 shadow-sm">•••</div>}
   {finder.step==="rooms"&&<IconReplies values={[1,2,3]} icon="🛏️" label={copy.roomLabel} onSelect={n=>void finder.chooseRooms(n)}/>} {finder.step==="guests"&&<IconReplies values={[1,2,3,4,5]} icon="👤" label={copy.guestLabel} onSelect={n=>void finder.chooseGuests(n)}/>} 
   {finder.step==="preferences"&&<section className="msg ml-10 rounded-[22px] border border-[#dfd6ca] bg-white p-4 shadow-sm"><div className="flex flex-wrap gap-2">{FILTERS.map(f=><button key={f} onClick={()=>finder.setFilters(v=>v.includes(f)?v.filter(x=>x!==f):[...v,f])} className={`rounded-full border px-3 py-2 text-xs font-bold ${finder.filters.includes(f)?"border-[#66714f] bg-[#66714f] text-white":"border-[#d9cfc2] bg-[#fbf9f6]"}`}>{copy.filters[f]}</button>)}</div><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>{finder.setFilters([]);void finder.searchRooms(copy.noPreference);}} className="min-h-12 rounded-2xl border border-[#d9cfc2] font-bold">{copy.noPreference}</button><button onClick={()=>void finder.searchRooms(copy.showRooms)} className="min-h-12 rounded-2xl bg-[#66714f] font-bold text-white">{copy.showRooms}</button></div></section>}
   {finder.step==="selecting"&&finder.visibleOffers.length>0&&<><RoomCarousel offers={finder.visibleOffers} copy={copy} language={language} money={money} onDetails={setDetail} onSelect={offer=>void finder.selectOffer(offer)}/><FeedbackArea copy={copy} mode={finder.feedback} onYes={()=>void finder.happy()} onDifferent={()=>void finder.different()} onType={()=>void finder.refineMode("type")} onFloor={()=>void finder.refineMode("floor")} onGroup={()=>void finder.fitGroup()} onInfo={()=>void whatsappTurn("info")} onOther={()=>void whatsappTurn("other")} onFilter={f=>void finder.refine(f)}/></>}
   {handoff&&<div className="msg ml-10 rounded-[20px] rounded-bl-[6px] border border-[#dfd6ca] bg-white px-4 py-3 text-[15px] shadow-sm">{handoff}</div>}
   {finder.step==="breakfast"&&<><SelectedRoomCard choices={finder.choices} copy={copy} language={language} checkin={finder.checkin} checkout={finder.checkout} money={money}/><div className="msg ml-10 rounded-[20px] rounded-bl-[6px] border border-[#dfd6ca] bg-white px-4 py-3 text-[15px] shadow-sm">{copy.breakfast}</div><section className="msg ml-10 overflow-hidden rounded-[22px] border border-[#dcd2c5] bg-white shadow-sm"><div className="relative h-36"><Image src={BREAKFAST_IMAGE} alt={copy.breakfastLabel} fill sizes="600px" className="object-cover"/></div><div className="flex gap-2 p-3"><button onClick={()=>void finder.chooseBreakfast(true)} className="rounded-full bg-[#66714f] px-4 py-2.5 text-sm font-bold text-white">{copy.yesBreakfast}</button><button onClick={()=>void finder.chooseBreakfast(false)} className="rounded-full border border-[#d8cec1] px-4 py-2.5 text-sm font-bold">{copy.noBreakfast}</button></div></section></>}
   {finder.step==="unavailable"&&<section className="ml-10 grid grid-cols-2 gap-2 rounded-[22px] border border-[#dfd6ca] bg-white p-4"><button onClick={()=>finder.reset()} className="min-h-12 rounded-2xl border font-bold">{copy.newSearch}</button><button onClick={()=>openWhatsApp(copy.unavailable)} className="min-h-12 rounded-2xl bg-[#287d4f] font-bold text-white">{copy.whatsapp}</button></section>}
   {finder.step==="complete"&&<section className="msg overflow-hidden rounded-[26px] border border-[#dcd2c5] bg-white shadow-[0_16px_45px_rgba(70,55,35,.10)] sm:ml-10"><div className="border-b bg-[#faf7f2] p-4"><div className="flex justify-between"><h2 className="text-lg font-black">{copy.summary}</h2><button onClick={()=>finder.reset()} className="text-xs font-bold underline">{copy.newSearch}</button></div><p className="mt-2 text-sm text-[#746b60]">📅 {finder.checkin} → {finder.checkout} · {copy.nightLabel(finder.nights)}</p></div><div className="p-4">{finder.choices.map(c=><div key={c.group} className="flex items-center gap-3 border-b py-3"><div className="relative h-14 w-[72px] overflow-hidden rounded-xl"><Image src={c.offer.image} alt={c.offer.name} fill sizes="72px" className="object-cover"/></div><div className="flex-1"><p className="font-bold">{c.offer.name}</p><p className="text-xs text-[#746b60]">{copy.guestLabel(c.guests)}</p></div><strong className="text-[#5f7448]">{money(c.offer.directTotal,language)}</strong></div>)}{finder.breakfast&&<div className="flex justify-between border-b py-3"><span>🥐 {copy.breakfastLabel}</span><strong>{money(breakfastTotal,language)}</strong></div>}<div className="mt-4 flex justify-between rounded-2xl bg-[#f1ede7] p-4 text-lg"><b>{copy.total}</b><strong className="text-xl text-[#5f7448]">{money(roomTotal+breakfastTotal,language)}</strong></div><div className="mt-5"><h3 className="text-lg font-black">{copy.contactTitle}</h3><p className="mt-1 text-sm text-[#746b60]">{copy.contactHelp}</p><div className="mt-3 space-y-2"><input value={contact.name} onChange={e=>setContact({...contact,name:e.target.value})} placeholder={copy.name} className="h-12 w-full rounded-2xl border border-[#d8cec1] px-4"/><input value={contact.phone} onChange={e=>setContact({...contact,phone:e.target.value})} placeholder={copy.phone} className="h-12 w-full rounded-2xl border border-[#d8cec1] px-4"/><input value={contact.email} onChange={e=>setContact({...contact,email:e.target.value})} placeholder={copy.email} className="h-12 w-full rounded-2xl border border-[#d8cec1] px-4"/></div><div className="mt-3 grid grid-cols-2 gap-2"><button disabled={sendStatus==="sending"} onClick={()=>void sendRequest()} className="min-h-12 rounded-2xl bg-[#66714f] font-bold text-white disabled:opacity-40">{copy.send}</button><button onClick={()=>openWhatsApp(whatsappContext(copy.contactTitle))} className="min-h-12 rounded-2xl bg-[#287d4f] font-bold text-white">{copy.whatsapp}</button></div>{sendStatus==="sent"&&<p className="mt-3 rounded-2xl bg-[#eef4e7] p-3 font-bold text-[#5f7448]">{copy.sent}</p>}{sendStatus==="error"&&<p className="mt-3 rounded-2xl bg-red-50 p-3 text-sm text-red-700">{copy.sendError}</p>}</div></div></section>}
  </div></div></div>
  <form onSubmit={finder.submit} className="shrink-0 border-t border-[#e2d9cd] bg-[#fbf8f3]/95 p-3"><div className="mx-auto flex max-w-3xl items-center gap-2 rounded-[24px] border border-[#d8cec1] bg-white p-2 shadow-sm"><input value={finder.input} onChange={e=>finder.setInput(e.target.value)} disabled={!inputEnabled} placeholder={inputEnabled?copy.placeholder:copy.chooseAbove} className="min-w-0 flex-1 bg-transparent px-3 py-2 text-[15px] outline-none disabled:text-[#a9a197]"/><button disabled={!inputEnabled||!finder.input.trim()} className="flex h-11 w-11 items-center justify-center rounded-full bg-[#6b604f] text-white disabled:bg-[#d7d0c6]">↑</button></div></form>
  {detail&&<div className="fixed inset-0 z-50 flex items-end bg-black/35 p-3 sm:items-center sm:justify-center"><section className="max-h-[88dvh] w-full overflow-hidden rounded-[26px] bg-white sm:max-w-xl"><div className="relative h-60"><Image src={detail.image} alt={detail.name} fill sizes="600px" className="object-cover"/><button onClick={()=>setDetail(null)} className="absolute right-3 top-3 h-10 w-10 rounded-full bg-white/90 text-xl">×</button></div><div className="p-5"><h2 className="text-2xl font-black">{detail.name}</h2><p className="mt-1 text-sm text-[#746b60]">{detail.category} · {detail.floor}</p><div className="mt-3 flex flex-wrap gap-2">{(detail.features||[]).map(x=><span key={x} className="rounded-full bg-[#f1ede7] px-3 py-1.5 text-xs font-semibold">{x}</span>)}</div><button onClick={()=>{setDetail(null);void finder.selectOffer(detail);}} className="mt-5 w-full rounded-2xl bg-[#66714f] p-3.5 font-black text-white">{copy.select}</button></div></section></div>}
 </main>;
}

function FeedbackArea({copy,mode,onYes,onDifferent,onType,onFloor,onGroup,onInfo,onOther,onFilter}:{copy:typeof ROOM_FINDER_COPY.el;mode:string;onYes:()=>void;onDifferent:()=>void;onType:()=>void;onFloor:()=>void;onGroup:()=>void;onInfo:()=>void;onOther:()=>void;onFilter:(f:RoomFinderFilter)=>void}){
 if(mode==="happy")return null;
 if(mode==="type"||mode==="floor"){const values:RoomFinderFilter[]=mode==="type"?["economy","kitchen","family"]:["noStairs","ground","first"];return <section className="msg ml-10 rounded-[22px] border border-[#dfd6ca] bg-white p-4 shadow-sm"><div className="flex flex-wrap gap-2">{values.map(f=><button key={f} onClick={()=>onFilter(f)} className="rounded-full border border-[#d8cec1] px-3 py-2 text-sm font-bold">{copy.filters[f]}</button>)}</div></section>;}
 return <section className="msg ml-10 rounded-[22px] border border-[#dfd6ca] bg-white p-4 shadow-sm"><p className="font-bold">{mode==="different"?copy.changePrompt:copy.feedbackQ}</p>{mode!=="different"?<div className="mt-3 grid gap-2 sm:grid-cols-2"><button onClick={onYes} className="rounded-2xl bg-[#66714f] px-3 py-3 text-sm font-bold text-white">{copy.feedbackYes}</button><button onClick={onDifferent} className="rounded-2xl border border-[#d8cec1] px-3 py-3 text-sm font-bold">{copy.feedbackDifferent}</button></div>:<div className="mt-3 grid gap-2"><button onClick={onType} className="rounded-2xl border p-3 text-left text-sm font-bold">{copy.roomType}</button><button onClick={onFloor} className="rounded-2xl border p-3 text-left text-sm font-bold">{copy.floor}</button><button onClick={onGroup} className="rounded-2xl border p-3 text-left text-sm font-bold">{copy.group}</button><button onClick={onInfo} className="rounded-2xl border p-3 text-left text-sm font-bold">{copy.info}</button><button onClick={onOther} className="rounded-2xl border p-3 text-left text-sm font-bold">{copy.other}</button></div>}</section>;
}
