export type RoomFinderLanguage = "el" | "en" | "de" | "fr" | "it" | "es" | "tr";

export type RoomFinderCopy = {
  welcome: string;
  breakfast: string;
  summary: string;
  online: string;
  details: string;
  select: string;
  selected: string;
  saving: string;
  total: string;
  yesBreakfast: string;
  noBreakfast: string;
  newSearch: string;
  previousStep: string;
  editDates: string;
  placeholder: string;
  changePlaceholder: string;
  waitingPlaceholder: string;
  contactTitle: string;
  contactHelp: string;
  name: string;
  phone: string;
  email: string;
  send: string;
  sent: string;
  sendError: string;
  whatsapp: string;
  whatsappHelp: string;
  breakfastLabel: string;
  languageLabel: string;
  roomLabel: (n: number) => string;
  guestLabel: (n: number) => string;
  nightLabel: (n: number) => string;
};

export const ROOM_FINDER_LANGUAGES: Array<[RoomFinderLanguage, string]> = [
  ["el", "Ελληνικά"],
  ["en", "English"],
  ["de", "Deutsch"],
  ["fr", "Français"],
  ["it", "Italiano"],
  ["es", "Español"],
  ["tr", "Türkçe"],
];

export const ROOM_FINDER_COPY: Record<RoomFinderLanguage, RoomFinderCopy> = {
  el: {
    welcome: "Καλώς ήρθατε στο Voulamandis House 👋 Πότε θα θέλατε να κάνετε check-in;",
    breakfast: "Θα θέλατε να προσθέσετε σπιτικό πρωινό στη διαμονή σας; ☕🥐",
    summary: "Η αίτηση διαμονής σας",
    online: "Διαθέσιμοι τώρα",
    details: "Λεπτομέρειες",
    select: "Επιλογή",
    selected: "Η επιλογή σας",
    saving: "Εξοικονομείτε",
    total: "Σύνολο",
    yesBreakfast: "Ναι, προσθήκη",
    noBreakfast: "Όχι, ευχαριστώ",
    newSearch: "Νέα αναζήτηση",
    previousStep: "Προηγούμενο βήμα",
    editDates: "Αλλαγή ημερομηνιών",
    placeholder: "Γράψτε ημερομηνία ή απάντηση…",
    changePlaceholder: "Γράψτε κάποια αλλαγή…",
    waitingPlaceholder: "Έλεγχος διαθεσιμότητας…",
    contactTitle: "Στείλτε την αίτηση στην ομάδα μας",
    contactHelp: "Γράψτε το όνομά σας και ένα τηλέφωνο ή email.",
    name: "Όνομα",
    phone: "Τηλέφωνο",
    email: "Email",
    send: "Αποστολή αιτήματος",
    sent: "✓ Το αίτημά σας στάλθηκε. Θα επικοινωνήσουμε μαζί σας το συντομότερο δυνατό. 😊",
    sendError: "Δεν ήταν δυνατή η αποστολή. Δοκιμάστε μέσω WhatsApp.",
    whatsapp: "WhatsApp",
    whatsappHelp: "Χρειάζεστε κάποια επιπλέον πληροφορία;",
    breakfastLabel: "Πρωινό",
    languageLabel: "Γλώσσα",
    roomLabel: n => `${n} ${n === 1 ? "δωμάτιο" : "δωμάτια"}`,
    guestLabel: n => `${n} ${n === 1 ? "άτομο" : "άτομα"}`,
    nightLabel: n => `${n} ${n === 1 ? "βραδιά" : "βραδιές"}`,
  },
  en: {
    welcome: "Welcome to Voulamandis House 👋 When would you like to check in?",
    breakfast: "Would you like to add homemade breakfast to your stay? ☕🥐",
    summary: "Your stay request",
    online: "Online now",
    details: "Details",
    select: "Select",
    selected: "Your selection",
    saving: "You save",
    total: "Total",
    yesBreakfast: "Yes, add breakfast",
    noBreakfast: "No, thank you",
    newSearch: "New search",
    previousStep: "Previous step",
    editDates: "Edit dates",
    placeholder: "Type a date or answer…",
    changePlaceholder: "Type a change…",
    waitingPlaceholder: "Checking availability…",
    contactTitle: "Send this request to our team",
    contactHelp: "Enter your name and either a phone number or email.",
    name: "Name",
    phone: "Phone",
    email: "Email",
    send: "Send request",
    sent: "✓ Your request was sent. We’ll contact you as soon as possible. 😊",
    sendError: "The request could not be sent. Try WhatsApp.",
    whatsapp: "WhatsApp",
    whatsappHelp: "Need any additional information?",
    breakfastLabel: "Breakfast",
    languageLabel: "Language",
    roomLabel: n => `${n} ${n === 1 ? "room" : "rooms"}`,
    guestLabel: n => `${n} ${n === 1 ? "guest" : "guests"}`,
    nightLabel: n => `${n} ${n === 1 ? "night" : "nights"}`,
  },
  de: {
    welcome: "Willkommen im Voulamandis House 👋 Wann möchten Sie einchecken?",
    breakfast: "Möchten Sie hausgemachtes Frühstück zu Ihrem Aufenthalt hinzufügen? ☕🥐",
    summary: "Ihre Aufenthaltsanfrage",
    online: "Jetzt erreichbar",
    details: "Details",
    select: "Auswählen",
    selected: "Ihre Auswahl",
    saving: "Sie sparen",
    total: "Gesamt",
    yesBreakfast: "Ja, hinzufügen",
    noBreakfast: "Nein, danke",
    newSearch: "Neue Suche",
    previousStep: "Vorheriger Schritt",
    editDates: "Daten ändern",
    placeholder: "Datum oder Antwort eingeben…",
    changePlaceholder: "Änderung eingeben…",
    waitingPlaceholder: "Verfügbarkeit wird geprüft…",
    contactTitle: "Anfrage an unser Team senden",
    contactHelp: "Geben Sie Ihren Namen und eine Telefonnummer oder E-Mail-Adresse ein.",
    name: "Name",
    phone: "Telefon",
    email: "E-Mail",
    send: "Anfrage senden",
    sent: "✓ Ihre Anfrage wurde gesendet. Wir melden uns so schnell wie möglich. 😊",
    sendError: "Die Anfrage konnte nicht gesendet werden. Versuchen Sie es über WhatsApp.",
    whatsapp: "WhatsApp",
    whatsappHelp: "Benötigen Sie weitere Informationen?",
    breakfastLabel: "Frühstück",
    languageLabel: "Sprache",
    roomLabel: n => `${n} ${n === 1 ? "Zimmer" : "Zimmer"}`,
    guestLabel: n => `${n} ${n === 1 ? "Gast" : "Gäste"}`,
    nightLabel: n => `${n} ${n === 1 ? "Nacht" : "Nächte"}`,
  },
  fr: {
    welcome: "Bienvenue à Voulamandis House 👋 Quand souhaitez-vous faire le check-in ?",
    breakfast: "Souhaitez-vous ajouter un petit-déjeuner maison à votre séjour ? ☕🥐",
    summary: "Votre demande de séjour",
    online: "Disponible maintenant",
    details: "Détails",
    select: "Choisir",
    selected: "Votre choix",
    saving: "Vous économisez",
    total: "Total",
    yesBreakfast: "Oui, ajouter",
    noBreakfast: "Non, merci",
    newSearch: "Nouvelle recherche",
    previousStep: "Étape précédente",
    editDates: "Modifier les dates",
    placeholder: "Saisissez une date ou une réponse…",
    changePlaceholder: "Saisissez une modification…",
    waitingPlaceholder: "Vérification des disponibilités…",
    contactTitle: "Envoyer cette demande à notre équipe",
    contactHelp: "Indiquez votre nom et un numéro de téléphone ou une adresse e-mail.",
    name: "Nom",
    phone: "Téléphone",
    email: "E-mail",
    send: "Envoyer la demande",
    sent: "✓ Votre demande a été envoyée. Nous vous contacterons dès que possible. 😊",
    sendError: "La demande n’a pas pu être envoyée. Essayez via WhatsApp.",
    whatsapp: "WhatsApp",
    whatsappHelp: "Besoin d’informations supplémentaires ?",
    breakfastLabel: "Petit-déjeuner",
    languageLabel: "Langue",
    roomLabel: n => `${n} ${n === 1 ? "chambre" : "chambres"}`,
    guestLabel: n => `${n} ${n === 1 ? "personne" : "personnes"}`,
    nightLabel: n => `${n} ${n === 1 ? "nuit" : "nuits"}`,
  },
  it: {
    welcome: "Benvenuti a Voulamandis House 👋 Quando desiderate effettuare il check-in?",
    breakfast: "Desiderate aggiungere la colazione fatta in casa al vostro soggiorno? ☕🥐",
    summary: "La vostra richiesta di soggiorno",
    online: "Disponibili ora",
    details: "Dettagli",
    select: "Seleziona",
    selected: "La vostra scelta",
    saving: "Risparmiate",
    total: "Totale",
    yesBreakfast: "Sì, aggiungi",
    noBreakfast: "No, grazie",
    newSearch: "Nuova ricerca",
    previousStep: "Passaggio precedente",
    editDates: "Modifica date",
    placeholder: "Scrivete una data o una risposta…",
    changePlaceholder: "Scrivete una modifica…",
    waitingPlaceholder: "Verifica disponibilità…",
    contactTitle: "Invia la richiesta al nostro team",
    contactHelp: "Inserite il vostro nome e un numero di telefono o un’e-mail.",
    name: "Nome",
    phone: "Telefono",
    email: "Email",
    send: "Invia richiesta",
    sent: "✓ La richiesta è stata inviata. Vi contatteremo il prima possibile. 😊",
    sendError: "Non è stato possibile inviare la richiesta. Provate con WhatsApp.",
    whatsapp: "WhatsApp",
    whatsappHelp: "Avete bisogno di altre informazioni?",
    breakfastLabel: "Colazione",
    languageLabel: "Lingua",
    roomLabel: n => `${n} ${n === 1 ? "camera" : "camere"}`,
    guestLabel: n => `${n} ${n === 1 ? "persona" : "persone"}`,
    nightLabel: n => `${n} ${n === 1 ? "notte" : "notti"}`,
  },
  es: {
    welcome: "Bienvenidos a Voulamandis House 👋 ¿Cuándo les gustaría hacer el check-in?",
    breakfast: "¿Quieren añadir desayuno casero a su estancia? ☕🥐",
    summary: "Su solicitud de estancia",
    online: "Disponibles ahora",
    details: "Detalles",
    select: "Elegir",
    selected: "Su selección",
    saving: "Ahorran",
    total: "Total",
    yesBreakfast: "Sí, añadir",
    noBreakfast: "No, gracias",
    newSearch: "Nueva búsqueda",
    previousStep: "Paso anterior",
    editDates: "Editar fechas",
    placeholder: "Escriban una fecha o respuesta…",
    changePlaceholder: "Escriban un cambio…",
    waitingPlaceholder: "Comprobando disponibilidad…",
    contactTitle: "Enviar esta solicitud a nuestro equipo",
    contactHelp: "Indiquen su nombre y un teléfono o correo electrónico.",
    name: "Nombre",
    phone: "Teléfono",
    email: "Email",
    send: "Enviar solicitud",
    sent: "✓ Su solicitud se ha enviado. Nos pondremos en contacto lo antes posible. 😊",
    sendError: "No se pudo enviar la solicitud. Prueben por WhatsApp.",
    whatsapp: "WhatsApp",
    whatsappHelp: "¿Necesitan información adicional?",
    breakfastLabel: "Desayuno",
    languageLabel: "Idioma",
    roomLabel: n => `${n} ${n === 1 ? "habitación" : "habitaciones"}`,
    guestLabel: n => `${n} ${n === 1 ? "persona" : "personas"}`,
    nightLabel: n => `${n} ${n === 1 ? "noche" : "noches"}`,
  },
  tr: {
    welcome: "Voulamandis House’a hoş geldiniz 👋 Ne zaman giriş yapmak istersiniz?",
    breakfast: "Konaklamanıza ev yapımı kahvaltı eklemek ister misiniz? ☕🥐",
    summary: "Konaklama talebiniz",
    online: "Şimdi çevrimiçi",
    details: "Detaylar",
    select: "Seç",
    selected: "Seçiminiz",
    saving: "Tasarrufunuz",
    total: "Toplam",
    yesBreakfast: "Evet, ekle",
    noBreakfast: "Hayır, teşekkürler",
    newSearch: "Yeni arama",
    previousStep: "Önceki adım",
    editDates: "Tarihleri değiştir",
    placeholder: "Tarih veya yanıt yazın…",
    changePlaceholder: "Bir değişiklik yazın…",
    waitingPlaceholder: "Müsaitlik kontrol ediliyor…",
    contactTitle: "Talebi ekibimize gönderin",
    contactHelp: "Adınızı ve telefon numaranızı veya e-posta adresinizi yazın.",
    name: "Ad",
    phone: "Telefon",
    email: "E-posta",
    send: "Talebi gönder",
    sent: "✓ Talebiniz gönderildi. En kısa sürede sizinle iletişime geçeceğiz. 😊",
    sendError: "Talep gönderilemedi. WhatsApp üzerinden deneyin.",
    whatsapp: "WhatsApp",
    whatsappHelp: "Ek bilgiye ihtiyacınız var mı?",
    breakfastLabel: "Kahvaltı",
    languageLabel: "Dil",
    roomLabel: n => `${n} oda`,
    guestLabel: n => `${n} kişi`,
    nightLabel: n => `${n} gece`,
  },
};