import { type LanguageCode, normalizePath } from "./languages";

export type RouteAction = "KEEP" | "CHECK" | "REDIRECT" | "REMOVE" | "MERGE";

export type PageTemplate =
  | "HomePage"
  | "RoomsCategoryPage"
  | "RoomDetailPage"
  | "BookingPage"
  | "DealsPage"
  | "ContactPage"
  | "ChiosGuidePage"
  | "ChiosCategoryPage"
  | "ChiosDetailPage"
  | "LandingPage"
  | "StaticPage"
  | "Redirect";

export type RouteContentType =
  | "home"
  | "rooms-category"
  | "room-detail"
  | "booking-rates"
  | "deals"
  | "contact"
  | "chios-guide-index"
  | "chios-category"
  | "chios-detail"
  | "landing-page"
  | "photos"
  | "videos"
  | "ai-chatbox"
  | "legal"
  | "old-test"
  | "redirect-candidate";

export type RouteRecord = {
  path: string;
  language: LanguageCode;
  contentType: RouteContentType;
  category?: string;
  itemId: string;
  template: PageTemplate;
  action: RouteAction;
  priority: "Critical" | "High" | "Medium" | "Low";
  canonicalPath?: string;
  notes?: string;
};

export const routeMap: readonly RouteRecord[] = [
  {
    path: "/",
    language: "en",
    contentType: "home",
    itemId: "home",
    template: "HomePage",
    action: "KEEP",
    priority: "Critical",
    notes: "English is the default/base language.",
  },
  {
    path: "/el/",
    language: "el",
    contentType: "home",
    itemId: "home",
    template: "HomePage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/fr/",
    language: "fr",
    contentType: "home",
    itemId: "home",
    template: "HomePage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/de/",
    language: "de",
    contentType: "home",
    itemId: "home",
    template: "HomePage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/it/",
    language: "it",
    contentType: "home",
    itemId: "home",
    template: "HomePage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/es/",
    language: "es",
    contentType: "home",
    itemId: "home",
    template: "HomePage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/tr/",
    language: "tr",
    contentType: "home",
    itemId: "home",
    template: "HomePage",
    action: "KEEP",
    priority: "Critical",
  },

  {
    path: "/chios-rooms/",
    language: "en",
    contentType: "rooms-category",
    category: "rooms",
    itemId: "rooms-index",
    template: "RoomsCategoryPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/el/domatia-xios/",
    language: "el",
    contentType: "rooms-category",
    category: "rooms",
    itemId: "rooms-index",
    template: "RoomsCategoryPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/fr/chambres-a-chios/",
    language: "fr",
    contentType: "rooms-category",
    category: "rooms",
    itemId: "rooms-index",
    template: "RoomsCategoryPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/de/chios-zimmer/",
    language: "de",
    contentType: "rooms-category",
    category: "rooms",
    itemId: "rooms-index",
    template: "RoomsCategoryPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/it/camere-a-chios/",
    language: "it",
    contentType: "rooms-category",
    category: "rooms",
    itemId: "rooms-index",
    template: "RoomsCategoryPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/es/habitaciones-en-chios/",
    language: "es",
    contentType: "rooms-category",
    category: "rooms",
    itemId: "rooms-index",
    template: "RoomsCategoryPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/tr/sakiz-adasi-odalari/",
    language: "tr",
    contentType: "rooms-category",
    category: "rooms",
    itemId: "rooms-index",
    template: "RoomsCategoryPage",
    action: "KEEP",
    priority: "Critical",
  },

  {
    path: "/chios-rooms/economy-double-rooms/",
    language: "en",
    contentType: "room-detail",
    category: "rooms",
    itemId: "economy-double",
    template: "RoomDetailPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/el/domatia-xios/oikonomiko-diklino-domatio/",
    language: "el",
    contentType: "room-detail",
    category: "rooms",
    itemId: "economy-double",
    template: "RoomDetailPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/fr/chambres-a-chios/chambres-doubles-economiques/",
    language: "fr",
    contentType: "room-detail",
    category: "rooms",
    itemId: "economy-double",
    template: "RoomDetailPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/de/zimmer-chios/economy-zimmer-auf-chios/",
    language: "de",
    contentType: "room-detail",
    category: "rooms",
    itemId: "economy-double",
    template: "RoomDetailPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/it/stanze-a-chios/camera-doppia-economica-chios/",
    language: "it",
    contentType: "room-detail",
    category: "rooms",
    itemId: "economy-double",
    template: "RoomDetailPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/es/habitaciones-en-chios/economicas-habitaciones-en-chios/",
    language: "es",
    contentType: "room-detail",
    category: "rooms",
    itemId: "economy-double",
    template: "RoomDetailPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/tr/chios-odalari/sakiz-adasindaki-ekonomi-cift-kisilik-oda/",
    language: "tr",
    contentType: "room-detail",
    category: "rooms",
    itemId: "economy-double",
    template: "RoomDetailPage",
    action: "KEEP",
    priority: "Critical",
  },

  {
    path: "/chios-rooms/standard-double-room/",
    language: "en",
    contentType: "room-detail",
    category: "rooms",
    itemId: "standard-double",
    template: "RoomDetailPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/el/domatia-xios/diklina-triklina-domatia/",
    language: "el",
    contentType: "room-detail",
    category: "rooms",
    itemId: "standard-double",
    template: "RoomDetailPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/fr/chambres-a-chios/chambres-doubles-standard/",
    language: "fr",
    contentType: "room-detail",
    category: "rooms",
    itemId: "standard-double",
    template: "RoomDetailPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/de/zimmer-chios/standard-doppelzimmer-auf-chios/",
    language: "de",
    contentType: "room-detail",
    category: "rooms",
    itemId: "standard-double",
    template: "RoomDetailPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/it/stanze-a-chios/camere-doppie-standard-chios/",
    language: "it",
    contentType: "room-detail",
    category: "rooms",
    itemId: "standard-double",
    template: "RoomDetailPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/es/habitaciones-en-chios/habitaciones-dobles-estandar/",
    language: "es",
    contentType: "room-detail",
    category: "rooms",
    itemId: "standard-double",
    template: "RoomDetailPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/tr/chios-odalari/standart-cift-kisilik-odalar/",
    language: "tr",
    contentType: "room-detail",
    category: "rooms",
    itemId: "standard-double",
    template: "RoomDetailPage",
    action: "KEEP",
    priority: "Critical",
  },

  {
    path: "/chios-rooms/family-chios-apartments/",
    language: "en",
    contentType: "room-detail",
    category: "rooms",
    itemId: "family-apartment",
    template: "RoomDetailPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/el/domatia-xios/oikogeneiako-diamerisma/",
    language: "el",
    contentType: "room-detail",
    category: "rooms",
    itemId: "family-apartment",
    template: "RoomDetailPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/fr/chambres-a-chios/appartements-familiaux-de-chios/",
    language: "fr",
    contentType: "room-detail",
    category: "rooms",
    itemId: "family-apartment",
    template: "RoomDetailPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/de/zimmer-chios/familienapartments-in-chios/",
    language: "de",
    contentType: "room-detail",
    category: "rooms",
    itemId: "family-apartment",
    template: "RoomDetailPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/it/stanze-a-chios/appartamenti-familiari-a-chios/",
    language: "it",
    contentType: "room-detail",
    category: "rooms",
    itemId: "family-apartment",
    template: "RoomDetailPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/es/habitaciones-en-chios/apartamentos-familiares-en-chios/",
    language: "es",
    contentType: "room-detail",
    category: "rooms",
    itemId: "family-apartment",
    template: "RoomDetailPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/tr/chios-odalari/sakiz-adasinda-buyuk-aile-daireleri/",
    language: "tr",
    contentType: "room-detail",
    category: "rooms",
    itemId: "family-apartment",
    template: "RoomDetailPage",
    action: "KEEP",
    priority: "Critical",
  },

  {
    path: "/chios-hotels-rates/",
    language: "en",
    contentType: "booking-rates",
    itemId: "booking",
    template: "BookingPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/el/amesi-kratisi-voulamandis-house/",
    language: "el",
    contentType: "booking-rates",
    itemId: "booking",
    template: "BookingPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/fr/tarifs-des-hotels-a-chios/",
    language: "fr",
    contentType: "booking-rates",
    itemId: "booking",
    template: "BookingPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/de/hotelpreise-auf-der-insel-chios/",
    language: "de",
    contentType: "booking-rates",
    itemId: "booking",
    template: "BookingPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/it/prezzi-hotel-chios/",
    language: "it",
    contentType: "booking-rates",
    itemId: "booking",
    template: "BookingPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/es/los-mejores-precios-de-hotel-en-la-isla-chios/",
    language: "es",
    contentType: "booking-rates",
    itemId: "booking",
    template: "BookingPage",
    action: "KEEP",
    priority: "Critical",
  },
  {
    path: "/tr/sakiz-adasi-rezervasyon/",
    language: "tr",
    contentType: "booking-rates",
    itemId: "booking",
    template: "BookingPage",
    action: "KEEP",
    priority: "Critical",
  },

  {
    path: "/best-chios-travel-deals-for-chios-hotels/",
    language: "en",
    contentType: "deals",
    itemId: "deals",
    template: "DealsPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/el/crazy-travel-deals-for-chios-hotels/",
    language: "el",
    contentType: "deals",
    itemId: "deals",
    template: "DealsPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/offres-de-voyage-pour-les-hotels-a-chios/",
    language: "fr",
    contentType: "deals",
    itemId: "deals",
    template: "DealsPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/beste-reiseangebote-fur-chios-hotels-auf-chios/",
    language: "de",
    contentType: "deals",
    itemId: "deals",
    template: "DealsPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/offerte-di-viaggio-hotels-chios/",
    language: "it",
    contentType: "deals",
    itemId: "deals",
    template: "DealsPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/mejores-ofertas-de-viaje-a-quios-para-hoteles-en-quios/",
    language: "es",
    contentType: "deals",
    itemId: "deals",
    template: "DealsPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-otel-firsatlari/",
    language: "tr",
    contentType: "deals",
    itemId: "deals",
    template: "DealsPage",
    action: "KEEP",
    priority: "High",
  },

  {
    path: "/voulamandis-house-contact-us-form-fill-in-the-form/",
    language: "en",
    contentType: "contact",
    itemId: "contact",
    template: "ContactPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/el/epikoinonia-voulamandis-house/",
    language: "el",
    contentType: "contact",
    itemId: "contact",
    template: "ContactPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/contactez-nous/",
    language: "fr",
    contentType: "contact",
    itemId: "contact",
    template: "ContactPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/kontaktieren-voulamandis-house/",
    language: "de",
    contentType: "contact",
    itemId: "contact",
    template: "ContactPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/contattaci-voulamandis-house/",
    language: "it",
    contentType: "contact",
    itemId: "contact",
    template: "ContactPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/contacta-con-voulamandis-house/",
    language: "es",
    contentType: "contact",
    itemId: "contact",
    template: "ContactPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-otelleri-ile-iletisim/",
    language: "tr",
    contentType: "contact",
    itemId: "contact",
    template: "ContactPage",
    action: "KEEP",
    priority: "High",
  },

  {
    path: "/chios-island/",
    language: "en",
    contentType: "chios-guide-index",
    category: "chios",
    itemId: "chios-index",
    template: "ChiosGuidePage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/el/ti-na-do-sti-xio/",
    language: "el",
    contentType: "chios-guide-index",
    category: "chios",
    itemId: "chios-index",
    template: "ChiosGuidePage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/chios-en-grece/",
    language: "fr",
    contentType: "chios-guide-index",
    category: "chios",
    itemId: "chios-index",
    template: "ChiosGuidePage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/chios-insel/",
    language: "de",
    contentType: "chios-guide-index",
    category: "chios",
    itemId: "chios-index",
    template: "ChiosGuidePage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/chios-lisola-in-grecia/",
    language: "it",
    contentType: "chios-guide-index",
    category: "chios",
    itemId: "chios-index",
    template: "ChiosGuidePage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/chios-en-grecia/",
    language: "es",
    contentType: "chios-guide-index",
    category: "chios",
    itemId: "chios-index",
    template: "ChiosGuidePage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi/",
    language: "tr",
    contentType: "chios-guide-index",
    category: "chios",
    itemId: "chios-index",
    template: "ChiosGuidePage",
    action: "KEEP",
    priority: "High",
  },

  {
    path: "/chios/chios-beaches/",
    language: "en",
    contentType: "chios-category",
    category: "beaches",
    itemId: "beaches-index",
    template: "ChiosCategoryPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/el/paralies-xios/",
    language: "el",
    contentType: "chios-category",
    category: "beaches",
    itemId: "beaches-index",
    template: "ChiosCategoryPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/plages-de-chios/",
    language: "fr",
    contentType: "chios-category",
    category: "beaches",
    itemId: "beaches-index",
    template: "ChiosCategoryPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/straende-chios/",
    language: "de",
    contentType: "chios-category",
    category: "beaches",
    itemId: "beaches-index",
    template: "ChiosCategoryPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/spiagge-chios/",
    language: "it",
    contentType: "chios-category",
    category: "beaches",
    itemId: "beaches-index",
    template: "ChiosCategoryPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/playas-chios/",
    language: "es",
    contentType: "chios-category",
    category: "beaches",
    itemId: "beaches-index",
    template: "ChiosCategoryPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-plajlari/",
    language: "tr",
    contentType: "chios-category",
    category: "beaches",
    itemId: "beaches-index",
    template: "ChiosCategoryPage",
    action: "KEEP",
    priority: "High",
  },

  {
    path: "/chios/chios-villages/",
    language: "en",
    contentType: "chios-category",
    category: "villages",
    itemId: "villages-index",
    template: "ChiosCategoryPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/el/xoria-xios/",
    language: "el",
    contentType: "chios-category",
    category: "villages",
    itemId: "villages-index",
    template: "ChiosCategoryPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/villages-de-chios/",
    language: "fr",
    contentType: "chios-category",
    category: "villages",
    itemId: "villages-index",
    template: "ChiosCategoryPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/doerfer-chios/",
    language: "de",
    contentType: "chios-category",
    category: "villages",
    itemId: "villages-index",
    template: "ChiosCategoryPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/villaggi-chios/",
    language: "it",
    contentType: "chios-category",
    category: "villages",
    itemId: "villages-index",
    template: "ChiosCategoryPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/pueblos-chios/",
    language: "es",
    contentType: "chios-category",
    category: "villages",
    itemId: "villages-index",
    template: "ChiosCategoryPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-koyleri/",
    language: "tr",
    contentType: "chios-category",
    category: "villages",
    itemId: "villages-index",
    template: "ChiosCategoryPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/chios/chios-museums/",
    language: "en",
    contentType: "chios-category",
    category: "museums",
    itemId: "museums-index",
    template: "ChiosCategoryPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/el/mouseia-xios/",
    language: "el",
    contentType: "chios-category",
    category: "museums",
    itemId: "museums-index",
    template: "ChiosCategoryPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/musees-de-chios/",
    language: "fr",
    contentType: "chios-category",
    category: "museums",
    itemId: "museums-index",
    template: "ChiosCategoryPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/museen-chios/",
    language: "de",
    contentType: "chios-category",
    category: "museums",
    itemId: "museums-index",
    template: "ChiosCategoryPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/musei-chios/",
    language: "it",
    contentType: "chios-category",
    category: "museums",
    itemId: "museums-index",
    template: "ChiosCategoryPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/museos-chios/",
    language: "es",
    contentType: "chios-category",
    category: "museums",
    itemId: "museums-index",
    template: "ChiosCategoryPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-muzeleri/",
    language: "tr",
    contentType: "chios-category",
    category: "museums",
    itemId: "museums-index",
    template: "ChiosCategoryPage",
    action: "KEEP",
    priority: "High",
  },

  {
    path: "/chios/chios-beaches/agia-dynami-beach-chios/",
    language: "en",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "agia-dynami",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/el/paralies-xios/paralia-agia-dynami/",
    language: "el",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "agia-dynami",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/plages-de-chios/plage-agia-dynami/",
    language: "fr",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "agia-dynami",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/straende-chios/agia-dynami-strand/",
    language: "de",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "agia-dynami",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/spiagge-chios/spiaggia-agia-dynami/",
    language: "it",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "agia-dynami",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/playas-chios/playa-agia-dynami/",
    language: "es",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "agia-dynami",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-plajlari/agia-dynami-plaji/",
    language: "tr",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "agia-dynami",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/chios/chios-beaches/lithi-beach/",
    language: "en",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "lithi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/el/paralies-xios/paralia-lithi/",
    language: "el",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "lithi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/plages-de-chios/plage-lithi/",
    language: "fr",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "lithi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/straende-chios/lithi-strand/",
    language: "de",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "lithi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/spiagge-chios/spiaggia-lithi/",
    language: "it",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "lithi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/playas-chios/playa-lithi/",
    language: "es",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "lithi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-plajlari/lithi-plaji/",
    language: "tr",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "lithi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/chios/chios-beaches/lefkathia-beach/",
    language: "en",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "lefkathia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/el/paralies-xios/paralia-lefkathia/",
    language: "el",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "lefkathia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/plages-de-chios/plage-lefkathia/",
    language: "fr",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "lefkathia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/straende-chios/lefkathia-strand/",
    language: "de",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "lefkathia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/spiagge-chios/spiaggia-lefkathia/",
    language: "it",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "lefkathia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/playas-chios/playa-lefkathia/",
    language: "es",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "lefkathia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-plajlari/lefkathia-plaji/",
    language: "tr",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "lefkathia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/chios/chios-beaches/nagos-beach/",
    language: "en",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "nagos",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/el/paralies-xios/paralia-nagos/",
    language: "el",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "nagos",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/plages-de-chios/plage-nagos/",
    language: "fr",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "nagos",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/straende-chios/nagos-strand/",
    language: "de",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "nagos",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/spiagge-chios/spiaggia-nagos/",
    language: "it",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "nagos",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/playas-chios/playa-nagos/",
    language: "es",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "nagos",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-plajlari/nagos-plaji/",
    language: "tr",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "nagos",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/chios/chios-beaches/avlonia-beach2/",
    language: "en",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "avlonia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/el/paralies-xios/paralia-avlonia/",
    language: "el",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "avlonia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/plages-de-chios/plage-avlonia/",
    language: "fr",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "avlonia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/straende-chios/avlonia-strand/",
    language: "de",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "avlonia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/spiagge-chios/spiaggia-avlonia/",
    language: "it",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "avlonia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/playas-chios/playa-avlonia/",
    language: "es",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "avlonia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-plajlari/avlonia-plaji/",
    language: "tr",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "avlonia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/chios/chios-beaches/salagona-beach/",
    language: "en",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "salagona",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/el/paralies-xios/paralia-salagona/",
    language: "el",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "salagona",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/plages-de-chios/plage-salagona/",
    language: "fr",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "salagona",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/straende-chios/salagona-strand/",
    language: "de",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "salagona",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/spiagge-chios/spiaggia-salagona/",
    language: "it",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "salagona",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/playas-chios/playa-salagona/",
    language: "es",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "salagona",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-plajlari/salagona-plaji/",
    language: "tr",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "salagona",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/chios/chios-beaches/agia-fotia-beach/",
    language: "en",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "agia-fotia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/el/paralies-xios/paralia-agia-fotia/",
    language: "el",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "agia-fotia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/plages-de-chios/plage-agia-fotia/",
    language: "fr",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "agia-fotia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/straende-chios/agia-fotia-strand/",
    language: "de",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "agia-fotia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/spiagge-chios/spiaggia-agia-fotia/",
    language: "it",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "agia-fotia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/playas-chios/playa-agia-fotia/",
    language: "es",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "agia-fotia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-plajlari/agia-fotia-plaji/",
    language: "tr",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "agia-fotia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/chios/chios-beaches/komi-beach/",
    language: "en",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "komi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/el/paralies-xios/paralia-komi/",
    language: "el",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "komi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/plages-de-chios/plage-komi/",
    language: "fr",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "komi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/straende-chios/komi-strand/",
    language: "de",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "komi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/spiagge-chios/spiaggia-komi/",
    language: "it",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "komi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/playas-chios/playa-komi/",
    language: "es",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "komi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-plajlari/komi-plaji/",
    language: "tr",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "komi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/chios/chios-beaches/emporios-beach/",
    language: "en",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "emporios",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/el/paralies-xios/paralia-mavra-volia/",
    language: "el",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "emporios",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/plages-de-chios/plage-mavra-volia/",
    language: "fr",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "emporios",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/straende-chios/mavra-volia-strand/",
    language: "de",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "emporios",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/spiagge-chios/spiaggia-mavra-volia/",
    language: "it",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "emporios",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/playas-chios/playa-mavra-volia/",
    language: "es",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "emporios",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-plajlari/mavra-volia-plaji/",
    language: "tr",
    contentType: "chios-detail",
    category: "beaches",
    itemId: "emporios",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },

  {
    path: "/chios/chios-villages/chios-pyrgi/",
    language: "en",
    contentType: "chios-detail",
    category: "villages",
    itemId: "pyrgi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/chios/chios-villages/mesta-chios/",
    language: "en",
    contentType: "chios-detail",
    category: "villages",
    itemId: "mesta",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/chios/chios-villages/vessa-chios/",
    language: "en",
    contentType: "chios-detail",
    category: "villages",
    itemId: "vessa",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/chios/chios-villages/olympoi-chios/",
    language: "en",
    contentType: "chios-detail",
    category: "villages",
    itemId: "olympoi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/chios/chios-villages/volissos-chios/",
    language: "en",
    contentType: "chios-detail",
    category: "villages",
    itemId: "volissos",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/chios/chios-villages/armolia-chios/",
    language: "en",
    contentType: "chios-detail",
    category: "villages",
    itemId: "armolia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/chios/chios-villages/lagada-chios/",
    language: "en",
    contentType: "chios-detail",
    category: "villages",
    itemId: "lagada",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/el/xoria-xios/pyrgi-xios/",
    language: "el",
    contentType: "chios-detail",
    category: "villages",
    itemId: "pyrgi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/el/xoria-xios/mesta-xios/",
    language: "el",
    contentType: "chios-detail",
    category: "villages",
    itemId: "mesta",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/el/xoria-xios/vessa-xios/",
    language: "el",
    contentType: "chios-detail",
    category: "villages",
    itemId: "vessa",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/el/xoria-xios/olympoi-xios/",
    language: "el",
    contentType: "chios-detail",
    category: "villages",
    itemId: "olympoi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/el/xoria-xios/volissos-xios/",
    language: "el",
    contentType: "chios-detail",
    category: "villages",
    itemId: "volissos",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/el/xoria-xios/armolia-xios/",
    language: "el",
    contentType: "chios-detail",
    category: "villages",
    itemId: "armolia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/el/xoria-xios/lagada-xios/",
    language: "el",
    contentType: "chios-detail",
    category: "villages",
    itemId: "lagada",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/villages-de-chios/village-pyrgi/",
    language: "fr",
    contentType: "chios-detail",
    category: "villages",
    itemId: "pyrgi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/villages-de-chios/village-mesta/",
    language: "fr",
    contentType: "chios-detail",
    category: "villages",
    itemId: "mesta",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/villages-de-chios/village-vessa/",
    language: "fr",
    contentType: "chios-detail",
    category: "villages",
    itemId: "vessa",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/villages-de-chios/village-olympoi/",
    language: "fr",
    contentType: "chios-detail",
    category: "villages",
    itemId: "olympoi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/villages-de-chios/village-volissos/",
    language: "fr",
    contentType: "chios-detail",
    category: "villages",
    itemId: "volissos",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/villages-de-chios/village-armolia/",
    language: "fr",
    contentType: "chios-detail",
    category: "villages",
    itemId: "armolia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/villages-de-chios/village-lagada/",
    language: "fr",
    contentType: "chios-detail",
    category: "villages",
    itemId: "lagada",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/doerfer-chios/pyrgi-dorf/",
    language: "de",
    contentType: "chios-detail",
    category: "villages",
    itemId: "pyrgi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/doerfer-chios/mesta-dorf/",
    language: "de",
    contentType: "chios-detail",
    category: "villages",
    itemId: "mesta",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/doerfer-chios/vessa-dorf/",
    language: "de",
    contentType: "chios-detail",
    category: "villages",
    itemId: "vessa",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/doerfer-chios/olympoi-dorf/",
    language: "de",
    contentType: "chios-detail",
    category: "villages",
    itemId: "olympoi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/doerfer-chios/volissos-dorf/",
    language: "de",
    contentType: "chios-detail",
    category: "villages",
    itemId: "volissos",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/doerfer-chios/armolia-dorf/",
    language: "de",
    contentType: "chios-detail",
    category: "villages",
    itemId: "armolia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/doerfer-chios/lagada-dorf/",
    language: "de",
    contentType: "chios-detail",
    category: "villages",
    itemId: "lagada",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/villaggi-chios/villaggio-pyrgi/",
    language: "it",
    contentType: "chios-detail",
    category: "villages",
    itemId: "pyrgi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/villaggi-chios/villaggio-mesta/",
    language: "it",
    contentType: "chios-detail",
    category: "villages",
    itemId: "mesta",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/villaggi-chios/villaggio-vessa/",
    language: "it",
    contentType: "chios-detail",
    category: "villages",
    itemId: "vessa",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/villaggi-chios/villaggio-olympoi/",
    language: "it",
    contentType: "chios-detail",
    category: "villages",
    itemId: "olympoi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/villaggi-chios/villaggio-volissos/",
    language: "it",
    contentType: "chios-detail",
    category: "villages",
    itemId: "volissos",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/villaggi-chios/villaggio-armolia/",
    language: "it",
    contentType: "chios-detail",
    category: "villages",
    itemId: "armolia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/villaggi-chios/villaggio-lagada/",
    language: "it",
    contentType: "chios-detail",
    category: "villages",
    itemId: "lagada",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/pueblos-chios/pueblo-pyrgi/",
    language: "es",
    contentType: "chios-detail",
    category: "villages",
    itemId: "pyrgi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/pueblos-chios/pueblo-mesta/",
    language: "es",
    contentType: "chios-detail",
    category: "villages",
    itemId: "mesta",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/pueblos-chios/pueblo-vessa/",
    language: "es",
    contentType: "chios-detail",
    category: "villages",
    itemId: "vessa",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/pueblos-chios/pueblo-olympoi/",
    language: "es",
    contentType: "chios-detail",
    category: "villages",
    itemId: "olympoi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/pueblos-chios/pueblo-volissos/",
    language: "es",
    contentType: "chios-detail",
    category: "villages",
    itemId: "volissos",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/pueblos-chios/pueblo-armolia/",
    language: "es",
    contentType: "chios-detail",
    category: "villages",
    itemId: "armolia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/pueblos-chios/pueblo-lagada/",
    language: "es",
    contentType: "chios-detail",
    category: "villages",
    itemId: "lagada",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-koyleri/pyrgi-koyu/",
    language: "tr",
    contentType: "chios-detail",
    category: "villages",
    itemId: "pyrgi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-koyleri/mesta-koyu/",
    language: "tr",
    contentType: "chios-detail",
    category: "villages",
    itemId: "mesta",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-koyleri/vessa-koyu/",
    language: "tr",
    contentType: "chios-detail",
    category: "villages",
    itemId: "vessa",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-koyleri/olympoi-koyu/",
    language: "tr",
    contentType: "chios-detail",
    category: "villages",
    itemId: "olympoi",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-koyleri/volissos-koyu/",
    language: "tr",
    contentType: "chios-detail",
    category: "villages",
    itemId: "volissos",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-koyleri/armolia-koyu/",
    language: "tr",
    contentType: "chios-detail",
    category: "villages",
    itemId: "armolia",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-koyleri/lagada-koyu/",
    language: "tr",
    contentType: "chios-detail",
    category: "villages",
    itemId: "lagada",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },

  {
    path: "/chios/chios-museums/the-mastic-museum-chios/",
    language: "en",
    contentType: "chios-detail",
    category: "museums",
    itemId: "mastic-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/chios/chios-museums/archaeological-museum-chios/",
    language: "en",
    contentType: "chios-detail",
    category: "museums",
    itemId: "archaeological-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/chios/chios-museums/chios-maritime-museum/",
    language: "en",
    contentType: "chios-detail",
    category: "museums",
    itemId: "maritime-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },


  // Localized museum detail routes
  {
    path: "/el/mouseia-xios/mouseio-mastichas-xios/",
    language: "el",
    contentType: "chios-detail",
    category: "museums",
    itemId: "mastic-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/musees-de-chios/musee-du-mastic-chios/",
    language: "fr",
    contentType: "chios-detail",
    category: "museums",
    itemId: "mastic-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/museen-chios/mastix-museum-chios/",
    language: "de",
    contentType: "chios-detail",
    category: "museums",
    itemId: "mastic-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/musei-chios/museo-del-mastice-chios/",
    language: "it",
    contentType: "chios-detail",
    category: "museums",
    itemId: "mastic-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/museos-chios/museo-mastiha-chios/",
    language: "es",
    contentType: "chios-detail",
    category: "museums",
    itemId: "mastic-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-muzeleri/sakiz-mastik-muzesi/",
    language: "tr",
    contentType: "chios-detail",
    category: "museums",
    itemId: "mastic-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },

  {
    path: "/el/mouseia-xios/arxaiologiko-mouseio-xios/",
    language: "el",
    contentType: "chios-detail",
    category: "museums",
    itemId: "archaeological-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/musees-de-chios/musee-archeologique-chios/",
    language: "fr",
    contentType: "chios-detail",
    category: "museums",
    itemId: "archaeological-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/museen-chios/archaeologisches-museum-chios/",
    language: "de",
    contentType: "chios-detail",
    category: "museums",
    itemId: "archaeological-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/musei-chios/museo-archeologico-chios/",
    language: "it",
    contentType: "chios-detail",
    category: "museums",
    itemId: "archaeological-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/museos-chios/museo-arqueologico-chios/",
    language: "es",
    contentType: "chios-detail",
    category: "museums",
    itemId: "archaeological-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-muzeleri/arkeoloji-muzesi-sakiz/",
    language: "tr",
    contentType: "chios-detail",
    category: "museums",
    itemId: "archaeological-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },

  {
    path: "/chios/chios-museums/chios-byzantine-museum/",
    language: "en",
    contentType: "chios-detail",
    category: "museums",
    itemId: "byzantine-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/el/mouseia-xios/vyzantino-mouseio-xios/",
    language: "el",
    contentType: "chios-detail",
    category: "museums",
    itemId: "byzantine-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/musees-de-chios/musee-byzantin-chios/",
    language: "fr",
    contentType: "chios-detail",
    category: "museums",
    itemId: "byzantine-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/museen-chios/byzantinisches-museum-chios/",
    language: "de",
    contentType: "chios-detail",
    category: "museums",
    itemId: "byzantine-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/musei-chios/museo-bizantino-chios/",
    language: "it",
    contentType: "chios-detail",
    category: "museums",
    itemId: "byzantine-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/museos-chios/museo-bizantino-chios/",
    language: "es",
    contentType: "chios-detail",
    category: "museums",
    itemId: "byzantine-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-muzeleri/bizans-muzesi-sakiz/",
    language: "tr",
    contentType: "chios-detail",
    category: "museums",
    itemId: "byzantine-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },

  {
    path: "/chios/chios-museums/koraes-library-chios/",
    language: "en",
    contentType: "chios-detail",
    category: "museums",
    itemId: "koraes-library",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/el/mouseia-xios/vivliothiki-korai-xios/",
    language: "el",
    contentType: "chios-detail",
    category: "museums",
    itemId: "koraes-library",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/musees-de-chios/bibliotheque-korais-chios/",
    language: "fr",
    contentType: "chios-detail",
    category: "museums",
    itemId: "koraes-library",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/museen-chios/korais-bibliothek-chios/",
    language: "de",
    contentType: "chios-detail",
    category: "museums",
    itemId: "koraes-library",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/musei-chios/biblioteca-korais-chios/",
    language: "it",
    contentType: "chios-detail",
    category: "museums",
    itemId: "koraes-library",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/museos-chios/biblioteca-korais-chios/",
    language: "es",
    contentType: "chios-detail",
    category: "museums",
    itemId: "koraes-library",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-muzeleri/korais-kutuphanesi-sakiz/",
    language: "tr",
    contentType: "chios-detail",
    category: "museums",
    itemId: "koraes-library",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },

  {
    path: "/el/mouseia-xios/naftiko-mouseio-xios/",
    language: "el",
    contentType: "chios-detail",
    category: "museums",
    itemId: "maritime-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/musees-de-chios/musee-maritime-chios/",
    language: "fr",
    contentType: "chios-detail",
    category: "museums",
    itemId: "maritime-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/museen-chios/schifffahrtsmuseum-chios/",
    language: "de",
    contentType: "chios-detail",
    category: "museums",
    itemId: "maritime-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/musei-chios/museo-marittimo-chios/",
    language: "it",
    contentType: "chios-detail",
    category: "museums",
    itemId: "maritime-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/museos-chios/museo-maritimo-chios/",
    language: "es",
    contentType: "chios-detail",
    category: "museums",
    itemId: "maritime-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-muzeleri/denizcilik-muzesi-sakiz/",
    language: "tr",
    contentType: "chios-detail",
    category: "museums",
    itemId: "maritime-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },

  {
    path: "/chios/chios-museums/kallimasia-folklore-museum/",
    language: "en",
    contentType: "chios-detail",
    category: "museums",
    itemId: "kallimasia-folklore-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/el/mouseia-xios/laografiko-mouseio-kallimasias/",
    language: "el",
    contentType: "chios-detail",
    category: "museums",
    itemId: "kallimasia-folklore-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/musees-de-chios/musee-folklorique-kallimasia/",
    language: "fr",
    contentType: "chios-detail",
    category: "museums",
    itemId: "kallimasia-folklore-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/museen-chios/volkskundemuseum-kallimasia/",
    language: "de",
    contentType: "chios-detail",
    category: "museums",
    itemId: "kallimasia-folklore-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/musei-chios/museo-folkloristico-kallimasia/",
    language: "it",
    contentType: "chios-detail",
    category: "museums",
    itemId: "kallimasia-folklore-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/museos-chios/museo-folclorico-kallimasia/",
    language: "es",
    contentType: "chios-detail",
    category: "museums",
    itemId: "kallimasia-folklore-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-muzeleri/kallimasia-folklor-muzesi/",
    language: "tr",
    contentType: "chios-detail",
    category: "museums",
    itemId: "kallimasia-folklore-museum",
    template: "ChiosDetailPage",
    action: "KEEP",
    priority: "High",
  },

  {
    path: "/chios-holidays-quiz/",
    language: "en",
    contentType: "landing-page",
    category: "landing",
    itemId: "chios-quiz",
    template: "LandingPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/el/diakopes-sti-chio-quiz/",
    language: "el",
    contentType: "landing-page",
    category: "landing",
    itemId: "chios-quiz",
    template: "LandingPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/quiz-vacances-a-chios/",
    language: "fr",
    contentType: "landing-page",
    category: "landing",
    itemId: "chios-quiz",
    template: "LandingPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/chios-urlaubsquiz/",
    language: "de",
    contentType: "landing-page",
    category: "landing",
    itemId: "chios-quiz",
    template: "LandingPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/quiz-vacanze-a-chios/",
    language: "it",
    contentType: "landing-page",
    category: "landing",
    itemId: "chios-quiz",
    template: "LandingPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/quiz-vacaciones-en-quios/",
    language: "es",
    contentType: "landing-page",
    category: "landing",
    itemId: "chios-quiz",
    template: "LandingPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/sakiz-adasi-tatil-testi/",
    language: "tr",
    contentType: "landing-page",
    category: "landing",
    itemId: "chios-quiz",
    template: "LandingPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/chios-beach-lovers/",
    language: "en",
    contentType: "landing-page",
    category: "landing",
    itemId: "beach-lovers",
    template: "LandingPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/el/xios-gia-latreis-paralias/",
    language: "el",
    contentType: "landing-page",
    category: "landing",
    itemId: "beach-lovers",
    template: "LandingPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/fr/chios-pour-amoureux-de-plage/",
    language: "fr",
    contentType: "landing-page",
    category: "landing",
    itemId: "beach-lovers",
    template: "LandingPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/de/chios-fuer-strandliebhaber/",
    language: "de",
    contentType: "landing-page",
    category: "landing",
    itemId: "beach-lovers",
    template: "LandingPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/it/chios-per-amanti-del-mare/",
    language: "it",
    contentType: "landing-page",
    category: "landing",
    itemId: "beach-lovers",
    template: "LandingPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/es/quios-para-amantes-de-la-playa/",
    language: "es",
    contentType: "landing-page",
    category: "landing",
    itemId: "beach-lovers",
    template: "LandingPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/tr/plaj-severler-icin-sakiz-adasi/",
    language: "tr",
    contentType: "landing-page",
    category: "landing",
    itemId: "beach-lovers",
    template: "LandingPage",
    action: "KEEP",
    priority: "High",
  },
  {
    path: "/best-beaches-in-chios/",
    language: "en",
    contentType: "redirect-candidate",
    category: "landing",
    itemId: "best-beaches-old",
    template: "Redirect",
    action: "REDIRECT",
    priority: "Medium",
    canonicalPath: "/chios-beach-lovers/",
    notes: "Old Beach Lovers / best beaches landing page. Redirect to the new Beach Lovers landing page.",
  },
  {
    path: "/family-travel-in-chios/",
    language: "en",
    contentType: "landing-page",
    category: "landing",
    itemId: "family-travel",
    template: "LandingPage",
    action: "KEEP",
    priority: "Medium",
  },
  {
    path: "/el/oikogeneiakes-diakopes-sti-xio/",
    language: "el",
    contentType: "landing-page",
    category: "landing",
    itemId: "family-travel",
    template: "LandingPage",
    action: "KEEP",
    priority: "Medium",
  },
  {
    path: "/fr/vacances-en-famille-a-chios/",
    language: "fr",
    contentType: "landing-page",
    category: "landing",
    itemId: "family-travel",
    template: "LandingPage",
    action: "KEEP",
    priority: "Medium",
  },
  {
    path: "/de/familienurlaub-auf-chios/",
    language: "de",
    contentType: "landing-page",
    category: "landing",
    itemId: "family-travel",
    template: "LandingPage",
    action: "KEEP",
    priority: "Medium",
  },
  {
    path: "/it/vacanze-in-famiglia-a-chios/",
    language: "it",
    contentType: "landing-page",
    category: "landing",
    itemId: "family-travel",
    template: "LandingPage",
    action: "KEEP",
    priority: "Medium",
  },
  {
    path: "/es/vacaciones-en-familia-en-quios/",
    language: "es",
    contentType: "landing-page",
    category: "landing",
    itemId: "family-travel",
    template: "LandingPage",
    action: "KEEP",
    priority: "Medium",
  },
  {
    path: "/tr/sakiz-adasi-aile-tatili/",
    language: "tr",
    contentType: "landing-page",
    category: "landing",
    itemId: "family-travel",
    template: "LandingPage",
    action: "KEEP",
    priority: "Medium",
  },
  {
    path: "/10-best-tips-to-explore-chiosvoulamandis-house/",
    language: "en",
    contentType: "landing-page",
    category: "landing",
    itemId: "explore-chios",
    template: "LandingPage",
    action: "KEEP",
    priority: "Medium",
  },
  {
    path: "/taste-lover-chios/",
    language: "en",
    contentType: "landing-page",
    category: "landing",
    itemId: "taste-lover",
    template: "LandingPage",
    action: "KEEP",
    priority: "Medium",
  },

  {
    path: "/mike-2/",
    language: "en",
    contentType: "old-test",
    itemId: "mike",
    template: "Redirect",
    action: "CHECK",
    priority: "Low",
    canonicalPath: "/",
    notes: "Looks like test/old page. Check analytics before redirect.",
  },
  {
    path: "/es/mike/",
    language: "es",
    contentType: "old-test",
    itemId: "mike",
    template: "Redirect",
    action: "CHECK",
    priority: "Low",
    canonicalPath: "/es/",
    notes: "Looks like test/old page. Check analytics before redirect.",
  },
  {
    path: "/tr/offer/",
    language: "tr",
    contentType: "redirect-candidate",
    itemId: "old-offer",
    template: "Redirect",
    action: "CHECK",
    priority: "Low",
    canonicalPath: "/tr/sakiz-adasi-otel-firsatlari/",
    notes: "Likely old offer page.",
  },
];

export type RouteMapItem = RouteRecord;

export function getRouteByPath(path: string): RouteMapItem | undefined {
  const normalizedPath = normalizePath(path);

  return routeMap.find((route) => route.path === normalizedPath);
}

export function getRoutesByItemId(itemId: string): RouteMapItem[] {
  return routeMap.filter((route) => route.itemId === itemId);
}

export function getRoutesByTemplate(template: PageTemplate): RouteMapItem[] {
  return routeMap.filter((route) => route.template === template);
}

export function getRoutesByLanguage(language: LanguageCode): RouteMapItem[] {
  return routeMap.filter((route) => route.language === language);
}

export function getLocalizedRoutes(path: string): RouteMapItem[] {
  const route = getRouteByPath(path);

  if (!route) {
    return [];
  }

  return getRoutesByItemId(route.itemId);
}

export function getCanonicalPath(path: string): string {
  const route = getRouteByPath(path);

  if (!route) {
    return normalizePath(path);
  }

  return normalizePath(route.canonicalPath || route.path);
}