export type BeachRegion = "near-city" | "northwest" | "northeast" | "west" | "south";

export type FamilyFit = "excellent" | "yes" | "yes-with-caution" | "older-children" | "not-recommended";

export type BeachMaster = {
  id: string;
  name: string;
  region: BeachRegion;
  image: string | null;
  bestTime?: string;
  recommendedDuration?: string;
  familyFit?: FamilyFit;
  familyNote?: string;
  character?: string[];
  surface?: string[];
  depth?: string;
  organization?: string;
  amenities?: string[];
  access?: string[];
  shade?: string;
  windNote?: string;
  highlights?: string[];
  tip?: string;
  pairWith?: string[];
  tags: string[];
  mapQuery: string;
};

export const excludedTripPlannerBeaches = [
  "Agia Irini",
  "Agios Isidoros",
  "Bella Vista",
  "Tagma / Agia Paraskevi",
] as const;

export const beaches: BeachMaster[] = [
  {
    id: "agia-dynami",
    name: "Αγία Δύναμη",
    region: "south",
    image: null,
    bestTime: "Νωρίς το πρωί, πριν γεμίσει και για να βρεις φυσική σκιά.",
    recommendedDuration: "3–4 ώρες",
    familyFit: "yes",
    character: ["ήσυχη", "φυσική", "πικνίκ"],
    organization: "Μη οργανωμένη",
    shade: "Υπάρχει φυσική σκιά, αλλά είναι περιορισμένη.",
    highlights: ["Μικρό ξωκλήσι κοντά στην παραλία", "Καλή επιλογή για πικνίκ"],
    tip: "Πήγαινε νωρίς και πάρε νερό/φαγητό μαζί σου, γιατί δεν υπάρχει οργανωμένη καντίνα.",
    pairWith: ["Ολύμποι", "Μεστά"],
    tags: ["family", "early-morning", "natural-shade", "picnic", "unorganized", "mastichochoria"],
    mapQuery: "Agia Dynami Beach Chios",
  },
  {
    id: "agia-fotia",
    name: "Αγία Φωτιά",
    region: "south",
    image: null,
    bestTime: "Νωρίς, επειδή το βασικό πάρκινγκ είναι μικρό.",
    recommendedDuration: "4 ώρες",
    familyFit: "yes",
    character: ["κοσμοπολίτικη", "ζωντανή", "κοντινή επιλογή"],
    organization: "Οργανωμένη",
    amenities: ["beach bars", "ξαπλώστρες με χρέωση"],
    access: ["Μικρό δημόσιο πάρκινγκ", "Υπάρχουν και ιδιωτικά πάρκινγκ με χρέωση"],
    highlights: ["Καλή κοντινή επιλογή όταν κάποιος είναι κουρασμένος και θέλει κάτι εύκολο και όμορφο"],
    tags: ["nearby", "family", "beach-bar", "paid-sunbeds", "cosmopolitan", "easy-option"],
    mapQuery: "Agia Fotia Beach Chios",
  },
  {
    id: "apothika",
    name: "Απόθικα",
    region: "south",
    image: null,
    bestTime: "Νωρίς το πρωί.",
    recommendedDuration: "Μπορεί να γίνει ολοήμερη στάση και να μείνεις μέχρι το βράδυ.",
    familyFit: "yes-with-caution",
    character: ["εξερεύνηση", "κρυφές γωνιές", "ολοήμερη"],
    surface: ["μικρό βότσαλο", "χοντρή άμμος"],
    depth: "Κανονικό",
    organization: "Οργανωμένη",
    amenities: ["καντίνα", "ομπρέλες/ξαπλώστρες", "κανό", "kayak", "SUP", "καταδύσεις"],
    access: ["Αυτοκίνητο", "Χωματόδρομος στο τελευταίο τμήμα"],
    highlights: ["Κρυφές σπηλιές/μικρές απομονωμένες γωνιές σαν μίνι παραλίες"],
    pairWith: ["Μεστά"],
    tags: ["full-day", "hidden-coves", "exploration", "organized", "canteen", "water-activities", "mesta"],
    mapQuery: "Apothika Beach Chios",
  },
  {
    id: "avlonia",
    name: "Αυλωνιά",
    region: "south",
    image: null,
    bestTime: "Από το μεσημέρι μέχρι αργά το απόγευμα.",
    recommendedDuration: "3–4 ώρες",
    familyFit: "yes",
    character: ["μαγική", "πανέμορφη"],
    organization: "Οργανωμένη",
    pairWith: ["Πυργί", "Μεστά", "Ολύμποι"],
    tags: ["beautiful", "family", "organized", "afternoon", "mastichochoria"],
    mapQuery: "Avlonia Beach Chios",
  },
  {
    id: "vroulidia",
    name: "Βρουλίδια",
    region: "south",
    image: null,
    bestTime: "Νωρίς.",
    recommendedDuration: "2–3 ώρες",
    familyFit: "yes",
    character: ["μικρή", "πολύ όμορφη"],
    amenities: ["καντίνα ψηλά από την παραλία"],
    access: ["Κατεβαίνεις την πλαγιά από τσιμεντένιο δρομάκι"],
    windNote: "Απάνεμη στον βοριά, όχι καλή επιλογή με νότιο άνεμο.",
    pairWith: ["Πυργί", "Μουσείο Μαστίχας", "Μαύρα Βόλια", "Κώμη για φαγητό"],
    tags: ["small", "beautiful", "family", "north-wind-shelter", "canteen", "pyrgi", "mastic-museum", "mavra-volia"],
    mapQuery: "Vroulidia Beach Chios",
  },
  {
    id: "kato-fana",
    name: "Κάτω Φανά",
    region: "south",
    image: null,
    bestTime: "Από το μεσημέρι μέχρι το απόγευμα.",
    recommendedDuration: "3–4 ώρες",
    familyFit: "yes",
    character: ["ήσυχη", "φυσική"],
    surface: ["άμμος"],
    depth: "Ρηχά",
    organization: "Μη οργανωμένη",
    access: ["Αυτοκίνητο", "Χωματόδρομος"],
    shade: "Υπάρχει φυσική σκιά.",
    amenities: ["χωρίς ναυαγοσώστη", "χωρίς θαλάσσιες δραστηριότητες", "χωρίς εστιατόριο κοντά"],
    pairWith: ["Ολύμποι"],
    tags: ["family", "sand", "shallow", "natural-shade", "quiet", "olympoi"],
    mapQuery: "Kato Fana Beach Chios",
  },
  {
    id: "komi",
    name: "Κώμη",
    region: "south",
    image: null,
    bestTime: "Όλη την ημέρα. Για περισσότερη ησυχία, προτίμησε το απόγευμα.",
    recommendedDuration: "Ολοήμερη επιλογή",
    familyFit: "excellent",
    character: ["κοσμοπολίτικη", "ζωντανή", "πλήρως εξυπηρετούμενη"],
    surface: ["άμμος"],
    depth: "Ρηχά",
    organization: "Οργανωμένη",
    amenities: ["beach bars", "ομπρέλες", "ξαπλώστρες", "ναυαγοσώστης", "θαλάσσιες δραστηριότητες", "εστιατόρια/ταβέρνες"],
    access: ["Αυτοκίνητο", "Λεωφορείο", "Πρόσβαση ΑμεΑ"],
    shade: "Χωρίς φυσική σκιά.",
    pairWith: ["Μουσείο Μαστίχας", "Καλαμωτή"],
    tip: "Αν θέλεις πιο ήρεμη εμπειρία, προτίμησέ την το απόγευμα.",
    tags: ["full-day", "family", "cosmopolitan", "sand", "shallow", "organized", "food", "water-sports", "mastic-museum", "kalamoti"],
    mapQuery: "Komi Beach Chios",
  },
  {
    id: "lilikas",
    name: "Λιλικάς",
    region: "south",
    image: null,
    bestTime: "09:00–12:00 ή μετά τις 17:30.",
    recommendedDuration: "3–4 ώρες",
    familyFit: "yes-with-caution",
    familyNote: "Ήσυχη και εύκολη, αλλά έχει βότσαλο/πέτρες και δεν υπάρχει ναυαγοσώστης.",
    character: ["ήσυχος", "γραφικός", "χαλαρωτικός"],
    surface: ["βότσαλα"],
    depth: "Ρηχά",
    organization: "Με βασικές ανέσεις κοντά",
    amenities: ["φαγητό κοντά"],
    access: ["Αυτοκίνητο", "Πεζή πρόσβαση"],
    shade: "Φυσική σκιά από αρμυρίκια.",
    tip: "Πάρε παπούτσια θαλάσσης και μάσκα για snorkeling.",
    pairWith: ["Μουσείο Μαστίχας", "Πυργί", "Μεστά", "Κώμη", "Μαύρα Βόλια"],
    tags: ["quiet", "family", "pebble", "shallow", "natural-shade", "snorkeling", "mastichochoria"],
    mapQuery: "Lilikas Beach Chios",
  },
  {
    id: "mavra-volia",
    name: "Μαύρα Βόλια",
    region: "south",
    image: null,
    bestTime: "08:30–11:30.",
    recommendedDuration: "2–3 ώρες",
    familyFit: "older-children",
    familyNote: "Όχι ιδανική για πολύ μικρά παιδιά· καλύτερη για μεγαλύτερα παιδιά και εφήβους.",
    character: ["εμβληματική", "ηφαιστειακή", "εντυπωσιακή"],
    surface: ["μεγάλα μαύρα ηφαιστειακά βότσαλα"],
    depth: "Βαθιά και απότομα νερά",
    shade: "Χωρίς φυσική σκιά.",
    highlights: ["Περπάτημα μέχρι τη δεύτερη συνεχόμενη παραλία / Φώκι"],
    tip: "Πήγαινε νωρίς και πάρε παπούτσια θαλάσσης ή σταθερές σαγιονάρες και ομπρέλα.",
    pairWith: ["Εμπορειός για φαγητό", "Πυργί", "Ολύμποι", "Αρχαιολογικός Χώρος Εμπορειού"],
    tags: ["must-see", "volcanic", "deep-water", "older-children", "no-shade", "pyrgi", "olympoi", "emporios"],
    mapQuery: "Mavra Volia Beach Chios",
  },
  {
    id: "salagona",
    name: "Σαλάγωνα",
    region: "south",
    image: null,
    bestTime: "14:00–20:30.",
    recommendedDuration: "3–4 ώρες",
    familyFit: "older-children",
    character: ["απομονωμένη", "άγρια", "ατμοσφαιρική"],
    surface: ["χοντρό βότσαλο", "πέτρες"],
    organization: "Beach bar",
    access: ["Χωματόδρομος", "Χρειάζεται προσοχή με χαμηλό αυτοκίνητο"],
    highlights: ["Ηλιοβασίλεμα"],
    tip: "Μην φύγεις πριν το ηλιοβασίλεμα και πάρε παπούτσια θαλάσσης. Προσοχή στην επιστροφή μετά το σούρουπο λόγω χωματόδρομου.",
    pairWith: ["Μεστά", "Λιμένας Μεστών", "Αυλωνιά"],
    tags: ["sunset", "quiet", "remote", "beach-bar", "dirt-road", "older-children", "mesta"],
    mapQuery: "Salagona Beach Chios",
  },
  {
    id: "trachilia-south",
    name: "Τραχήλια",
    region: "south",
    image: null,
    bestTime: "09:00–13:00.",
    recommendedDuration: "2–3 ώρες",
    familyFit: "not-recommended",
    familyNote: "Δεν είναι καλή επιλογή για οικογένειες με μικρά παιδιά.",
    character: ["παρθένα", "απομονωμένη", "άγρια"],
    organization: "Εντελώς ανοργάνωτη",
    access: ["Χωματόδρομος", "Προσοχή με χαμηλό αυτοκίνητο"],
    highlights: ["Δύο μικροί όρμοι που χωρίζονται από στενή λωρίδα γης", "Ψαρόσπιτα, βάρκες και θέα προς τη βραχονησίδα Μουλά"],
    tip: "Πάρε νερό, σνακ, ομπρέλα και παπούτσια θαλάσσης.",
    pairWith: ["Μεστά", "Λιμένας Μεστών", "Σπήλαιο Ολύμπων"],
    tags: ["remote", "wild", "quiet", "dirt-road", "no-facilities", "couples", "mesta"],
    mapQuery: "Trachilia Beach Chios Mesta",
  },
  {
    id: "lithi",
    name: "Λιθί",
    region: "west",
    image: null,
    bestTime: "Από το μεσημέρι (13:00) μέχρι το βράδυ.",
    recommendedDuration: "4+ ώρες",
    familyFit: "excellent",
    character: ["οικογενειακή", "γραφικό λιμανάκι", "sunset"],
    surface: ["ψιλή άμμος"],
    depth: "Πολύ ρηχά νερά για μεγάλη απόσταση",
    organization: "Οργανωμένη",
    amenities: ["ξαπλώστρες", "ντουζιέρες", "ψαροταβέρνες"],
    highlights: ["Ηλιοβασίλεμα"],
    tip: "Μην φύγεις νωρίς· αξίζει να μείνεις για το ηλιοβασίλεμα.",
    pairWith: ["Βέσσα", "Φαγητό στο Λιθί"],
    tags: ["family", "sand", "shallow", "organized", "food", "sunset"],
    mapQuery: "Lithi Beach Chios",
  },
  {
    id: "elinta",
    name: "Ελίντα",
    region: "west",
    image: null,
    bestTime: "09:00–12:00 ή νωρίς το απόγευμα.",
    recommendedDuration: "2–3 ώρες",
    familyFit: "older-children",
    familyNote: "Όχι για πολύ μικρά παιδιά.",
    character: ["κλειστός κόλπος", "απομονωμένη", "φυσική"],
    surface: ["λευκό βότσαλο"],
    depth: "Βαθαίνει απότομα",
    organization: "Εντελώς ανοργάνωτη",
    access: ["Σύντομο κομμάτι χωματόδρομου/τσιμεντόδρομου"],
    tip: "Πάρε ομπρέλα, νερό και παπούτσια θαλάσσης.",
    pairWith: ["Ανάβατος", "Αυγώνυμα"],
    tags: ["remote", "deep-water", "unorganized", "older-children", "anavatos", "avgonyma"],
    mapQuery: "Elinta Beach Chios",
  },
  {
    id: "trachili-west",
    name: "Τραχήλι",
    region: "west",
    image: null,
    bestTime: "09:00–12:30.",
    recommendedDuration: "2 ώρες",
    familyFit: "not-recommended",
    character: ["γραφική χερσόνησος", "άγρια", "απομονωμένη"],
    surface: ["λευκή άμμος", "βότσαλο"],
    organization: "Ανοργάνωτη",
    access: ["Το τελευταίο κομμάτι μπορεί να είναι απαιτητικό για απλό ΙΧ"],
    highlights: ["Μεσαιωνική βίγλα πάνω στον λόφο", "Πανοραμική θέα"],
    tip: "Αξίζει το μονοπάτι μέχρι τη βίγλα. Αν χρειαστεί, άφησε το αυτοκίνητο πιο ψηλά.",
    pairWith: ["Λιθί"],
    tags: ["remote", "wild", "vigla", "viewpoint", "not-small-children", "lithi"],
    mapQuery: "Trachili Beach Lithi Chios",
  },
  {
    id: "tigani",
    name: "Τηγάνι",
    region: "west",
    image: null,
    bestTime: "Μετά τις 17:00 μέχρι το ηλιοβασίλεμα.",
    recommendedDuration: "2–3 ώρες",
    familyFit: "older-children",
    familyNote: "Καλή κυρίως για μεγαλύτερα παιδιά που αγαπούν τις εξερευνήσεις.",
    character: ["κρυμμένη", "απομονωμένη", "φυσική"],
    surface: ["ψιλό βότσαλο", "άμμος"],
    organization: "Ανοργάνωτη",
    highlights: ["Εντυπωσιακός βυθός", "Μικροί ύφαλοι και νησάκια", "Πεύκα κοντά στο νερό"],
    tip: "Ιδανική για snorkeling και ψάρεμα· πάρε μάσκα και βατραχοπέδιλα.",
    pairWith: ["Σιδηρούντα"],
    tags: ["sunset", "snorkeling", "fishing", "remote", "older-children", "sidirounta"],
    mapQuery: "Tigani Beach Chios Sidirounta",
  },
  {
    id: "agia-markella",
    name: "Αγία Μαρκέλλα",
    region: "northwest",
    image: null,
    bestTime: "08:30–11:30.",
    recommendedDuration: "2 ώρες",
    familyFit: "yes-with-caution",
    familyNote: "Με προσοχή λόγω κρύων, βαθιών νερών και πιθανών κυμάτων.",
    character: ["θρησκευτικό ορόσημο", "ιστορική", "βόρεια ακτή"],
    highlights: ["Προσκύνημα Αγίας Μαρκέλλας", "Μονοπάτι προς το αγίασμα"],
    tip: "Περπάτησε το μονοπάτι μέχρι το αγίασμα με κλειστά παπούτσια γιατί τα βράχια γλιστρούν.",
    pairWith: ["Βολισσός"],
    tags: ["pilgrimage", "history", "deep-water", "cold-water", "volissos"],
    mapQuery: "Agia Markella Beach Chios",
  },
  {
    id: "agiasmata",
    name: "Αγιάσματα",
    region: "northwest",
    image: null,
    bestTime: "Νωρίς το μεσημέρι ή αργά το απόγευμα.",
    recommendedDuration: "2 ώρες",
    familyFit: "not-recommended",
    familyNote: "Όχι για μικρά παιδιά.",
    character: ["άγρια", "επιβλητική", "απομονωμένη"],
    highlights: ["Ιαματικά λουτρά / υδροθεραπευτήριο", "Μεταλλικά νερά"],
    windNote: "Ανοιχτή στο πέλαγος· με βόρειο άνεμο χρειάζεται μεγάλη προσοχή στο κολύμπι.",
    tip: "Μην πηγαίνεις στα βαθιά όταν έχει μελτέμι. Συνδύασέ την με τα λουτρά.",
    pairWith: ["Κέραμος", "Λεπτόποδα", "Ορεινά χωριά Αμανής"],
    tags: ["thermal-baths", "wild", "remote", "wind-aware", "amani"],
    mapQuery: "Agiasmata Beach Chios",
  },
  {
    id: "managros",
    name: "Μάναγρος",
    region: "northwest",
    image: null,
    bestTime: "Από το μεσημέρι μέχρι το ηλιοβασίλεμα.",
    recommendedDuration: "2–3 ώρες",
    familyFit: "yes-with-caution",
    character: ["απέραντη", "ήσυχη", "απομονωμένη"],
    surface: ["άμμος", "ψιλό βότσαλο"],
    organization: "Σχεδόν όλη η έκταση ανοργάνωτη",
    tip: "Πάρε δική σου ομπρέλα, νερό και σνακ.",
    pairWith: ["Λημνιά"],
    tags: ["large-beach", "quiet", "remote", "sunset", "unorganized", "limnia"],
    mapQuery: "Managros Beach Chios",
  },
  {
    id: "limnos-volissos",
    name: "Λήμνος",
    region: "northwest",
    image: null,
    bestTime: "12:00–17:00.",
    recommendedDuration: "3+ ώρες",
    familyFit: "yes",
    character: ["ισορροπημένη", "οργανωμένη", "κοσμοπολίτικη"],
    surface: ["ψιλό βότσαλο", "άμμος"],
    depth: "Βαθιά, καθαρά νερά",
    organization: "Οργανωμένη",
    amenities: ["ξαπλώστρες", "beach bars", "εστιατόρια"],
    pairWith: ["Λημνιά / Λιμένας Βολισσού"],
    tags: ["family", "organized", "food", "deep-water", "volissos", "limnia"],
    mapQuery: "Limnos Beach Volissos Chios",
  },
  {
    id: "lefkathia",
    name: "Λευκάθια",
    region: "northwest",
    image: null,
    bestTime: "09:00–12:30.",
    recommendedDuration: "3 ώρες",
    familyFit: "excellent",
    character: ["δημοφιλής", "προστατευμένος κόλπος", "οργανωμένη"],
    surface: ["ψιλή σκούρη άμμος", "μικρό βότσαλο"],
    depth: "Βαθιά, καθαρά νερά",
    organization: "Οργανωμένη με beach bar",
    shade: "Πεύκα και αρμυρίκια γύρω από την παραλία.",
    tip: "Πήγαινε νωρίς, ειδικά τα Σαββατοκύριακα, γιατί ο διαθέσιμος χώρος γεμίζει γρήγορα.",
    pairWith: ["Λήμνος", "Κάστρο Βολισσού"],
    tags: ["family", "organized", "beach-bar", "volissos", "sunset-pairing"],
    mapQuery: "Lefkathia Beach Chios",
  },
  {
    id: "giosonas",
    name: "Γιόσωνας",
    region: "northeast",
    image: null,
    bestTime: "13:00–17:00.",
    recommendedDuration: "2–3 ώρες",
    familyFit: "older-children",
    character: ["άγρια ομορφιά", "ανοιχτός ορίζοντας", "δροσερά νερά"],
    surface: ["μεγάλα βότσαλα"],
    depth: "Βαθαίνει απότομα",
    organization: "Beach bar",
    windNote: "Εκτεθειμένη στους βορειάδες.",
    highlights: ["Στην ευρύτερη περιοχή του Φαραγγιού Καμπιών"],
    tip: "Πάρε παπούτσια θαλάσσης για τα μεγάλα βότσαλα.",
    pairWith: ["Καμπιά", "Μάρμαρα"],
    tags: ["wild", "older-children", "beach-bar", "wind-aware", "kampia", "kardamyla"],
    mapQuery: "Giosonas Beach Chios",
  },
  {
    id: "nagos",
    name: "Ναγός",
    region: "northeast",
    image: null,
    bestTime: "09:00–12:00.",
    recommendedDuration: "2–3 ώρες",
    familyFit: "yes-with-caution",
    familyNote: "Εύκολη επιλογή με ταβέρνες κοντά, αλλά τα νερά είναι πολύ κρύα και βαθαίνουν απότομα.",
    character: ["πράσινος", "δροσερός", "γραφικός κόλπος"],
    surface: ["πολύχρωμα βότσαλα"],
    depth: "Βαθαίνει απότομα",
    shade: "Πλούσια βλάστηση και πλατάνια κοντά στην ακτή.",
    highlights: ["Φυσικές πηγές με τρεχούμενα νερά"],
    pairWith: ["Άνω Καρδάμυλα", "Κάτω Καρδάμυλα", "Λιμάνι Καρδαμύλων"],
    tags: ["green", "springs", "cold-water", "family-caution", "kardamyla"],
    mapQuery: "Nagos Beach Chios",
  },
  {
    id: "karfas",
    name: "Καρφάς",
    region: "near-city",
    image: null,
    bestTime: "Οποιαδήποτε ώρα της ημέρας.",
    recommendedDuration: "4+ ώρες",
    familyFit: "excellent",
    character: ["οργανωμένη", "τουριστική", "αμμώδης"],
    surface: ["ψιλή χρυσή άμμος"],
    depth: "Πολύ ρηχά, ζεστά νερά",
    organization: "Πλήρως οργανωμένη",
    amenities: ["ταβέρνες", "beach bars", "θαλάσσια σπορ", "καταδύσεις"],
    tip: "Για περισσότερη ησυχία, απέφυγε τα Σαββατοκύριακα του Αυγούστου.",
    pairWith: ["Κάμπος Χίου", "Παραλιακός δρόμος Καρφά"],
    tags: ["family", "sand", "shallow", "organized", "nearby", "food", "water-sports", "kambos"],
    mapQuery: "Karfas Beach Chios",
  },
  {
    id: "megas-limnionas",
    name: "Μέγας Λιμνιώνας",
    region: "near-city",
    image: null,
    bestTime: "Μεσημέρι προς απόγευμα.",
    recommendedDuration: "3 ώρες",
    familyFit: "excellent",
    character: ["κλασική", "οργανωμένη", "παραδοσιακή ατμόσφαιρα"],
    surface: ["ψιλό βότσαλο", "άμμος"],
    depth: "Ρηχά, ζεστά νερά",
    organization: "Οργανωμένη",
    amenities: ["ταβέρνες", "ενοικιαζόμενα δωμάτια"],
    pairWith: ["Θυμιανά", "Φαγητό στον Μέγα Λιμνιώνα"],
    tags: ["family", "organized", "shallow", "food", "nearby", "thymiana"],
    mapQuery: "Megas Limnionas Beach Chios",
  },
  {
    id: "daskalopetra",
    name: "Δασκαλόπετρα",
    region: "near-city",
    image: null,
    bestTime: "09:00–12:00.",
    recommendedDuration: "2 ώρες",
    familyFit: "yes-with-caution",
    familyNote: "Καλή για οικογένεια, αλλά έχει μεγάλο βότσαλο.",
    character: ["ιστορική", "εύκολη", "Βροντάδος"],
    surface: ["μεγάλα λευκά βότσαλα"],
    organization: "Οργανωμένη",
    highlights: ["Πέτρα του Ομήρου πάνω από την παραλία"],
    tip: "Συνδύασε το μπάνιο με τη σύντομη ανάβαση στην Πέτρα του Ομήρου και πάρε παπούτσια θαλάσσης.",
    pairWith: ["Λιμανάκι Δασκαλόπετρας"],
    tags: ["history", "family-caution", "organized", "homer", "vrontados"],
    mapQuery: "Daskalopetra Beach Chios",
  },
  {
    id: "afanis-naftis",
    name: "Αφανής Ναύτης",
    region: "near-city",
    image: null,
    bestTime: "Μεσημέρι ή αργότερα για γρήγορη βουτιά.",
    recommendedDuration: "1–2 ώρες",
    familyFit: "yes",
    character: ["γρήγορη βουτιά", "εύκολη πρόσβαση", "Βροντάδος"],
    surface: ["μικρά βότσαλα"],
    highlights: ["Άγαλμα Αφανούς Ναύτη"],
    windNote: "Με δυνατό βόρειο άνεμο μπορεί να έχει μεγάλο κύμα και προσελκύει windsurfing.",
    pairWith: ["Μύλοι Βροντάδου"],
    tags: ["quick-swim", "near-city", "windsurfing", "vrontados", "mills"],
    mapQuery: "Afanis Naftis Beach Chios",
  },
  {
    id: "glaroi",
    name: "Γλάροι",
    region: "near-city",
    image: null,
    bestTime: "Από τις 14:00 μέχρι αργά το απόγευμα.",
    recommendedDuration: "3–4 ώρες",
    familyFit: "not-recommended",
    character: ["νεανική", "ζωντανή", "beach bar"],
    surface: ["ψιλή άμμος"],
    depth: "Βαθύς κόλπος",
    organization: "Οργανωμένη με beach bar",
    tip: "Η παραλία είναι μικρή και οι ξαπλώστρες γεμίζουν γρήγορα· πήγαινε σχετικά νωρίς αν θέλεις θέση.",
    pairWith: ["Glaroi Beach Bar"],
    tags: ["youth", "beach-bar", "music", "sand", "deep-water", "near-city"],
    mapQuery: "Glaroi Beach Chios",
  },
  {
    id: "ormos-lo",
    name: "Όρμος Λω",
    region: "near-city",
    image: null,
    bestTime: "Πρωί ή απόγευμα.",
    recommendedDuration: "2–3 ώρες",
    familyFit: "yes",
    character: ["μικρή", "οργανωμένη", "προστατευμένη"],
    surface: ["άμμος", "ψιλό βότσαλο"],
    organization: "Οργανωμένη",
    highlights: ["Χρησιμοποιείται και για κολυμβητική προπόνηση"],
    pairWith: ["Βροντάδος για καφέ ή φαγητό"],
    tags: ["family", "organized", "sheltered", "swimming", "vrontados"],
    mapQuery: "Ormos Lo Beach Chios",
  },
  {
    id: "mersinidi",
    name: "Μερσινίδι",
    region: "near-city",
    image: null,
    bestTime: "Μετά τις 17:00.",
    recommendedDuration: "2 ώρες",
    familyFit: "yes-with-caution",
    character: ["ήσυχος κόλπος", "φυσική", "κοντά στην πόλη"],
    organization: "Ανοργάνωτη",
    shade: "Το απόγευμα ο μεγάλος βράχος δημιουργεί φυσική σκιά στην ακτή.",
    access: ["Σύντομο βατό μονοπάτι"],
    highlights: ["Κάτω από τη Μονή Παναγίας Μυρσινιδιώτισσας"],
    pairWith: ["Μονή Μυρσινιδίου"],
    tags: ["quiet", "unorganized", "afternoon", "natural-shade", "near-city", "monastery"],
    mapQuery: "Mersinidi Beach Chios",
  },
];

export const beachesById = Object.fromEntries(beaches.map((beach) => [beach.id, beach])) as Record<string, BeachMaster>;

export const beachesByRegion = beaches.reduce<Record<BeachRegion, BeachMaster[]>>(
  (acc, beach) => {
    acc[beach.region].push(beach);
    return acc;
  },
  { "near-city": [], northwest: [], northeast: [], west: [], south: [] },
);
