export type PlannerExtraCategory = "sights" | "food" | "drink";
export type PlannerExtraRegion = "NW" | "NE" | "SW" | "SE";
export type PlannerFoodStopType = "meal" | "quick" | "sweet" | "cafe" | "drink";

export type PlannerExtraPlace = {
  id: string;
  name: string;
  category: PlannerExtraCategory;
  region: PlannerExtraRegion;
  image: string | null;
  meta: string;
  location?: string;
  cuisineType?: string;
  priceRange?: string;
  whyWeRecommendIt?: string;
  stopType?: PlannerFoodStopType;
  idealForLunch?: boolean;
};

type CuratedFoodPlace = {
  id: string;
  name: string;
  regions: PlannerExtraRegion[];
  location: string;
  cuisineType: string;
  priceRange: string;
  whyWeRecommendIt: string;
  shortWhy: string;
  stopType: PlannerFoodStopType;
  idealForLunch: boolean;
};

const curatedFoodPlaces: CuratedFoodPlace[] = [
  {
    id: "karagiorgis-taverna",
    name: "Karagiorgis Taverna",
    regions: ["SE", "SW"],
    location: "Εμπορειός",
    cuisineType: "Θαλασσινά & Ψαρικά",
    priceRange: "€€",
    whyWeRecommendIt: "Ιδανική επιλογή αμέσως μετά το μπάνιο στα Μαύρα Βόλια. Φρέσκο ψάρι και ουζάκι κυριολεκτικά δίπλα στο κύμα, στο γραφικό λιμανάκι του Εμπορειού.",
    shortWhy: "Μετά τα Μαύρα Βόλια, δίπλα στο κύμα.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "poseidonas-emporios",
    name: "Ποσειδώνας",
    regions: ["SE", "SW"],
    location: "Εμπορειός",
    cuisineType: "Ελληνική Κουζίνα / Θαλασσινά",
    priceRange: "€€",
    whyWeRecommendIt: "Αγαπημένη επιλογή στο λιμανάκι του Εμπορειού. Προσφέρει χορταστικές μερίδες, παραδοσιακές γεύσεις και φρέσκα ψάρια, ακριβώς δίπλα στο μονοπάτι για τα Μαύρα Βόλια.",
    shortWhy: "Παραδοσιακές γεύσεις στο λιμανάκι του Εμπορειού.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "volcano-emporios",
    name: "Volcano",
    regions: ["SE", "SW"],
    location: "Εμπορειός",
    cuisineType: "Ελληνική / Μεσογειακή / Πίτσα",
    priceRange: "€€",
    whyWeRecommendIt: "Πολύ καλό σημείο στο λιμάνι με μεγάλη ποικιλία στο μενού. Πέρα από τα παραδοσιακά, είναι εξαιρετική επιλογή αν η παρέα θέλει πίτσα και ζυμαρικά μετά το μπάνιο.",
    shortWhy: "Μεγάλη ποικιλία για παρέες μετά το μπάνιο.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "porto-emporios",
    name: "Porto Emporios",
    regions: ["SE", "SW"],
    location: "Εμπορειός",
    cuisineType: "Ελληνική / Μεσογειακή / Θαλασσινά",
    priceRange: "€-€€",
    whyWeRecommendIt: "Μια εξαιρετική και προσεγμένη επιλογή στο λιμάνι του Εμπορειού. Προσφέρει χαλαρή ατμόσφαιρα, ιδανική για ένα απολαυστικό γεύμα με θέα τη θάλασσα και τα καΐκια.",
    shortWhy: "Χαλαρό γεύμα με θέα στο λιμανάκι.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "lava-stones",
    name: "Lava Stones",
    regions: ["SE", "SW"],
    location: "Εμπορειός",
    cuisineType: "Ελληνική / Μεσογειακή / Ελαφρύ Γεύμα",
    priceRange: "€",
    whyWeRecommendIt: "Ιδανικό σημείο για δροσερό καφέ, ποτό ή σνακ. Βρίσκεται ακριβώς στο μονοπάτι προς τα Μαύρα Βόλια.",
    shortWhy: "Εύκολη στάση στο μονοπάτι για Μαύρα Βόλια.",
    stopType: "quick",
    idealForLunch: true,
  },
  {
    id: "amethystos",
    name: "Αμέθυστος",
    regions: ["SE", "SW"],
    location: "Ολύμποι",
    cuisineType: "Ελληνική Κουζίνα / Μαγειρευτά",
    priceRange: "€€",
    whyWeRecommendIt: "Πολύ ζεστός χώρος στο μεσαιωνικό χωριό των Ολύμπων. Προσφέρει εξαιρετικά μαγειρευτά και ντόπιες συνταγές, ιδανικό για χαλάρωση μετά την εξερεύνηση των Μαστιχοχωρίων.",
    shortWhy: "Μαγειρευτά και ντόπιες γεύσεις στους Ολύμπους.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "kato-porta",
    name: "Κάτω Πόρτα",
    regions: ["SE", "SW"],
    location: "Ολύμποι",
    cuisineType: "Παραδοσιακή Ταβέρνα / Μεζέδες",
    priceRange: "€€",
    whyWeRecommendIt: "Αυθεντική ταβέρνα που αναδεικνύει τον παραδοσιακό χαρακτήρα του καστροχωρίου. Εξαιρετική στάση για καλό φαγητό και ντόπιους μεζέδες.",
    shortWhy: "Αυθεντικοί μεζέδες στο καστροχώρι.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "mestousiko",
    name: "Μεστουσικο Σουβλατζίδικο",
    regions: ["SE", "SW"],
    location: "Μεστά",
    cuisineType: "Σουβλάκι / Ψητοπωλείο",
    priceRange: "€",
    whyWeRecommendIt: "Γρήγορη και οικονομική επιλογή μέσα στο μεσαιωνικό χωριό των Μεστών. Ιδανικό για χορταστικό σουβλάκι κατά την περιήγηση στα σοκάκια.",
    shortWhy: "Γρήγορο και οικονομικό μέσα στα Μεστά.",
    stopType: "quick",
    idealForLunch: true,
  },
  {
    id: "tou-serga",
    name: "Του Σέργα (Σουβλατζίδικο)",
    regions: ["SE", "SW"],
    location: "Μεστά",
    cuisineType: "Σουβλάκι / Ψητοπωλείο",
    priceRange: "€",
    whyWeRecommendIt: "Γρήγορη και οικονομική επιλογή για αυθεντικό σουβλάκι στα Μεστά, ιδανική για μια χορταστική στάση κατά την εξερεύνηση των Μαστιχοχωρίων.",
    shortWhy: "Σουβλάκι και γρήγορη στάση στα Μεστά.",
    stopType: "quick",
    idealForLunch: true,
  },
  {
    id: "katsika-armolia",
    name: "Κατσίκα Ταβέρνα",
    regions: ["SE", "SW"],
    location: "Αρμόλια",
    cuisineType: "Παραδοσιακή Ταβέρνα / Κρεατικά",
    priceRange: "€-€€",
    whyWeRecommendIt: "Εξαιρετική στάση στο χωριό των κεραμικών, που αποτελεί σταυροδρόμι για τα νότια. Ιδανική επιλογή για παραδοσιακό φαγητό πριν ή μετά την περιήγηση στις παραλίες.",
    shortWhy: "Παραδοσιακό φαγητό στο σταυροδρόμι των νότιων διαδρομών.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "perfect-armolia",
    name: "Ζαχαροπλαστείο Perfect",
    regions: ["SE", "SW"],
    location: "Αρμόλια",
    cuisineType: "Ζαχαροπλαστείο / Παγωτό / Γλυκά",
    priceRange: "€",
    whyWeRecommendIt: "Εξαιρετική στάση στα Αρμόλια για ωραίο παγωτό και νόστιμα γλυκά. Μια δροσερή και γλυκιά ανάπαυλα καθώς διασχίζεις τη νότια Χίο.",
    shortWhy: "Γλυκιά στάση για παγωτό και γλυκά.",
    stopType: "sweet",
    idealForLunch: false,
  },
  {
    id: "salale",
    name: "Salale (Τα 3 Αστέρια)",
    regions: ["SE", "SW"],
    location: "Έλατα",
    cuisineType: "Παραδοσιακή Ταβέρνα / Μεζέδες / Καφέ",
    priceRange: "€-€€",
    whyWeRecommendIt: "Όμορφο και αυθεντικό στέκι στο μεσαιωνικό χωριό των Ελάτων. Ιδανικό για καφέ, ποτό ή παραδοσιακούς μεζέδες σε ήσυχο και γραφικό περιβάλλον.",
    shortWhy: "Ήσυχη στάση για μεζέδες ή καφέ στα Έλατα.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "kosta-vessa",
    name: "Κώστα Ταβέρνα",
    regions: ["SE", "SW"],
    location: "Βέσσα",
    cuisineType: "Παραδοσιακή Ταβέρνα",
    priceRange: "€-€€",
    whyWeRecommendIt: "Παραδοσιακή ταβέρνα στην καρδιά του μεσαιωνικού χωριού της Βέσσας. Ιδανική επιλογή για αυθεντικές γεύσεις μετά την περιήγηση στα γραφικά σοκάκια.",
    shortWhy: "Παραδοσιακές γεύσεις στην καρδιά της Βέσσας.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "kanelos-mesta",
    name: "Κανέλος Λουκουμάδες",
    regions: ["SE", "SW"],
    location: "Μεστά",
    cuisineType: "Λουκουμάδες / Γλυκά / Καφέ",
    priceRange: "€",
    whyWeRecommendIt: "Φημισμένο στέκι στην κεντρική πλατεία των Μεστών για παραδοσιακούς, φρεσκοτηγανισμένους λουκουμάδες. Ιδανική γλυκιά στάση μετά την περιήγηση.",
    shortWhy: "Λουκουμάδες στην πλατεία των Μεστών.",
    stopType: "sweet",
    idealForLunch: false,
  },
  {
    id: "paxata-mesta",
    name: "Παξάτα",
    regions: ["SE", "SW"],
    location: "Μεστά",
    cuisineType: "Καφέ / Ποτό",
    priceRange: "€€",
    whyWeRecommendIt: "Πολύ γνωστό στέκι στα Μεστά, ιδανικό για καφέ το πρωί ή χαλαρό ποτό το βράδυ. Βρίσκεται σε κεντρικό σημείο με μεσαιωνική ατμόσφαιρα.",
    shortWhy: "Καφέ ή χαλαρό ποτό στο κέντρο των Μεστών.",
    stopType: "cafe",
    idealForLunch: false,
  },
  {
    id: "sergia-mesta-port",
    name: "Σεργιά",
    regions: ["SE", "SW"],
    location: "Λιμένας Μεστών",
    cuisineType: "Θαλασσινά / Ψαροταβέρνα",
    priceRange: "€€",
    whyWeRecommendIt: "Εξαιρετική ψαροταβέρνα στο λιμάνι των Μεστών. Ιδανική επιλογή για φρέσκο ψάρι και θαλασσινά δίπλα στο κύμα.",
    shortWhy: "Ψάρι και θαλασσινά στο λιμάνι των Μεστών.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "tria-aderfia-lithi",
    name: "Τα 3 Αδέρφια",
    regions: ["SE", "SW"],
    location: "Παραλία Λιθίου",
    cuisineType: "Θαλασσινά / Ψαρικά",
    priceRange: "€€",
    whyWeRecommendIt: "Φημισμένη ψαροταβέρνα ακριβώς πάνω στην αμμουδιά της παραλίας του Λιθίου. Ιδανική μετά το μπάνιο, με φρέσκο ψάρι και θαλασσινά.",
    shortWhy: "Ψάρι πάνω στην αμμουδιά του Λιθίου.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "to-kyma-lithi",
    name: "Το Κύμα",
    regions: ["SE", "SW"],
    location: "Παραλία Λιθίου",
    cuisineType: "Θαλασσινά / Ψαρικά",
    priceRange: "€€",
    whyWeRecommendIt: "Κλασική και αγαπημένη ψαροταβέρνα πάνω στο κύμα στην παραλία του Λιθίου. Τέλεια επιλογή για φρέσκο ψάρι, θαλασσινά και ούζο.",
    shortWhy: "Κλασική ψαροταβέρνα πάνω στο κύμα.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "o-kavos-limnia",
    name: "Ο Κάβος",
    regions: ["NW"],
    location: "Λιμνιά - Βολισσός",
    cuisineType: "Θαλασσινά / Ψαρικά / Ελληνική Κουζίνα",
    priceRange: "€€",
    whyWeRecommendIt: "Γραφική ταβέρνα στο λιμανάκι των Λιμνιών στη Βολισσό. Ιδανική επιλογή για φρέσκο ψάρι και παραδοσιακούς μεζέδες με θέα τα ψαροκάικα.",
    shortWhy: "Ψάρι και μεζέδες στο λιμανάκι των Λιμνιών.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "makouti-limnos",
    name: "Μακουτί (Makouti)",
    regions: ["NW"],
    location: "Παραλία Λήμνος - Βολισσός",
    cuisineType: "Ταβέρνα / Ελληνική Κουζίνα",
    priceRange: "€-€€",
    whyWeRecommendIt: "Παραθαλάσσια ταβέρνα στην παραλία Λήμνος της Βολισσού, ιδανική για χαλαρό γεύμα μετά το μπάνιο.",
    shortWhy: "Παραθαλάσσιο φαγητό στην παραλία Λήμνος.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "fabrika-volissos",
    name: "Φάμπρικα",
    regions: ["NW"],
    location: "Βολισσός",
    cuisineType: "Καφέ / Μπαρ / Σνακ",
    priceRange: "€-€€",
    whyWeRecommendIt: "Ατμοσφαιρικό στέκι στον παραδοσιακό οικισμό της Βολισσού. Ιδανικό για καφέ, ποτό ή χαλαρό snack σε ιδιαίτερο χώρο.",
    shortWhy: "Καφέ, ποτό ή snack στη Βολισσό.",
    stopType: "cafe",
    idealForLunch: false,
  },
  {
    id: "agia-markella-taverna",
    name: "Ταβέρνα Αγία Μαρκέλλα",
    regions: ["NW"],
    location: "Αγία Μαρκέλλα - Βολισσός",
    cuisineType: "Παραδοσιακή Ταβέρνα / Ελληνική Κουζίνα",
    priceRange: "€-€€",
    whyWeRecommendIt: "Παραδοσιακή ταβέρνα κοντά στο προσκύνημα και την παραλία της Αγίας Μαρκέλλας. Ιδανική στάση για φαγητό και τοπικές γεύσεις.",
    shortWhy: "Εύκολη στάση κοντά στην Αγία Μαρκέλλα.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "palio-chorio-potamia",
    name: "Το Παλιό Χωριό",
    regions: ["NW"],
    location: "Παλαιά Ποταμιά",
    cuisineType: "Παραδοσιακή Ταβέρνα / Ελληνική Κουζίνα",
    priceRange: "€-€€",
    whyWeRecommendIt: "Αυθεντική ταβέρνα στον γραφικό και απομονωμένο οικισμό της Παλαιάς Ποταμιάς, με παραδοσιακές γεύσεις σε ήσυχο περιβάλλον.",
    shortWhy: "Αυθεντικό φαγητό στην Παλαιά Ποταμιά.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "avgerino-fyta",
    name: "Αυγερινό",
    regions: ["NW"],
    location: "Φυτά",
    cuisineType: "Παραδοσιακή Ταβέρνα / Ελληνική Κουζίνα",
    priceRange: "€-€€",
    whyWeRecommendIt: "Παραδοσιακή ταβέρνα στο ορεινό χωριό Φυτά. Ιδανική στάση για αυθεντικό φαγητό και τοπικές συνταγές σε ήσυχο περιβάλλον.",
    shortWhy: "Τοπικές γεύσεις στο ορεινό χωριό Φυτά.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "to-klai-viki",
    name: "Το Κλαί",
    regions: ["NW"],
    location: "Βίκυ",
    cuisineType: "Παραδοσιακή Ταβέρνα / Ελληνική Κουζίνα",
    priceRange: "€-€€",
    whyWeRecommendIt: "Παραδοσιακή ταβέρνα στο ορεινό χωριό Βίκυ. Ιδανική στάση για αυθεντικές γεύσεις και τοπικά πιάτα.",
    shortWhy: "Παραδοσιακό φαγητό στο ήσυχο Βίκυ.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "amades-restaurant",
    name: "Εστιατόριο Αμάδες",
    regions: ["NW"],
    location: "Αμάδες",
    cuisineType: "Παραδοσιακή Ταβέρνα / Ελληνική Κουζίνα",
    priceRange: "€-€€",
    whyWeRecommendIt: "Παραδοσιακό εστιατόριο στο ορεινό χωριό Αμάδες. Ιδανική στάση για σπιτικές γεύσεις και τοπικά πιάτα σε φιλόξενο περιβάλλον.",
    shortWhy: "Σπιτικές γεύσεις στο ορεινό χωριό Αμάδες.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "to-palio-pityos",
    name: "Το Παλιό",
    regions: ["NE"],
    location: "Πιτυός",
    cuisineType: "Παραδοσιακή Ταβέρνα / Κρεατικά",
    priceRange: "€-€€",
    whyWeRecommendIt: "Παραδοσιακή και ιστορική ταβέρνα στο γραφικό Πιτυός, γνωστή για κρεατικά στα κάρβουνα και αυθεντικές παραδοσιακές γεύσεις.",
    shortWhy: "Κρεατικά στα κάρβουνα στο Πιτυός.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "nostos-lagada",
    name: "Νόστος",
    regions: ["NE"],
    location: "Λαγκαδά",
    cuisineType: "Θαλασσινά / Ψαροταβέρνα",
    priceRange: "€€",
    whyWeRecommendIt: "Ωραία ταβέρνα στον παραθαλάσσιο οικισμό της Λαγκαδά, ιδανική για φρέσκο ψάρι και θαλασσινά δίπλα στο γραφικό λιμανάκι.",
    shortWhy: "Ψάρι και θαλασσινά στο λιμανάκι της Λαγκαδάς.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "passas-lagada",
    name: "Πασσάς",
    regions: ["NE"],
    location: "Λαγκαδά",
    cuisineType: "Θαλασσινά / Παραδοσιακή Ψαροταβέρνα",
    priceRange: "€€",
    whyWeRecommendIt: "Γνωστή ψαροταβέρνα στη Λαγκαδά, για φρέσκα ψάρια, θαλασσινά και παραδοσιακές γεύσεις δίπλα στη θάλασσα.",
    shortWhy: "Κλασική ψαροταβέρνα στη Λαγκαδά.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "o-geros-lagada",
    name: "Ο Γέρος",
    regions: ["NE"],
    location: "Λαγκαδά",
    cuisineType: "Παραδοσιακή Ταβέρνα / Μεζέδες",
    priceRange: "€-€€",
    whyWeRecommendIt: "Παραδοσιακό στέκι στη Λαγκαδά για μεζέδες, κρασί και αυθεντική φιλοξενία σε γραφικό περιβάλλον.",
    shortWhy: "Μεζέδες και κρασί στη Λαγκαδά.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "tageri-lagada",
    name: "Ταγέρι",
    regions: ["NE"],
    location: "Λαγκαδά",
    cuisineType: "Παραδοσιακή Ταβέρνα / Ψαροταβέρνα",
    priceRange: "€€",
    whyWeRecommendIt: "Αυθεντική ταβέρνα στη Λαγκαδά, ιδανική για ντόπιες γεύσεις και θαλασσινά με θέα στον κόλπο.",
    shortWhy: "Ντόπιες γεύσεις με θέα στον κόλπο.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "vardas-lagada",
    name: "Βάρδας",
    regions: ["NE"],
    location: "Λαγκαδά",
    cuisineType: "Παραδοσιακή Ταβέρνα / Ψαροταβέρνα",
    priceRange: "€€",
    whyWeRecommendIt: "Παραδοσιακή ταβέρνα στη Λαγκαδά, εξαιρετική επιλογή για φρέσκο ψάρι, θαλασσινά και τοπικούς μεζέδες δίπλα στη θάλασσα.",
    shortWhy: "Ψάρι και τοπικοί μεζέδες δίπλα στη θάλασσα.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "pantoukios-taverna",
    name: "Ταβέρνα Παντούκιος",
    regions: ["NE"],
    location: "Παντούκιος",
    cuisineType: "Παραδοσιακή Ταβέρνα / Ψαροταβέρνα",
    priceRange: "€-€€",
    whyWeRecommendIt: "Γραφική παραδοσιακή ταβέρνα στον παραθαλάσσιο οικισμό του Παντουκίου, ιδανική για φρέσκο ψάρι και μεζέδες δίπλα στο κύμα.",
    shortWhy: "Ψαροταβέρνα δίπλα στο κύμα στο Παντούκιος.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "oz-bay",
    name: "Oz Bay",
    regions: ["NE"],
    location: "Άγιος Ισίδωρος - Λαγκαδά",
    cuisineType: "Beach Bar / Σνακ / Ελαφρύ Γεύμα",
    priceRange: "€-€€",
    whyWeRecommendIt: "Δημοφιλές beach bar στον Άγιο Ισίδωρο, ιδανικό για μπάνιο, δροσερά ποτά και ελαφρύ φαγητό ή σνακ δίπλα στη θάλασσα.",
    shortWhy: "Beach stop για ποτό και ελαφρύ φαγητό.",
    stopType: "quick",
    idealForLunch: true,
  },
  {
    id: "mouria-vrontados",
    name: "Μουριά",
    regions: ["NE"],
    location: "Βροντάδος",
    cuisineType: "Θαλασσινά / Ελληνική / Μεσογειακή",
    priceRange: "€-€€",
    whyWeRecommendIt: "Ταβέρνα στον Βροντάδο, ιδανική για ελληνικές γεύσεις και θαλασσινά σε παραθαλάσσιο περιβάλλον.",
    shortWhy: "Ελληνικές γεύσεις και θαλασσινά στον Βροντάδο.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "oi-myloi-chios",
    name: "Οι Μύλοι",
    regions: ["NE"],
    location: "Πόλη Χίου",
    cuisineType: "Παραδοσιακή Ταβέρνα / Ελληνική Κουζίνα",
    priceRange: "€-€€",
    whyWeRecommendIt: "Γνωστή παραδοσιακή ταβέρνα στην πόλη της Χίου, ιδανική για αυθεντικές γεύσεις και καλό φαγητό σε ζεστό περιβάλλον.",
    shortWhy: "Παραδοσιακό φαγητό στην πόλη της Χίου.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "ichthyoskala",
    name: "Ιχθυόσκαλα",
    regions: ["NE"],
    location: "Λιμάνι - Πόλη Χίου",
    cuisineType: "Θαλασσινά / Ψαροταβέρνα",
    priceRange: "€€",
    whyWeRecommendIt: "Ψαροταβέρνα κοντά στο λιμάνι της Χίου, καλή επιλογή για φρέσκο ψάρι, θαλασσινά και ουζάκι.",
    shortWhy: "Ψάρι και θαλασσινά κοντά στο λιμάνι.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "kadenes-castle",
    name: "Καδένες",
    regions: ["NE"],
    location: "Κάστρο Χίου",
    cuisineType: "Παραδοσιακή Ταβέρνα / Μεζέδες",
    priceRange: "€-€€",
    whyWeRecommendIt: "Ατμοσφαιρική ταβέρνα μέσα στα ιστορικά τείχη του Κάστρου της Χίου. Ιδανική στάση για παραδοσιακούς μεζέδες και κρασί.",
    shortWhy: "Μεζέδες μέσα στο Κάστρο της Χίου.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "vradypous-castle",
    name: "Βραδύπους",
    regions: ["NE"],
    location: "Κάστρο Χίου",
    cuisineType: "Μεζεδοπωλείο / Ελληνική Κουζίνα",
    priceRange: "€-€€",
    whyWeRecommendIt: "Προσεγμένο μεζεδοπωλείο εντός του Κάστρου της Χίου, με εκλεκτές γεύσεις και χαλαρή ατμόσφαιρα.",
    shortWhy: "Μεζεδοπωλείο σε ιστορικό σκηνικό.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "apeiron-castle",
    name: "Άπειρον",
    regions: ["NE"],
    location: "Κάστρο Χίου",
    cuisineType: "Καφέ / Μπαρ / Μεζέδες",
    priceRange: "€-€€",
    whyWeRecommendIt: "Όμορφος και ατμοσφαιρικός χώρος μέσα στο Κάστρο της Χίου. Ιδανικός για καφέ, ποτό ή ελαφριές γεύσεις.",
    shortWhy: "Καφέ ή ελαφριές γεύσεις μέσα στο Κάστρο.",
    stopType: "cafe",
    idealForLunch: false,
  },
  {
    id: "tsikoudia-chios",
    name: "Τσικουδιά",
    regions: ["NE"],
    location: "Λιμάνι - Πόλη Χίου",
    cuisineType: "Κρητική Κουζίνα / Μεζεδοπωλείο",
    priceRange: "€-€€",
    whyWeRecommendIt: "Ζωντανό μεζεδοπωλείο κοντά στο λιμάνι της πόλης της Χίου. Εξαιρετική επιλογή για κρητικές γεύσεις, μεζέδες και τσικουδιά.",
    shortWhy: "Κρητικοί μεζέδες κοντά στο λιμάνι.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "karatzas-karfas",
    name: "Καρατζάς",
    regions: ["SE", "SW"],
    location: "Καρφάς",
    cuisineType: "Παραδοσιακή Ταβέρνα / Ελληνική Κουζίνα",
    priceRange: "€-€€",
    whyWeRecommendIt: "Παραδοσιακή ταβέρνα ακριβώς στην αμμουδιά του Καρφά. Ιδανική επιλογή για φαγητό και χαλάρωση δίπλα στη θάλασσα μετά το μπάνιο.",
    shortWhy: "Φαγητό πάνω στην αμμουδιά του Καρφά.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "bahari-agia-ermioni",
    name: "Μπαχάρι",
    regions: ["SE", "SW"],
    location: "Αγία Ερμιόνη",
    cuisineType: "Παραδοσιακή Ταβέρνα / Μεζέδες",
    priceRange: "€-€€",
    whyWeRecommendIt: "Ατμοσφαιρική ταβέρνα στον γραφικό οικισμό της Αγίας Ερμιόνης. Καλή επιλογή για μεζέδες και παραδοσιακές γεύσεις δίπλα στο νερό.",
    shortWhy: "Μεζέδες δίπλα στο νερό στην Αγία Ερμιόνη.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "agyra-megas-limnionas",
    name: "Άγκυρα",
    regions: ["SE", "SW"],
    location: "Μέγας Λιμνιώνας",
    cuisineType: "Θαλασσινά / Ψαροταβέρνα",
    priceRange: "€€",
    whyWeRecommendIt: "Ψαροταβέρνα στον Μέγα Λιμνιώνα, πάνω στο κύμα. Ιδανική στάση για φρέσκο ψάρι, θαλασσινά και ούζο με θέα.",
    shortWhy: "Ψαροταβέρνα πάνω στο κύμα.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "apomero-thymiana",
    name: "Απόμερο",
    regions: ["SE", "SW"],
    location: "Θυμιανά",
    cuisineType: "Παραδοσιακή Ταβέρνα / Μεζέδες",
    priceRange: "€-€€",
    whyWeRecommendIt: "Όμορφος και ιδιαίτερος χώρος στα Θυμιανά, ιδανικός για χαλαρό φαγητό, ποιοτικούς μεζέδες και όμορφη ατμόσφαιρα.",
    shortWhy: "Χαλαρό φαγητό και μεζέδες στα Θυμιανά.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "kapileio-thymiana",
    name: "Το Καπηλειό",
    regions: ["SE", "SW"],
    location: "Θυμιανά",
    cuisineType: "Παραδοσιακό Καπηλειό / Μεζέδες",
    priceRange: "€-€€",
    whyWeRecommendIt: "Παραδοσιακό στέκι στα Θυμιανά, γνωστό για αυθεντική ατμόσφαιρα, μεζέδες και παραδοσιακές γεύσεις.",
    shortWhy: "Αυθεντικό καπηλειό και μεζέδες στα Θυμιανά.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "stou-giorgou",
    name: "Στου Γιώργου",
    regions: ["NE"],
    location: "Πόλη Χίου",
    cuisineType: "Παραδοσιακή Ταβέρνα / Ελληνική Κουζίνα",
    priceRange: "€-€€",
    whyWeRecommendIt: "Παραδοσιακή ταβέρνα στην πόλη της Χίου, γνωστή για αυθεντική ατμόσφαιρα, νόστιμες γεύσεις και ζεστή φιλοξενία.",
    shortWhy: "Παραδοσιακή ταβέρνα στην πόλη της Χίου.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "meltemaki-katarraktis",
    name: "Μελτεμάκι",
    regions: ["SE", "SW"],
    location: "Καταρράκτης",
    cuisineType: "Θαλασσινά / Μεζέδες / Ουζερί",
    priceRange: "€-€€",
    whyWeRecommendIt: "Γραφικό στέκι στον παραθαλάσσιο Καταρράκτη, ιδανικό για ουζάκι, μεζέδες και θαλασσινά δίπλα στο κύμα.",
    shortWhy: "Ουζάκι και θαλασσινά δίπλα στο κύμα.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "o-molos-katarraktis",
    name: "Ο Μόλος",
    regions: ["SE", "SW"],
    location: "Καταρράκτης",
    cuisineType: "Παραδοσιακή Ταβέρνα / Θαλασσινά",
    priceRange: "€-€€",
    whyWeRecommendIt: "Παραδοσιακή ταβέρνα πάνω στον μόλο του Καταρράκτη, καλή επιλογή για ψάρι, θαλασσινά και ουζάκι με θέα.",
    shortWhy: "Θαλασσινά πάνω στον μόλο του Καταρράκτη.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "rousiko-katarraktis",
    name: "Ρούσικο",
    regions: ["SE", "SW"],
    location: "Καταρράκτης",
    cuisineType: "Παραδοσιακή Ταβέρνα / Μεζέδες",
    priceRange: "€-€€",
    whyWeRecommendIt: "Αυθεντικό παραδοσιακό στέκι στον Καταρράκτη, ιδανικό για καλό φαγητό, ντόπιους μεζέδες και φιλόξενη ατμόσφαιρα.",
    shortWhy: "Ντόπιοι μεζέδες στον Καταρράκτη.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "drosia-katarraktis",
    name: "Δροσιά",
    regions: ["SE", "SW"],
    location: "Καταρράκτης",
    cuisineType: "Ελληνική / Μεσογειακή / Θαλασσινά",
    priceRange: "€-€€",
    whyWeRecommendIt: "Γραφική επιλογή στον Καταρράκτη για ελληνικές γεύσεις και θαλασσινά σε δροσερή παραθαλάσσια ατμόσφαιρα.",
    shortWhy: "Ελληνικές γεύσεις και θαλασσινά στον Καταρράκτη.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "artemis-nenita",
    name: "Άρτεμις",
    regions: ["SE", "SW"],
    location: "Νένητα",
    cuisineType: "Παραδοσιακή Ταβέρνα / Ελληνική Κουζίνα",
    priceRange: "€-€€",
    whyWeRecommendIt: "Παραδοσιακή ταβέρνα στο ιστορικό χωριό των Νενήτων. Ιδανική επιλογή για αυθεντικές γεύσεις, τοπικά πιάτα και παραδοσιακή φιλοξενία.",
    shortWhy: "Τοπικές γεύσεις στα Νένητα.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "konstantis-vokaria",
    name: "Στου Κωνσταντή το στέκι (Bokaria Restaurant)",
    regions: ["SE", "SW"],
    location: "Βοκαριά - Νένητα",
    cuisineType: "Παραδοσιακή Ταβέρνα / Ψαροταβέρνα",
    priceRange: "€€",
    whyWeRecommendIt: "Δημοφιλές παραθαλάσσιο εστιατόριο στο λιμανάκι της Βοκαριάς. Προσφέρει φρέσκο ψάρι, θαλασσινά και παραδοσιακά πιάτα δίπλα στο κύμα.",
    shortWhy: "Ψάρι και θαλασσινά στο λιμανάκι της Βοκαριάς.",
    stopType: "meal",
    idealForLunch: true,
  },
  {
    id: "asteri-avgonyma",
    name: "Αστέρι",
    regions: ["NW"],
    location: "Αυγώνυμα",
    cuisineType: "Ελληνική Ταβέρνα / Παραδοσιακή Κουζίνα",
    priceRange: "€€",
    whyWeRecommendIt: "Ταβέρνα στα Αυγώνυμα, ιδανική για παραδοσιακό φαγητό με δυτική θέα και όμορφο ηλιοβασίλεμα, ειδικά μετά τον Ανάβατο.",
    shortWhy: "Παραδοσιακό φαγητό με θέα και ηλιοβασίλεμα.",
    stopType: "meal",
    idealForLunch: true,
  },
];

const foodPlaces: PlannerExtraPlace[] = curatedFoodPlaces.flatMap((item) =>
  item.regions.map((region) => ({
    id: `${item.id}-${region.toLowerCase()}`,
    name: item.name,
    category: "food" as const,
    region,
    image: null,
    meta: `${item.location} · ${item.cuisineType} · ${item.priceRange} · ${item.shortWhy}`,
    location: item.location,
    cuisineType: item.cuisineType,
    priceRange: item.priceRange,
    whyWeRecommendIt: item.whyWeRecommendIt,
    stopType: item.stopType,
    idealForLunch: item.idealForLunch,
  })),
);

export const plannerExtraPlaces: PlannerExtraPlace[] = [
  {
    id: "mastic-museum",
    name: "Μουσείο Μαστίχας Χίου",
    category: "sights",
    region: "SE",
    image: null,
    meta: "Κοντά στο Πυργί · ιδανικό μαζί με Μαστιχοχώρια και νότιες παραλίες.",
  },
  {
    id: "olympoi-cave",
    name: "Σπήλαιο Ολύμπων",
    category: "sights",
    region: "SW",
    image: null,
    meta: "Σπήλαιο κοντά στους Ολύμπους · έλεγξε το εποχικό ωράριο πριν πας.",
  },
  {
    id: "nea-moni",
    name: "Νέα Μονή",
    category: "sights",
    region: "NW",
    image: null,
    meta: "Ιστορική μονή στην κεντροδυτική Χίο · συνδυάζεται με Ανάβατο και Αυγώνυμα.",
  },
  {
    id: "agia-markella-shrine",
    name: "Προσκύνημα Αγίας Μαρκέλλας",
    category: "sights",
    region: "NW",
    image: null,
    meta: "Βορειοδυτική Χίος · ταιριάζει με Βολισσό και παραλίες της περιοχής.",
  },
  {
    id: "daskalopetra-homer",
    name: "Πέτρα του Ομήρου · Δασκαλόπετρα",
    category: "sights",
    region: "NE",
    image: null,
    meta: "Σύντομη πολιτιστική στάση στον Βροντάδο, δίπλα στην παραλία Δασκαλόπετρα.",
  },
  {
    id: "chios-castle",
    name: "Κάστρο Χίου",
    category: "sights",
    region: "NE",
    image: null,
    meta: "Εύκολη στάση κοντά στη Χώρα για βόλτα και ιστορία.",
  },

  ...foodPlaces,

  {
    id: "drink-mesta",
    name: "Μεστά · βραδινό ποτό",
    category: "drink",
    region: "SW",
    image: null,
    meta: "Χαλαρό ποτό στην πλατεία μετά τη νοτιοδυτική διαδρομή.",
  },
  {
    id: "drink-avgonyma",
    name: "Αυγώνυμα · sunset drink",
    category: "drink",
    region: "NW",
    image: null,
    meta: "Δυτική θέα και ηλιοβασίλεμα στο τέλος της ημέρας.",
  },
  {
    id: "drink-chios-town",
    name: "Χώρα Χίου · βραδινό ποτό",
    category: "drink",
    region: "NE",
    image: null,
    meta: "Εύκολο κλείσιμο ημέρας κοντά στην πόλη.",
  },
  {
    id: "drink-karfas",
    name: "Καρφάς · beach bar",
    category: "drink",
    region: "SE",
    image: null,
    meta: "Παραθαλάσσιο ποτό κοντά στον Κάμπο και τη νότια ακτή.",
  },
  {
    id: "drink-glaroi",
    name: "Γλάροι · beach bar",
    category: "drink",
    region: "NE",
    image: null,
    meta: "Πιο ζωντανή επιλογή για απογευματινό ή early-evening ποτό.",
  },
];

export const plannerExtraPlacesByCategory = {
  sights: plannerExtraPlaces.filter((item) => item.category === "sights"),
  food: plannerExtraPlaces.filter((item) => item.category === "food"),
  drink: plannerExtraPlaces.filter((item) => item.category === "drink"),
} as const;
