import Image from "next/image";
import { PolishChiosHotelsLiveSearch } from "@/components/booking/PolishChiosHotelsLiveSearch";

const primaryButton = "inline-flex min-h-12 items-center justify-center rounded-full bg-[#e8c77f] px-5 py-3 text-center text-xs font-black uppercase tracking-[0.08em] !text-[#2f261f] shadow-lg transition hover:-translate-y-0.5 hover:bg-white focus:outline-none focus:ring-4 focus:ring-amber-200/40";
const lightButton = "inline-flex min-h-12 items-center justify-center rounded-full border border-white/30 bg-white/10 px-5 py-3 text-center text-xs font-black uppercase tracking-[0.08em] !text-white backdrop-blur transition hover:-translate-y-0.5 hover:bg-white hover:!text-[#2f261f] focus:outline-none focus:ring-4 focus:ring-white/25";
const kicker = "text-[10px] font-black uppercase tracking-[0.2em] text-amber-800 sm:text-[11px] sm:tracking-[0.24em]";
const mobileCarousel = "-mx-4 flex snap-x snap-mandatory gap-4 overflow-x-auto px-4 pb-5 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden sm:-mx-6 sm:px-6 md:mx-0 md:grid md:overflow-visible md:px-0 md:pb-0";

function SectionHeader({ eyebrow, title, text, id }: { eyebrow: string; title: string; text?: string; id: string }) {
  return <header className="mx-auto max-w-4xl text-center"><p className={kicker}>{eyebrow}</p><h2 id={id} className="mt-3 text-balance text-3xl font-black tracking-[-0.04em] sm:mt-4 sm:text-4xl lg:text-5xl">{title}</h2>{text ? <p className="mx-auto mt-4 max-w-3xl text-[15px] leading-7 text-[#574b3f] sm:mt-5 sm:text-lg sm:leading-8">{text}</p> : null}</header>;
}

const areas = [
  { id: "chios-town", title: "Miasto Chios", badge: "Port i życie miejskie", text: "Praktyczny wybór dla osób przypływających promem, chcących mieć restauracje, sklepy i nabrzeże w zasięgu spaceru.", bestFor: "Krótkie pobyty, prom i podróż bez samochodu" },
  { id: "kambos", title: "Kambos", badge: "Historycznie i spokojnie", text: "Ogrody cytrusowe, kamienne mury i dawne rezydencje, a jednocześnie łatwy dojazd do miasta, lotniska i południowej części wyspy.", bestFor: "Pary, rodziny i osoby zwiedzające samochodem" },
  { id: "karfas", title: "Karfas i wybrzeże", badge: "Blisko plaży", text: "Popularny kierunek dla osób, które chcą mieć zorganizowaną plażę i bardziej wakacyjny, nadmorski charakter pobytu.", bestFor: "Wakacje plażowe i pobyty letnie" },
  { id: "mastic", title: "Wioski mastykowe", badge: "Tradycyjne południe", text: "Pyrgi, Mesta i inne średniowieczne wioski oferują wyjątkową architekturę i mocny lokalny charakter.", bestFor: "Objazd wyspy, historia i tradycyjne wioski" },
];

const roomCategories = [
  { title: "Ekonomiczne pokoje dwuosobowe", label: "Najlepsza cena dla dwóch", text: "Kompaktowe, odnowione pokoje z prywatną łazienką, klimatyzacją, Wi-Fi, telewizorem i lodówką.", facts: ["2 gości", "ok. 16 m²", "Prywatna łazienka"], image: "/images/rooms/received_1753964631359257.webp", href: "/pl/pokoje-na-chios/economy-double/" },
  { title: "Pokoje na parterze", label: "Łatwy dostęp, bez schodów", text: "Pokoje dwu- i trzyosobowe z wygodnym dostępem do dziedzińca lub ogrodu.", facts: ["2–3 gości", "Bez schodów", "Dostęp do ogrodu"], image: "/images/rooms/double-triple-room.jpg", href: "/pl/pokoje-na-chios/standard/" },
  { title: "Pokoje na piętrze", label: "Taras i widok", text: "Jasne pokoje dwu- i trzyosobowe na piętrze, z dostępem do wspólnego tarasu i aneksem kuchennym w wybranych pokojach.", facts: ["2–4 gości", "Piętro", "Wybrane aneksy"], image: "/images/rooms/DSC07776-2-e1675109942622.webp", href: "/pl/pokoje-na-chios/standard/" },
  { title: "Apartamenty rodzinne", label: "Więcej przestrzeni i kuchnia", text: "Niezależne apartamenty 40–45 m² z osobną sypialnią, salonem i pełną kuchnią.", facts: ["Do 4 gości", "40–45 m²", "Pełna kuchnia"], image: "/images/rooms/chios-apartments-voulamandis.webp", href: "/pl/apartamenty-na-chios/" },
];

export function PolishChiosHotelsGuidePage() {
  return (
    <main className="min-h-screen overflow-x-hidden bg-[#fbf6ef] text-[#2f261f]">
      <section className="relative isolate overflow-hidden bg-[#263127] text-white" aria-labelledby="chios-hotels-title-pl">
        <div className="absolute inset-0 -z-20 bg-[radial-gradient(circle_at_top_left,rgba(232,199,127,0.25),transparent_32rem),linear-gradient(135deg,#263127,#3b4b3c)]" />
        <div className="mx-auto grid max-w-7xl lg:min-h-[700px] lg:grid-cols-[1.08fr_0.92fr]">
          <div className="flex flex-col justify-center px-4 py-10 sm:px-6 sm:py-14 lg:px-8 lg:py-24">
            <span className="w-fit rounded-full border border-amber-200/25 bg-white/10 px-3 py-2 text-[9px] font-black uppercase tracking-[0.16em] text-amber-100 sm:px-4 sm:text-[11px] sm:tracking-[0.2em]">HOTELE CHIOS • GDZIE NOCOWAĆ</span>
            <h1 id="chios-hotels-title-pl" className="mt-5 max-w-4xl text-balance text-4xl font-black leading-[0.98] tracking-[-0.05em] text-white sm:mt-6 sm:text-5xl lg:text-7xl">Hotele na Chios, pokoje i apartamenty — gdzie najlepiej nocować?</h1>
            <p className="mt-5 max-w-3xl text-pretty text-[15px] leading-7 text-white/84 sm:mt-6 sm:text-lg sm:leading-8">Porównaj najważniejsze rejony wyspy, typy zakwaterowania i sprawdź aktualną dostępność spokojnego pobytu w historycznym Kambos.</p>
            <div className="mt-6 max-w-3xl rounded-[22px] border border-amber-200/20 bg-[#1f281f]/80 p-4 text-sm font-semibold leading-6 text-amber-50 sm:p-5 sm:text-base sm:leading-7"><span className="font-black text-amber-200">Ważne:</span> Voulamandis House nie jest hotelem. To rodzinny obiekt oferujący pokoje i apartamenty w Kambos na Chios.</div>
            <div className="mt-7 grid grid-cols-2 gap-3 sm:mt-8 sm:flex sm:flex-wrap"><a href="#live-availability" className={primaryButton}>Sprawdź dostępność</a><a href="#where-to-stay" className={lightButton}>Porównaj rejony</a><a href="/ai-assistant/?lang=en" className="col-span-2 inline-flex min-h-12 items-center justify-center rounded-full border border-amber-200/35 px-5 py-3 text-center text-xs font-black uppercase tracking-[0.08em] !text-amber-100 transition hover:-translate-y-0.5 hover:bg-amber-100 hover:!text-[#2f261f] sm:col-span-1">AI Room Finder</a></div>
          </div>
          <div className="relative min-h-[320px] sm:min-h-[420px] lg:min-h-full"><Image src="/images/activities/chios.hotels.voulamandis.house_.hero_.image_.webp" alt="Pokoje i apartamenty Voulamandis House w ogrodach Kambos na Chios" fill priority sizes="(min-width: 1024px) 46vw, 100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#263127]/85 via-transparent to-transparent lg:bg-gradient-to-r lg:from-[#263127]/45 lg:via-transparent lg:to-transparent" /><div className="absolute bottom-4 left-4 right-4 rounded-[24px] border border-white/20 bg-[#263127]/76 p-5 shadow-2xl backdrop-blur-md sm:bottom-8 sm:left-8 sm:right-8 sm:p-6"><p className="text-[10px] font-black uppercase tracking-[0.2em] text-amber-200">LOKALNY PRZEWODNIK PO NOCLEGACH</p><p className="mt-2 text-xl font-black tracking-[-0.03em] text-white sm:text-2xl">Najpierw porównaj. Potem sprawdź realną dostępność w Kambos.</p></div></div>
        </div>
      </section>

      <section className="border-b border-amber-900/10 bg-white"><div className="mx-auto flex max-w-7xl snap-x snap-mandatory overflow-x-auto bg-amber-900/10 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden lg:grid lg:grid-cols-6 lg:gap-px lg:overflow-visible">{[["Baza", "Historyczny Kambos"], ["Lotnisko", "ok. 3 km"], ["Port", "ok. 6 km"], ["Typ pobytu", "Pokoje i apartamenty"], ["Dla", "Par i rodzin"], ["Dostępność", "Na żywo"]].map(([label, value]) => <div key={label} className="min-w-[44%] snap-start border-r border-amber-900/10 bg-white px-3 py-4 text-center sm:min-w-[30%] sm:px-4 sm:py-5 lg:min-w-0 lg:border-r-0"><p className="text-[9px] font-black uppercase tracking-[0.14em] text-amber-800 sm:text-[10px]">{label}</p><p className="mt-1.5 text-sm font-black sm:mt-2 sm:text-base">{value}</p></div>)}</div></section>

      <section className="px-4 py-12 sm:px-6 sm:py-16 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[1.15fr_0.85fr] lg:gap-16"><div><p className={kicker}>ZACZNIJ OD WŁAŚCIWEGO REJONU</p><h2 className="mt-3 max-w-4xl text-balance text-3xl font-black tracking-[-0.04em] sm:text-4xl lg:text-5xl">Dobre wyszukiwanie hoteli na Chios zaczyna się od wyboru miejsca</h2><div className="mt-6 space-y-4 text-[15px] leading-7 text-[#574b3f] sm:mt-7 sm:space-y-5 sm:text-lg sm:leading-8"><p>Fraza „hotele Chios” obejmuje w praktyce różne potrzeby: bliskość portu, lotniska lub plaży, większą przestrzeń dla rodziny, ciszę albo łatwy start do zwiedzania wyspy samochodem.</p><p>Miasto Chios jest praktyczne przy krótkich pobytach i podróży bez auta. Kambos oferuje spokojniejsze, historyczne otoczenie blisko miasta i lotniska. Karfas odpowiada bardziej plażowemu stylowi pobytu, a południowe wioski sprawdzą się u osób planujących objazd wyspy.</p><p>Na tej stronie używamy frazy „hotele Chios” tak, jak korzystają z niej podróżni w wyszukiwarce, ale wyraźnie odróżniamy hotel od pokoi, apartamentów i mniejszych obiektów noclegowych.</p></div></div><aside className="self-start rounded-[30px] border border-amber-900/10 bg-white p-6 shadow-[0_24px_70px_rgba(47,38,31,0.10)] sm:p-8"><p className={kicker}>JAK KORZYSTAĆ Z TEJ STRONY</p><ol className="mt-5 grid gap-4">{["Porównaj główne rejony Chios.", "Wybierz hotel, pokój, apartament lub mniejszy obiekt.", "Podaj realne daty w wyszukiwarce dostępności.", "Otwórz szczegóły pokoju lub skontaktuj się z recepcją."].map((step, index) => <li key={step} className="flex gap-3 text-sm leading-6 text-[#574b3f] sm:text-base sm:leading-7"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#263127] text-xs font-black text-amber-200">{index + 1}</span><span>{step}</span></li>)}</ol></aside></div></section>

      <PolishChiosHotelsLiveSearch />

      <section id="where-to-stay" className="scroll-mt-24 bg-[#f1e7d8] px-4 py-12 sm:px-6 sm:py-16 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><SectionHeader eyebrow="GDZIE NOCOWAĆ NA CHIOS" title="Porównaj główne rejony wyspy" text="Każda część Chios daje inny rytm pobytu. Porównaj dostęp, atmosferę i styl podróży." id="where-to-stay-pl" /><div className={`${mobileCarousel} mt-7 md:grid-cols-2 md:gap-5 sm:mt-10`}>{areas.map((area) => <article key={area.id} id={area.id} className="min-w-[86vw] snap-start rounded-[28px] border border-amber-900/10 bg-white p-5 shadow-[0_20px_55px_rgba(47,38,31,0.09)] sm:min-w-[64vw] sm:p-7 md:min-w-0"><span className="rounded-full bg-amber-100 px-3 py-1.5 text-[10px] font-black uppercase tracking-[0.08em] text-amber-900">{area.badge}</span><h3 className="mt-5 text-2xl font-black tracking-[-0.035em]">{area.title}</h3><p className="mt-3 text-sm leading-7 text-[#574b3f]">{area.text}</p><div className="mt-5 rounded-[20px] bg-[#fbf6ef] p-4"><p className="text-[10px] font-black uppercase tracking-[0.12em] text-amber-800">Najlepsze dla</p><p className="mt-2 text-sm font-bold leading-6">{area.bestFor}</p></div></article>)}</div></div></section>

      <section className="px-4 py-12 sm:px-6 sm:py-16 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><SectionHeader eyebrow="HOTEL, POKÓJ CZY APARTAMENT?" title="Wybierz rodzaj pobytu zgodny z Twoimi priorytetami" text="Słowo hotel jest często używane jako ogólna fraza, ale realne typy noclegów na Chios różnią się zakresem usług i przestrzenią." id="types-pl" /><div className="mt-8 overflow-hidden rounded-[30px] border border-amber-900/10 bg-white shadow-[0_24px_70px_rgba(47,38,31,0.09)] sm:mt-10"><div className="hidden grid-cols-[0.8fr_1fr_1.5fr] bg-[#263127] px-6 py-4 text-xs font-black uppercase tracking-[0.09em] text-amber-100 md:grid"><span>Typ zakwaterowania</span><span>Najlepsze dla</span><span>Typowe cechy</span></div>{[["Klasyczny hotel", "Podróżni oczekujący usług na miejscu", "Recepcja, wspólne udogodnienia i — zależnie od obiektu — restauracja, basen lub dodatkowe usługi."], ["Kameralny obiekt", "Mniejszy i bardziej osobisty pobyt", "Mniej pokoi, bezpośredni kontakt z gospodarzem i spokojniejsza atmosfera."], ["Prywatny pokój", "Pary i krótsze pobyty", "Prywatna łazienka i podstawowe udogodnienia, zwykle prostszy model usług."], ["Apartament rodzinny", "Rodziny i dłuższy pobyt", "Więcej przestrzeni, osobna sypialnia, salon i kuchnia."]].map(([title, suited, features]) => <article key={title} className="grid gap-3 border-b border-amber-900/10 p-5 last:border-b-0 sm:p-6 md:grid-cols-[0.8fr_1fr_1.5fr] md:items-start"><h3 className="text-lg font-black">{title}</h3><p className="text-sm font-bold leading-6 text-amber-900">{suited}</p><p className="text-sm leading-6 text-[#574b3f]">{features}</p></article>)}</div><p className="mx-auto mt-6 max-w-4xl rounded-[22px] border border-amber-900/10 bg-amber-50 p-5 text-center text-sm font-semibold leading-7 text-amber-950">Voulamandis House jest rodzinnym obiektem z prywatnymi pokojami i apartamentami. To alternatywa dla klasycznego hotelu na Chios, a nie hotel pod inną nazwą.</p></div></section>

      <section id="kambos-alternative" className="scroll-mt-24 px-4 py-12 sm:px-6 sm:py-16 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl overflow-hidden rounded-[32px] bg-[#263127] text-white shadow-2xl lg:grid-cols-[0.9fr_1.1fr] lg:rounded-[42px]"><div className="relative min-h-[300px] sm:min-h-[420px] lg:min-h-full"><Image src="/images/beaches/voulamandis-house-courtyard-chios.webp" alt="Voulamandis House w Kambos na Chios" fill sizes="(min-width: 1024px) 44vw, 100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#263127]/60 via-transparent to-transparent lg:bg-gradient-to-r lg:from-transparent lg:to-[#263127]/40" /></div><div className="p-5 sm:p-9 lg:p-12"><p className="text-[10px] font-black uppercase tracking-[0.22em] text-amber-200">INNY RODZAJ POBYTU</p><h2 className="mt-3 text-balance text-3xl font-black tracking-[-0.04em] text-white sm:text-4xl lg:text-5xl">Spokojna alternatywa dla klasycznego hotelu na Chios</h2><div className="mt-5 space-y-4 text-[15px] leading-7 text-white/80 sm:mt-6 sm:text-base sm:leading-8"><p>Voulamandis House odpowiada podróżnym, którzy cenią ciszę, bezpośredni kontakt i wygodną bazę do zwiedzania wyspy.</p><p>Do wyboru są pokoje ekonomiczne, pokoje na parterze bez schodów, pokoje na piętrze oraz rodzinne apartamenty z pełną kuchnią.</p><p>Obiekt leży około 3 km od lotniska i 6 km od portu, blisko miasta, ale poza jego najbardziej ruchliwą częścią.</p></div><div className="mt-7 grid gap-3 sm:flex sm:flex-wrap"><a href="/pl/pokoje-na-chios/" className={primaryButton}>Zobacz pokoje i apartamenty</a><a href="/pl/rezerwacja/" className={lightButton}>Sprawdź ceny</a></div></div></div></section>

      <section className="bg-[#f1e7d8] px-4 py-12 sm:px-6 sm:py-16 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><SectionHeader eyebrow="RZECZYWISTE OPCJE NOCLEGU" title="Pokoje i apartamenty w Voulamandis House" text="Porównaj główne kategorie przed wyborem terminu. Każda karta prowadzi do właściwej strony pokoju." id="rooms-pl" /><div className={`${mobileCarousel} mt-7 md:grid-cols-2 md:gap-6 sm:mt-10`}>{roomCategories.map((room) => <a key={room.title} href={room.href} className="group min-w-[86vw] snap-start overflow-hidden rounded-[28px] border border-amber-900/10 bg-white shadow-[0_22px_60px_rgba(47,38,31,0.11)] transition hover:-translate-y-1 sm:min-w-[72vw] md:min-w-0"><article className="grid h-full sm:grid-cols-[0.9fr_1.1fr]"><div className="relative min-h-[220px] bg-stone-200 sm:min-h-full"><Image src={room.image} alt={`${room.title} · Voulamandis House`} fill sizes="(min-width: 768px) 34vw, 86vw" className="object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/45 via-transparent to-transparent" /></div><div className="flex flex-col p-5 sm:p-7"><p className="text-[9px] font-black uppercase tracking-[0.15em] text-amber-800">{room.label}</p><h3 className="mt-3 text-2xl font-black tracking-[-0.035em]">{room.title}</h3><p className="mt-3 flex-1 text-sm leading-7 text-[#574b3f]">{room.text}</p><div className="mt-4 flex flex-wrap gap-2">{room.facts.map((fact) => <span key={fact} className="rounded-full bg-amber-50 px-3 py-1.5 text-[10px] font-black text-amber-900 ring-1 ring-amber-900/10">{fact}</span>)}</div><span className="mt-5 inline-flex text-xs font-black uppercase tracking-[0.08em] text-amber-800">Zobacz zakwaterowanie <span className="ml-2" aria-hidden="true">→</span></span></div></article></a>)}</div></div></section>

      <section className="bg-white px-4 py-12 sm:px-6 sm:py-16 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><SectionHeader eyebrow="ZAPLANUJ POBYT" title="Zobacz więcej niż sam pokój" text="Kambos jest dobrą bazą do plaż, miasta i południowej części wyspy." id="planning-pl" /><div className={`${mobileCarousel} mt-7 md:grid-cols-2 md:gap-4 lg:grid-cols-4 sm:mt-10`}>{[["Noclegi na Chios", "Porównaj pokoje, apartamenty i spokojny pobyt w Kambos.", "/pl/noclegi-chios/"], ["Kambos Chios", "Poznaj historyczne rezydencje, kamienne mury i ogrody cytrusowe.", "/pl/kambos-chios/"], ["Pokoje na Chios", "Zobacz wszystkie główne kategorie pokoi i ich szczegóły.", "/pl/pokoje-na-chios/"], ["Rezerwacja bezpośrednia", "Sprawdź ceny i aktualną dostępność pobytu.", "/pl/rezerwacja/"]].map(([title, text, href]) => <a key={href} href={href} className="group min-w-[78vw] snap-start rounded-[24px] border border-amber-900/10 bg-[#fbf6ef] p-5 shadow-[0_16px_40px_rgba(47,38,31,0.07)] transition hover:-translate-y-1 hover:bg-white sm:min-w-[52vw] sm:p-6 md:min-w-0"><h3 className="text-xl font-black tracking-[-0.03em]">{title}</h3><p className="mt-3 text-sm leading-7 text-[#574b3f]">{text}</p><span className="mt-5 inline-flex text-xs font-black uppercase tracking-[0.08em] text-amber-800">Otwórz przewodnik <span className="ml-2" aria-hidden="true">→</span></span></a>)}</div></div></section>

      <section className="bg-[#f1e7d8] px-4 py-12 sm:px-6 sm:py-16 lg:px-8 lg:py-24"><div className="mx-auto max-w-4xl"><SectionHeader eyebrow="HOTELE CHIOS FAQ" title="Pytania przed wyborem noclegu na Chios" id="faq-pl" /><div className="mt-8 space-y-3 sm:mt-10">{[["Czy Voulamandis House jest hotelem?", "Nie. To rodzinny obiekt oferujący pokoje i apartamenty w Kambos. Strona odpowiada na popularne wyszukiwanie „hotele Chios”, ale jasno pokazuje różnice między typami zakwaterowania."], ["Jaki rejon Chios wybrać?", "Miasto Chios jest praktyczne dla portu i osób bez auta. Kambos oferuje spokojniejszą, historyczną bazę blisko miasta i lotniska. Karfas jest bardziej plażowy, a południowe wioski najlepiej pasują do objazdu samochodem."], ["Czy są noclegi blisko lotniska Chios?", "Tak. Kambos znajduje się blisko lotniska, a Voulamandis House leży około 3 km od terminalu."], ["Czy na Chios są apartamenty dla rodzin?", "Tak. Voulamandis House oferuje rodzinne apartamenty z osobną sypialnią, salonem i kuchnią."], ["Jak sprawdzić aktualną dostępność?", "Skorzystaj z wyszukiwarki na tej stronie lub przejdź do strony rezerwacji bezpośredniej z aktualnymi cenami i dostępnością."]].map(([question, answer]) => <details key={question} className="group rounded-[22px] border border-amber-900/10 bg-white px-4 py-1 shadow-[0_14px_35px_rgba(47,38,31,0.06)] sm:px-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 py-4 text-left text-[15px] font-black sm:py-5 sm:text-lg"><span>{question}</span><span aria-hidden="true" className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-amber-100 text-lg text-amber-900 transition group-open:rotate-45">+</span></summary><p className="border-t border-amber-900/10 pb-4 pt-3 text-sm leading-7 text-[#574b3f] sm:pb-5 sm:pt-4 sm:text-base">{answer}</p></details>)}</div></div></section>

      <section className="relative isolate overflow-hidden bg-[#263127] px-4 py-14 text-white sm:px-6 lg:px-8 lg:py-24"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_bottom_right,rgba(232,199,127,0.22),transparent_30rem)]" /><div className="mx-auto max-w-4xl text-center"><p className="text-[10px] font-black uppercase tracking-[0.2em] text-amber-200">TWÓJ POBYT NA CHIOS ZACZYNA SIĘ TUTAJ</p><h2 className="mt-3 text-balance text-3xl font-black tracking-[-0.04em] text-white sm:text-4xl lg:text-6xl">Znajdź spokojny pokój lub apartament w Kambos</h2><p className="mx-auto mt-5 max-w-2xl text-[15px] leading-7 text-white/80 sm:text-lg sm:leading-8">Porównaj kategorie, wybierz realne daty i sprawdź opcję najlepiej dopasowaną do liczby gości oraz potrzeb Twojej podróży.</p><div className="mx-auto mt-8 grid max-w-xl grid-cols-2 gap-3"><a href="/pl/rezerwacja/" className={primaryButton}>Sprawdź dostępność</a><a href="/pl/pokoje-na-chios/" className={lightButton}>Wszystkie pokoje</a></div></div></section>
    </main>
  );
}
